### ISSUE TITLE
Old address transaction witness

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/jormungandr#1005]
Missing:

https://github.com/input-output-hk/jormungandr/blob/be63a2b631b3818ce1389f71a4166493c5bc57b1/jcli/src/jcli_app/transaction/mk_witness.rs#L78-L83

**Comment by KtorZ** [comment]
Okay, found this:

https://github.com/input-output-hk/jormungandr/blob/08fe9eb7ef0b6ba48daae38d3e6fd22a32ef1b0a/jormungandr-lib/src/interfaces/block0_configuration/initial_fragment.rs#L94-L119

So, normal genesis fund declarations are actually wrapped into transaction with empty inputs, whereas the legacy declarations are not. :woman_shrugging: 

This remains a blocker however: https://github.com/input-output-hk/chain-libs/blob/master/chain-impl-mockchain/src/transaction/witness.rs#L159
