### ISSUE TITLE
leader event starting-->cannot process leadership block-->panic

### ISSUE THREAD

**Issue by Madmosa** [input-output-hk/jormungandr#1008]
**Describe the bug**

**Mandatory Information**
1. `jcli 0.5.6 (HEAD-7ab929e+, release, linux [arm]) - [rustc 1.38.0 (625451e37 2019-09-23)]
2. `jormungandr 0.5.6 (HEAD-7ab929e+, release, linux [arm]) - [rustc 1.38.0 (625451e37 2019-09-23)]

**To Reproduce**
./jormungandr --config ./node-config.yaml --secret node_secret.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --log-level=info

**Result
Oct 21 21:33:22.066 INFO leader event starting, date: 241.20994, leader: 1, task: leadership
thread 'block0' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Msg("cannot process leadership block"), State { next_error: Some(Error(BlockHeaderVerificationFailed("Block signature is invalid"), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
   0: backtrace::capture::Backtrace::new_unresolved
   1: error_chain::backtrace::imp::InternalBacktrace::new
   2: jormungandr::blockchain::chain::Blockchain::post_check_header
   3: <futures::future::map::Map<A,F> as futures::future::Future>::poll
   4: futures::task_impl::Spawn<T>::poll_future_notify
   5: std::thread::local::LocalKey<T>::with
   6: jormungandr::blockchain::process::run_handle_input
   7: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll
   8: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
   9: futures::task_impl::std::set
  10: tokio_threadpool::worker::Worker::run_task
  11: tokio_threadpool::worker::Worker::run
  12: std::thread::local::LocalKey<T>::with
  13: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  14: std::sys_common::backtrace::__rust_begin_short_backtrace
  15: core::ops::function::FnOnce::call_once{{vtable.shim}}
  16: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  17: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
) } })), backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
   0: backtrace::capture::Backtrace::new_unresolved
   1: error_chain::backtrace::imp::InternalBacktrace::new
   2: jormungandr::blockchain::chain::Blockchain::post_check_header
   3: <futures::future::map::Map<A,F> as futures::future::Future>::poll
   4: futures::task_impl::Spawn<T>::poll_future_notify
   5: std::thread::local::LocalKey<T>::with
   6: jormungandr::blockchain::process::run_handle_input
   7: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll
   8: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
   9: futures::task_impl::std::set
  10: tokio_threadpool::worker::Worker::run_task
  11: tokio_threadpool::worker::Worker::run
  12: std::thread::local::LocalKey<T>::with
  13: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  14: std::sys_common::backtrace::__rust_begin_short_backtrace
  15: core::ops::function::FnOnce::call_once{{vtable.shim}}
  16: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  17: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
) } })', src/libcore/result.rs:1084:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at src/libcore/result.rs:1084
  11: jormungandr::blockchain::process::run_handle_input
  12: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll
  13: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  14: futures::task_impl::std::set
  15: tokio_threadpool::worker::Worker::run_task
  16: tokio_threadpool::worker::Worker::run
  17: std::thread::local::LocalKey<T>::with
  18: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'leadership2' panicked at 'Expect the event to not close', src/libcore/option.rs:1166:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
           called `Result::unwrap()` on an `Err` value: Error(Msg("cannot process leadership block"), State { next_error: Some(Error(BlockHeaderVerificationFailed("Block signature is invalid"), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
   0: backtrace::capture::Backtrace::new_unresolved
   1: error_chain::backtrace::imp::InternalBacktrace::new
   2: jormungandr::blockchain::chain::Blockchain::post_check_header
   3: <futures::future::map::Map<A,F> as futures::future::Future>::poll
   4: futures::task_impl::Spawn<T>::poll_future_notify
   5: std::thread::local::LocalKey<T>::with
   6: jormungandr::blockchain::process::run_handle_input
   7: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll
   8: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
   9: futures::task_impl::std::set
  10: tokio_threadpool::worker::Worker::run_task
  11: tokio_threadpool::worker::Worker::run
  12: std::thread::local::LocalKey<T>::with
  13: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  14: std::sys_common::backtrace::__rust_begin_short_backtrace
  15: core::ops::function::FnOnce::call_once{{vtable.shim}}
  16: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  17: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
) } })), backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
   0: backtrace::capture::Backtrace::new_unresolved
   1: error_chain::backtrace::imp::InternalBacktrace::new
   2: jormungandr::blockchain::chain::Blockchain::post_check_header
   3: <futures::future::map::Map<A,F> as futures::future::Future>::poll
   4: futures::task_impl::Spawn<T>::poll_future_notify
   5: std::thread::local::LocalKey<T>::with
   6: jormungandr::blockchain::process::run_handle_input
   7: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll
   8: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
   9: futures::task_impl::std::set
  10: tokio_threadpool::worker::Worker::run_task
  11: tokio_threadpool::worker::Worker::run
  12: std::thread::local::LocalKey<T>::with
  13: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  14: std::sys_common::backtrace::__rust_begin_short_backtrace
  15: core::ops::function::FnOnce::call_once{{vtable.shim}}
  16: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  17: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
) } })
  at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::option::expect_failed
             at src/libcore/option.rs:1166
  11: futures::future::chain::Chain<A,B,C>::poll
  12: <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll
  13: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  14: futures::task_impl::std::set
  15: tokio_threadpool::worker::Worker::run_task
  16: tokio_threadpool::worker::Worker::run
  17: std::thread::local::LocalKey<T>::with
  18: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'leadership2' panicked at 'cannot access stderr during shutdown', src/libcore/option.rs:1166:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::option::expect_failed
             at src/libcore/option.rs:1166
  11: core::option::Option<T>::expect
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/option.rs:345
  12: std::io::stdio::stderr
             at src/libstd/io/stdio.rs:629
  13: std::io::stdio::print_to::{{closure}}
             at src/libstd/io/stdio.rs:786
  14: std::thread::local::LocalKey<T>::try_with
             at src/libstd/thread/local.rs:262
  15: std::io::stdio::print_to
             at src/libstd/io/stdio.rs:780
  16: std::io::stdio::_eprint
             at src/libstd/io/stdio.rs:811
  17: jormungandr::utils::task::Services::spawn_future::{{closure}}
  18: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  19: futures::task_impl::std::set
  20: tokio_threadpool::worker::Worker::run_task
  21: tokio_threadpool::worker::Worker::run
  22: std::thread::local::LocalKey<T>::with
  23: tokio::runtime::threadpool::builder::Builder::build::{{closure}}

**Comment by NicolasDP** [comment]
please, use `0.6.5` now

**Comment by NicolasDP** [comment]
list of releases are there: https://github.com/input-output-hk/jormungandr/releases

**Comment by Madmosa** [comment]
Sorry my bad, used the wrong directory to pull version info, I am actually on 6.5

jormungandr 0.6.5 (HEAD-052f7be, release, linux [arm]) - [rustc 1.38.0 (625451e37 2019-09-23)]
jcli 0.6.5 (HEAD-052f7be, release, linux [arm]) - [rustc 1.38.0 (625451e37 2019-09-23)]
