### ISSUE TITLE
system just failed to compute an appropriate instant.

### ISSUE THREAD

**Issue by RonnyTome** [input-output-hk/jormungandr#1038]
Jcli v7 rc1
Jormungandr v7 rc1

Oct 26 15:27:25.046 INFO connecting to peer, node_id: f1d1954a7ac55ec46c797236856a7b5b7b5f4eca94f1cb0a5157b618f4a85005, peer_addr: 18.184.181.30:3000, task: network
thread 'leadership0' panicked at 'not yet implemented: The system just failed to compute an appropriate instant.
This could be due to a system suspension or hibernation, in order not to miss out on future
leader elections please prevent your system from suspending or hibernating.
Oct 26 15:27:25.047', jormungandr/src/leadership/mod.rs: 244:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
CRIT system recorded a 176s delay. This could be due to a system suspension or hibernation, in order not to miss out on future leader elections please prevent your system from suspending or hibernating., epoch: 12, reason: second time provided was later than self, slot_system_time: 2019-10-26T19:24:29+00:00, now: 2019-10-26T19:27:25.047407478+00:00, not yet implemented: The system just failed to compute an appropriate instant.
This could be due to a system suspension or hibernation, in order not to miss out on future
leader elections please prevent your system from suspending or hibernating.

**Comment by dkijania** [comment]
duplicates: #982
