### ISSUE TITLE
Transactions not propagating

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/jormungandr#1042]
**Describe the bug**
Transactions sent to trusted peers do not propagate to stake pools all the time. As can be seen in the transactions graph here https://monitoring.jormungandr-testnet2.iohkdev.io/grafana/d/7wVByzAZj/jormungandr-monitor?orgId=1&refresh=1m stake pools receive far fewer transactions than trusted peers.
**Mandatory Information**
1. `jcli --full-version` output;
2. `jormungandr --full-version` output;

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by dkijania** [comment]
What are the values for `topics_of_interest` setting in node configuration for mentioned stakepools ?

**Comment by disassembler** [comment]
high/high

**Comment by disassembler** [comment]
This issue is still not resolved with rc3. We see stake pools have about 10 transactions received and trusted peers are at 80.

**Comment by NicolasDP** [comment]
ok, so that's a propagation of transaction event. `rc4` contains a rework of the `poldercast` parameters. Notably more likely to contact closer nodes of interests. I'd be curious if this is still the case with this new version?

**Comment by NicolasDP** [comment]
I think this is resolved now
