### ISSUE TITLE
Transactions lost on rollbacks

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/jormungandr#1043]
**Describe the bug**
When a node rolls back to a different chain (which happens very frequently), transactions it made in it's fork disappear and are not repropagated so other stake pools can adopt them when they create blocks. This can be seen in requests from the faucet being received and within an hour are like they never existed after a rollback.
**Mandatory Information**
1. `jcli --full-version` output;
2. `jormungandr --full-version` output;

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by rickymac68** [comment]
jcli 0.7.0-rc1 (HEAD-5583e5e8, release, macos [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
jormungandr 0.7.0-rc1 (HEAD-5583e5e8, release, macos [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
 
<img width="979" alt="Screen Shot 2019-10-28 at 5 48 52 PM" src="https://user-images.githubusercontent.com/25856278/67739303-4b657e80-f9cf-11e9-97ca-b7750e7a7a19.png">

**Comment by rickymac68** [comment]
I delegated my stake to my pool. The transaction went into a block, but the delegation did not occur.

- fragment_id: ab7eaccb4448ff537c52476f2c92cbff039245614ed10b945f83927724cd7b9a
  last_updated_at: "2019-10-29T07:57:53.729310+00:00"
  received_at: "2019-10-29T07:51:37.104177+00:00"
  received_from: Rest
  status:
    InABlock:
      block: 51ded0fc9630a0d64e6d3092853245b2568227a37d2a2a348dad2d6f8ba4d970
      date: "28.1002"
<img width="1099" alt="Screen Shot 2019-10-29 at 1 11 13 AM" src="https://user-images.githubusercontent.com/25856278/67748834-08180980-f9e9-11e9-9f6a-bb5b66d5102a.png">

**Comment by mmahut** [comment]
Same here, seen this several times on the nighly.

**Comment by NicolasDP** [comment]
Fork can and **will** happen on the blockchain. This is how the protocol works.

Regarding _re-propagating transactions_ proposed by @disassembler : This is a wallet job. If the wallet wishes to continue asking for a transaction to happen, even after a fork/rollback, then it is the wallet to do so.
