### ISSUE TITLE
UTxO query by FragmentID

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/jormungandr#1048]
- [ ] remove the current UTxO end point that returns the whole list of UTxO;
- [ ] add an end point to query the UTxO via **FragmentId** and **Output Index** (GET `/utxo/<fragment-id>/<output-index>`)
    * returns `null` if the fragment is not or is no longer an UTxO;
    * returns `{ address: "bech32-encoded-address", value: Value }`

**Comment by ziro-official** [comment]
@NicolasDP How can I get UtxO for an account, what is FragmentId and where can I get it?
