### ISSUE TITLE
Passive node does not sync (receive blocks) - `v0.7.0-rc3` (local cluster, 2 nodes)

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#1057]
**Describe the bug**
Passive does not do not receive any blocks from Leader/Stake Pool node.

**Mandatory Information**
```
jcli 0.7.0-rc3 (HEAD-466c0fb0, release, windows [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
jormungandr 0.7.0-rc3 (HEAD-466c0fb0, release, windows [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
```

**To Reproduce**
1. Start node 1 (leader node - configs attached) - `jormungandr ---genesis-block block-0.bin --config node_config.yaml --secret node_secret.yaml`
2. Start node 2 (passive node - config attached) - `jormungandr ---config node_config.yaml --genesis-block-hash a087451eceeaef00ddf7d69c2084b961bd2bdcb4c891a11db16b779199a6bdaf`

**Expected behavior**
The passive node should be in sync with the leader node.

**Additional context**
Configuration details:
- VM with windows
- 2 nodes connected together (direct connectivity) - 1 passive + 1 leader (with 1 stake pool configured inside genesis.yaml)

Attachments:
- leader node
[node1_faucet.zip](https://github.com/input-output-hk/jormungandr/files/3797870/node1_faucet.zip)
[leader_node_logs.txt](https://github.com/input-output-hk/jormungandr/files/3797871/leader_node_logs.txt)

- passive node
[node2_stake_pool.zip](https://github.com/input-output-hk/jormungandr/files/3797872/node2_stake_pool.zip)
[passive_node_logs.txt](https://github.com/input-output-hk/jormungandr/files/3797873/passive_node_logs.txt)

Other results:
```
$ netstat -an | grep -E ":(3000|3001|3002)"
  TCP    127.0.0.1:3001         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:3001         127.0.0.1:63822        ESTABLISHED
  TCP    127.0.0.1:3002         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:63822        127.0.0.1:3001         ESTABLISHED
```
```
Node 1 network stats:
---
- establishedAt: "2019-11-01T11:38:03.092771900+00:00"
  lastBlockReceived: ~
  lastFragmentReceived: ~
  lastGossipReceived: "2019-11-01T11:45:53.108602600+00:00"
  nodeId: f4c07edd4388e196ce461a0cada3d2976c4f5fd67aaed6d4201539bf8ed1fcc1
- establishedAt: "2019-11-01T11:47:00.765411600+00:00"
  lastBlockReceived: ~
  lastFragmentReceived: ~
  lastGossipReceived: "2019-11-01T12:12:10.767305900+00:00"
  nodeId: 0ed1306eff0ea25eea8599bc147f745976213772bbedf41cc76a977c80deabf8
----------------------------------------------------------
Node 2 network stats:
---
- establishedAt: "2019-11-01T11:47:00.750369100+00:00"
  lastBlockReceived: ~
  lastFragmentReceived: ~
  lastGossipReceived: ~
  nodeId: 2a539d5693872ca26bd7935cd01cfd7778f2e203464506f48719d5b64c9fed59
```
```
Node 1 stats:
---
blockRecvCnt: 115
lastBlockDate: "109.163"
lastBlockFees: 0
lastBlockHash: 60ada21e5983757c06c5275c800c27993a27a812995e12a1ed23cb2e1bbbd524
lastBlockHeight: "115"
lastBlockSum: 0
lastBlockTime: "2019-11-01T12:12:06+00:00"
lastBlockTx: 0
state: Running
txRecvCnt: 0
uptime: 2157
----------------------------------------------------------
Node 2 stats:
---
blockRecvCnt: 0
lastBlockDate: "105.197"
lastBlockFees: 0
lastBlockHash: adcec825bd9cdcbcd268bb9175dae1261dd9b7c0b33cd7478730075da48d4864
lastBlockHeight: "39"
lastBlockSum: 0
lastBlockTime: ~
lastBlockTx: 0
state: Running
txRecvCnt: 0
uptime: 1506
```

**Comment by rinor** [comment]
You need to use **allow_private_addresses**: true

under p2p config

**Comment by dorin100** [comment]
From where do you have that info @rinor ?

**Comment by dorin100** [comment]
+ in this case, there is direct communication - nothing private/public

**Comment by rinor** [comment]
From here https://github.com/input-output-hk/jormungandr/commit/04ffac434216674bd80db167b5d3ab90373d52c2

**Comment by NicolasDP** [comment]
this is not documented in the generated doc, would one of you guys mind adding that? It should go there https://input-output-hk.github.io/jormungandr/configuration/introduction.html

**Comment by NicolasDP** [comment]
source file for the doc is: https://github.com/input-output-hk/jormungandr/tree/master/doc/configuration

**Comment by dorin100** [comment]
It is still unclear to me when `allow_private_addresses` should be used as **true** or **false**.

**Comment by rinor** [comment]
**missing** == allow_private_addresses: **false**.

Simplified answer
**true** needs to be set if the IP addresses configured for p2p are not public/global. Like in your case 127.0.0.1 is not a public IP address.

**Comment by dorin100** [comment]
I confirm the functionality with allow_private_addresses: true
