### ISSUE TITLE
Error in the overall configuration of the node  |-> Error while parsing the node configuration file: p2p.trusted_peers[0].id: Odd number of digits at line 13 column 11  |-> p2p.trusted_peers[0].id: Odd number of digits at line 13 column 11

### ISSUE THREAD

**Issue by RonnyTome** [input-output-hk/jormungandr#1094]
Error in the overall configuration of the node
 |-> Error while parsing the node configuration file: p2p.trusted_peers[0].id: Odd number of digits at line 13 column 11
 |-> p2p.trusted_peers[0].id: Odd number of digits at line 13 column 11

jcli 0.7.0-rc6 (HEAD-a5af99a6, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

jormungandr 0.7.0-rc6 (HEAD-a5af99a6, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

**Comment by mark-stopka** [comment]
You're using wrong config file, see [IOHK repo for genesis and config file](https://hydra.iohk.io/job/Cardano/jormungandr/jormungandrConfigs.nightly/latest).

**Comment by Philluminati** [comment]
i had the same issue. Please update the node-config.yaml in the doku.
https://iohk.zendesk.com/hc/en-us/articles/360036898153
