### ISSUE TITLE
Re-open #1094

### ISSUE THREAD

**Issue by phillewis** [input-output-hk/jormungandr#1104]
I have the same issue as reported in #1094 

I suspect this may be a documentation issue.

If following https://iohk.zendesk.com/hc/en-us/articles/360036898153 I use the same config as is also listed https://testnet.iohkdev.io/cardano/shelley/get-started/configuring-your-network/ for the "beta" release testnet.

The link supplied as a resolution in #1094 for the correct config appears to be for the nightly release.  If so then where is the correct config for the "beta" release?  Is the config on the above links correct for the "beta" release?

NOTE: I am using the latest RC release (v0.7.0-rc7) with this config as I assume that is the "beta" release, given there isn't an RC release nightly.

Thanks

**Comment by mmahut** [comment]
Hello @phillewis,

Please browse to https://hydra.iohk.io/jobset/Cardano/jormungandr and choose the latest build, there you will be able to click on the ```beta``` or ```nightly```.

Please close this issue, as this is not directly related to the ```jormungandr``` software, but rather to the testnet network. Feel free to join us on the telegram channel in future in case you need additional help! https://hydra.iohk.io/jobset/Cardano/jormungandr

**Comment by NicolasDP** [comment]
rc7 is not compatible with `beta` testnet. Use nightly instead

**Comment by phillewis** [comment]
I wasn't able to "click on beta" as instructed, as I couldn't find it after selecting latest build.  The comment that rc7 isn't supported on the beta testnet also seems to contradict the instructions at https://iohk.zendesk.com/hc/en-us/articles/360036898153-How-to-install-Jormungandr-Networking-Linux-macOS- which is why I have assumed this is a documentation issue.

Thanks for your help.  I have logged a ticket on the Zendesk for further assistance.
