### ISSUE TITLE
Grpc port in use - better logging request

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#1122]
**Is your feature request related to a problem/context ? Please describe if applicable.**
Automated tests suffered from port collision for grpc protocol in jormungandr. To overcome this a fix in test code was applied. However, this error was obscured with 'panic at Box<Any>'  error message. This can be enhanced with better error message

**Describe the solution you'd like**
`P2P listen port already in use` or similar

**Comment by mzabaluev** [comment]
This hinges on #913.

**Comment by carl-IOHK** [comment]
Linked to https://iohk.myjetbrains.com/youtrack/issue/IOHKS-157
