### ISSUE TITLE
Stake pools with valid stake does not create blocks - `0.7.0` - local cluster, 2 (stake pool) nodes

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#1124]
**Describe the bug**
Second stake pool node, with 30% of the stake, does not create any block.

**Mandatory Information**
```
jcli 0.7.0 (HEAD-a93d4f67, release, windows [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
jormungandr 0.7.0 (HEAD-a93d4f67, release, windows [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
```

**To Reproduce**
1. Start node1 --> `jormungandr ---genesis-block block-0.bin --config node_config.yaml --secret node_secret.yaml`
2. Start node2 --> `jormungandr --config node_config.yaml --secret node_secret.yaml --genesis-block-hash d82710b1ded65e7810392ad8567adb4bd5c82387a091b539f6f7dc72da8bcf06`
3. send some funds to the account owning the stake pool from node2 --> `bash send-money.sh ca1sku4yc68q9cuwlsg296l6yrk6ccth2pzqu26r4s5r8enymyfeyptgl5vxk4 15000000000000 9001 ed25519e_sk18r7nd20gaxjfgmahyqu2vngv98leqefcdcft2nevcakpf999spx55t4ph8ryqslp6ac7uryekjcqsqzl63rjpmh0k92dvquesweq38cc8a0wc`
4. delegate the account from point no 3 to the stake pool of node2 --> `bash delegate-account.sh dd879881832622786b2e14fbedadd5d050163e638b4a1a5830776af37d9ba207 9002 ed25519e_sk1xpdwnr5wx54mh4fpexxsyrc9n0zejfnf7pczr0zr9c3ym98wgpde2drs8t6lkshgeg5z4n2l7lkgkj4kyw97a62mljsrljze9j0c6zgh5j28d`
5. wait 2 epochs
6. check the stake pool distribution and the node creation distribution --> `python janalyze.py -r "http://127.0.0.1:9001/api" -x`

**Actual results**
1. all the blocks are created only by the first node/stake pool (encoded into the genesis) 
2. if we stop and start the nodes without deleting the storage, node1 will crash (and stop) with the bellow error:
```
Nov 13 12:58:56.017 DEBG block is already present, thread 'dateblock2:' panicked at ' not yet implemented: method to load a Ref from the storage is not yet there', 9862.21jormungandr\src\blockchain\chain.rs, :parent259:: 37c8ce25cb0247961f984e74e88b8751425425b546c44f89923aa5a6714c43a217
, note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Expected behavior**
The number of blocks created by each stake pool node should be proportional with the percentage of the total stake owned by each node --> both stake pool nodes should create valid blocks in each epoch.

**Additional context**
Scenario description:
- OS: win10
- local cluster with 2 nodes - both stake pool certificates (1 per node) and the delegation certificate for account owning node1 stake pool are added into genesis

- Delegated stake in the system for the first 2 epochs:
```
epoch: 9861
stake:
  dangling: 0
  pools:
    - - c6b2ec91096c31936de99aa20ac94c2e944c9b4f00d29568d255e5390dfd42ae
      - 50000000000000
    - - dd879881832622786b2e14fbedadd5d050163e638b4a1a5830776af37d9ba207
      - 0
  unassigned: 0
```

- Block creation per stake pool in the system for the first 2 epochs:
```
D:\iohk\otherProjects\jormungandr\scripts\local_cluster>python janalyze.py -r "http://127.0.0.1:9001/api" -x

Jormungandr Stake and Block Distribution Cross Reference:

Epoch:               9861
Dangling:            0.000000 ADA
Unassigned:          0.000000 ADA
TotalADA:            50,000,000.000000 ADA
TotalBlocks:         48
TotalStaked:         50,000,000.000000 ADA
TotalPercentStaked:  100.00%

+------------------------------------------------------------------+-----------------+--------------+---------------------+---------------------+
| EPOCH 9861, Pool (Node ID)                                       |     Stake (ADA) |   Blocks (#) |   PercentStaked (%) |   PercentBlocks (%) |
|------------------------------------------------------------------+-----------------+--------------+---------------------+---------------------|
| c6b2ec91096c31936de99aa20ac94c2e944c9b4f00d29568d255e5390dfd42ae | 50000000.000000 |           48 |                 100 |                 100 |
| dd879881832622786b2e14fbedadd5d050163e638b4a1a5830776af37d9ba207 |        0.000000 |              |                   0 |                     |
+------------------------------------------------------------------+-----------------+--------------+---------------------+---------------------+
```

- Delegated stake in the system after the first 2 epochs:
```
epoch: 9865
stake:
  dangling: 0
  pools:
    - - c6b2ec91096c31936de99aa20ac94c2e944c9b4f00d29568d255e5390dfd42ae
      - 34999999998900
    - - dd879881832622786b2e14fbedadd5d050163e638b4a1a5830776af37d9ba207
      - 14999999988950
  unassigned: 0
```
- Block creation per stake pool in the system after the first 2 epochs:
```
D:\iohk\otherProjects\jormungandr\scripts\local_cluster>python janalyze.py -r "http://127.0.0.1:9001/api" -x

Jormungandr Stake and Block Distribution Cross Reference:

Epoch:               9863
Dangling:            0.000000 ADA
Unassigned:          0.000000 ADA
TotalADA:            49,999,999.987850 ADA
TotalBlocks:         47
TotalStaked:         49,999,999.987850 ADA
TotalPercentStaked:  100.00%

+------------------------------------------------------------------+-----------------+--------------+---------------------+---------------------+
| EPOCH 9863, Pool (Node ID)                                       |     Stake (ADA) |   Blocks (#) |   PercentStaked (%) |   PercentBlocks (%) |
|------------------------------------------------------------------+-----------------+--------------+---------------------+---------------------|
| c6b2ec91096c31936de99aa20ac94c2e944c9b4f00d29568d255e5390dfd42ae | 34999999.998900 |           47 |                  70 |                 100 |
| dd879881832622786b2e14fbedadd5d050163e638b4a1a5830776af37d9ba207 | 14999999.988950 |              |                  30 |                     |
+------------------------------------------------------------------+-----------------+--------------+---------------------+---------------------+
```

**Attachments**:
- Node1
[node1.zip](https://github.com/input-output-hk/jormungandr/files/3840689/node1.zip)
[node1_logs.txt](https://github.com/input-output-hk/jormungandr/files/3840690/node1_logs.txt)

- Node2
[node2.zip](https://github.com/input-output-hk/jormungandr/files/3840691/node2.zip)
[node2_logs.txt](https://github.com/input-output-hk/jormungandr/files/3840692/node2_logs.txt)

- python script: https://github.com/input-output-hk/jormungandr-ops/blob/master/scripts/janalyze.sh

**Comment by rinor** [comment]
The nodes are **forking**. If you check the stats from `node2` you may have a different view.
However, not sure if `"consensus_genesis_praos_active_slot_coeff": 1` is ever supposed to be 1, since you will have **multiple leaders** for **each slot** and natural forking is expected, and don't know if the protocol is expected to recover in this constant case. Interesting nevertheless...

**Comment by NicolasDP** [comment]
thanks @rinor. as usual good job finding the issue of the issue :) 

@dorin100 it `"consensus_genesis_praos_active_slot_coeff": 1,` is not valid for what you are trying to do.
