### ISSUE TITLE
Which faucet to use for the latest release v0.7.0?

### ISSUE THREAD

**Issue by liebmann** [input-output-hk/jormungandr#1135]
**Describe the bug**
I cannot setup a stake pool without a faucet for the latest release v0.7.0.

Non of the faucets 
https://faucet.beta.jormungandr-testnet.iohkdev.io/send-money/
https://faucet.nightly.jormungandr-testnet.iohkdev.io/send-money/
seems to give coins on the 
dceef4d6696ead83eadb5104c6383e1905aa81fc7a79ea2ca87a97c2bfd2f4a1
chain.

**Mandatory Information**
1. `jcli --full-version` output;
2. `jormungandr --full-version` output;
jcli 0.7.0 (HEAD-a93d4f6, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
jormungandr 0.7.0 (HEAD-a93d4f6, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

**Comment by mmahut** [comment]
@liebmann this is a known issue. IOHK DevOps team is working on getting the faucets working. Feel free to close this issue, as it's not related to the software itself.

**Comment by ziro-official** [comment]
@mmahut I tried to get the faucet but failed, is it fixed?
`https://testnet.iohkdev.io/en/cardano/shelley/tools/faucet/`
Return invalid address format for `ca1s0yr5aheekwx08ztdm9m4gm5trjjr65y2z6dpmgyjls9mtat4h8f23daamk`

Beta network, config from `https://hydra.iohk.io/build/1360575`
