### ISSUE TITLE
`max_number_of_transactions_per_block` does not increase more than 250

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#1137]
**Describe the bug**
`max_number_of_transactions_per_block` is limited to 250.

**Mandatory Information**
```
jcli 0.7.0 (HEAD-a93d4f67, release, windows [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
jormungandr 0.7.0 (HEAD-a93d4f67, release, windows [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
```

**To Reproduce**
1. start node1 - `jormungandr ---genesis-block block-0.bin --config node_config.yaml --secret node_secret.yaml`
2. start node2 - `jormungandr --config node_config.yaml --secret node_secret.yaml --genesis-block-hash 3bae53f25be7523ce63c1dc09c9d3b3fbf7dac810e095bff1b8f498fa8de4e4d`
3. extract the scripts in the same folder
4. run script - `bash multipleBashScripts.sh 9001 ed25519e_sk18r7nd20gaxjfgmahyqu2vngv98leqefcdcft2nevcakpf999spx55t4ph8ryqslp6ac7uryekjcqsqzl63rjpmh0k92dvquesweq38cc8a0wc`

**Expected behavior**
"max_number_of_transactions_per_block" should respect the set value inside genesis file.

**Additional context**
- scenario: 2 stake pool nodes connected together
- in my genesis file 
```
   - "max_number_of_transactions_per_block": 1000
   - "consensus_genesis_praos_active_slot_coeff": 0.1
   - "slot_duration": 2
   - "slots_per_epoch": 110
````
- `multipleBashScripts.sh` is creating 10 accounts that will initiate, in parallel, 100 transactions each to a new account each. There will be ~12 txs per second for ~70 seconds. 

- node 1 files
[node1.zip](https://github.com/input-output-hk/jormungandr/files/3852402/node1.zip)

- node 2 files
[node2.zip](https://github.com/input-output-hk/jormungandr/files/3852403/node2.zip)

- scripts 
[scripts.zip](https://github.com/input-output-hk/jormungandr/files/3852401/scripts.zip)

- as you can see in the below picture, even there were 530 fragments in Pending, only 250 were included between 2 consecutive blocks
![fragments1](https://user-images.githubusercontent.com/29144964/68960550-0c119d00-07d9-11ea-9efc-f3b8d243037f.png)

- using the attached python script we can look also at the fragment counts per blocks --> again there is a maximum of 250 fragments per block
```
D:\iohk\otherProjects\jormungandr\scripts\local_cluster>python logs_analyzer.py -l 9001 -t
================= Node 9001 - Transactions per block/epoch ====================
{'InABlock': {'block': '8e56eebc04fa4434561d5fe59ff18e2000e1c78b15943c681c6f09ea5fd8e8de', 'date': '5377.32'}}     250
{'InABlock': {'block': '68e18da55a6b987e95fba371f15cf94374e34f99f1d57598b3e139420fe92178', 'date': '5377.51'}}     250
{'InABlock': {'block': 'decf16be5221815b2756f71eda3a335673b9c9281cab660175ff928902fbe20a', 'date': '5377.58'}}     202
{'InABlock': {'block': '7a57c648275b42fa400c1c51b402df7c4afd8e74d2d6b00b95d1e536109e3ceb', 'date': '5377.12'}}     1
{'InABlock': {'block': '5822659ffcdd772142b1ccfe63993b03581a0b26d0b295b139c46526f973a32b', 'date': '5375.87'}}     1
{'InABlock': {'block': '8ba4482a1eb75a591fc45eec45c36502992c5ad58e520a8065aa0fc862c58914', 'date': '5376.34'}}     1
{'InABlock': {'block': '460f81e742e4129cc8ffbcb3e34361974fedbfcd08ff5251c00e4a0c34e94038', 'date': '5376.66'}}     1
{'InABlock': {'block': '7bb61722e459e5edd2cffe3cae888fe3d37ddbaab372e8073cc32a08e553dbcf', 'date': '5376.56'}}     1
{'InABlock': {'block': '454d439a6ee02cd99919759ea8f47ab3d143ff2d231f809006334c8bf3ff8e23', 'date': '5376.101'}}    1
{'InABlock': {'block': 'c2a4d9ff9966c6ca7b61cced450dddd4238df50d5e82b44ab7efd52b0fb83127', 'date': '5376.87'}}     1
```

**Comment by dorin100** [comment]
if you set `max_number_of_transactions_per_block = 20`, and will re-execute the test, there will be still  250 mined fragments per block;

**Comment by rdlrt** [comment]
Changing [this](https://github.com/input-output-hk/jormungandr/blob/bcfd19b9065623a19fc740fc48b14b38c062c297/jormungandr/src/leadership/process.rs#L648) number and recompiling it takes more, but its a dummy value for now

**Comment by CodeSandwich** [comment]
I'm sorry, but I'm going to close this issue without fixing it. This setting shouldn't be used at all. It's incomplete, has broken design and will be replaced soon with the real solution to the problem: https://github.com/input-output-hk/jormungandr/issues/86
