### ISSUE TITLE
Timing issue in Jormungandr for slot leader signing blocks

### ISSUE THREAD

**Issue by rickymac68** [input-output-hk/jormungandr#1143]
<img width="1586" alt="Epoch-16-1" src="https://user-images.githubusercontent.com/25856278/69015354-dc34d780-0947-11ea-81be-a71a553f7fce.png">
<img width="1571" alt="Epoch-18" src="https://user-images.githubusercontent.com/25856278/69015362-eb1b8a00-0947-11ea-99de-c63067e6b15f.png">

**Describe the bug**
My node timing is correct as verified by 3 different time sources and automatic time sync is turned on. When my node is supposed to sign a block I intermittently get this error in the log:
Nov 16 13:46:36.917 ERRO Eek... we missed an event schedule, system time might be off?, event_end: 2019-11-16T18:46:39+00:00, event_start: 2019-11-16T18:46:37+00:00, event_date: 12.1468, leader_id: 1, task: leadership

The problem may be more obvious when delegated stake %, but a detailed look into the problem shows it is more likely related to time. "Missed the deadline to compute the schedule" shows up in the leader logs. However a closer look at some of the time shows the system clock was 1 second ahead of what the protocol is expecting. Screen cap for Epoch 18 has red dots showing the discrepancy. The problem of blocks not being signed in time shows up between blocks that were signed correctly so that tells me system time is good in addition to my manual comparisons to 3 other time sources.

**Mandatory Information**
1. `jcli --full-version` output;
jcli 0.7.0 (HEAD-a93d4f67, release, macos [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
2. `jormungandr --full-version` output;
jormungandr 0.7.0 (HEAD-a93d4f67, release, macos [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

**To Reproduce**
1. Operate Jormungandr on the nightly test net.
2. Have a low % stake <1% to make more obvious
3. jcli rest v0 leaders logs get -h http://127.0.0.1:3101/api

**Expected behavior**
Blocks get signed correctly.

**Additional context**
Using Mac OSX Catalina 10.15.1 on a Mac Pro server with auto time sync turned on.
Logs and screen captures attached. Log and screen cap for Epoch 18 when stake % is higher. Screen caps from previous epochs when stake was less than 1%
<img width="1488" alt="Epoch-9" src="https://user-images.githubusercontent.com/25856278/69015319-9e37b380-0947-11ea-9ba6-13080a00fa02.png">
<img width="784" alt="Epoch-10" src="https://user-images.githubusercontent.com/25856278/69015323-a55ec180-0947-11ea-953f-a06b309329dc.png">
<img width="1498" alt="Epoch-10-1" src="https://user-images.githubusercontent.com/25856278/69015324-abed3900-0947-11ea-8915-aa7ea96c227b.png">
<img width="1384" alt="Epoch-11" src="https://user-images.githubusercontent.com/25856278/69015330-b14a8380-0947-11ea-9974-4dd331e9d575.png">
<img width="1490" alt="Epoch-13" src="https://user-images.githubusercontent.com/25856278/69015335-bad3eb80-0947-11ea-87f5-ae500e5b2aec.png">
<img width="1500" alt="Epoch-14" src="https://user-images.githubusercontent.com/25856278/69015341-c32c2680-0947-11ea-9ddc-7a2f3a3ee565.png">

[leader-logs-epoch-18-rick.log](https://github.com/input-output-hk/jormungandr/files/3856207/leader-logs-epoch-18-rick.log)

**Comment by maneav** [comment]
[leader-logs-epoch-18-Vio.log](https://github.com/input-output-hk/jormungandr/files/3856233/leader-logs-epoch-18-Vio.log)

**Comment by rickymac68** [comment]
@NicolasDP This problem still exists in 0.7.1

Nov 21 22:58:26.934 WARN system woke a bit early for the event, delaying until right time., event_end: 2019-11-22T03:58:29+00:00, event_start: 2019-11-22T03:58:27+00:00, event_date: 44.3623, leader_id: 1, task: leadership
Nov 21 22:58:27.001 INFO Leader event started, event_remaining_time: 1s 998ms 933us, event_end: 2019-11-22T03:58:29+00:00, event_start: 2019-11-22T03:58:27+00:00, event_date: 44.3623, leader_id: 1, task: leadership
Nov 21 22:58:29.000 ERRO Eek... took too long to process the event..., reason: deadline has elapsed, event_remaining_time: 1s 998ms 933us, event_end: 2019-11-22T03:58:29+00:00, event_start: 2019-11-22T03:58:27+00:00, event_date: 44.3623, leader_id: 1, task: leadership

**Comment by rickymac68** [comment]
Looks like this issue is resolved. Text logs are attached. Thank you!
<img width="1577" alt="Epoch-49" src="https://user-images.githubusercontent.com/25856278/69480114-3eaf2d00-0db9-11ea-8bb5-a8d09539df10.png">
<img width="1581" alt="Epoch-50" src="https://user-images.githubusercontent.com/25856278/69480124-4a025880-0db9-11ea-9bc1-26900229b671.png">
[leader-log-epoch-49-Rick.txt](https://github.com/input-output-hk/jormungandr/files/3882541/leader-log-epoch-49-Rick.txt)
[leader-log-epoch-50-Rick.txt](https://github.com/input-output-hk/jormungandr/files/3882542/leader-log-epoch-50-Rick.txt)
