### ISSUE TITLE
Local 0.7.0 Jormungandr node not receiving blocks from Incentivized TestNet

### ISSUE THREAD

**Issue by alan-mcnicholas** [input-output-hk/jormungandr#1147]
**Describe the bug**
When connected to the incentivized testnet; the local node stops receiving blocks from the network. This issue was not evident on the 15th and 16th of November and has only been seen consistently today. 

**Mandatory Information**
`$ ./jcli --full-version
jcli 0.7.0 (HEAD-a93d4f67, release, windows [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
`
`$ ./jormungandr.exe --full-version
jormungandr 0.7.0 (HEAD-a93d4f67, release, windows [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
`

**To Reproduce**
Connect to incentivized testnet using the following configuration:

`[
      {
        "address": "/ip4/3.124.55.91/tcp/3000",
        "id": "d5cb4aa6e28a4b4951fb3121365da45466a2a31c880b44a5"
      },
      {
        "address": "/ip4/54.183.206.246/tcp/3000",
        "id": "67282e0bf1dcdf5e4559c85b057de122ba7a248f16ac5226"
      },
      {
        "address": "/ip4/52.8.126.235/tcp/3000",
        "id": "75534bbbb7dddfeee3783ae5e7983c28349209138351c278"
      },
      {
        "address": "/ip4/3.113.195.95/tcp/3000",
        "id": "617ff3920bac9e90faec3adc5d32c2937cbb6b8528b1b22d"
      },
      {
        "address": "/ip4/18.176.14.159/tcp/3000",
        "id": "55f82104122f4d5101ae549935943071c8c646f1bd62cd0b"
      },
      {
        "address": "/ip4/3.124.166.70/tcp/3000",
        "id": "96a84a81a74715c7fb29d906ddff32b2874aac4d14acc7db"
      },
      {
        "address": "/ip4/3.125.15.153/tcp/3000",
        "id": "97fd215d7e294b5943960056af1e1a0316c3593a4aa3cb76"
      },
      {
        "address": "/ip4/3.124.103.156/tcp/3000",
        "id": "173ca3b1198816989c585785a8c912fea3c5ec14895eaa6b"
      }
    ]
`
**Genesis Hash** 0f9d564199ad7f71af3daaff4b6997cb7f2e3d7c422fa29097f5d6a018c440d1

**Expected behavior**
The nodes connects to the network and blocks are received consistently.

**Comment by alan-mcnicholas** [comment]
Closing as a duplicate of https://github.com/input-output-hk/jormungandr/issues/1146

**Comment by carl-IOHK** [comment]
Linked to https://iohk.myjetbrains.com/youtrack/issue/IOHKS-154
