### ISSUE TITLE
Add monitoring API on REST

### ISSUE THREAD

**Issue by vincenthz** [input-output-hk/jormungandr#115]
We need to be able to connect to the node and query/gather informations related to the node itself.
this is useful for out-of-band management and something that the decoupled wallet need for operation

The swagger for part of the initial api on the haskell node is at:

https://rebilly.github.io/ReDoc/?url=https://gist.githubusercontent.com/KtorZ/0db1eed2df1b546a255445b79fea3efb/raw/5d043c8609686254f1e0f80e4c959648b57f1e23/cardano-node-api.swagger.json

Apart from the specific API calls themselves, we need to be able to:

* [x] configure the port to listen to
* [ ] configure local TLS certificates
* [x] listen to REST like call

**Comment by NicolasDP** [comment]
This is to implement the server side of the service using a provided swagger file that describes the APIs.

**Comment by NicolasDP** [comment]
The rest module allows to download the blocks and to monitor the blockchain
