### ISSUE TITLE
Fragment ids should be unique even for identical transactions

### ISSUE THREAD

**Issue by wxsq2004** [input-output-hk/jormungandr#1152]
Creating 2 identical transactions through jcli produces the same fragment id

**Mandatory Information**
1. jcli 0.7.0 (HEAD-a93d4f6, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
2. jormungandr 0.7.0 (HEAD-a93d4f6, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

**To Reproduce**
1. Create a 'send value' transaction
2. Create the same transaction
3. The fragment ids for both transactions are equal

**Expected behavior**
Fragment ids should be different

**Comment by vincenthz** [comment]
if you create 2 identical things, it does, by definition, create twice the same thing. the node will not apply 2 transactional fragments that have the same fragment-id, as a side effect of how things works, not directly though.
