### ISSUE TITLE
Transactions rejected with 'Error or Invalid account: Value calculation failed' - single node, 0.7.0

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#1156]
**Describe the bug**
Transactions rejected with 'Error or Invalid account: Value calculation failed`

**Mandatory Information**
```
jcli 0.7.0 (HEAD-a93d4f67, release, windows [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
jormungandr 0.7.0 (HEAD-a93d4f67, release, windows [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
```

**To Reproduce**
1. start the node - `jormungandr ---genesis-block block-0.bin --config node_config.yaml --secret node_secret.yaml`
2. set `TOTAL_TRANSACTIONS_PER_SOURCE=2000` inside `generate_parallel_txs.sh` script
3. run script for generating transactions - `bash generate_parallel_txs.sh 9001 ed25519e_sk18r7nd20gaxjfgmahyqu2vngv98leqefcdcft2nevcakpf999spx55t4ph8ryqslp6ac7uryekjcqsqzl63rjpmh0k92dvquesweq38cc8a0wc`
- this will generate ~10 txs per second
4. wait for the script to finish

**Expected behavior**
All transactions should be correctly processes by the node.

**Additional context**
- the transactions are mined at a rate of 250 txs per block; due to this, the number of pending transactions is increasing - when there are around 7500 pending txs, these starts to be rejected with the messaje from this issue; no other txs are processed/mined after this moment.

- OS: windows 10
- scenario - single node
- node configs:
[node1.zip](https://github.com/input-output-hk/jormungandr/files/3862951/node1.zip)
- node logs (debug):
[node1_logs.txt](https://github.com/input-output-hk/jormungandr/files/3862953/node1_logs.txt)
- node stats:
```
D:\iohk\otherProjects\jormungandr\scripts\local_cluster>python logs_analyzer.py -l 9001 -t
================= Node 9001 - Transactions per block/epoch ====================
{'Rejected': {'reason': 'Error or Invalid account: Value calculation failed'}}                                     10920
{'InABlock': {'block': 'b645f75192854f181728bf2af3dbb67bff61ff2c1ee210b3ea57eb978270b3d2', 'date': '6826.26'}}     250
{'InABlock': {'block': 'de97473f68b1d9e177ab0b6af0d3a042f4f4ffeedb4035f06b7a3e82704b9ee4', 'date': '6824.36'}}     250
{'InABlock': {'block': '06386135c40de0d5df1bf810c6a6f16e28424fad9cea9c78e5791869fbdc16eb', 'date': '6824.62'}}     250
{'InABlock': {'block': '5e2e24048ba3918d363cc010c690553360eb38401364455762dd204da3c6c15b', 'date': '6826.83'}}     250
```

```
D:\iohk\otherProjects\jormungandr\scripts\local_cluster>python logs_analyzer.py -l 9001 -z
================= Node 9001 - Fragment Status Counts ====================
InABlock: 9090 fragments
Pending : 0 fragments
Rejected: 10920 fragments
======= Node 9001 - Rejected reason count =======
{'Rejected': {'reason': 'Error or Invalid account: Value calculation failed'}}    10920
Name: status, dtype: int64
======= Node 9001 - Rejected fragment_ids =======
['f2faa60e8cbcc8b237805d5a6cc1e88211171cdf5bd54c5023f26a1e0e6e8274'
 '05e941e321395443279df942879f474e99ec307168f2446c8d27ab762fa0d2bc'
 'b20eb92a31e5fb535346204a06f9d3114b4ecd9ddcf1a150659439ee56f47ce2' ...
 'b3b967ddcdfb164832be4f2696d05240d7bbc3e2069af677194f03d0bd2db4d0'
 '189c040953ca480a8ac6c814a7a09c4723be1c09670dd343fec13899bdef2ad6'
 '9cea541bc41e5c713df2d6acdd1fe66567f9372c18d612f365dd9083b4848fcd']
```
```
===== total test time for sending txs (+ 1 new block): 1099 secs = 00:18:19
===== sent transactions : 20000
===== mined transactions: 9080
```

- scripts
[scripts.zip](https://github.com/input-output-hk/jormungandr/files/3862969/scripts.zip)

**Comment by NicolasDP** [comment]
If a transaction is not accepted, it means the transaction is invalid. Look at the transaction that has been rejected, `jcli transaction info` will help you. If you actually see something odd, then please, create an issue.

**Comment by dorin100** [comment]
Actually `transaction info` is showing the same details like for any other tx (counter is incrementing, etc).
- log with tx_info details
[script1Logs.txt](https://github.com/input-output-hk/jormungandr/files/3863826/script1Logs.txt)

I think this issue is related to the no of Pending transactions in the node queue. 

**Scenario 1**: 
- run the node with `TOTAL_TRANSACTIONS_PER_SOURCE=1000`
- issue not reproducible - there will be max 3500 Pending txs in queue. If you wait long enough all of them will be processed and included in blocks;

**Scenario 2**: 
- run the node with `TOTAL_TRANSACTIONS_PER_SOURCE=1500`
- issue not reproducible - there will be max 5500 Pending txs in queue. If you wait long enough all of them will be processed and included in blocks;

**Scenario 3**: 
- run the node with `TOTAL_TRANSACTIONS_PER_SOURCE=1800`
- 

```
D:\iohk\otherProjects\jormungandr\scripts\local_cluster>python logs_analyzer.py -l 9001 -t
================= Node 9001 - Transactions per block/epoch ====================
Pending                                                                                                            8720
{'InABlock': {'block': 'aa0525e7dc987d9b90acb16cb129fc9ce1076c8cbf58ec1a507ef6da01b8c994', 'date': '3784.74'}}     250
{'InABlock': {'block': '694b7bf7310c1a7cfd9b71dcde97b7dcc0c76683470c1ec141ffbccbc66d968e', 'date': '3785.66'}}     250
{'InABlock': {'block': '46d007e951d85401cce5c33fbb078bb78ac228323e2eac94966a38057b6baf14', 'date': '3786.83'}}     250
{'InABlock': {'block': '4f3d32aaae2a8709f7cba2d4c4f73bfd401f9fa322439786f80803839f429ca4', 'date': '3785.184'}}    250
```
- `and in the next second all Pending transactions are Rejected`:
```
D:\iohk\otherProjects\jormungandr\scripts\local_cluster>python logs_analyzer.py -l 9001 -t
================= Node 9001 - Transactions per block/epoch ====================
{'Rejected': {'reason': 'Error or Invalid account: Value calculation failed'}}                                     8506
{'InABlock': {'block': 'aa0525e7dc987d9b90acb16cb129fc9ce1076c8cbf58ec1a507ef6da01b8c994', 'date': '3784.74'}}     250
{'InABlock': {'block': '46d007e951d85401cce5c33fbb078bb78ac228323e2eac94966a38057b6baf14', 'date': '3786.83'}}     250
{'InABlock': {'block': '4f3d32aaae2a8709f7cba2d4c4f73bfd401f9fa322439786f80803839f429ca4', 'date': '3785.184'}}    250
{'InABlock': {'block': '14da7c9a338a1c9ad9ca37a837595ec96bb0ff23d9dd6e2109ca1e959709ba35', 'date': '3785.152'}}    250
{'InABlock': {'block': 'c54fd0d9462180aa3e15fab86e61f26bcb77e45c0c6e9331da4f1dabf4ea397e', 'date': '3784.150'}}    250
{'InABlock': {'block': 'e11d64f2e9015397b821323e964cae0d0e2f03b0061935dc1542f0621020ddaa', 'date': '3785.103'}}    250
```

If you find this and Issue too, I would prefer to reopen this one as I already spent a lot of time saving and adding logs here :).

**Comment by rinor** [comment]
@dorin100 I checked quickly the numbers regarding your transactions and here is what I think happened.

**One** of the causes of the rejection message
```
    "status": {
      "Rejected": {
        "reason": "Error or Invalid account: Value calculation failed"
      }
    }
```
is related to _fund unavailability/depletion_. So I did some math to confirm this.

From your logs
```
================= Node 9001 - Fragment Status Counts ====================
InABlock: 9090 fragments
Pending : 0 fragments
Rejected: 10920 fragments
======= Node 9001 - Rejected reason count =======
{'Rejected': {'reason': 'Error or Invalid account: Value calculation failed'}}    10920
.....
===== total test time for sending txs (+ 1 new block): 1099 secs = 00:18:19
===== sent transactions : 20000
===== mined transactions: 9080
```
there are **20_010** tx in total where:
- **10 tx** - sending funds from faucet to your 10 source addresses
- **20_000 tx** - sent from your 10 source addresses, where:  
  - **9_080 tx** - InABlock 
  - **10_920 tx** - rejected

Now as far as I can tell `script1Logs.txt` doe not contain the exact data from the initial scenario you reported, but the result is the same.

As initial set values you appear to have:
- **1_000_000** lovelaces initial balance for each source address (`INIT_TX_VALUE=1000000`)
- each tx costs you **1_101** lovelaces, from your logs:
```
SRC_COUNTER_INCR  : 0
tx_hash           : 0f4e6c5e11df44c9963cbddcaa1f4fccb49e79e6319db62c18e3600130e338fe
Transaction 2de028f2d8290441e9f4de90287bfad335661bddf676942c4342ebabead30684 (sealed)
  Input:   1101
  Output:  1
  Fees:    1100
  Balance: 0
 - 838aec8fd569fca8f41d63acc4c13cd238e5ca04d01fd2157822f90250a14ee2 1101
 + ca1shj9xut4x54fha7nqw6cj4xkj8p3x6vupjqkvk4d5nv9677thhsrcuzcs8c 1
```
---

So if the numbers are correct you were able to perform **908 tx** per source account before depleting the account funds (292 lovelaces balance) = **9_080** tx in total from 10 source accounts accepted. Let me know if it makes sense.

**Comment by dorin100** [comment]
My theory related to the no of Pending txs was invalidated 
```
D:\iohk\otherProjects\jormungandr\scripts\local_cluster>python logs_analyzer.py -l 9001 -t
================= Node 9001 - Transactions per block/epoch ====================
Pending                                                                                                            11560
{'InABlock': {'block': '5503e3843c0acfef4f9c12b8b754027c766d4c80d5a607e7218a3fcb6e737340', 'date': '3340.389'}}    250
{'InABlock': {'block': 'aa3afb697ca5b7ad61f2dc0d8a6d134ad33f7da057362e15401a8c612664a509', 'date': '3341.66'}}     250
{'InABlock': {'block': '20e45e0eb38279d8371a3f58caea4d2f38465c50eb1f144142e1e05a4af4dc56', 'date': '3340.66'}}     10
```
