### ISSUE TITLE
return stake-pools public VRF key

### ISSUE THREAD

**Issue by gufmar** [input-output-hk/jormungandr#1163]
let 
`jcli rest v0 stake-pools get` also return the VRF public key. 
Perhaps only in the json-formated output to not break existing scripts.

Or alternatively, introduce a new command
`jcli rest v0 stake-pools get-details [pool-ID]` 
and return all publicly known pool-related data (stake, VRF PK, lastGossipReceived, lastFragmentReceived, ...)

**Comment by gufmar** [comment]
ok, don't click on that "try related issues link" on top right when creating a new issue. It will remove the text you just wrote :-/

**Comment by gufmar** [comment]
Similar request to #1099

**Comment by CodeSandwich** [comment]
@gufmar What exactly do you mean by getting `lastGossipReceived` about stake pool?

**Comment by gufmar** [comment]
@CodeSandwich having the VRF public key is great. 
I noted LastGossip, Fragment and BlockReceived is already provided by `network stats get`. So the original demand on this issues request is fulfilled. 

It would be awesome to also have returned the remote Node's IP address by network stats. 

It is not urgent/critical but would be very useful for network diagnostics and a better understanding what's going on (or wrong)

**Comment by CodeSandwich** [comment]
I've created an issue for that: https://github.com/input-output-hk/jormungandr/issues/1261

What about https://github.com/input-output-hk/jormungandr/issues/233#issuecomment-511780194?
