### ISSUE TITLE
jcli how to create an address that is compatible with Daedalus addresses? 

### ISSUE THREAD

**Issue by elviejo79** [input-output-hk/jormungandr#1166]
**Is your feature request related to a problem/context ? Please describe if applicable.**
On the balance check testnet I have created a wallet with Daedalus that has some ADA.
Now I want to create an address with jcli and transfer funds from the Daedauls wallet to the address created with jcil. However it seems that I need to specify a better account parameters with jcli to create o compatible address.

**Describe the solution you'd like**
Step by step commands I would need to execute in the terminal to generate an address with jcli that is compatible with address created with daedaulus.

**Additional context**
I think this feature request might be related to: #450 

@dorin100 maybe you have a suggestion for my question?

**Comment by dorin100** [comment]
@elviejo79 - from what I know, the 2 types of addresses are not compatible. I might worth to raise the same issue also for Daedalus :).

**Comment by mark-stopka** [comment]
This pull request from @SebastienGllmt be related: https://github.com/input-output-hk/chain-libs/pull/165

**Comment by NicolasDP** [comment]
if the address is rejected by Daedalus it is a bug in Daedalus/wallet backend. JCLI creates all the set of addresses that are compatible with the blockchain

**Comment by vincenthz** [comment]
this is a limitation needlessly imposed by the wallet-backend @elviejo79 .. they need to fix their side to make it work.

**Comment by mark-stopka** [comment]
@vincenthz, thanks for pointing it out, next time please remember you don't live in your own ivory tower and report issues to other related projects / teams so they won't appear in publicly launched products, like the issue with legacy address discovery in balance check Daedalus...

**Comment by KtorZ** [comment]
This is a known limitation imposed for the first release of the balance check where **account addresses** would be rejected by Daedalus until development stabilised in this area (UTxO addresses works as normal). 

Although Daedalus will not generate account addresses, there's however no reason to not allow account addresses to be part of transaction outputs made from Daedalus moving forward.

**Comment by vincenthz** [comment]
@mark-stopka this has been reported already 2 weeks ago.
