### ISSUE TITLE
Discordant results between jcli and janalyze about leadership stats

### ISSUE THREAD

**Issue by feqifei** [input-output-hk/jormungandr#1176]
**Describe the bug**
jcli leaders logs show that my pool generated a certain number of blocks that differs from the number shown by the command janalyze.py -a -r

**Mandatory Information**
1. jcli 0.7.0 (HEAD-a93d4f6, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
2. jormungandr 0.7.0 (HEAD-a93d4f6, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
3. Nightly network
4. Pool Id eb873a5a7d35789a5f7b0b84fe2651e59977cb9054767ebd1af5ab10b52a859e

Attached files:
- leaders_epoch_40.log is the output of jcli rest v0 leaders logs get during epoch 40 when my pool already generated some blocks. During the whole epoch 40 janalyze never showed statistics about my pool
- leader_epoch_43.log. You can see that my pool generated three blocks during epoch 43.
- janalyze_epoch_43.log. You can see that janalyze lists only two blocks for the pool ID.
[janalyze_epoch_43.log](https://github.com/input-output-hk/jormungandr/files/3877538/janalyze_epoch_43.log)
[leader_epoch_43.log](https://github.com/input-output-hk/jormungandr/files/3877539/leader_epoch_43.log)
[leader_epoch_40.log](https://github.com/input-output-hk/jormungandr/files/3877540/leader_epoch_40.log)

**Comment by papacarp** [comment]
This is normal.  Your leader logs designate how many blocks you have generated from your node.  However, its quite possible that multiple nodes generated blocks for that same epoch/slot which leads to competition as there can only be ONE block at a specific epoch/slot.  

Janalyze will examine which pool successfully WON the block for that slot.   It does this by working backwards from the TIP and looking at parent blocks in succession. In your case, you lost and this block was not in the final chain.  

Please reach out on telegram (@papacarp) for more information and I'll give you some links to our lostblock.py script that will alert you whenever you have lost a block like this.

**Comment by feqifei** [comment]
thanks papacarp, I'll contact you on telegram.

**Comment by feqifei** [comment]
papacarp provided me explanations about the competition on generating blocks.
Links
https://medium.com/unraveling-the-ouroboros/introduction-to-ouroboros-1c2324912193
Script to check lost blocks
https://raw.githubusercontent.com/rdlrt/Alternate-Jormungandr-Testnet/master/scripts/lostblocks.py
