### ISSUE TITLE
bootstrap script to create accounts with error

### ISSUE THREAD

**Issue by dmernies-atix** [input-output-hk/jormungandr#1182]
**Describe the bug**
When the bootstrap script is run with ./bootstrap -o -g it shows the following error: "./bootstrap: 56: set: Illegal option -o pipefail".

**Mandatory Information**
1. jcli 0.7.1 (master-65ea6fce, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
2. jormungandr 0.7.1 (master-65ea6fce, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

**To Reproduce**
1. Download jourmungander
2. Go to 'scripts'
3. Exec ./bootstrap -o -g

**Expected behavior**
The files to create a new account is expected.

**Additional context**
Running jormungandr on localhost

**Comment by enzoc4** [comment]
I saw this too, I think it was introduced by #1131. It's because the shebang is for posix shell, and `set -o pipefail` is not POSIX. Probably the easiest solution is to change the shebang to bash?

**Comment by eugene-babichenko** [comment]
The workaround would be to check if this option is actually available on the current shell with something like `set -o | grep 'pipefail'`. I don't like the idea of being tied to a particular shell.
