### ISSUE TITLE
0.7.1 Node startup fails with logging options in config

### ISSUE THREAD

**Issue by Linicks** [input-output-hk/jormungandr#1184]
**Describe the bug**
In version 0.7.1  the node fails to start with this warning when the logging options are included in the node configuration file.  Once you remove the options from the configuration the node starts up.

Error:

Error in the overall configuration of the node
 |-> Error while parsing the node configuration file: log: invalid type: map, expected a sequence at line 3 column 9
 |-> log: invalid type: map, expected a sequence at line 3 column 9

Configuration Params:

---
log:
  format: plain
  level: info
  output: stderr
p2p:
### Rest of config ....

**Mandatory Information**
1. `jcli --full-version` output;
jcli 0.7.1 (HEAD-c57466d, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
2. `jormungandr --full-version` output;
jormungandr 0.7.1 (HEAD-c57466d, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

**To Reproduce**
Connect a node to the current nightly test-net with these options.

**Comment by rinor** [comment]
There was a change regarding logging in https://github.com/input-output-hk/jormungandr/pull/1134 also mentioned in release log.
the correct config is now:
```
log:
  - output: stderr
    level:  info
    format: plain
```

**Comment by Linicks** [comment]
@rinor Fantastic!  I read the changelog but didn't catch this and I think others were in the same boat.  I made the change in my configuration and all worked well.  Thanks, I'll share with others on TG!
