### ISSUE TITLE
Dummy node creation without demo script

### ISSUE THREAD

**Issue by CodeSandwich** [input-output-hk/jormungandr#119]
**Is your feature request related to a problem/context ? Please describe if applicable.**
Currently the only way to conveniently create a dummy node is with the demo script. Unfortunately it does not work on Windows out of the box and requires installation of additional tools. It's also hard to configure on other platforms, it requires specific binaries built and put to specific directories.

**Describe the solution you'd like**
The solution could be migration from a bash script to a Rust binary. It would make it portable and it could include all tools required for node creation without any dependencies in runtime.

**Additional context**
The dummy node is needed by developers and testers. It won't be used by end users or power users.

**Comment by CodeSandwich** [comment]
Bikeshedding question: what binary should generate nodes. There are at least 3 options:
1. Jormungandr
  * Pros
    1. Distributed to everyone
  * Cons
    1. Not needed by 99,99% of users
    1. Purpouse of this binary is running a node, it's confusing to use it as a shell tool to generate configs
1. Jormungandr-cli
  * pros
    1. This is a power user tooling binary and dummy node generator is such tool
    1. Key generation code is already there, less refactoring
  * cons
    1. Requires distribution along Jormungandr to run a dummy node
1. A new binary
  * pros
    1. It does not litter previous binaries
    1. Usage is obvious and trivial
  * cons
    1. Yet another binary to remember and maintain
    1. Requires distribution along Jormungandr to run a dummy node

**Comment by NicolasDP** [comment]
The creation of a node is fairly easy now and well documented. There is a windows/linux/osx compatible test suite for the node too.

**Comment by carl-shepherd** [comment]
Hello Alexander,

We'd love to hear what you think of our customer service. Please take a moment to tell us. How would you rate the support you received? Please one of these in your reply that will help us to report on our efforts to the team.

Good, I'm satisfied
Bad, I'm unsatisfied

Thanks,
The IOHK Technical Support Desk Team
