### ISSUE TITLE
0.7.4 Node randomly shuts itself down.

### ISSUE THREAD

**Issue by bjarnekvae** [input-output-hk/jormungandr#1216]
**Describe the bug**
The node shuts itself down after ~15 min of running, last line in log:
`Nov 27 14:03:28.467 INFO Shutting down node`
Happened 3 times in a row.

**Mandatory Information**
1. `jcli --full-version` output; jcli 0.7.4 (HEAD-4a1463a, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
2. `jormungandr --full-version` output; jormungandr 0.7.4 (HEAD-4a1463a, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

**To Reproduce**
Start and run the node, the error does not seem to be hard to reproduce

**Expected behavior**
The node should not shut down

**Additional context**
Logs:
[shutdown.zip](https://github.com/input-output-hk/jormungandr/files/3896947/shutdown.zip)

**Comment by mzabaluev** [comment]
Please do not collect strace as a matter of course. It's rarely needed and it adds a lot of bulk to the troubleshooting data. Thank you.

**Comment by mzabaluev** [comment]
Is there a panic backtrace on the standard output?

**Comment by bjarnekvae** [comment]
No, as you seen in the node_log the node just shuts down, no error or warning.
