### ISSUE TITLE
0.7.3-0.7.4, error compiling jormungandr-lib v0.7.3-0.7.4

### ISSUE THREAD

**Issue by ruslansoluyanov** [input-output-hk/jormungandr#1217]
Jormungandr is not installed at the cargo compilation stage.

0. CentOS Linux 7 (Core), Linux version 3.10.0-1062.4.3.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) )
1. rustc 1.39.0, stable-x86_64-unknown-linux-gnu unchanged (4560ea788 2019-11-04)
2. jormungandr v0.7.4
3. jcli v0.7.4

**To Reproduce**
0. `ls -lrt && rustup install stable && rustup default stable && git clone --recurse-submodules https://github.com/input-output-hk/jormungandr && cd jormungandr && git checkout tags/v0.7.4 && cargo install --path jormungandr && cargo install --path jcli`
1. `Compiling jormungandr-lib v0.7.4 (/home/1zmena/jormungandr/jormungandr-lib)
error[E0063]: missing field `per_certificate_fees` in initializer of `chain_impl_mockchain::fee::LinearFee`
 --> jormungandr-lib/src/interfaces/linear_fee.rs:5:66
  |
5 | #[serde(deny_unknown_fields, rename_all = "snake_case", remote = "LinearFee")]
  |                                                                  ^^^^^^^^^^^ missing `per_certificate_fees`

   Compiling prost-types v0.5.0
error: aborting due to previous error

For more information about this error, try `rustc --explain E0063`.
error: could not compile `jormungandr-lib`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `jormungandr v0.7.4 (/home/1zmena/jormungandr/jormungandr)`, intermediate artifacts can be found at `/home/1zmena/jormungandr/target`

Caused by:
  build failed`

Same error I saw when compiling 0.7.3

**Comment by eugene-babichenko** [comment]
Try calling `git submodule update` after you switch to another branch/tag.

**Comment by eugene-babichenko** [comment]
The command will become `ls -lrt && rustup install stable && rustup default stable && git clone --recurse-submodules https://github.com/input-output-hk/jormungandr && cd jormungandr && git checkout tags/v0.7.4 && git submodule update && cargo install --path jormungandr && cargo install --path jcli`

**Comment by ruslansoluyanov** [comment]
It's worked, thank u!
