### ISSUE TITLE
0.7.4 - Blocks not getting added to chain

### ISSUE THREAD

**Issue by stakeyourada** [input-output-hk/jormungandr#1220]
**Describe the bug**
I have a leader node which is running and generating blocks when scheduled, however looking at nightly explorer it seems like none of the slots are getting added to the chain.

**Mandatory Information**
1. `jcli --full-version` output;
 jcli 0.7.4 (HEAD-4a1463ac, release, windows [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

2. `jormungandr --full-version` output;
jormungandr 0.7.4 (HEAD-4a1463ac, release, windows [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

**To Reproduce**
1. upgraded from 0.7.0 to 0.7.4, did not delete the DB 2. Wait for scheduled slots to get generated 3. Check https://explorer.nightly.jormungandr-testnet.iohkdev.io/ and try to locate the slot or block which the node generated. 
4. Can never find either. No other node processed the slot and the block does not exist. 

Id Created Scheduled Finished Status Block Wake_at -- -------------------- ---------- -------------------- -------- ---------------------------------------------------------------- -------------------- 1 2019-11-27 15:53:54Z 77.3856 2019-11-27 16:06:13Z Block 0dbf6394b9d341dacdc07f8833e2fe30d2d58aa4bf337f89f629d1f2dc93d3bc 2019-11-27 16:06:13Z 1 2019-11-27 15:53:54Z 77.4068 2019-11-27 16:13:17Z Block 97637b511bd3531e6ac1ae6d159b349b6341ebfba91ffe474e8e036ccebe344a 2019-11-27 16:13:17Z 1 2019-11-27 15:53:54Z 77.4547 2019-11-27 16:29:15Z Block 7a59ed9c0852317a75ef873e0565d62ffae3686ec8ab71b81eea7c1f5b382cc4 2019-11-27 16:29:15Z 1 2019-11-27 15:53:54Z 77.4555 2019-11-27 16:29:31Z Block 70211a0c4761ebb4a4f06474f711eb94b9debdd443c7ff7eda94f5c66cdb4535 2019-11-27 16:29:31Z 1 2019-11-27 15:53:54Z 77.6009 Pending 1 2019-11-27 15:53:54Z 77.6303 Pending 1 2019-11-27 15:53:54Z 77.6827 Pending

**Expected behavior**
I expect all slots to be included in the chain. I expect any slot my node successfully processed to show in the explorer. I expect the block to be found in the explorer.
![Annotation 2019-11-27 105253](https://user-images.githubusercontent.com/57019181/69745426-cb365400-1107-11ea-9c3c-7e3a77b980ec.png)
![Annotation 2019-11-27 105313](https://user-images.githubusercontent.com/57019181/69745427-cbceea80-1107-11ea-8ac5-bba4cfcea283.png)

**Additional context**

**Comment by stakeyourada** [comment]
this is no longer reproducible on nightly with 0.8.0-rc1, latest hash

**Comment by NicolasDP** [comment]
I believe this is fixed with #1290. It will be included in the next release.

The network was hanging on the blockchain task, this has been addressed now.
