### ISSUE TITLE
0.7.5 (or nightly testnet) - generated blocks are not added to the blockchain

### ISSUE THREAD

**Issue by feqifei** [input-output-hk/jormungandr#1221]
**Describe the bug**
In nightly testnet generated blocks are not added to the blockchain even if are correctly generated by the pool. 
No error messages in log. 
I don't know if it's a version problem or a nightly testnet one. 

**Mandatory Information**
1. `jcli 0.7.5 (HEAD-c07bbfe, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
2. jormungandr 0.7.5 (HEAD-c07bbfe, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

**To Reproduce**
On my pool all generated blocks have not been added to the blockchain. See attachment. 

**Additional context**
Doc describes some cases
[missing blocks in blockchain.docx](https://github.com/input-output-hk/jormungandr/files/3898045/missing.blocks.in.blockchain.docx)

**Comment by hodlonaut** [comment]
Observing the same issue on the private testnet using 0.7.5 binaries, in both passive and leader nodes... 'received block notification' log messages are visible, but the lastBlockHeight is not being incremented in either case.

**Comment by NicolasDP** [comment]
I believe this is fixed with #1290 and #1292 . It will be included in the next release
