### ISSUE TITLE
0.8.0-rc2 - Node still shutting down on beta testnet

### ISSUE THREAD

**Issue by feqifei** [input-output-hk/jormungandr#1234]
**Describe the bug**
Hello, I updated the node to the latest 0.8.0-rc2, but the shutting down issue still happens.
The node is working on a blocks.sqlite db fully downloaded through the previous exe version 0.8.0-rc1.
RUST_BACKTRACE =full doesn't add anything more in the log file.
I have a twin node running on nightly using the same exe version but since it's using a new hash I don't face a similar problem.

**Mandatory Information**
1. jcli 0.8.0-rc2 (HEAD-f262db1, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
2. jormungandr 0.8.0-rc2 (HEAD-f262db1, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

**To Reproduce**
1. start the node and after a while (10-30 minutes) I receive this error:
Nov 30 06:56:16.154 DEBG finished pushing headers, node_id: c7c177287f893d18bc391cde59deddb05ac1b70be3acbefc, peer_addr: 95.216.251.22:3101, task: network
Nov 30 06:56:16.383 INFO service finished with error, task: client-query
Nov 30 06:56:16.383 INFO Shutting down node

**Additional context**
I attach the full log in debug mode

[nohup.log](https://github.com/input-output-hk/jormungandr/files/3906827/nohup.log)

**Comment by NicolasDP** [comment]
I believe this is fixed with #1290 and #1292 . It will be included in the next release
