### ISSUE TITLE
bootstrap.sh - error: The following required arguments were not provided:     --serial <SERIAL>

### ISSUE THREAD

**Issue by laplasz** [input-output-hk/jormungandr#1244]
**Describe the bug**
When using bootstrap.sh for the first time got the following error msg:

```
error: The following required arguments were not provided:
    --serial <SERIAL>
```

**Mandatory Information**
jcli 0.7.0-rc1 (HEAD-5583e5e, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
jormungandr 0.7.0-rc1 (HEAD-5583e5e, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

**To Reproduce**
./bootstrap.sh

**Expected behavior**
no error

**Additional context**
on https://testnet.iohkdev.io/en/cardano/shelley/get-started/setting-up-a-self-node/ there is no any hint which version should be downloaded or built.

**Comment by rdlrt** [comment]
Not exactly a github issue, the version you're using is old. Consider joining the [telegram workgroup](https://t.me/CardanoStakePoolWorkgroup) - if you havnt already or use [zendesk support](iohk.zendesk.com/hc/en-us/requests/new) for assistance.

**Comment by NicolasDP** [comment]
checkout the sources to the right tag: `git checkout v0.7.0-rc1`. The scripts will be compatible with your version then.

**Comment by laplasz** [comment]
I think this a github issue  - since it turned out there is not version check between the scripts and the application, and the scripts are not part of the release packages.
