### ISSUE TITLE
Expose rewards and treasury parameters inside the `jcli rest v0 settings get`

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#1260]
**Describe the bug**
Expose rewards and treasury parameters inside the `jcli rest v0 settings get`

**Mandatory Information**
0.8.0

**To Reproduce**

**Expected behavior**
The `jcli rest v0 settings get` command would expose the useful details inside the genesis file.

**Additional context**
- to be taken into consideration:
```
    "reward_parameters": {
      "halving": {
        "epoch_rate": 3,
        "epoch_start": 1,
        "ratio": "13/19",
        "constant": 100
      }
    }
```
```
"treasury": 0
```
```
per_certificate_fees
```

**Comment by NicolasDP** [comment]
duplicate of #1248
