### ISSUE TITLE
Downloading data on incentivized node is very slowly

### ISSUE THREAD

**Issue by congle-ibl** [input-output-hk/jormungandr#1262]
Hi all,

I'm re-downloading incentivized node with version v0.7.5 but it's quite slowly than before. It seems that each block is processed very slowly. After 30 minutes, it just downloaded 96 blocks only.
```
state | "Running"
-- | --
blockRecvCnt | 96
lastBlockDate | "0.115211"
lastBlockFees | 0
lastBlockHash | "183ba68585b8d14b703adbd29cdf3d6144e05963e9f6e798ba404b403e6d922a"
lastBlockHeight | "2096"
lastBlockSum | 0
lastBlockTime | "2019-12-03T10:08:55+00:00"
lastBlockTx | 0
txRecvCnt | 0
uptime | 1869
```
Am I missing something in configuration or could you give me some suggestion to speed it up? Thank you so much for your time.

**Comment by NicolasDP** [comment]
Thanks. This has been fixed in `0.8.0-rc7`.
