### ISSUE TITLE
0.8.0 rc5 block production slowing

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/jormungandr#1270]
**Describe the bug**

Graph shows block production slowing after working fine at first:

![nightly-block-slowing](https://user-images.githubusercontent.com/651205/70078556-e5bd7100-15d0-11ea-9f27-1bb1b71489bc.png)

**Mandatory Information**
1. `jcli --full-version` output;
2. `jormungandr --full-version` output;

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by NicolasDP** [comment]
<img width="570" alt="Screenshot 2019-12-03 at 18 32 25" src="https://user-images.githubusercontent.com/5445840/70078870-7d37b980-15fb-11ea-95f0-dd499b477ad2.png">

not really slowing

**Comment by disassembler** [comment]
Too small of a sample size with new genesis
