### ISSUE TITLE
jormungandr 0.8.0-rc5-cecea4d got stuck on synchronisation

### ISSUE THREAD

**Issue by bohenicus** [input-output-hk/jormungandr#1273]
I'm trying to run jormungandr (on beta blockchain, version jormungandr 0.8.0-rc5-cecea4d and 
jcli 0.8.0-rc5)
as a passive node. Every time jormungandr  got stuck on while synch-ing.
I'm testing the version on two different hosts (on different ports) - one host on x86_64-linux and second on armv7-linux 

Both of hosts are getting stuck every time while synch-ing, eg:

blockRecvCnt: 515
lastBlockDate: "3.3557"
lastBlockFees: 0
lastBlockHash: b9b8f3a019346234ce2fc0943bf87cc1e1bc1c0aec273944c149a4b2842934af
lastBlockHeight: "2512"
lastBlockSum: 0
lastBlockTime: "2019-12-03T19:21:02+00:00"
lastBlockTx: 0
state: Running
txRecvCnt: 1
uptime: 3385

and the second:

blockRecvCnt: 185
lastBlockDate: "3.175"
lastBlockFees: 0
lastBlockHash: 93b6b9c5dc69f9ebe885f5f961d9e436ff6227a30da2a2e63ab857d66164e38c
lastBlockHeight: "2160"
lastBlockSum: 0
lastBlockTime: "2019-12-03T19:52:57+00:00"
lastBlockTx: 0
state: Running
txRecvCnt: 0
uptime: 1445

node is run like this:
./jormungandr --config ./node-config.yaml --genesis-block-hash 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29  > ./logs/node.out

My node-config.yaml is:
{
  "log": [{
    "format": "plain",
    "level": "info",
    "output": "stderr"
  }],
  "p2p": {
    "topics_of_interest": {
      "blocks": "normal",
      "messages": "low"
    },
    "trusted_peers": [
      {
        "address": "/ip4/52.9.85.113/tcp/3000",
        "id": "7f47c880339670ad98d38ad3b379e1f7853479f8ef4f6fc7"
      },
      {
        "address": "/ip4/13.57.72.175/tcp/3000",
        "id": "b8b20f58b34dd7a485c8cff0d67f800149b1ff220b826632"
      },
      {
        "address": "/ip4/52.8.62.219/tcp/3000",
        "id": "f51aa0ce82b7f061e12762bd22b84424129f690655441b8e"
      },
      {
        "address": "/ip4/52.194.124.233/tcp/3000",
        "id": "255df5de725cd9d1087b8a3e4ff66d65572c36ceed791679"
      },
      {
        "address": "/ip4/52.197.220.18/tcp/3000",
        "id": "50768a0bb41781baa551cd96fb46a62e666e97874bca1cf5"
      },
      {
        "address": "/ip4/3.125.20.154/tcp/3000",
        "id": "ddfea960bc2fe1aa45af9b385b6bd3e949c050df61b5b451"
      },
      {
        "address": "/ip4/3.124.255.35/tcp/3000",
        "id": "2b7216b51b890ef1e8ade8e513dd6f2b35173e46b08ac1a9"
      }
    ]
  },
  "rest": {
    "listen": "127.0.0.1:3101"
  },
  "storage": "/home/pi/Cardano/sql_working/"
}
 
Last log entries:
Dec 03 22:07:17.357 INFO received block announcement, hash: 31a96d00ed9144702f46d144241c0c65ff75caefb380e679b1774870bc405d3d, direction: in, stream: block_events, node_id: 13a1c1938ba4267467121dd0b1defabdf7d6ed33e1ece683, peer_addr: 3.125.55.146:3000, task: network
Dec 03 22:07:17.375 INFO received block announcement, hash: 31a96d00ed9144702f46d144241c0c65ff75caefb380e679b1774870bc405d3d, direction: in, stream: block_events, node_id: ec434246c6b12fc6f45d0d7a939a6a06edfb9aebcbd9e8d7, peer_addr: 142.93.41.221:8010, task: network
Dec 03 22:07:17.472 INFO received block announcement, hash: 31a96d00ed9144702f46d144241c0c65ff75caefb380e679b1774870bc405d3d, direction: in, stream: block_events, node_id: 6fc684aa224287d2d219abb5dceda73d0e073e81747e34ff, peer_addr: 95.216.251.22:3100, task: network
Dec 03 22:07:21.370 INFO connecting to peer, node_id: 1f7a224ff5f665bc240a1107d0c4fa4eb75a9f1dac25b6d5, peer_addr: 137.135.247.150:3100, task: network
Dec 03 22:07:21.374 INFO connecting to peer, node_id: fbf524764ecced61ba89c6f41fb4e4face95a009fefe0be3, peer_addr: 34.66.35.112:31400, task: network
Dec 03 22:07:21.378 INFO connecting to peer, node_id: b1e31c0f6297a074fadbccc6dbffc65a4d52aaab7b565b57, peer_addr: 137.117.87.183:3100, task: network
Dec 03 22:07:21.382 INFO connecting to peer, node_id: 3bac7ba2da3efaeaa24e1e8ef5cf89aa837e38cfecaa692f, peer_addr: 144.76.40.23:3333, task: network
Dec 03 22:07:21.388 INFO connecting to peer, node_id: 12662c26edde28cd53275f87c07e416d4439262874ad2498, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:21.393 INFO connecting to peer, node_id: 9fd89744cc8807eb65237a2d2b695199be73515eeb825fa3, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:21.398 INFO connecting to peer, node_id: 84911de641641d2caffdd3ad4a886c697be55d41642243b4, peer_addr: 37.223.25.33:14510, task: network
Dec 03 22:07:21.401 INFO connecting to peer, node_id: 7dcbfa6c2a85c1f6671a2770de59222c5ff92c7a506ee698, peer_addr: 50.116.38.107:3100, task: network
Dec 03 22:07:21.403 INFO connecting to peer, node_id: 1f366b320b5e1145f39e0c288effc97ac17f6e9b0c389e70, peer_addr: 116.203.42.12:3000, task: network
Dec 03 22:07:21.405 INFO connecting to peer, node_id: f86d67083d1bef2f4db47b5a5d5cb49061b183fb888d331d, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:21.408 INFO connecting to peer, node_id: 20ee731de9bb688abb4c96a2b4a32d013d0dfc2e93e1562b, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:21.410 INFO connecting to peer, node_id: 0967faf9c641631fd8a62ccaeb792a6c75a3805903e4fcea, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:21.412 INFO connecting to peer, node_id: de7264fe966f8949c3ceeeaa82c0d9da7e0567f1b44e9d28, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:21.414 INFO connecting to peer, node_id: e180ac7cbf494958a20357b42523603c1f49a76734d268b7, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:21.416 INFO connecting to peer, node_id: 0afbd0e8858ea869310ab0a28f1a0dfee1d6a2cffe097d25, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:24.923 INFO connecting to peer, node_id: 7b3cab90bf791201d327f328be705f9aa9e72c527bdc5f0f, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:24.937 INFO connecting to peer, node_id: 3bac7ba2da3efaeaa24e1e8ef5cf89aa837e38cfecaa692f, peer_addr: 144.76.40.23:3333, task: network
Dec 03 22:07:24.942 INFO connecting to peer, node_id: ffda96476cb6e874b291845c9de5479d29b80eabaa574e3a, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:24.949 INFO connecting to peer, node_id: 20f9ce3e408b53382f01c96198789e55a0cb3fc5e8f1e1df, peer_addr: 50.116.38.107:3100, task: network
Dec 03 22:07:24.956 INFO connecting to peer, node_id: 84911de641641d2caffdd3ad4a886c697be55d41642243b4, peer_addr: 37.223.25.33:14510, task: network
Dec 03 22:07:24.962 INFO connecting to peer, node_id: b1e31c0f6297a074fadbccc6dbffc65a4d52aaab7b565b57, peer_addr: 137.117.87.183:3100, task: network
Dec 03 22:07:24.969 INFO connecting to peer, node_id: 004341fc5d1e4a79296b42b9fd2be3f7badaffd1cbde721e, peer_addr: 50.116.38.107:3100, task: network
Dec 03 22:07:24.973 INFO connecting to peer, node_id: b917049219ed1ef0b5d8551b0a0d8ece405568841597d01e, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:24.979 INFO connecting to peer, node_id: fbf524764ecced61ba89c6f41fb4e4face95a009fefe0be3, peer_addr: 34.66.35.112:31400, task: network
Dec 03 22:07:24.987 INFO connecting to peer, node_id: 45580a69c0ed887bb1fd01cb558c3b64722034afc5a96d10, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:24.995 INFO connecting to peer, node_id: 7dcbfa6c2a85c1f6671a2770de59222c5ff92c7a506ee698, peer_addr: 50.116.38.107:3100, task: network
Dec 03 22:07:24.999 INFO connecting to peer, node_id: 0351607feb82dfc235e70ac1189503597dc7eb1760270b43, peer_addr: 50.116.38.107:3100, task: network
Dec 03 22:07:25.007 INFO connecting to peer, node_id: 215d2cc5fa3d86d203aee5604103aab4617da74559b0132c, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:26.966 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 4e5c04f2c70a5da75a63c7ae87aa24a17be76b8b294a3f18, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:26.967 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 41980fa8b78bc66ecf1f9285b70e6b45726de3a45c1ee494, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:34.919 WARN blockchain is not moving up, the last block was 1610943 seconds ago, task: stuck_notifier
Dec 03 22:07:34.927 INFO connecting to peer, node_id: 0845a73a4ff7544448b79a73f0582041d4b30cffd0241a0e, peer_addr: 46.101.204.59:9050, task: network
Dec 03 22:07:34.940 INFO connecting to peer, node_id: 16279fcb1dfb9801bda68eafb0f19b1cbd0aaf592fefcfdd, peer_addr: 78.21.94.247:3000, task: network
Dec 03 22:07:34.944 INFO connecting to peer, node_id: fc4602a0fca917ea2c45abd17b0a69189f013b48766a4691, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:34.947 INFO connecting to peer, node_id: f86d67083d1bef2f4db47b5a5d5cb49061b183fb888d331d, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:34.959 INFO connecting to peer, node_id: 1f7a224ff5f665bc240a1107d0c4fa4eb75a9f1dac25b6d5, peer_addr: 137.135.247.150:3100, task: network
Dec 03 22:07:34.970 INFO connecting to peer, node_id: 4a93dbf2e4f5b282ed4060b241ccefa03597c3e250ee4c67, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:34.980 INFO connecting to peer, node_id: c73fcb411cee62b85735bb4b34d6998db956f62b162d8ac0, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:37.207 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 1d622639d93d6b0f04a1ff01ba80c27c65123baa28f3c0a7, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:37.208 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 68ee47531e0cba0e6f795e1732e004caa3c3a1859b44dcb5, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:44.926 INFO connecting to peer, node_id: 2521970ab832988d26f86fe656a51b5fc710baaf8576c31c, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:44.933 INFO connecting to peer, node_id: d6f25f0af85f490bf634da3de1aba47a53ec4bccb1e4d1b7, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:44.955 INFO connecting to peer, node_id: ac6c59807331eec5f8a2bdaf1ea7a0cb00acf0cc180ad55b, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:44.967 INFO connecting to peer, node_id: 1e2609c3324d047f128a678237503c3b88f26198a683590e, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:44.980 INFO connecting to peer, node_id: e180ac7cbf494958a20357b42523603c1f49a76734d268b7, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:45.255 INFO disconnecting client, node_id: 9be896234e0e889ee4b32702164ed17e5d4ffd7d0667e1f7, peer_addr: 37.0.94.41:3000, task: network
Dec 03 22:07:47.446 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: b3ed21990bcf2b53469fad8b486f8c6cfe3b41c3b5307ee2, peer_addr: 116.203.42.12:3000, task: network
Dec 03 22:07:47.455 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 54abfa30ecb1223a4d1992999e382fb9e2041c00612a21c5, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:47.460 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: ea992bdb65af6ba8994cd4c39c77d2a164f58626617e7220, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:47.464 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 615816b8cdeef4209ae868c09f1c3338cc7e327b4b779406, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:47.469 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 42c442419ba31457e227dfa5e7f6793997f5ca31eb369716, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:47.475 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: e97e517f07c99e3a192cfae56640443a34864ae8417a9331, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:47.479 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: fdf2abed4e7f982408ceb68f41c82be578563203765035b6, peer_addr: 45.32.64.190:3105, task: network
Dec 03 22:07:51.299 INFO received block announcement, hash: 2a916f71a430f3a3974a3e1089cb1a9b63e54dd3cd96edeaeae8d1d7109556a2, direction: in, stream: block_events, node_id: c0e33c8a002fd6ce5dff835a13d0cfdbec3235ebcb0fed46, peer_addr: 116.233.83.147:3300, task: network
Dec 03 22:07:51.390 INFO received block announcement, hash: 2a916f71a430f3a3974a3e1089cb1a9b63e54dd3cd96edeaeae8d1d7109556a2, direction: in, stream: block_events, node_id: 7fba22e77017da8f3b5a4709da9f2aeed87f5ea42054ea79, peer_addr: 148.251.90.119:3000, task: network
Dec 03 22:07:54.919 INFO connecting to peer, node_id: 6a2e6f3a10a9b399c31824db18b5642997c4457240baf098, peer_addr: 116.203.42.12:3000, task: network
Dec 03 22:07:54.927 INFO connecting to peer, node_id: 204174f580c18abd57e1a1f713e14e8a3946ec5bfbf5bc46, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:54.941 INFO connecting to peer, node_id: 7dab423d1b821b19d9b86094e3a12379c6dd9c7d52f88a9a, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:54.952 INFO connecting to peer, node_id: 5fe3d72abb6a0b762e91d87322d556b0bc78792b9c8be311, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:54.974 INFO connecting to peer, node_id: 7fe7c57851cb7b46b7685542ddba090fd5f103289182d86d, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:54.982 INFO connecting to peer, node_id: 4c341a091ce58c0c68f0d99d4fd5f55f6702622f3f217ef1, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:54.993 INFO connecting to peer, node_id: eeafcfd0eea6ddafb434e7fb3b7ba1b54d501731be63a1da, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:55.000 INFO connecting to peer, node_id: 806162e3771190d9b58a481dc88a521ec048ce0b0046ae96, peer_addr: 185.254.190.11:3000, task: network
Dec 03 22:07:55.007 INFO connecting to peer, node_id: 9d4ba6972aed0ac60aea99b546793fe3de9db8cf82cd5847, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:55.015 INFO connecting to peer, node_id: 27af40ba54ee07792603680402d00991587d548d7124bf41, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:55.020 INFO connecting to peer, node_id: dfb82f592463e7878b14f96aa580080d396e90e47e1a2630, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:56.807 INFO disconnecting client, node_id: f7d376616cd5613cc456eedf448f05d135cc98f8b7eb99fe, peer_addr: 144.91.101.52:8001, task: network
Dec 03 22:07:57.686 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: bad76b777528e0ec81bc1f6405176c4eb511caf27091df50, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:57.695 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: e355399a6869dda03ee8e4dfe8ddf4e0f50cb63371a4d21e, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:57.703 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 680ef7a79f8c45ba02c5dd5dbac198dda3a9b7100effd6e2, peer_addr: 37.223.25.33:14509, task: network
Dec 03 22:07:57.711 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: c5387bbaa64135e8d479b60448fcb5749055aef3bd6abdeb, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:07:59.446 INFO disconnecting client, node_id: 3bac7ba2da3efaeaa24e1e8ef5cf89aa837e38cfecaa69af, peer_addr: 51.79.35.204:6666, task: network
Dec 03 22:08:04.926 INFO connecting to peer, node_id: 5ff35d2b0ab8b95195cb1cd6ae2fcd2039c933e50bb8555a, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:08:04.933 INFO connecting to peer, node_id: de7264fe966f8949c3ceeeaa82c0d9da7e0567f1b44e9d28, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:08:04.943 INFO connecting to peer, node_id: 1f1d77f7109bf1c79b374c8d9906d0b21800efabf8d0a2ce, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:08:04.959 INFO connecting to peer, node_id: 478b52da4abef272bfc24263fde6379e7b80caa0b471335b, peer_addr: 187.133.75.92:3100, task: network
Dec 03 22:08:04.970 INFO connecting to peer, node_id: 1f366b320b5e1145f39e0c288effc97ac17f6e9b0c389e70, peer_addr: 116.203.42.12:3000, task: network
Dec 03 22:08:04.988 INFO connecting to peer, node_id: c6706dc40c7b11b94fe516befeaaa50a266c8a77f8026b1d, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:08:05.000 INFO connecting to peer, node_id: 1be011bab553d7fb6430a8a96e9290b521c6046c1444782a, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:08:05.485 INFO failed to connect to peer, reason: Connection refused (os error 111), node_id: 478b52da4abef272bfc24263fde6379e7b80caa0b471335b, peer_addr: 187.133.75.92:3100, task: network
Dec 03 22:08:07.926 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: f3a1a78742bb2a2036ed8e048e36f14250d4293feca91385, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:08:07.934 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 3a55c90ae7e51aaf2152db5b2e9fb6fe6f3787a1c02e61a8, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:08:07.938 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 1138e2d1dcee95e1dfa25dac77d6cc07456ff3931b43c6ba, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:08:14.919 INFO connecting to peer, node_id: 92b4c07620dcc61f8cac35f1a98a7c7178b77dd85406b355, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:08:14.928 INFO connecting to peer, node_id: 71a71d9b11ea1462f1265b653253e2177cc76be758896504, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:08:14.934 INFO connecting to peer, node_id: 4e43f41786ee0146761a1726d55456f1c659a1e73abe0c61, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:08:14.936 INFO connecting to peer, node_id: 0afbd0e8858ea869310ab0a28f1a0dfee1d6a2cffe097d25, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:08:14.946 INFO connecting to peer, node_id: e99e5d56b0bdfb8b0ff8438285a1f4fa816fb631bd5733b5, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:08:14.970 INFO connecting to peer, node_id: f27665357f5289b0fc3911d4f2286d5198a16a7366aefc1c, peer_addr: 50.116.38.107:3100, task: network
Dec 03 22:08:17.340 INFO received block announcement, hash: 0bd23a28dd861ad4d5fcd29685560b305780284d55f9adc8e435785a88a3055a, direction: in, stream: block_events, node_id: 6d38e77753f158cd2c6bb8e123a82d1199fe8c76d8dd0545, peer_addr: 40.118.186.37:5222, task: network
Dec 03 22:08:18.166 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 7006729539d6886711bb7c836408448fb82be95c10cfe73b, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:08:18.167 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 10c93d3c9c85c96d943f2058540b06ba31e8cab8acc207ef, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:08:18.167 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 8df844cf9d01927cce9caa779baceedcaa2c73c8c19c9f37, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:08:18.168 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 16b43f41a71fe30bf91f7dd5e9ccc7f2cc1129d337027b64, peer_addr: 106.10.59.106:3000, task: network
Dec 03 22:08:18.169 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 118e11496048c9fb4eb9e7fb354f243120107f77a2c546ea, peer_addr: 106.10.59.106:3000, task: network

**Comment by bohenicus** [comment]
Today's update:
I was restarting both nodes today in the morning at 6:00 AM and now at about 20:00 PM the state is like this - not synchronised:  

blockRecvCnt: 1408
lastBlockDate: "8.2756"
lastBlockFees: 0
lastBlockHash: 4a897e14694b2550789c7609de30695511778a34084893e2e1457103c99ea05d
lastBlockHeight: "6080"
lastBlockSum: 0
lastBlockTime: "2019-12-04T06:11:33+00:00"
lastBlockTx: 0
state: Running
txRecvCnt: 17
uptime: 46078
version: jormungandr 0.8.0-rc5-cecea4d

and the second node:
---
blockRecvCnt: 288
lastBlockDate: "6.6135"
lastBlockFees: 209000
lastBlockHash: 2fe94cb914a33cb462aed9e0f62bbe0e3228d3f60fbbc87f6b7e81c56564ef73
lastBlockHeight: "4928"
lastBlockSum: 228000
lastBlockTime: "2019-12-04T06:04:46+00:00"
lastBlockTx: 190
state: Running
txRecvCnt: 0
uptime: 834
version: jormungandr 0.8.0-rc5-cecea4d


In the logs I can see that after some synching the nodes stopped and now are logging only:
"failed to connect to peer, reason: Connection timed out"

Dec 04 19:42:42.323 INFO connecting to peer, node_id: 83226e94ed937c6afd7651c120a21ca48edd85f8a2065002, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:42.344 INFO connecting to peer, node_id: 69a90f74db22f4e3d6bd93fb59fd0cb9e602dff8c55b5be0, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:42.359 INFO connecting to peer, node_id: e97fde93bc2f3d4e4bfdfaa438d7ff775065258be9f27edf, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:42.364 INFO connecting to peer, node_id: fbfcdd4afc08198d3e31f46d5f71169d0331087d0e749b94, peer_addr: 116.203.42.12:3000, task: network
Dec 04 19:42:42.370 INFO connecting to peer, node_id: 4c7df3a93920bb82cff2113430a10c3ceb0a424e465c55eb, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:42.375 INFO connecting to peer, node_id: 49881d1721d946c97988c062740d11f5fcfee24546a4c74b, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:42.385 INFO connecting to peer, node_id: 788ee6430b7b8b65cd60294c1e303a3135b328ad5f86b518, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:42.400 INFO connecting to peer, node_id: 4e301a10c466280a3080e0e3010ef4bd391171f4c1c32bca, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:42.420 INFO connecting to peer, node_id: fe8cbe49a3f5626660498264c26f3828ec4f167e95711d16, peer_addr: 116.203.42.12:3000, task: network
Dec 04 19:42:42.426 INFO connecting to peer, node_id: 827b6c086f97472e2dc909e278bb1d4648b44965fa3a4602, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:43.447 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 46d428d7d5bac5483d75e2f6c080c219f50d39043db7ee73, peer_addr: 116.203.42.12:3000, task: network
Dec 04 19:42:43.452 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 0e3172a5df221df6025b9ca91f2cabd85575e00d3289b7d4, peer_addr: 212.71.249.113:3100, task: network
Dec 04 19:42:43.455 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 1d3f2a6d2e98e4cd58043905970806918c34d0f0a1c1c1b6, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:43.457 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: d0114ccf4211e3b1c5b1288beb584cbc39efe1a5aafc326c, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:43.460 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 261129256e7dc15243b911045da785f80c443cc8b6e220c0, peer_addr: 188.72.115.136:3100, task: network
Dec 04 19:42:43.462 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 31b0b3d0bc17facfd465427245cb02a3c1b318b4aefd4800, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:43.464 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 7e8cbf46e6ce87bf7191c1903c6388e5b458eee6c164183f, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:43.467 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 65092edb38af2dafdca1f7dde83beb146405b82b96080938, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:43.469 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 27af40ba54ee07792603680402d00991587d548d7124bf41, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:43.471 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 5217196c21fd91bb8cb1519864f959a7439426c16850cc5a, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:52.333 INFO connecting to peer, node_id: c6d390bd89fcd74b1fdd509d51acc39cf8a95cd05339f4d7, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:52.350 INFO connecting to peer, node_id: 80b01389ede1d4e235d3836771f5a6cbae17daf88888f99e, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:52.356 INFO connecting to peer, node_id: 6a6d22f7115982b11299609d418131ddab3563d4e84d3130, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:52.378 INFO connecting to peer, node_id: 10329c1c1ff535c6d1ac7870c29888b5fb935e577fad6f6c, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:52.384 INFO connecting to peer, node_id: 089c0947ac0a2a0860b1e5b6a858d9e2313a2e9e78539c66, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:52.395 INFO connecting to peer, node_id: b390080af4d619dba1a27850639ce9f7fc28a6fe79fdbeeb, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:52.412 INFO connecting to peer, node_id: 892bccef8a3bae4f995bed4114f5246aa5f60cc992dce97f, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:53.686 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 372c692d8635a682e8b860cd7334c86495b88ec7380c5b0f, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:53.696 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: a96ed34884c3d16bd649deb2cba5a8355cad4251d7923bd6, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:53.704 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: d43fb47f690af133c33ef633e0760eb4df93f3ac105a133e, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:53.712 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 73a64a37b13d56688b77b7af7f07723d33244bfadb1aeb87, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:53.717 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: d82ade458da7b3c319ec108b84fee271392e9aade72ef57c, peer_addr: 51.143.9.3:3100, task: network
Dec 04 19:42:53.721 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: fe055dbe357b39e2ad2995d6a64f18abcded8aebee5b388e, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:53.726 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: 4afba1fa5aaaed18609438b1be87aebf099e016d7063b4d1, peer_addr: 106.10.59.106:3000, task: network
Dec 04 19:42:53.730 INFO failed to connect to peer, reason: Connection timed out (os error 110), node_id: a20c457a42d4327c7a152b3bd00c1a7dca78129b3c8ae676, peer_addr: 95.216.251.22:3101, task: network

**Comment by NicolasDP** [comment]
thanks, this is very similar to what we are experiencing under heavy load of transaction (#1256 ). `0.8.0-rc7` has had a transaction flood of 1millions last night

**Comment by NicolasDP** [comment]
I believe this is fixed with #1290 and #1292 . It will be included in the next release
