### ISSUE TITLE
0.8 rc6 - delegator accounts (standalone) still not getting paid rewards

### ISSUE THREAD

**Issue by hodlonaut** [input-output-hk/jormungandr#1274]
jormungandr --full-version
jormungandr 0.8.0-rc6 (master-478e5621+, release, macos [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

Hopefully the extra logging I added below is self-explanatory:
============================================

pool total reward for pool a504efa34dbc655db68a6163bd9a9fa89889ba59839cbe940a9a1d31328008ea is calculated to be 1063490 for 10 blocks
inside distribute_poolid_rewards
Pool a504efa34dbc655db68a6163bd9a9fa89889ba59839cbe940a9a1d31328008ea epoch 17 distr.taxed 106349 distr after tax 957141
inside None case for the rward account
Leftover reward (distr.after_tax) 957141

Account 7ba1c265be76d19595b9a365313a6af9edf2e94d4c3a8f3e6e37cad3b4e22e11, stake Stake(10000180), total stake: Stake(1010873634)
inside new and improved scale_value, called with 957141
scaled_divided: 0 after multiplying 957141 by SCALE and dividing by 1010873634
scaled_divided multiplied by self.stake.0 10000180 is 0 which is our result
PercentStake PercentStake { stake: Stake(10000180), total: Stake(1010873634) }, after scaling the payment is Value(0) for epoch 17

Account 59e89e709921dd96da16481236a3c85432396db9802afb21bd759ca3d1f36544, stake Stake(1000873454), total stake: Stake(1010873634)
inside new and improved scale_value, called with 957141
scaled_divided: 0 after multiplying 957141 by SCALE and dividing by 1010873634
scaled_divided multiplied by self.stake.0 1000873454 is 0 which is our result
PercentStake PercentStake { stake: Stake(1000873454), total: Stake(1010873634) }, after scaling the payment is Value(0) for epoch 17

distribute_poolid_rewards - Leftover going to treasury is 957141

**Comment by NicolasDP** [comment]
fixed in #1276
