### ISSUE TITLE
Rewards for the current epoch are allocated at the beginning of the epoch - 0.8.0-RC7

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#1282]
**Describe the bug**
Rewards for the current epoch are allocated at the beginning of the epoch (instead of the beginning of the next epoch).

**Mandatory Information**
```
jcli 0.8.0-rc7 (HEAD-ab32b2cd, release, windows [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
jormungandr 0.8.0-rc7 (HEAD-ab32b2cd, release, windows [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
```

**To Reproduce**
1. get the account stats for an account delegating its stake to a stake pool
2. compare the value of the `last rewards/epoch` parameter with the one of the latest created block 

**Expected behavior**
The rewards for the current epoch are calculated at the end of the epoch and are distributed at the very beginning of the next epoch.

**Additional context**
![rewards](https://user-images.githubusercontent.com/29144964/70200262-6651ae00-1746-11ea-997c-0e6eb21ab0a1.png)

**Comment by NicolasDP** [comment]
it's because you have the epoch when the reward became active. It's off by one. But there is not much we can do here tbh.

**Comment by dorin100** [comment]
only to make it clear into the documentation
