### ISSUE TITLE
0.8.0-RC9+1 - value_taxed > TAX_LIMIT for stake pool

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#1304]
**Describe the bug**
TAX_LIMIT should be the max value for the stake pool reward (based on https://input-output-hk.github.io/jormungandr/stake_pool/registering_stake_pool.html)

At this moment, `value_taxed =  TAX_LIMIT + TAX_VALUE` 

**Mandatory Information**
```
jcli 0.8.0-rc9+1 (HEAD-3339987e, release, windows [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
jormungandr 0.8.0-rc9+1 (HEAD-3339987e, release, windows [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
```

**To Reproduce**
1. Create 1 stake pool with the below tax parameters:
    - TAX_VALUE = 7
    - TAX_RATIO = "1/10"
    - TAX_LIMIT = 100000
2. start the stake pool node
3. get the stake pool details after a couple of epochs
```
$ jcli rest v0 stake-pool get b65bbed7c3059b522059ac02a3a96eca3f3d7291d92c42a7e19e33db5e8066ee --host "http://127.0.0.1:9001/api"
---
kesPublicKey: kes25519-12-pk1jjqnua9shwavmtng8vfpfja8ja9qlnhnxad3fdssg3k5ep7r2eksehdllp
rewards:
  epoch: 238
  value_for_stakers: 2557077526659
  value_taxed: 100007
tax:
  fixed: 7
  max: 100000
  ratio:
    denominator: 10
    numerator: 1
total_stake: 12557077626666
vrfPublicKey: vrf_pk1n22fd0zrjvhfxea98fzs3a4tz9k583zxf3udzrgm7ve8w6jfzsuqn7f3pk
```
As it can be seen above, `value_taxed =  TAX_LIMIT + TAX_VALUE` 

**Expected behavior**
`value_taxed =  TAX_LIMIT`

**Additional context**

**Comment by kevinhammond** [comment]
This is not needed for the testnet settings.  It can be fixed after the initial release.

**Comment by rinor** [comment]
@dorin100, is that the case also for the `treasury_tax` distribution?

**Comment by dorin100** [comment]
@rinor - No.

**Comment by kevinhammond** [comment]
max_limit for treasury_tax also wouldn't be an issue

**Comment by mark-stopka** [comment]
According to @NicolasDP this is a documentation error; TAX_LIMIT should apply only to fees collected from TAX_RATIO, not TAX_VALUE + TAX_RATIO.
