### ISSUE TITLE
Local node on QA Network stops receiving blocks after time

### ISSUE THREAD

**Issue by alan-mcnicholas** [input-output-hk/jormungandr#1305]
**Describe the bug**
Having a local node connected to the QA cluster (0.8.0-rc9+1) for over 24 hours I am seeing that it has stopped receiving blocks for more than one hour. The health of the nodes in Grafana look fine and I don't see any indicators here that would lead me to think that there is an issue with the cluster.

https://monitoring.qa.jormungandr-testnet.iohkdev.io/grafana/d/7wVByzAZj/jormungandr-monitor

**Mandatory Information**
*Windows 10*
```jcli 0.8.0-rc9+1 (HEAD-3339987e, release, windows [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
jormungandr 0.8.0-rc9+1 (HEAD-3339987e, release, windows [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]```


**To Reproduce**
`set RUST_BACKTRACE=full`
1. Connect to QA cluster using configurations details as follows (for trusted peer IPs please ping amc or Dorin)

```---
log:
  - output: stderr
    level: info  
    format: plain
    
p2p:
  topics_of_interest:
    blocks: normal
    messages: low
  trusted_peers:
  - address: "/ip4/x.x.x.x/tcp/3000"
    id: a85bfdff5bd4ea55beac7d5644e71958db6cb2c6ec600553
  - address: "/ip4/x.x.x.x/tcp/3000"
    id: 725ef9c3900a8bfb970d2dc403319f77b354806fa4a28158
  - address: "/ip4/x.x.x.x/tcp/3000"
    id: 251ed5489e85503358e6fc9b6dec8cd01180444860d83d5a
  - address: "/ip4/x.x.x.x/tcp/3000"
    id: cede82e828ccd57ed5bd21c765680aa5177c3c744b2e5fb3
  - address: "/ip4/x.x.x.x/tcp/3000"
    id: a9005255e416b5b6050be795c5fc89d84c1612bfd9576809
  - address: "/ip4/x.x.x.x/tcp/3000"
    id: 22075b4f1abaef6d42cbad8f6e9d6f8264cec1881e6c0b6f
  - address: "/ip4/x.x.x.x/tcp/3000"
    id: 02c3c4398064548430bad21718599d10cb457d82a1b32ff5
rest:
  listen: 127.0.0.1:3101
storage: "/080rc9_1qa"```

2. Leave the node running for an extended period of time (in this case ~24 hours)

**Expected behaviour**
The local node should remain synced with the network; I can see the network continues to produce blocks but the local node is not receiving them. Querying node status shows that the last block was received almost 2 hours ago. 

The last output from the logs prior to the `stuck_notifier` is:
```
Dec 08 14:20:56.745 INFO receiving block stream from network, task: block
Dec 08 14:20:56.745 INFO received block announcement, hash: 39d98a0cf7da21eecbe099897c4d5953976c4a11092203f94fefb614e34440e8, direction: in, stream: block_events, node_id: 4d2cb5f9a4eec68dead6b45f393c942e838e96c948757b31, peer_addr: 3.124.45.245:3000, task: network
Dec 08 14:20:56.745 INFO receiving block announcement from network, from_node_id: 4d2cb5f9a4eec68dead6b45f393c942e838e96c948757b31, date: 61.92, parent: b34096db3b49955ba9de7f7aaed4fb234795bb5821bc141e871148b92805c3a1, hash: 39d98a0cf7da21eecbe099897c4d5953976c4a11092203f94fefb614e34440e8, task: block
Dec 08 14:20:56.745 INFO receiving block stream from network, task: block
Dec 08 14:20:56.813 INFO block successfully applied, date: 61.92, parent: b34096db3b49955ba9de7f7aaed4fb234795bb5821bc141e871148b92805c3a1, hash: 39d98a0cf7da21eecbe099897c4d5953976c4a11092203f94fefb614e34440e8, task: block
Dec 08 14:20:56.814 INFO update current branch tip, task: block
Dec 08 14:20:57.489 ERRO cannot compute the time passed since the last block: second time provided was later than self, task: stuck_notifier
Dec 08 14:51:57.489 WARN blockchain is not moving up, the last block was 1859 seconds ago, task: stuck_notifier
Dec 08 14:52:57.489 WARN blockchain is not moving up, the last block was 1919 seconds ago, task: stuck_notifier
Dec 08 14:53:57.489 WARN blockchain is not moving up, the last block was 1979 seconds ago, task: stuck_notifier
Dec 08 14:54:57.489 WARN blockchain is not moving up, the last block was 2039 seconds ago, task: stuck_notifier
Dec 08 14:55:57.489 WARN blockchain is not moving up, the last block was 2099 seconds ago, task: stuck_notifier
```
Note system clock is up to date and the machine has been in an active state since (i.e. no suspension or hibernation.

**Additional context**
Add any other context about the problem here.

**Comment by rinor** [comment]
If/when possible can you check smth please.
What is the output of `jcli rest v0 network stats get` when the node is in that state?
I am interested to check if you get **timeout** instead of normal response.

**Comment by piotr-iohk** [comment]
I have observed the same behavior when I put my computer in the sleep mode for a moment (with the node running) and then put it back to active. After that I see that my node no longer receives blocks and see those warnings after a while:
```
WARN blockchain is not moving up, the last block was 2099 seconds ago, task: stuck_notifier
```

**Comment by alan-mcnicholas** [comment]
@rinor this is the output, I have left the node in this state in the event there is any additional spelunking I can do to have to get to the bottom of it. @piotr-iohk are you able to reproduce this 100% via `sleep`?

```$ jcli rest v0 network stats get -h http://127.0.0.1:3101/api
---
- establishedAt: "2019-12-08T14:07:27.487200100+00:00"
  lastBlockReceived: "2019-12-08T14:13:36.648407500+00:00"
  lastFragmentReceived: ~
  lastGossipReceived: "2019-12-08T14:13:41.191662500+00:00"
  nodeId: cede82e828ccd57ed5bd21c765680aa5177c3c744b2e5fb3
- establishedAt: "2019-12-08T14:07:27.488196300+00:00"
  lastBlockReceived: "2019-12-08T14:13:36.662447200+00:00"
  lastFragmentReceived: ~
  lastGossipReceived: "2019-12-08T14:13:41.285662700+00:00"
  nodeId: a9005255e416b5b6050be795c5fc89d84c1612bfd9576809
- establishedAt: "2019-12-08T14:07:27.486198600+00:00"
  lastBlockReceived: "2019-12-08T14:13:36.782409200+00:00"
  lastFragmentReceived: ~
  lastGossipReceived: "2019-12-08T14:13:41.301686300+00:00"
  nodeId: 251ed5489e85503358e6fc9b6dec8cd01180444860d83d5a
- establishedAt: "2019-12-08T14:07:27.487200100+00:00"
  lastBlockReceived: "2019-12-08T14:13:36.782409200+00:00"
  lastFragmentReceived: ~
  lastGossipReceived: "2019-12-08T14:13:41.528827300+00:00"
  nodeId: facc617a5aa6cb0ecbea4b74724e32b99a702f47c3700787
- establishedAt: "2019-12-08T14:07:27.486198600+00:00"
  lastBlockReceived: "2019-12-08T14:13:36.783408700+00:00"
  lastFragmentReceived: ~
  lastGossipReceived: "2019-12-08T14:13:41.608836500+00:00"
  nodeId: 73609ac8207a631a95c50b64060554c3a79825f0732aa1dc
- establishedAt: "2019-12-08T14:07:27.488196300+00:00"
  lastBlockReceived: "2019-12-08T14:13:36.783408700+00:00"
  lastFragmentReceived: ~
  lastGossipReceived: "2019-12-08T14:13:41.720458700+00:00"
  nodeId: 679e900fa0e2ee7f85de37bd5694504ae435b693fec7d173
- establishedAt: "2019-12-08T14:07:27.489197300+00:00"
  lastBlockReceived: "2019-12-08T14:13:36.653415+00:00"
  lastFragmentReceived: ~
  lastGossipReceived: "2019-12-08T14:13:43.306137600+00:00"
  nodeId: c25862d4a6574e65c541fdc2235f8d3adb3646cf792a5f55
- establishedAt: "2019-12-08T14:07:27.488196300+00:00"
  lastBlockReceived: "2019-12-08T14:13:36.644412400+00:00"
  lastFragmentReceived: ~
  lastGossipReceived: "2019-12-08T14:13:43.556478800+00:00"
  nodeId: 7ad079a773ae4af5eca4f3b7a8f6fa2f08e11a7eea1f5498
- establishedAt: "2019-12-08T14:14:07.486639+00:00"
  lastBlockReceived: "2019-12-08T14:20:56.743656400+00:00"
  lastFragmentReceived: ~
  lastGossipReceived: "2019-12-08T14:20:58.913436900+00:00"
  nodeId: 4d2cb5f9a4eec68dead6b45f393c942e838e96c948757b31
- establishedAt: "2019-12-08T14:14:07.485640800+00:00"
  lastBlockReceived: "2019-12-08T14:20:56.742646500+00:00"
  lastFragmentReceived: ~
  lastGossipReceived: "2019-12-08T14:20:59.077901100+00:00"
  nodeId: 168a8a37853e213c98c71e4552ed6136ca7cb4738ef5837b
- establishedAt: "2019-12-08T14:14:07.487637400+00:00"
  lastBlockReceived: "2019-12-08T14:20:56.742646500+00:00"
  lastFragmentReceived: ~
  lastGossipReceived: "2019-12-08T14:21:00.408213+00:00"
  nodeId: 49e171f81e3abb62bb3360946ba67a2a05129ef9b9a84030
- establishedAt: "2019-12-08T14:14:07.486639+00:00"
  lastBlockReceived: "2019-12-08T14:20:56.742646500+00:00"
  lastFragmentReceived: ~
  lastGossipReceived: "2019-12-08T14:21:00.428211600+00:00"
  nodeId: 02c3c4398064548430bad21718599d10cb457d82a1b32ff5
- establishedAt: "2019-12-08T14:14:07.486639+00:00"
  lastBlockReceived: "2019-12-08T14:20:56.742646500+00:00"
  lastFragmentReceived: ~
  lastGossipReceived: "2019-12-08T14:21:00.483218800+00:00"
  nodeId: 22075b4f1abaef6d42cbad8f6e9d6f8264cec1881e6c0b6f
- establishedAt: "2019-12-08T14:14:07.485640800+00:00"
  lastBlockReceived: "2019-12-08T14:20:56.742646500+00:00"
  lastFragmentReceived: ~
  lastGossipReceived: "2019-12-08T14:21:00.517479800+00:00"
  nodeId: a8f4d660ff8fb38d72fb4b521a869e317a278bd5e55b68b0
- establishedAt: "2019-12-08T14:14:07.486639+00:00"
  lastBlockReceived: "2019-12-08T14:20:56.742646500+00:00"
  lastFragmentReceived: ~
  lastGossipReceived: "2019-12-08T14:21:00.623738100+00:00"
  nodeId: 0faf2e58af0bb537d8044b092b1ee400ea3a736692b1e481
- establishedAt: "2019-12-08T14:14:07.485640800+00:00"
  lastBlockReceived: "2019-12-08T14:20:56.587651300+00:00"
  lastFragmentReceived: ~
  lastGossipReceived: "2019-12-08T14:21:00.800764100+00:00"
  nodeId: 725ef9c3900a8bfb970d2dc403319f77b354806fa4a28158
- establishedAt: "2019-12-08T14:14:07.485640800+00:00"
  lastBlockReceived: "2019-12-08T14:20:56.587651300+00:00"
  lastFragmentReceived: ~
  lastGossipReceived: "2019-12-08T14:21:00.875767300+00:00"
  nodeId: a85bfdff5bd4ea55beac7d5644e71958db6cb2c6ec600553
```

**Comment by roxkamx** [comment]
> If/when possible can you check smth please.
> What is the output of `jcli rest v0 network stats get` when the node is in that state?
> I am interested to check if you get **timeout** instead of normal response.

I am reporting the same problem ... in my case all calls to the REST API time out

**Comment by roxkamx** [comment]
> > If/when possible can you check smth please.
> > What is the output of `jcli rest v0 network stats get` when the node is in that state?
> > I am interested to check if you get **timeout** instead of normal response.
> 
> I am reporting the same problem ... in my case all calls to the REST API time out
> 
> I am running on a VPS (Ubuntu 16.04.6 LTS) so no sleep involved in my case
> 
> present in rc10 too:
> 
> ```
> ❯  jcli rest v0 node stats get --host http://127.0.0.1:3100/api
> 
> failed to make a REST request
>   |-> connection with node timed out
>   |-> http://127.0.0.1:3100/api/v0/node/stats: timed out
> ```

and in rc11
