### ISSUE TITLE
jcli help message to improve and error message to be more precise

### ISSUE THREAD

**Issue by JSCSJSCS** [input-output-hk/jormungandr#1310]
**Describe the bug**
When trying to derive a new key from a public key using jcli key derive --input <file_with_public_key>, the input file contents are not recognized as having a valid bech32 human readable part.

**Mandatory Information**
1. jcli 0.8.0-rc9+1 (HEAD-3339987e, release, windows [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
2. jormungandr 0.8.0-rc9+1 (HEAD-3339987e, release, windows [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
3. GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
4. Powershell 5.1.18362.145

**To Reproduce**
1. In powershell, enter the command to create a UTF8 file with a public key:
`jcli key generate --type ed25519extended | jcli key to-public | Set-Content temp.key -Passthru -NoNewline`
2. In powershell, enter the command to derive a new key for the key from step 1.
`jcli key derive --input temp.key 0`
3. Note error output:
```
jcli : unrecognized public key bech32 HRP: 'ed25519_pk'
At line:1 char:1
+ jcli key derive --input temp.key 0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (unrecognized pu...P: 'ed25519_pk':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

**Expected behavior**
Expected output of new bech32 public key

**Additional context**
Attention had to be paid to creating a UTF8 file that had only the public key with no CFLF or new blank last line or other errors were also thrown.

I also tried git bash:
```
jcli key generate --type ed25519extended | jcli key to-public | tr -d '\n' > temp.key
jcli key derive --input temp.key 0
unrecognized public key bech32 HRP: 'ed25519_pk'
```

**Comment by rinor** [comment]
It does not work that way. It is related to bip32 keys. Check https://github.com/input-output-hk/jormungandr/issues/450 for more info.

**Comment by NicolasDP** [comment]
thanks @rinor

**Comment by NicolasDP** [comment]
actually reopening. the documentation is not precise enough in jcli.

`jcli key derive --help` should say that bip32 keys are required. and the error message should be more clear, expected `ed25519bip32`.

**Comment by rinor** [comment]
@JSCSJSCS to wrap it up the commands will be:
```
jcli key generate --type ed25519bip32 | jcli key to-public temp.key
jcli key derive --input temp.key 0
```
