### ISSUE TITLE
cannot process network headers, reason: deadline has elapsed, task: block

### ISSUE THREAD

**Issue by dusanmrozek** [input-output-hk/jormungandr#1320]
**Describe the bug**
My node was up and running through epoch 14-17 creating couple of blocks in each. Suddenly, no blocks in epochs 18-20. Not sure if this is somehow connected but t
he only "new" visible thing is an repeating error in Jörmungandr log stating "cannot process network headers, reason: deadline has elapsed, task: block".

Sorry I can see now that the blockchain is not moving up, my node is stuck in epoch 18:

lastBlockDate: "18.688"

**Mandatory Information**
1. `jcli --full-version` output;

jcli 0.8.0-rc9+1 (HEAD-3339987e, release, windows [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

2. `jormungandr --full-version` output;

jormungandr 0.8.0-rc9+1 (HEAD-3339987e, release, windows [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

**To Reproduce**
Nothing to reproduce, see attached Powershell screenshot:

![image](https://user-images.githubusercontent.com/58665645/70516253-f9b82400-1b36-11ea-8773-15b502dd0d4f.png)

**Expected behavior**
Node creating couple of blocks, no errors in the log.

**Additional context**

**Comment by dusanmrozek** [comment]
I had to stop Jormungandr and delete storage to get my node moving up again. Actually I had to do it twice.

**Comment by mark-stopka** [comment]
@NicolasDP, please re-open the issue; deleting storage is not a solution for this issue. There was one more guy reporting the same issue in the Cardano Stake Pool Workgroup telegram channel.

**Comment by rinor** [comment]
Can we close this one in favor of https://github.com/input-output-hk/jormungandr/issues/1413? Thank you.

**Comment by dusanmrozek** [comment]
Sure
