### ISSUE TITLE
Documentation update for REST API

### ISSUE THREAD

**Issue by carl-IOHK** [input-output-hk/jormungandr#1334]
**Is your feature request related to a problem/context ? Please describe if applicable.**
Detailed Doccumentation for REST API exists in this repo, is it updated for changes made in 
v0.8.0-rc11
v0.8.0-rc10
v0.8.0-rc5 
v0.7.0-rc5

**Describe the solution you'd like**
Please let me know if updates are made so that I can replicate them in the support portal. 

**Additional context**
Thanks!

**Comment by rinor** [comment]
Right now the rest api is up to date with the available features in the latest version. Do you see anything yet missing? If not can we close this issue please. Thank you.

**Comment by rinor** [comment]
@carl-IOHK can we close this one or there is more information requested?
