### ISSUE TITLE
The transaction fees should not be included into the rewards for the Incentivized testnet

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#1340]
**Describe the bug**
At this moment the transaction fees are included into rewards.

**Mandatory Information**
0.8.0-RC11

**To Reproduce**

**Expected behavior**
The transaction fees should not be included into the rewards for the Incentivized testnet

**Additional context**

**Comment by vincenthz** [comment]
is `fees-go-to` set to `treasury` ?

**Comment by dorin100** [comment]
of course not - I was correlating that parameter with `JORMUNGANDR_REWARD_DUMP_DIRECTORY` but now I understand that I was wrong :)

**Comment by dorin100** [comment]
fees-go-to works as expected
