### ISSUE TITLE
make-witness account transaction error trying to register pool

### ISSUE THREAD

**Issue by dogpatchmedia** [input-output-hk/jormungandr#1344]
**Describe the bug**
trying to make the transaction (https://input-output-hk.github.io/jormungandr/jcli/transaction.html) to submit my pool info, but there is no transaction-id in the info for an account based transaction. im not sure what to do now...

**Mandatory Information**
1. `jcli --full-version` output; jcli 0.8.0rc11
2. `jormungandr --full-version` output; jormungandr 0.8.0-rc11

**To Reproduce**

following steps here to creater transaction: https://input-output-hk.github.io/jormungandr/jcli/transaction.html

command:

jcli transaction make-witness --genesis-block-hash 65a9b15f82619fffd5a7571fdbf973a18480e9acf1d2fddeb606ebb53ecca839 --type account --account-spending-counter 0 witness private.key

result:

error: Invalid value for '<transaction-id>': invalid hex encoding for digest value

transaction info:

jcli transaction info --fee-constant 5 --fee-coefficient 2 --staging tx

balance: 2
fee: 11
input: 100000000
inputs:
  - account: 50b1e6826884f7e32092b11ab2c1008cd21facc189c6c6d23832403eabad4ea0
    kind: account
    value: 100000000
num_inputs: 1
num_outputs: 2
num_witnesses: 0
output: 99999987
outputs:
  - address: ca1sk64xzm34ur5cqs7z3wmdyucwtd8dn9dtwnllcdqjjwrxp37w0n5zp5wd7n
    value: 50
  - address: ca1sk64xzm34ur5cqs7z3wmdyucwtd8dn9dtwnllcdqjjwrxp37w0n5zp5wd7n
    value: 99999937
sign_data_hash: 2c4714295bdc07006b70ac358abd194257d8cee2ee8d414eec3562e91395c5dd
status: finalizing

there is no transaction-id to pass as an argument and the docs say that its not needed if your doing an account transaction:

> When using an account as input, the command takes account as the type and an additional parameter: --account-spending-counter, that should be increased every time the account is used as input. error: Invalid value for '<transaction-id>': invalid hex encoding for digest value

**Expected behavior**
not sure. i guess i should just get back the prompt without any errors.

**Additional context**

**Comment by rinor** [comment]
Please check https://github.com/input-output-hk/jormungandr/issues/1323

**Comment by dogpatchmedia** [comment]
thanks that worked.
