### ISSUE TITLE
Rewards per epoch not fully credited

### ISSUE THREAD

**Issue by adascanBovich** [input-output-hk/jormungandr#1348]
**Describe the bug**

There was one pool created on a private testnet during genesis block + 2 delegators delegating to it. Pool tax is 10%, reward per epoch - 1000. No treasury enabled. During epoch 8 was created 2 blocks, pool got 100 and two delegators 449 lovelaces each. Total distributed reward - 998 instead of 1000.

**Mandatory Information**
1. jcli 0.8.0 (HEAD-7868354, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
2. jormungandr 0.8.0 (HEAD-7868354, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

**To Reproduce**
1. Create new blockchain with provided genesis settings below.
2. Wait for any epoch to end. 
3. Check how many blocks were created during that epoch.
4. Calculate pool tax and remaining rewards that should be distributed.
5. Compare it with data returned by jcli.

**Expected behavior**
Total sum of distributed rewards should be 1000.

**Additional context**
genesis.yaml:
https://pastebin.com/4gW7AwER

Pool's owner rewards for epoch 8:
<img width="705" alt="Screenshot 2019-12-12 at 12 32 22" src="https://user-images.githubusercontent.com/58727428/70705945-a7653780-1cdd-11ea-99cc-8a8ea84aa96b.png">

Delegator1 rewards for epoch 8:
<img width="708" alt="Screenshot 2019-12-12 at 12 34 02" src="https://user-images.githubusercontent.com/58727428/70705984-b51abd00-1cdd-11ea-8851-958698147637.png">

Delegator2 rewards for epoch 8:
<img width="708" alt="Screenshot 2019-12-12 at 12 35 21" src="https://user-images.githubusercontent.com/58727428/70706009-c19f1580-1cdd-11ea-8878-998ff44ead3d.png">

Pool info (don't mind balances, jcli call was made on epoch 10):
<img width="708" alt="Screenshot 2019-12-12 at 12 37 10" src="https://user-images.githubusercontent.com/58727428/70706058-d7143f80-1cdd-11ea-8a0f-5da6aff3dd6e.png">

**Comment by hodlonaut** [comment]
Create a new folder and set the environment variable as mentioned here: https://input-output-hk.github.io/jormungandr/configuration/introduction.html#advanced

Stop and start your node.

Zip up the generated reward dump files for epochs 0 through 9 and attach them to this issue for analysis.

**Comment by adascanBovich** [comment]
> Create a new folder and set the environment variable as mentioned here: https://input-output-hk.github.io/jormungandr/configuration/introduction.html#advanced
> 
> Stop and start your node.
> 
> Zip up the generated reward dump files for epochs 0 through 9 and attach them to this issue for analysis.

I wish I could do that. But epochs 0 thought 9 are no longer exist on my chain. Because of:

https://github.com/input-output-hk/jormungandr/issues/1356

But I can do it for any other epoch number if it is so critical, it is very easy to reproduce, took me about 5 mins.  

Anyway, can anyone from the devs team confirm that this rewards dump is needed here?

**Comment by hemants1** [comment]
I have staking from last 5days but the rewards are not being distributed at all:

xxxxxxxxxxxxx:/ada/v0.7.2$ jcli rest v0 stake-pool get $(cat stake_pool.id) -h http://127.0.0.1:3101/api
---
kes_public_key: kes25519-12-pk1pv2ttn52m9skpxur4w5l3gue4jrnn0j3n4lnw3yyyadhcj0cvaxquflzrq
rewards:
  epoch: 0
  value_for_stakers: 0
  value_taxed: 0
tax:
  fixed: 100
  max: 1000000000000000000
  ratio:
    denominator: 10
    numerator: 1
total_stake: 400174899800
vrf_public_key: vrf_pk1lezh40a7w9l6f2hqawcranplnqlh23znsrml7jrn0twd642ure8shyqs2u

Isn't rewards were supposed to be distributed every epoc?
