### ISSUE TITLE
Network with single pool getting stuck without any chance to recover

### ISSUE THREAD

**Issue by adascanBovich** [input-output-hk/jormungandr#1356]
**Describe the bug**
Private network with single pool and 2 delegators + 1 passive node connected to it. After 1-2 hours blocks creation is getting stuck, node restart doesn't help. Only way is to delete storage folder completely or create new genesis block, loosing all generated rewards.

**Mandatory Information**
1. jcli 0.8.0 (HEAD-7868354, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
2. jormungandr 0.8.0 (HEAD-7868354, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

**To Reproduce**
1. Create new network with provided genesis settings below.
2. Launch pool node + 1 passive node on separate machines.
3. Wait 1-2 hours for stuck notifications in the log.

**Expected behavior**
Network shouldn't get stuck without any chance to recover.

**Additional context**
genesis.yaml:
https://pastebin.com/4gW7AwER

node.log:
https://pastebin.com/U7NCuFMY

ulimit is set to 9000
VPS with 8GB RAM, 4 cores.

**Comment by rinor** [comment]
@adascanBovich is this still an issue (regarding your private network) also with v0.8.5?

**Comment by rinor** [comment]
@adascanBovich closing this one since it shouldn't be an issue with v0.8.5 (regarding your private network). Feel free to reopen if not the case.
