### ISSUE TITLE
Error in the overall configuration of the node/ bootstrap file.  v0.8.2  

### ISSUE THREAD

**Issue by MarcinSiennicki** [input-output-hk/jormungandr#1363]
Hello, 
I have an issue with starting the node. I followed the instruction and after run _./bootstrap_ and then  _jormungandr --genesis-block block-0.bin --config config.yaml --secret poolsecret1.yaml_. 
I received this error. 
_Error in the overall configuration of the node
 |-> Error while parsing the node configuration file: log: invalid type: map, expected a sequence at line 3 column 10
 |-> log: invalid type: map, expected a sequence at line 3 column 10_

I found out the problem is in the config.yaml file with bold part
_storage: "D:/CardanoNode/jormungandr-node/storage/"
log:
    **level: debug
    format: plain
    output: stderr**
rest:
  listen: "127.0.0.1:48443"
p2p:
  trusted_peers: []
  public_address: "/ip4/127.0.0.1/tcp/8299"
  topics_of_interest:
    messages: low
    blocks: normal_

**Comment by eugene-babichenko** [comment]
The configuration format was changed by #1134 so that you can list multiple outputs for logging. The correct configuration should be in the form of a list and your case it will be something like that:

```yaml
log:
  - output: stderr
    format: plain
    level: debug
```

**Comment by MarcinSiennicki** [comment]
Thanks for the immediate reply.

Good luck with the development.
