### ISSUE TITLE
Twice the same owner in a pool registration certificate?

### ISSUE THREAD

**Issue by KtorZ** [input-output-hk/jormungandr#1366]
**Describe the bug**
There's a certificate published in the ledger (nightly) that has twice the same owner.
The corresponding pool id is the following:

```
03a01cb9acffb3374c9a86ff39b2b5d85128c9ce3ac3fdba51ceceaca0685f98 
```

**Mandatory Information**
1. `jcli --full-version` output;
N/A: The version currently deployed on the nightly network. I guess `0.8.2`

2. `jormungandr --full-version` output;
N/A: The version currently deployed on the nightly network. I guess `0.8.2`

**To Reproduce**

The certificate is the following:
```
SERIAL:          00000000000000000000000000000000 
START TIME:      0000000000000000
PERMISSIONS:     0000000000000001
VRF PUBKEY:      041b97a0f8c61470f6fff723508c209aff467d04f16abdbb3b1f711ff3e44736
KES PUBKEY:      75c9d29466341087563d47c0a37f452f32b21ec2456ac1eb24b95055ed4d7bce
NB OWNERS:       02
OWNER #1:        53f9688f883453f5487f50d22df47dd6a95b7c24721db73b3c54de2f6d1e1615
OWNER #2:        53f9688f883453f5487f50d22df47dd6a95b7c24721db73b3c54de2f6d1e1615
TAX FIXED:       0000000000000000
TAX NUMERATOR:   0000000000000000
TAX DENOMINATOR: 0200000000000000
TAX LIMIT:       6400000000000000
REWARD ACCOUNT?: 0000
```

**Expected behavior**
To me, this doesn't really sound like a valid certificate that should be accepted by the ledger. But, I'd like to confirm that?

**Comment by NicolasDP** [comment]
Looking at the certificate format, documentation and the ledger rules, there is nothing that say this should not be allowed. so not a bug.

**Comment by dcoutts** [comment]
If/when pool owner pledges are implemented then this may be something to revisit, to avoid double-counting the pledge from one owner.

For what it's worth, the Shelley formal spec uses a _set_ of pool owners (key hashes). See figure 26.

**Comment by michaeljfazio** [comment]
This is my certificate. I reported the fact it has my owner I’d duplicated on telegram and to iohk support. What was more interest I though was that I used the scripted method to create it like most other people. Hence my owner is was not specified twice but somehow this was still the result on chain.
