### ISSUE TITLE
0.8.3 ITN WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network

### ISSUE THREAD

**Issue by liebmann** [input-output-hk/jormungandr#1387]
**Describe the bug**
I am getting multiple warning and error messages of the type below.

Dec 17 15:03:01.067 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Dec 17 15:03:15.828 ERRO cannot process network headers, reason: deadline has elapsed, task: block

**Mandatory Information**
1. `jcli --full-version` output;
jcli 0.8.3 (HEAD-8f276c0, release, linux [aarch64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
2. `jormungandr --full-version` output;
jormungandr 0.8.3 (HEAD-8f276c0, release, linux [aarch64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

**Additional context**
The server has ntp enabled. So no timing issue on my side.

**Comment by JSCSJSCS** [comment]
Same here. Following. Blocks are slow to come through. Have to restart jorm to catch up most of the time. There are network issues being reported in telegram group, but this error message does not help the less technical of us.

```
{"msg":"cannot process block announcement","level":"ERRO","ts":"2019-12-17T07:25:59.427184700-08:00","from_node_id":"b852c1d8ee440fc1b05956dc780319ca11aadf84b46a53d1","date":"3.36365","parent":"cead4e7337003b8b2aa83c05295df45e779af4a9c597ec7da130896c989840e2","hash":"0368f69800180e53783985c4c18ea04842656cd2c9307414368d0b660f3245c8","task":"block","reason":"deadline has elapsed"}
{"msg":"cannot process network headers","level":"ERRO","ts":"2019-12-17T07:26:02.418174700-08:00","task":"block","reason":"deadline has elapsed"}
```

**Comment by rinor** [comment]
Probably the same as https://github.com/input-output-hk/jormungandr/issues/1383
