### ISSUE TITLE
Thread 'blockX' panicked at missed chain pull root candidate

### ISSUE THREAD

**Issue by aidik** [input-output-hk/jormungandr#1388]
**Describe the bug**
While running a stake pool using Jormungandr 0.8.3 I get **blockX** thread panics.

**Mandatory Information**
1. `jcli 0.8.3 (heads/v0.8.3-8f276c00, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]` 
2. `jormungandr 0.8.3 (heads/v0.8.3-8f276c00, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]`

**To Reproduce**
1. run: `jormungandr --config "jormungandr-node-config-0.8.3.yaml" --genesis-block-hash $(cat genesis-hash.txt) --secret node_secret.yaml`
2. wait and get:

```
thread 'block7' panicked at 'missed chain pull root candidate a5f310d695f7a89a456484ddba8bacba9075fa15b18b72e2ff44caea96825ffe that got committed to storage', jormungandr/src/blockchain/candidate.rs:562:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:339
   9: jormungandr::blockchain::candidate::CandidateForestThickets::apply_block
  10: futures::future::chain::Chain<A,B,C>::poll
  11: futures::future::chain::Chain<A,B,C>::poll
  12: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  13: futures::future::chain::Chain<A,B,C>::poll
  14: futures::future::chain::Chain<A,B,C>::poll
  15: futures::future::chain::Chain<A,B,C>::poll
  16: <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll
  17: futures::future::chain::Chain<A,B,C>::poll
  18: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  19: futures::task_impl::std::set
  20: std::panicking::try::do_call
  21: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  22: tokio_threadpool::task::Task::run
  23: tokio_threadpool::worker::Worker::run_task
  24: tokio_threadpool::worker::Worker::run
  25: tokio_timer::clock::clock::with_default
  26: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  27: std::thread::local::LocalKey<T>::with
  28: std::thread::local::LocalKey<T>::with
```

**Comment by rinor** [comment]
This was observed also in this https://github.com/input-output-hk/jormungandr/pull/1346#issuecomment-565015656 conversation. Thank you for filing this report, so we can continue the discussions in here.

**Comment by hodlonaut** [comment]
jormungandr --full-version
jormungandr 0.8.3 (master-ce0e7ab9+, debug, macos [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

(latest master)

Got the below panic - not sure if that's meant to have been addressed as a part of this issue or is something separate?

Dec 18 22:02:27.369 INFO disconnecting client, node_id: 1a3426082d6c2483fcf863122dbeae936fd8cb9db6af4326, peer_addr: 95.216.251.21:3100, task: network
thread 'block1' panicked at 'chain pull root candidate db5551b15871b7f2bdd8a830c85ff73b5ae10a30651ae62360097a89366b0b7e was cached, but not yet applied', jormungandr/src/blockchain/candidate.rs:486:21
stack backtrace:
   0:        0x103c6d8a5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h66f38d4abb2e41c1
   1:        0x103c90be0 - core::fmt::write::h4f487e714088986d
   2:        0x103c679fb - std::io::Write::write_fmt::h7bd7b6fe8b47c5fb
   3:        0x103c6fbaa - std::panicking::default_hook::{{closure}}::heee79636c241547c
   4:        0x103c6f8b5 - std::panicking::default_hook::hfcbd07059d15441e
   5:        0x103c70307 - std::panicking::rust_panic_with_hook::h0c4b67125f55410a
   6:        0x103c6fe4d - std::panicking::continue_panic_fmt::h0e74ab2b215a1401
   7:        0x103c6fdae - std::panicking::begin_panic_fmt::hc4b1bbb2a0641af7
   8:        0x1020cdd05 - jormungandr::blockchain::candidate::CandidateForestThickets::add_or_refresh_root::h9c1464b8b31f78ef
   9:        0x101eeac13 - jormungandr::blockchain::candidate::CandidateForest::land_header_chain::{{closure}}::{{closure}}::hb66217cb4527405f
  10:        0x1027fb8a5 - <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::{{closure}}::{{closure}}::h34619608bbbebbb1
  11:        0x101f6f435 - core::result::Result<T,E>::map::h2c96fbf4fd778887
  12:        0x1027f83c7 - <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::{{closure}}::haa889979b9d9ea44
  13:        0x10260cbb4 - futures::future::chain::Chain<A,B,C>::poll::hcfbeea4ada2759ac
  14:        0x1027f2a4f - <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::h3b0204e44f8e912a
  15:        0x10299d6e4 - <futures::future::either::Either<A,B> as futures::future::Future>::poll::h2b3ace641b9b9bda
  16:        0x1025c21e4 - futures::future::chain::Chain<A,B,C>::poll::h3559817e7e91bdbc
  17:        0x1027f229f - <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::h078e18620518a499
  18:        0x1025bcdc9 - futures::future::chain::Chain<A,B,C>::poll::h2b45162e89aaafdb
  19:        0x1027f364f - <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::hac7dc7c1e10c158f
  20:        0x1025ca3a9 - futures::future::chain::Chain<A,B,C>::poll::h494af35fc5092799
  21:        0x10285a7ef - <futures::future::then::Then<A,B,F> as futures::future::Future>::poll::hcb010001e925acec
  22:        0x10280bf8c - <tokio_timer::timeout::Timeout<T> as futures::future::Future>::poll::hae771617e8c71981
  23:        0x102b316cc - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h2cc8f28f000ed89e
  24:        0x103c4b9ca - <alloc::boxed::Box<F> as futures::future::Future>::poll::hc3c62f42d544b201
  25:        0x103b9bf95 - futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}::h72fe5c242d363553
  26:        0x103b9c243 - futures::task_impl::Spawn<T>::enter::{{closure}}::h0c9464ccd68e274b
  27:        0x103bb0ed7 - futures::task_impl::std::set::h6ba1e4d4be95a5f3
  28:        0x103b9c1e8 - futures::task_impl::Spawn<T>::enter::hf9e25a822de66188
  29:        0x103b9be55 - futures::task_impl::Spawn<T>::poll_fn_notify::he71add4e83262ce7
  30:        0x103b9bf25 - futures::task_impl::Spawn<T>::poll_future_notify::h20d356c0a66e4389
  31:        0x103b9d99d - tokio_threadpool::task::Task::run::{{closure}}::h4abd643704e13807
  32:        0x103bc3cad - core::ops::function::FnOnce::call_once::h047a167f683651c3
  33:        0x103bab3c8 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::ha4c7138c1772d5f8
  34:        0x103babd5d - std::panicking::try::do_call::hd8ca205db38edaa0
  35:        0x103c7412f - __rust_maybe_catch_panic
  36:        0x103babb83 - std::panicking::try::hfa0b2abfb7726a01
  37:        0x103bab91f - std::panic::catch_unwind::h9294e9d5f8da2bd3

38:        0x103b9d324 - tokio_threadpool::task::Task::run::hf8536e5b21170213
  39:        0x103bc99d3 - tokio_threadpool::worker::Worker::run_task2::h67e71e07f9d6dca2
  40:        0x103bc9346 - tokio_threadpool::worker::Worker::run_task::h2ac1d55969803429
  41:        0x103bc8acc - tokio_threadpool::worker::Worker::try_run_owned_task::hb2ec6505d71f3d61
  42:        0x103bc856d - tokio_threadpool::worker::Worker::try_run_task::h2e4f6af15a1e3d2e
  43:        0x103bc83ee - tokio_threadpool::worker::Worker::run::hc8ba0af0d8669022
  44:        0x103b24e9c - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}::hf0506fd2afb97818
  45:        0x103b1f09b - tokio_timer::timer::handle::with_default::hb48993f30bd564f7
  46:        0x103b24ef3 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::h2bbbc1d89be08528
  47:        0x103b1c7b6 - tokio_timer::clock::clock::with_default::ha427bc0a7eed2ff6
  48:        0x103b24f37 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::h257966aeff9e021e
  49:        0x103b2881e - tokio_reactor::with_default::h3c0f7d01bb4ace31
  50:        0x103b24fc0 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::hcc2342f58477d189
  51:        0x103bbbc16 - tokio_threadpool::callback::Callback::call::hdbbdd252a87fcfda
  52:        0x103bc80e8 - tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}}::hb056f655a26442a1
  53:        0x103ba88f9 - tokio_executor::global::with_default::{{closure}}::h6734729b1c5c4153
  54:        0x103bc162e - std::thread::local::LocalKey<T>::try_with::hde1724a27bcdb32a
  55:        0x103bc0dc0 - std::thread::local::LocalKey<T>::with::hb50fbeb4b3a99e35
  56:        0x103ba87fc - tokio_executor::global::with_default::h9c786460504f5232
  57:        0x103bc8187 - tokio_threadpool::worker::Worker::do_run::{{closure}}::hcecc10b7cee6d1f1
  58:        0x103bc11a1 - std::thread::local::LocalKey<T>::try_with::h3efeae341c727eb2
  59:        0x103bc0e6d - std::thread::local::LocalKey<T>::with::hf4183622ef5985e3
  60:        0x103bc7fc4 - tokio_threadpool::worker::Worker::do_run::hbe76d3b2b93e717d
  61:        0x103bd1f85 - tokio_threadpool::pool::Pool::spawn_thread::{{closure}}::h02522770b54f5ebc
  62:        0x103ba8a40 - std::sys_common::backtrace::__rust_begin_short_backtrace::heaebad436376f986
  63:        0x103bbd150 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::haebb44d639c26a95
  64:        0x103bab390 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h738274f274cef414
  65:        0x103babcf5 - std::panicking::try::do_call::hbf17315d137033d0
  66:        0x103c7412f - __rust_maybe_catch_panic
  67:        0x103bab9f5 - std::panicking::try::h3695bd28b7fb87b8
  68:        0x103bab960 - std::panic::catch_unwind::hd98c897fdbf81ca4
  69:        0x103bbcf9e - std::thread::Builder::spawn_unchecked::{{closure}}::hd85981720be79d5f
  70:        0x103bc3ba5 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h16b65ba71dc244f0
  71:        0x103c607de - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hd1afe4d791e3679f
  72:        0x103c7364e - std::sys::unix::thread::Thread::new::thread_start::h785fcf8d81bd0f52
  73:     0x7fff6471d2eb - _pthread_body
  74:     0x7fff64720249 - _pthread_start
Dec 18 22:02:27.716 CRIT Task panicked, task: block

**Comment by rinor** [comment]
@mzabaluev the node of @hodlonaut is compiled in debug mode.
based on the changes
https://github.com/input-output-hk/jormungandr/blob/ce0e7ab91120d59095c913b455ed0fe6168e8941/jormungandr/src/blockchain/candidate.rs#L485-L495
you are already handling it. Is this still considered a bug?

**Comment by mzabaluev** [comment]
> Is this still considered a bug?

An unexpected state can still be reached, as the assertion shows.
@hodlonaut or anyone who can reproduce the [latest panic](https://github.com/input-output-hk/jormungandr/issues/1388#issuecomment-566987703), can you post the zipped log output with `debug` level?

**Comment by rinor** [comment]
@mzabaluev 
`missed chain pull root ...` - [itn_v1-missed_chain_pull_root_candidate-master-ee41f58c.zip](https://github.com/input-output-hk/jormungandr/files/3983107/itn_v1-missed_chain_pull_root_candidate-master-ee41f58c.zip)

**Comment by rinor** [comment]
@mzabaluev 
`chain pull root candidate..cached..` - [itn_v1-chain_pull_root_candidate-master-ee41f58c.zip](https://github.com/input-output-hk/jormungandr/files/3983527/itn_v1-chain_pull_root_candidate-master-ee41f58c.zip)


just in case you need it.
