### ISSUE TITLE
The blocks my pool creates are not visible in the ITN explorer.

### ISSUE THREAD

**Issue by dmbtc** [input-output-hk/jormungandr#1391]
**Describe the bug**
The blocks my pool creates are not visible in the ITN explorer. 
but if I query the status of my node and search for the received block in the explorer it will be found so I am in sync.

**Mandatory Information**
1. `jcli --full-version` output: jcli 0.8.3 (HEAD-8f276c0, release, linux [aarch64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
2. `jormungandr --full-version` output: jormungandr 0.8.3 (HEAD-8f276c0, release, linux [aarch64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

**To Reproduce**

Pool ID : 5f3e0e1dbd5a1770a1d4ec10e14076f7e49106047a7270fba9a103a57f89276a
1.  ./jcli rest v0 leaders logs get -h .......

- created_at_time: "2019-12-18T06:23:58.501326406+00:00"
  enclave_leader_id: 1
  finished_at_time: "2019-12-18T06:50:49.028952846+00:00"
  scheduled_at_date: "4.20916"
  scheduled_at_time: "2019-12-18T06:50:49+00:00"
  status:
    Block:
      block: 359d22d435ba851f94ffbf9ab06a372cc3f9fb981eb46de4c07863db2eaf1e99
      chain_length: 17242
  wake_at_time: "2019-12-18T06:50:49.001538485+00:00"

2. ./jcli rest v0 node stats get --host .....
---
blockRecvCnt: 105
lastBlockContentSize: 315
lastBlockDate: "4.21468"
lastBlockFees: 800000
lastBlockHash: 41eed36eeab07b85dcc5fe1392bd41df04ca03bdb21c4a05950af68132575c6b
lastBlockHeight: "17287"
lastBlockSum: 39629374318
lastBlockTime: "2019-12-18T07:18:12+00:00"
lastBlockTx: 1
state: Running
txRecvCnt: 75
uptime: 3339
version: jormungandr 0.8.3-8f276c0

**Comment by rinor** [comment]
It happens, if you or the explorer are on different forks. Will check more a bit later, but it appears that indeed your pool produced a block in epoch 4 slot 20916, but it was in a fork that later on was resolved (assuming that you are in the same tip as explorer shows). So the branch/fork in which you produced the block was discarded. As you can check also from the explorer, in the actual chain there is no block produced for epoch 4 slot 20916. The nearest one is slot 20914 and after that the next one is slot 20973. Will dig more later on.

**Comment by NicolasDP** [comment]
Like @rinor said, this may happen. It could be for multiple reasons:

* your block was not propagated to the network;
* your leader had a concurrent leader for the same slot and the network favoured that other leader for _consensus reasons_.
* your node was out of sync for long enough to be create a block on a fork that was dismissed.

**Comment by dmbtc** [comment]
My node was always in sync with the explorer before and after. I checked that specially. 
Here an leader event after i reported but the block doesn´t exist. It happens on every block I've been selected for in this epoch. 

Dec 18 10:54:25.002 INFO Leader event started, event_remaining_time: 1s 998ms 214us 788ns, event_end: 2019-12-18T10:54:27+00:00, event_start: 2019-12-18T10:54:25+00:00, event_date: 4.28224, leader_id: 1, task: leadership
Dec 18 10:54:25.056 INFO receiving block from leadership service, date: 4.28224, parent: 73b97515aa326c305f28e25af9e442227881d23a23e22aa3ba172aa0c67ae6ef, hash: b3b09faaafecac46d94dac944357d507b0dbb2d6820a2350aae4b90e78690fb6, task: block
Dec 18 10:54:25.126 INFO block from leader event successfully stored, date: 4.28224, parent: 73b97515aa326c305f28e25af9e442227881d23a23e22aa3ba172aa0c67ae6ef, hash: b3b09faaafecac46d94dac944357d507b0dbb2d6820a2350aae4b90e78690fb6, task: block
