### ISSUE TITLE
Duplicate stakepool with same ticker (MOON2)

### ISSUE THREAD

**Issue by dusanmrozek** [input-output-hk/jormungandr#1398]
**Describe the bug**
I was re-creating my stakepool and registered MOON2 with same pledge address, but probably different owner. Not sure exactly, but now users can see two MOON2 stake pools in Daedalus some of them are delegating to bad one (offline / not running).

In the registry there are currently correct metadata for MOON2 ticker in ed25519_pk1z62ntm5lzhdzfsjn2rkym4fmxf7n4pdqrl64km8xpskn9fd8203sahkful.json file. I can not find the other file with old metada as I already do not know the owner public key.

**Mandatory Information**
Not relevant here

**To Reproduce**
Not relevant here

**Expected behavior**
Only the stakepools listed in registry should be visible in Daedalus and Yoroi

**Additional context**
I was trying to raise this issue in registry github, but it is locked with a reference to this repo and stake pool de-registration. But people are delegating to a bad pool as it is visible in Daedalus.

![image](https://user-images.githubusercontent.com/58665645/71132204-26cf9b00-21f7-11ea-9300-ec96272cdfa9.png)

**Comment by rdlrt** [comment]
Invalid
1. Wrong repo - this is for jormungandr node itself.
2. Pool is not registered in registry, owner key is - any pool created with that owner key will show up with that ticker. You can elect to not run one of them and it will start going lower. You can submit PR on right repository if you'd like to replace owner to a different account, which has only 1 pool if needed.

**Comment by dusanmrozek** [comment]
All clear now, thank you. Its a pitty there is no way to remove particular pool ID.
