### ISSUE TITLE
Wrong parent block - j. 0.8.3

### ISSUE THREAD

**Issue by A-Caccese** [input-output-hk/jormungandr#1403]
**Describe the bug**
My node was scheduled as leader at 2019-12-19T10:25:07+00:00 and successfully created a block with hash 2f08630a9a97fb5631df07b5174d1921070230630682ae8f9151ac554db04791 and parent block hash a80c8ca71aebe2edbfc26154406935bf012140c94080a470d276bc73a85d0670. However the block that my node generated was on a fork, so is not visible on https://shelleyexplorer.cardano.org (CARDANO EXPLORER). 
Digging in my logs and searching on CARDANO EXPLORER I found that the parent node of my block was created at 03:35:23, December 19, 2019, epoch 5, slot 13253. This block is already the parent of the block 2d5d2777d8673817b0776a9983029d536a360174612e3aafd6298fc6ccd09f69.

I'm pretty sure that my node was full sync with the version of the blockchain visible on CARDANO EXPLORER during the leader event, because the last block hash reported in my node stats is visible on CARDANO EXPLORER. 

How is possible that my node generate a block with a block parent already used and with a previous block with a wrong date?

---------------------------------------------------------------

1. jcli 0.8.3 (8.3_Legacy-8f276c00, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)];

2. jormungandr 0.8.3 (8.3_Legacy-8f276c00, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)];

**Comment by A-Caccese** [comment]
I have to rectify. My node wasn't sync, so I think that this problem is the same as the last ones reported.

**Comment by rinor** [comment]
@A-Caccese closing this one since as you mentioned this is a side effect of other issues reported and being tracked. Thank you for the report.
