### ISSUE TITLE
gossip_interval cannot be set

### ISSUE THREAD

**Issue by Rugbertl** [input-output-hk/jormungandr#1406]
**Describe the bug**
It is currently not possible to change the gossip_interval.

**Mandatory Information**
1.) jcli 0.8.3 (HEAD-8f276c0, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
2.) jormungandr 0.8.3 (HEAD-8f276c0, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

**To Reproduce**
1. Change config
2. Start node

**Expected behavior**

**Additional context**
Error in the overall configuration of the node
 |-> Error while parsing the node configuration file: p2p.gossip_interval: unknown unit at 2-2 at line 13 column 24
 |-> p2p.gossip_interval: unknown unit at 2-2 at line 13 column 24

**Comment by NicolasDP** [comment]
what value did you set?

**Comment by Rugbertl** [comment]
I tried
10, 5, 4
"10", "5"

**Comment by NicolasDP** [comment]
ha ok. make sense with the `unknown unit` error. It cannot tell if you are speaking seconds or minutes or hours or day. try `10s`

**Comment by Rugbertl** [comment]
OK thanks for the info. Please update the documentation on this one here:
https://input-output-hk.github.io/jormungandr/configuration/network.html

the default is 10s or 10m or 10h or 10d?
