### ISSUE TITLE
On 0.8.4 Same issue as #1401: Node keeps crashing

### ISSUE THREAD

**Issue by Gertjan-stakingpoolholder** [input-output-hk/jormungandr#1407]
**Describe the bug**
Exactly the same as described in #1401 

**Mandatory Information**
1. `jcli --full-version` output; jcli 0.8.4 (HEAD-2227eb2, release, macos [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
2. `jormungandr --full-version` output; jormungandr 0.8.4 (HEAD-2227eb2, release, macos [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**Comment by mzabaluev** [comment]
> Exactly the same as described in #1401

No need to file a separate issue for this, then.
