### ISSUE TITLE
Error in documentation of public_id

### ISSUE THREAD

**Issue by mark-stopka** [input-output-hk/jormungandr#1420]
**Describe the bug**
On a page [Node network](https://input-output-hk.github.io/jormungandr/configuration/network.html) of the Jormungandr documentation, in section **Setting the public_id** it says 

> Unless you want to advertise your node as a trusted peer, you don't want to set a public_id. **This is completely useful**. If not set, the node will generate a random one automatically.

While I disagree with the statement, because it will reduce the log noise upon node restart for other poldercast peers; I believe in order for the paragraph to make any sort of sense, word **useful** should be replace by a word **useless**.

**Mandatory Information**
1. N/A
2. N/A

**To Reproduce**
Already mentioned in bug description.

**Comment by thiago-tsnnst** [comment]
The documentantion to generate public id is also outdated. I tryed to conect 2 nodes and i cant reach the point to generate the simplified key. Its the derivate option? what is the index parameter?

**Comment by mark-stopka** [comment]
@thiago-tsnnst you can generate public_id by running `openssl rand -hex 24`;
