### ISSUE TITLE
no data at API endpoint /api/v0/stake_pool

### ISSUE THREAD

**Issue by dogpatchmedia** [input-output-hk/jormungandr#1421]
**Describe the bug**

Query jormungandr API for stake_pool endpoint and nothing is returned.

**Mandatory Information**
1. `jcli --full-version` output;
jcli 0.8.4
2. `jormungandr --full-version` output;
jormungandr 0.8.4

**To Reproduce**

https://editor.swagger.io/?url=https://raw.githubusercontent.com/input-output-hk/jormungandr/master/doc/openapi.yaml

[get] /api/v0/stake_pool

enter terminal and type:
$ curl -X GET "http://127.0.0.1:3100/api/v0/stake_pool" -H "accept: application/json"

you'll get nothing back.

**Expected behavior**
JSON results from API query

**Additional context**
using Guzzle in a PHP application you get the specific error of:
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET http://127.0.0.1:3100/api/v0/stake_pool` resulted in a `404 Not Found`

**Comment by laplasz** [comment]
at least the query via jcli is working:
`jcli rest v0 stake-pool get <node id> -h http://127.0.0.1:3100/api`
