### ISSUE TITLE
I WANT make STAKE POOL

### ISSUE THREAD

**Issue by z6586** [input-output-hk/jormungandr#1424]
failed to make a REST request
  |-> node rejected request because of invalid parameters
  |-> http://127.0.0.1:3100/api/v0/account/d5fbd475fbcbdc1f850c95fc6d16ff10e75ada6c2ad4c23b14b17d4d4546fbb7: Client Error: 404 Not Found
 ##1. Create the offline transaction file
 ##2. Add the Account to the transaction
 ##3. Add the certificate to the transaction
 ##4. Finalize the transaction
 ##5. Make the witness
error: Invalid value for '--account-spending-counter <account-spending-counter>': cannot parse integer from empty string ##5. Retrieve your stake pool id (NodeId)

ADDRESS:        addr1sh2lh4r4l09ac8u9pj2lcmgklugwwkk6ds4dfs3mzjch6n29gmamwky50e3

please help

**Comment by z6586** [comment]
I have no test ada. Is there any other way?

**Comment by laplasz** [comment]
Do you have ada from snapshot? Do you have testnet wallet? What was the command you executed that REST request?

**Comment by NicolasDP** [comment]
you can find more help there: https://testnet.iohkdev.io/en/
