### ISSUE TITLE
Block produced but is not visible in Cardano Explorer

### ISSUE THREAD

**Issue by frugalpool** [input-output-hk/jormungandr#1427]
**Describe the bug**

My node produced a block that is not visible in Cardano Explorer. I've been losing a large number of blocks without error messages so I investigated this one.

**Mandatory Information**
1. `jcli --full-version` output;

jcli 0.8.5-alpha2 (HEAD-71d252e, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

2. `jormungandr --full-version` output;

jormungandr 0.8.5-alpha2 (HEAD-71d252e, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**To Reproduce**

See screenshots attached
<img width="1874" alt="Screenshot 2019-12-22 05 58 12" src="https://user-images.githubusercontent.com/58694484/71321590-24807180-2481-11ea-9ca4-220d641fa04d.png">
<img width="1310" alt="Screenshot 2019-12-22 05 56 40" src="https://user-images.githubusercontent.com/58694484/71321592-2e09d980-2481-11ea-9296-241ac1301369.png">

**Expected behavior**

Expected block to be visible in Cardano Explorer but is not

**Comment by frugalpool** [comment]
Here's some more information:

- created_at_time: "2019-12-22T10:20:43.645650301+00:00"
  enclave_leader_id: 1
  finished_at_time: "2019-12-22T11:45:59.003994389+00:00"
  scheduled_at_date: "8.29771"
  scheduled_at_time: "2019-12-22T11:45:59+00:00"
  status:
    Block:
      block: 7e4dd1a606ad2596434b413ca9286c2364cdbb6c628d01a67fbf6aecc90f6bb4
      chain_length: 29314
  wake_at_time: "2019-12-22T11:45:59.000896781+00:00"

Also, some later blocks show up in Explorer and some don't, and then sometimes they show and up and then not! Maybe Explorer has an issue. 

Maybe it will help you to debug if you have some subsequent blocks:

blockRecvCnt: 178
lastBlockContentSize: 315
lastBlockDate: "8.30833"
lastBlockFees: 800000
lastBlockHash: ff17d3ef18eefe91fdc01b69e94ab2c6f231d60992c599f5affc557375853998
lastBlockHeight: "29401"
lastBlockSum: 423725107743
lastBlockTime: "2019-12-22T12:21:46+00:00"
lastBlockTx: 1
state: Running
txRecvCnt: 72
uptime: 1943
version: jormungandr 0.8.5-alpha2-71d252e


blockRecvCnt: 181
lastBlockContentSize: 0
lastBlockDate: "8.30886"
lastBlockFees: 0
lastBlockHash: cef7fbc80b22f3760c561144a79106b27056ac09addc0ce0e1a85170314f37bd
lastBlockHeight: "29404"
lastBlockSum: 0
lastBlockTime: "2019-12-22T12:23:09+00:00"
lastBlockTx: 0
state: Running
txRecvCnt: 74
uptime: 2044
version: jormungandr 0.8.5-alpha2-71d252e

**Comment by frugalpool** [comment]
A subsequent leader event shows up in Explorer

- created_at_time: "2019-12-22T11:49:39.047317749+00:00"
enclave_leader_id: 1
  finished_at_time: "2019-12-22T13:28:07.002542498+00:00"
  scheduled_at_date: "8.32835"
  scheduled_at_time: "2019-12-22T13:28:07+00:00"
  status:
    Block:
      block: 0b4f0fe3596ba2fdea79f809f397b75a90b043e85c6a228416a87cbb7fc9f32f
      chain_length: 29560
  wake_at_time: "2019-12-22T13:28:07.001188077+00:00"
- created_at_time: "2019-12-22T11:49:39.047352299+00:00"

<img width="1337" alt="Screenshot 2019-12-22 07 32 39" src="https://user-images.githubusercontent.com/58694484/71322552-58ae5f00-248e-11ea-8cc1-171342f17d61.png">
<img width="1830" alt="Screenshot 2019-12-22 07 34 57" src="https://user-images.githubusercontent.com/58694484/71322561-77acf100-248e-11ea-9eb4-5280feb7c711.png">

I expect 19 blocks to be registered in Explorer but only 10 show up. There were no failure notifications on the others.
<img width="1480" alt="Screenshot 2019-12-22 07 46 51" src="https://user-images.githubusercontent.com/58694484/71322614-43860000-248f-11ea-943f-906b6d830be1.png">


TAG32835---
blockRecvCnt: 433
lastBlockContentSize: 0
lastBlockDate: "8.32843"
lastBlockFees: 0
lastBlockHash: 1290ca78a3569512211b8ffba43db7cf17ef708a8a2320af925f07a8aed8f0f5
lastBlockHeight: "29561"
lastBlockSum: 0
lastBlockTime: "2019-12-22T13:28:25+00:00"
lastBlockTx: 0
state: Running
txRecvCnt: 167
uptime: 5932
version: jormungandr 0.8.5-alpha2-71d252e

== Scheduled leader events 
8.32835
8.34970
8.38046
8.38189
8.40026
8.40446
8.41571
7
== recently minted blocks 
8.32835 
Time accuracy 
synchronised to NTP server (206.108.0.133) at stratum 2 
   time correct to within 28 ms
   polling server every 1024 s

Pool info 
stake pool id  8819ca23c3ac6865d6578350de0bcb072e797519410b923d18f56b61370d93ff
https://shelleyexplorer.cardano.org/en/stake-pool/1171304154a20bd28cae430c7e9c915e5bdc1eec69893dc69d7267be7197ae21/

Blocks scheduled:  26 
Leader events accomplished without failure notification so far, apparently :  19 
Leader events missed so far in this epoch:  0

**Comment by frugalpool** [comment]
I discovered a workaround to this problem: I simply restart jormungandr with REST command within 20 minutes of the leader event.  Blocks then successfully show up in Cardano Explorer.

**Comment by frugalpool** [comment]
Even when keeping Jormungandr "fresh" I still experience this anomalous behavior from time to time but much less frequently

**Comment by frugalpool** [comment]
for example I produced a block as scheduled at 14.29395 but you won't find this block date in Explorer for Epoch 14 and it wasn't credited as a minted block

**Comment by frugalpool** [comment]
now using jormungandr 0.8.5 (HEAD-3db0680, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)] which actually seems to be more susceptible such anomalous behavior than the prior alpha 3 version but I don't have hard data on that

**Comment by Proxiweb** [comment]
What is the block hash you have created ? 7e4dd1a606ad2596434b413ca9286c2364cdbb6c628d01a67fbf6aecc90f6bb4 ?

**Comment by frugalpool** [comment]
minted
14.75
14.480
14.1231
14.2407
14.6208
14.6612
14.7958
14.9540
14.12885
>>14.18809
14.19801
14.19993
14.23555
>>14.29395
14.30319
15    

You won't find the block times identified with ">>" in explorer and the total number produced for FRGL pool shows up as 13 so far in this Epoch.  This is not a problem of conjunction with another pool where they are assigned the same block date otherwise this block date would show up in explorer and it doesn't. I have lost blocks do to being assigned same scheduled dates so I know what that looks like.  At the moment I'm restarting Jormungandr before each scheduled block so that it's not more than 1820 seconds from a restart at the time the block needs to be produced. Even so, I've lost 2 of 15 blocks so far this Epoch.

**Comment by frugalpool** [comment]
> What is the block hash you have created ? 7e4dd1a606ad2596434b413ca9286c2364cdbb6c628d01a67fbf6aecc90f6bb4 ?
- created_at_time: "2019-12-28T11:38:08.205081332+00:00"
  enclave_leader_id: 1
  finished_at_time: "2019-12-28T12:04:15.003301920+00:00"
  scheduled_at_date: "14.30319"
  scheduled_at_time: "2019-12-28T12:04:15+00:00"
  status:
    Block:
      block: 1613306fa1bd24b61d6bb8c81873d7b8b36d4d3332c01e638129373d4deffb42
      chain_length: 48575
  wake_at_time: "2019-12-28T12:04:15.000800548+00:00"

**Comment by frugalpool** [comment]
the block hash from the original post doesn't show up with the jcli rest api but the more recent two to show up:

root@frugalmain:~/frugalpool# ./jcli rest v0 block 7e4dd1a606ad2596434b413ca9286c2364cdbb6c628d01a67fbf6aecc90f6bb4 get
failed to make a REST request
  |-> node rejected request because of invalid parameters
  |-> http://127.0.0.1:3102/api/v0/block/7e4dd1a606ad2596434b413ca9286c2364cdbb6c628d01a67fbf6aecc90f6bb4: Client Error: 404 Not Found
root@frugalmain:~/frugalpool# ./jcli rest v0 block 75a50523263f33b15a6656976adbe1fdcb0e5d86c426b6ba0dd127f562ff905e get
02b60002000000000000000e000049790000ba790e5751c026e543b2e8ab2eb06099daa1d1e5df47778f7787faab45cdf12fe3a8d641a56144373d2fdb7913675fdffceba2848c8daa022131bfe235d1a400b6431171304154a20bd28cae430c7e9c915e5bdc1eec69893dc69d7267be7197ae2176c693e409184f62e0ed523156b2d3c0152eab3897ab97edcb26d98c746b845ddaab9791ee4354d9bf429a170c0eab96b6f7bdbeacd3e8d0f5a603ba4ac57106b8bfecafc295ac8cec837330a45d537146ce1cebe050f14d6bbb9bcbfcf7b7020000000084a284d70c21115bfc222de082f9a772e215e1697b5fbaf7e883f3461a5b91fb6412368b2e23d60300098faabf5e8b982cd7af6f3a6f23342c011b5c951f4902b15340ba451915d71dba2aecf9a5814cb8b30ef7ba2e836eb291df54426acc664160130f705ce316ebe336197ce7733f01987a9d3bcb71ea3522ff26558c8c4fa8fdc6a9b9b021722db2c09363f009d7fca2391c26b6a76cfb50a3ceb8c3fefc2e36a19a312a51a06d6f437dcf1116d6c9eda40343fb2d2a0633c36262686f84f634b4adaed7d350d0d1665dae58295ceac832709a01e91a2a0ec510f2975f1f34590f80dff25a1993cf156af363b3fd18cb515fa5465fd6bae0d42d3f81393bfca3fa965282fdf57be06de6f1b02c8ffde1d2ddf84e262c94e3b8368af0b24793dcaf90667e547159e722b387495557eb66f8a440fed7dcbc1e96cd51df946911610b250e71d3a4cceee33f20d483ff12023f8c328403d6ef16cb4395b4ca17790cc094bf3be3f39ef2d5b3359fceb386998290ebed00d82792b0550a6b4892f2cbc6774673d93dc063b39916eaefabb68e05857a0e503873c1ee1f319e72c993fc3f615de89ab2b66652c2f862234de1728309cff2e2024405b93e43ae5d776b513d803a3e772692f487ef1b6addcc9b2108b920ae37511c74700e446faf6c
root@frugalmain:~/frugalpool# ./jcli rest v0 block 0bfe5eb14dd751577cfc5f9a257848b649fd571cad626ae9332c73231cb83ac3 get
02b60002000000000000000e000072d30000bd710e5751c026e543b2e8ab2eb06099daa1d1e5df47778f7787faab45cdf12fe3a8142f303c55f19eae22997e02a3deacafc5eae611cd9124ee0556f3f9b9468b241171304154a20bd28cae430c7e9c915e5bdc1eec69893dc69d7267be7197ae2170f5889bc16684cacc0c6e6b015901d3f7b9c48d9e91e92661b47c82025a8a1c47e428a3e8b8ec60fec0035fbc54fef0d7e67671dc2e32587ac508b62f3f2a0c8558f44173c3404c3e6d139f8d2b7fe0c357203a30c4b6a2eb0a5891d33d500d0000000004e82eb2a3c2556515776862a7f32af62ea263839088219ad1a62b3f85427a30f763e8067a955460d3553f7a8fdb0c3cd67233ee102e36a4abd6c015fd6bd200b15340ba451915d71dba2aecf9a5814cb8b30ef7ba2e836eb291df54426acc664160130f705ce316ebe336197ce7733f01987a9d3bcb71ea3522ff26558c8c4fa8fdc6a9b9b021722db2c09363f009d7fca2391c26b6a76cfb50a3ceb8c3fefc2e36a19a312a51a06d6f437dcf1116d6c9eda40343fb2d2a0633c36262686f84f634b4adaed7d350d0d1665dae58295ceac832709a01e91a2a0ec510f2975f1f34590f80dff25a1993cf156af363b3fd18cb515fa5465fd6bae0d42d3f81393bfca3fa965282fdf57be06de6f1b02c8ffde1d2ddf84e262c94e3b8368af0b24793dcaf90667e547159e722b387495557eb66f8a440fed7dcbc1e96cd51df946911610b250e71d3a4cceee33f20d483ff12023f8c328403d6ef16cb4395b4ca17790cc094bf3be3f39ef2d5b3359fceb386998290ebed00d82792b0550a6b4892f2cbc6774673d93dc063b39916eaefabb68e05857a0e503873c1ee1f319e72c993fc3f615de89ab2b66652c2f862234de1728309cff2e2024405b93e43ae5d776b513d803a3e772692f487ef1b6addcc9b2108b920ae37511c74700e446faf6c
root@frugalmain:~/frugalpool#

**Comment by frugalpool** [comment]
So I check on another machine I have and it only finds one of the blocks. I'm using two machines with same secret.yaml and one machine minted one of the recent blocks and the other machine did the other block, even though one of the machines found both recently blocks.

```
root@frugal_de:~/frugalpool# ./jcli rest v0 block 7e4dd1a606ad2596434b413ca9286c2364cdbb6c628d01a67fbf6aecc90f6bb4 get
failed to make a REST request
  |-> node rejected request because of invalid parameters
  |-> http://127.0.0.1:3102/api/v0/block/7e4dd1a606ad2596434b413ca9286c2364cdbb6c628d01a67fbf6aecc90f6bb4: Client Error: 404 Not Found
root@frugal_de:~/frugalpool# ./jcli rest v0 block 75a50523263f33b15a6656976adbe1fdcb0e5d86c426b6ba0dd127f562ff905e get
failed to make a REST request
  |-> node rejected request because of invalid parameters
  |-> http://127.0.0.1:3102/api/v0/block/75a50523263f33b15a6656976adbe1fdcb0e5d86c426b6ba0dd127f562ff905e: Client Error: 404 Not Found
root@frugal_de:~/frugalpool# ./jcli rest v0 block 0bfe5eb14dd751577cfc5f9a257848b649fd571cad626ae9332c73231cb83ac3 get
02b60002000000000000000e000072d30000bd710e5751c026e543b2e8ab2eb06099daa1d1e5df47778f7787faab45cdf12fe3a8142f303c55f19eae22997e02a3deacafc5eae611cd9124ee0556f3f9b9468b241171304154a20bd28cae430c7e9c915e5bdc1eec69893dc69d7267be7197ae2170f5889bc16684cacc0c6e6b015901d3f7b9c48d9e91e92661b47c82025a8a1c47e428a3e8b8ec60fec0035fbc54fef0d7e67671dc2e32587ac508b62f3f2a0c8558f44173c3404c3e6d139f8d2b7fe0c357203a30c4b6a2eb0a5891d33d500d0000000004e82eb2a3c2556515776862a7f32af62ea263839088219ad1a62b3f85427a30f763e8067a955460d3553f7a8fdb0c3cd67233ee102e36a4abd6c015fd6bd200b15340ba451915d71dba2aecf9a5814cb8b30ef7ba2e836eb291df54426acc664160130f705ce316ebe336197ce7733f01987a9d3bcb71ea3522ff26558c8c4fa8fdc6a9b9b021722db2c09363f009d7fca2391c26b6a76cfb50a3ceb8c3fefc2e36a19a312a51a06d6f437dcf1116d6c9eda40343fb2d2a0633c36262686f84f634b4adaed7d350d0d1665dae58295ceac832709a01e91a2a0ec510f2975f1f34590f80dff25a1993cf156af363b3fd18cb515fa5465fd6bae0d42d3f81393bfca3fa965282fdf57be06de6f1b02c8ffde1d2ddf84e262c94e3b8368af0b24793dcaf90667e547159e722b387495557eb66f8a440fed7dcbc1e96cd51df946911610b250e71d3a4cceee33f20d483ff12023f8c328403d6ef16cb4395b4ca17790cc094bf3be3f39ef2d5b3359fceb386998290ebed00d82792b0550a6b4892f2cbc6774673d93dc063b39916eaefabb68e05857a0e503873c1ee1f319e72c993fc3f615de89ab2b66652c2f862234de1728309cff2e2024405b93e43ae5d776b513d803a3e772692f487ef1b6addcc9b2108b920ae37511c74700e446faf6c
root@frugal_de:~/frugalpool#

```

**Comment by frugalpool** [comment]
And the results from a third machine I have but is using is not acting as a slot leader.  It finds the two most recent blocks but the one from 6 days ago.

```root@frugal_de:~/frugalpool# ./jcli rest v0 block 75a50523263f33b15a6656976adbe1fdcb0e5d86c426b6ba0dd127f562ff905e get
failed to make a REST request
  |-> node rejected request because of invalid parameters
  |-> http://127.0.0.1:3102/api/v0/block/75a50523263f33b15a6656976adbe1fdcb0e5d86c426b6ba0dd127f562ff905e: Client Error: 404 Not Found
root@frugal_de:~/frugalpool# ./jcli rest v0 block 0bfe5eb14dd751577cfc5f9a257848b649fd571cad626ae9332c73231cb83ac3 get
02b60002000000000000000e000072d30000bd710e5751c026e543b2e8ab2eb06099daa1d1e5df47778f7787faab45cdf12fe3a8142f303c55f19eae22997e02a3deacafc5eae611cd9124ee0556f3f9b9468b241171304154a20bd28cae430c7e9c915e5bdc1eec69893dc69d7267be7197ae2170f5889bc16684cacc0c6e6b015901d3f7b9c48d9e91e92661b47c82025a8a1c47e428a3e8b8ec60fec0035fbc54fef0d7e67671dc2e32587ac508b62f3f2a0c8558f44173c3404c3e6d139f8d2b7fe0c357203a30c4b6a2eb0a5891d33d500d0000000004e82eb2a3c2556515776862a7f32af62ea263839088219ad1a62b3f85427a30f763e8067a955460d3553f7a8fdb0c3cd67233ee102e36a4abd6c015fd6bd200b15340ba451915d71dba2aecf9a5814cb8b30ef7ba2e836eb291df54426acc664160130f705ce316ebe336197ce7733f01987a9d3bcb71ea3522ff26558c8c4fa8fdc6a9b9b021722db2c09363f009d7fca2391c26b6a76cfb50a3ceb8c3fefc2e36a19a312a51a06d6f437dcf1116d6c9eda40343fb2d2a0633c36262686f84f634b4adaed7d350d0d1665dae58295ceac832709a01e91a2a0ec510f2975f1f34590f80dff25a1993cf156af363b3fd18cb515fa5465fd6bae0d42d3f81393bfca3fa965282fdf57be06de6f1b02c8ffde1d2ddf84e262c94e3b8368af0b24793dcaf90667e547159e722b387495557eb66f8a440fed7dcbc1e96cd51df946911610b250e71d3a4cceee33f20d483ff12023f8c328403d6ef16cb4395b4ca17790cc094bf3be3f39ef2d5b3359fceb386998290ebed00d82792b0550a6b4892f2cbc6774673d93dc063b39916eaefabb68e05857a0e503873c1ee1f319e72c993fc3f615de89ab2b66652c2f862234de1728309cff2e2024405b93e43ae5d776b513d803a3e772692f487ef1b6addcc9b2108b920ae37511c74700e446faf6c
root@frugal_de:~/frugalpool# ./jcli rest v0 block 0bfe5eb14dd751577cfc5f9a257848b649fd571cad626ae9332c73231cb83ac3 get
02b60002000000000000000e000072d30000bd710e5751c026e543b2e8ab2eb06099daa1d1e5df47778f7787faab45cdf12fe3a8142f303c55f19eae22997e02a3deacafc5eae611cd9124ee0556f3f9b9468b241171304154a20bd28cae430c7e9c915e5bdc1eec69893dc69d7267be7197ae2170f5889bc16684cacc0c6e6b015901d3f7b9c48d9e91e92661b47c82025a8a1c47e428a3e8b8ec60fec0035fbc54fef0d7e67671dc2e32587ac508b62f3f2a0c8558f44173c3404c3e6d139f8d2b7fe0c357203a30c4b6a2eb0a5891d33d500d0000000004e82eb2a3c2556515776862a7f32af62ea263839088219ad1a62b3f85427a30f763e8067a955460d3553f7a8fdb0c3cd67233ee102e36a4abd6c015fd6bd200b15340ba451915d71dba2aecf9a5814cb8b30ef7ba2e836eb291df54426acc664160130f705ce316ebe336197ce7733f01987a9d3bcb71ea3522ff26558c8c4fa8fdc6a9b9b021722db2c09363f009d7fca2391c26b6a76cfb50a3ceb8c3fefc2e36a19a312a51a06d6f437dcf1116d6c9eda40343fb2d2a0633c36262686f84f634b4adaed7d350d0d1665dae58295ceac832709a01e91a2a0ec510f2975f1f34590f80dff25a1993cf156af363b3fd18cb515fa5465fd6bae0d42d3f81393bfca3fa965282fdf57be06de6f1b02c8ffde1d2ddf84e262c94e3b8368af0b24793dcaf90667e547159e722b387495557eb66f8a440fed7dcbc1e96cd51df946911610b250e71d3a4cceee33f20d483ff12023f8c328403d6ef16cb4395b4ca17790cc094bf3be3f39ef2d5b3359fceb386998290ebed00d82792b0550a6b4892f2cbc6774673d93dc063b39916eaefabb68e05857a0e503873c1ee1f319e72c993fc3f615de89ab2b66652c2f862234de1728309cff2e2024405b93e43ae5d776b513d803a3e772692f487ef1b6addcc9b2108b920ae37511c74700e446faf6c
root@frugal_de:~/frugalpool# 

```

**Comment by hex-pool** [comment]
I've noticed this as all and I'm almost certain it's a syncing / timing / latency issue.

I've used pooltool to monitor the latest reported height vs my node's height and noticed the following:

If my node is fully in sync before it's due to create a block, the block will get accepted by the network.

If it's off by just one block it created a block with an "older" parent which will get rejected.

To better explain this, let's assume that my node's last block height is 48813.
Someone one the network creates 48814, but my node doesn't see it yet. My node is due to create a block, so it will use 48813 as a parent. When it pushes the new block, the network will see an older block with 48813 as a parent (which by now might be part of a longer chain) and my new block with the same 48813 as a parent (shorter / newer chain).

**Comment by frugalpool** [comment]
> I've noticed this as well and I'm almost certain it's a syncing / timing / latency issue.
> 
> I've used pooltool to monitor the latest reported height vs my node's height and noticed the following:
> 
> If my node is fully in sync before it's due to create a block, the block will get accepted by the network.
> 
> If it's off by just one block it creates a block with an "older" parent which will get rejected.
> 
> To better explain this, let's assume that my node's last block height is 48813.
> Someone one the network creates 48814, but my node doesn't see it yet. My node is due to create a block, so it will use 48813 as a parent. When it pushes the new block, the network will see an older block with 48813 as a parent (which by now might be part of a longer chain) and my new block with the same 48813 as a parent (shorter / newer chain).

that would explain why a "fresh" restart would help get blocks that stick on the main chain but I still need to explain why my third machine has two blocks that aren't on the main chain, unless it stored the temporary forks too?

**Comment by frugalpool** [comment]
> I've noticed this as well and I'm almost certain it's a syncing / timing / latency issue.
> 
> I've used pooltool to monitor the latest reported height vs my node's height and noticed the following:
> 
> If my node is fully in sync before it's due to create a block, the block will get accepted by the network.
> 
> If it's off by just one block it creates a block with an "older" parent which will get rejected.
> 
> To better explain this, let's assume that my node's last block height is 48813.
> Someone one the network creates 48814, but my node doesn't see it yet. My node is due to create a block, so it will use 48813 as a parent. When it pushes the new block, the network will see an older block with 48813 as a parent (which by now might be part of a longer chain) and my new block with the same 48813 as a parent (shorter / newer chain).

Thanks for the feedback and insight.
