### ISSUE TITLE
itn_rewards_v1 - jcli generates a binary genesis which hash is different from the official one

### ISSUE THREAD

**Issue by wxsq2004** [input-output-hk/jormungandr#1430]
**Describe the bug**
Instead of launching a node with the provided pre-computed hash of genesis block,  I'd like to launch it with the genesis binary file. 
But the hash resulting from this binary is not equal to the pre-computed one.

This occurs with itn_rewards_v1 deployment buid, and not with nightly or legacy.

**Mandatory Information**
jcli 0.8.3 (HEAD-8f276c0, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
jormungandr 0.8.3 (HEAD-8f276c0, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

**To Reproduce**
1. Download YAML file from deployment build: https://hydra.iohk.io/build/1523436/download/1/itn_rewards_v1-genesis.yaml
2. Generate BIN file:
jcli genesis encode --input genesis.yaml --output genesis.bin
3. Compute hash from BIN file:
jcli genesis hash --input genesis.bin

The generated hash is '193950a45c1df112957efda7f8874b94c55e6e1605251394b95da7ae07c1e092' instead of '8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676'

**Expected behavior**
Hashes should be equal

**Additional context**
If we decode the generated BIN back to YAML
jcli genesis decode --input genesis.bin --output genesis-decoded.yaml
we can identify the differences (dictionnary keys orders, missing key/value pairs, string instead of float).

Attached,  the diff output that will help in identifying the differencies:
[diff.txt](https://github.com/input-output-hk/jormungandr/files/3993154/diff.txt)

**Comment by manveru** [comment]
For now you can find the actual config at https://explorer.incentivized-testnet.iohkdev.io/genesis/
The GitHub one was truncated because we didn't want such a large file in the repo.

**Comment by wxsq2004** [comment]
thanks

**Comment by wxsq2004** [comment]
What is the recommended way of starting the node, with the --genesis-block-hash option or with the --genesis-block one?
