### ISSUE TITLE
Cannot start Stake pool node

### ISSUE THREAD

**Issue by hdiuk** [input-output-hk/jormungandr#1431]
Guys, I am stuck right at the start. I have followed the instructions to start the pool and here is what I get

$ ./jormungandr --config beta-config.yaml --genesis-block-hash 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29
Error in the overall configuration of the node
 |-> Error while parsing the node configuration file: log: invalid type: map, expected a sequence at line 2 column 10
 |-> log: invalid type: map, expected a sequence at line 2 column 10

I am guessing that the issue is with the config file? 
I used the one provided. please can someone assist ?

**Comment by mark-stopka** [comment]
@hdiuk it would help if you posted the config... Use "```" at the begging and the end of your posted config for a nice formatting...

**Comment by hdiuk** [comment]
The problem persists with all methods so I tried to start a basic node and stake pool

I started a fresh 

This is the most recent method used  https://iohk.zendesk.com/hc/en-us/articles/360036898353 
all went great until I execute the command ./jormungandr.exe --config config.yaml --genesis-block-hash 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29| tee my-node.log

This is the output 

 Error in the overall configuration of the node
 |-> Error while parsing the node configuration file: log: invalid type: map, expected a sequence at line 2 column 10
 |-> log: invalid type: map, expected a sequence at line 2 column 10

The config file is as downloaded

{
  "log": {
    "format": "plain",
    "level": "info",
    "output": "stderr"
  },
  "p2p": {
    "topics_of_interest": {
      "blocks": "normal",
      "messages": "low"
    },
    "trusted_peers": [
      {
        "address": "/ip4/52.9.85.113/tcp/3000",
        "id": "7f47c880339670ad98d38ad3b379e1f7853479f8ef4f6fc7"
      },
      {
        "address": "/ip4/13.57.72.175/tcp/3000",
        "id": "b8b20f58b34dd7a485c8cff0d67f800149b1ff220b826632"
      },
      {
        "address": "/ip4/52.8.62.219/tcp/3000",
        "id": "f51aa0ce82b7f061e12762bd22b84424129f690655441b8e"
      },
      {
        "address": "/ip4/52.194.124.233/tcp/3000",
        "id": "255df5de725cd9d1087b8a3e4ff66d65572c36ceed791679"
      },
      {
        "address": "/ip4/52.197.220.18/tcp/3000",
        "id": "50768a0bb41781baa551cd96fb46a62e666e97874bca1cf5"
      },
      {
        "address": "/ip4/3.125.20.154/tcp/3000",
        "id": "ddfea960bc2fe1aa45af9b385b6bd3e949c050df61b5b451"
      },
      {
        "address": "/ip4/3.124.255.35/tcp/3000",
        "id": "2b7216b51b890ef1e8ade8e513dd6f2b35173e46b08ac1a9"
      }
    ]
  },
  "rest": {
    "listen": "127.0.0.1:3100"
  }
}

**Comment by zmeel** [comment]
Try:
  "log": [
    {
      "format": "plain",
      "level": "info",
      "output": "stderr"
    }
  ],

**Comment by hdiuk** [comment]
> Try:
> 
> ```
>   "log": [
>     {
>       "format": "plain",
>       "level": "info",
>       "output": "stderr"
>     }
>   ],
> ```

Thanks for that. When I try that on my PC install Windows 10, it throws up some other error. However, I am trying on my mac now as an experiment. So I changed to your suggestion on the mac and progress. Although short lived joy!

here is what happened

$ ./jormungandr --config beta-config.yaml --genesis-block-hash 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29
Dec 31 10:02:17.494 INFO Starting jormungandr 0.8.4 (HEAD-2227eb2, release, macos [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)], task: init
Dec 31 10:02:17.496 WARN Node started without path to the stored secret keys (not a stake pool or a BFT leader), task: init
Dec 31 10:02:17.516 INFO storing blockchain in memory, task: init
Dec 31 10:02:17.516 INFO fetching block 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29, peer_address: 3.124.255.35:3000, block: 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29, task: init
Dec 31 10:02:17.603 WARN failed to download block, error: GetBlocksStream { source: Error { code: InvalidArgument, source: Custom { kind: InvalidInput, error: StructureInvalid("Invalid config parameter tag") } } }, peer_address: 3.124.255.35:3000, block: 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29, task: init
Dec 31 10:02:17.603 INFO fetching block 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29, peer_address: 3.125.20.154:3000, block: 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29, task: init
Dec 31 10:02:17.665 WARN failed to download block, error: GetBlocksStream { source: Error { code: InvalidArgument, source: Custom { kind: InvalidInput, error: StructureInvalid("Invalid config parameter tag") } } }, peer_address: 3.125.20.154:3000, block: 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29, task: init
Dec 31 10:02:17.665 INFO fetching block 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29, peer_address: 52.197.220.18:3000, block: 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29, task: init
Dec 31 10:02:18.168 WARN failed to download block, error: GetBlocksStream { source: Error { code: InvalidArgument, source: Custom { kind: InvalidInput, error: StructureInvalid("Invalid config parameter tag") } } }, peer_address: 52.197.220.18:3000, block: 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29, task: init
Dec 31 10:02:18.168 INFO fetching block 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29, peer_address: 52.194.124.233:3000, block: 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29, task: init
Dec 31 10:02:18.707 WARN failed to download block, error: GetBlocksStream { source: Error { code: InvalidArgument, source: Custom { kind: InvalidInput, error: StructureInvalid("Invalid config parameter tag") } } }, peer_address: 52.194.124.233:3000, block: 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29, task: init
Dec 31 10:02:18.707 INFO fetching block 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29, peer_address: 52.8.62.219:3000, block: 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29, task: init
Dec 31 10:02:19.026 WARN failed to download block, error: GetBlocksStream { source: Error { code: InvalidArgument, source: Custom { kind: InvalidInput, error: StructureInvalid("Invalid config parameter tag") } } }, peer_address: 52.8.62.219:3000, block: 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29, task: init
Dec 31 10:02:19.026 INFO fetching block 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29, peer_address: 13.57.72.175:3000, block: 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29, task: init
Dec 31 10:02:19.338 WARN failed to download block, error: GetBlocksStream { source: Error { code: InvalidArgument, source: Custom { kind: InvalidInput, error: StructureInvalid("Invalid config parameter tag") } } }, peer_address: 13.57.72.175:3000, block: 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29, task: init
Dec 31 10:02:19.338 INFO fetching block 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29, peer_address: 52.9.85.113:3000, block: 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29, task: init
Dec 31 10:02:19.655 WARN failed to download block, error: GetBlocksStream { source: Error { code: InvalidArgument, source: Custom { kind: InvalidInput, error: StructureInvalid("Invalid config parameter tag") } } }, peer_address: 52.9.85.113:3000, block: 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29, task: init
Error fetching the genesis block from the network
 |-> could not download block hash 27668e95121566df0bb2e2c11c5fd95dfe59efd570f8f592235ecff167ca3f29

**Comment by zmeel** [comment]
If you want to connect to the ITN you should use the proper genesis-hash:
```8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676```

**Comment by zmeel** [comment]
Also, if you want to run a stake pool node you should start with the node_secret.yaml parameter too, otherwise you are running a passive node.

**Comment by hdiuk** [comment]
> If you want to connect to the ITN you should use the proper genesis-hash:
> `8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676`

Great stuff, thanks zmeel. I have got a little bit further. it looks like I managed to start the node but I got this error amongst the outputs 

Dec 31 16:05:40.616 WARN Node started without path to the stored secret keys (not a stake pool or a BFT leader), task: init

Should my config file include a path parameter? if so, how do I put it in?
also, your other comment "Also, if you want to run a stake pool node you should start with the node_secret.yaml parameter too, otherwise you are running a passive node."
I wondered if you were able to help me with some more info on that? is that a file I need? 

As for the node in the Terminal window, this is what is happening now. looks like it is running

Dec 31 16:05:40.708 WARN unable to reach peer for block download, reason: HTTP/2.0 connection error, peer_address: 3.125.31.84:3000, block: 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676, task: init
Dec 31 16:05:40.714 INFO fetching block 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676, peer_address: 52.9.77.197:3000, block: 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676, task: init
Dec 31 16:12:04.167 WARN failed to download block, error: GetBlocksStream { source: Error { code: Unknown, source: Status { code: Unknown, message: "h2 protocol error: broken pipe" } } }, peer_address: 52.9.77.197:3000, block: 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676, task: init
Dec 31 16:12:04.167 INFO fetching block 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676, peer_address: 18.182.115.51:3000, block: 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676, task: init
Dec 31 16:12:04.931 WARN failed to download block, error: GetBlocksStream { source: Error { code: Unknown, source: Status { code: Unknown, message: "h2 protocol error: broken pipe" } } }, peer_address: 18.182.115.51:3000, block: 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676, task: init
Dec 31 16:12:04.931 INFO fetching block 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676, peer_address: 3.125.183.71:3000, block: 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676, task: init
Dec 31 16:12:28.953 INFO genesis block fetched, peer_address: 3.125.183.71:3000, block: 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676, task: init
Dec 31 16:12:29.516 INFO connecting to bootstrap peer 54.183.149.167:3000, peer_addr: 54.183.149.167:3000, task: bootstrap
Dec 31 16:16:13.759 WARN initial bootstrap failed, error: PullStreamFailed { source: Error { code: Unknown, source: Status { code: Unknown, message: "h2 protocol error: broken pipe" } } }, peer_addr: 54.183.149.167:3000, task: bootstrap
Dec 31 16:16:13.878 INFO connecting to bootstrap peer 3.115.154.161:3000, peer_addr: 3.115.154.161:3000, task: bootstrap

**Comment by zmeel** [comment]
You can best follow the official [how to](https://github.com/input-output-hk/shelley-testnet/blob/master/docs/stake_pool_operator_how_to.md) written by IOHK to setup a stake node. I follow this one too.

**Comment by hdiuk** [comment]
> You can best follow the official [how to](https://github.com/input-output-hk/shelley-testnet/blob/master/docs/stake_pool_operator_how_to.md) written by IOHK to setup a stake node. I follow this one too.

is there the same guide for windows? 
I finally got the node running on windows but in the guide you link to, 
After 3.1 Create an account address using the script
the command lines shown are not being recognized by PowerShell

**Comment by hdiuk** [comment]
no actually, I got it,. Using "Git Bash" instead of power shell

**Comment by rinor** [comment]
@hdiuk can we close this one or you still need more info? If so please let us know or feel free to close this issue. Thank you.

**Comment by hdiuk** [comment]
Yes please close

Download the new Brave Browser and speed up your web browsing by blocking
ads and trackers. https://brave.com/jim398
