### ISSUE TITLE
Node crash

### ISSUE THREAD

**Issue by Bmtxs** [input-output-hk/jormungandr#1434]
**Describe the bug**
The jormungandr node crashes every time, reporting ''Segmentation fault (core dumped)''

**Mandatory Information**
1. `jcli --v0.8.5-alpha1
2. `jormungandr --v0.8.5-alpha1

**To Reproduce**
1. Start jormungandr with pool settings
2. Let it sync
3.See error

**Expected behavior**
I expect jormungandr to run without error

**Comment by CodeSandwich** [comment]
Could you paste the logs from before the crash?

**Comment by Bmtxs** [comment]
can you give me some instructions on how to use the backtrace and copy the logs, please?

**Comment by CodeSandwich** [comment]
When there's a segmentation fault, there is no backtrace. By default the logs are printed directly to the terminal, so they can be just copied from there.

**Comment by Bmtxs** [comment]
i m afraid i cant reproduce the crash anymore, i will close the issue
