### ISSUE TITLE
thread 'block1' panicked at 'internal error: entered unreachable code' - v0.8.5

### ISSUE THREAD

**Issue by hemants1** [input-output-hk/jormungandr#1438]
**Describe the bug**

The error does not crash the node and it continues to run. It stops getting new block updates and eventually lags behind.

**Mandatory Information**
1. `jcli --full-version` output;

jcli 0.8.5 (HEAD-3db0680, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

2. `jormungandr --full-version` output;

jormungandr 0.8.5 (HEAD-3db0680, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**To Reproduce**
1. Start Node as leader:

jormungandr --genesis-block-hash 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676 --config config.yaml --secret ./accounts/pool/node_secret.yaml

**Expected behavior**

Excepted to see it node running without any issues, synch and stable but after 4hrs of continues running started throwing panic errors causing node to lag behind block updates. Had to restart the node to re-synch blockchain..!   

**Additional context**

Dec 24 01:33:15.885 CRIT Task panicked, reason: internal error: entered unreachable code, task: block
Dec 24 01:33:15.885 WARN response canceled by the processing task, request: UploadBlocks, sub_task: server, task: network
thread 'block0' panicked at 'internal error: entered unreachable code', jormungandr/src/blockchain/storage.rs:92:49
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::begin_panic
  12: jormungandr::blockchain::storage::Storage::put_block
  13: <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll
  14: <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll
  15: <futures::stream::fold::Fold<S,F,Fut,T> as futures::future::Future>::poll
  16: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  17: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  18: <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll
  19: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  20: futures::task_impl::std::set
  21: tokio_threadpool::worker::Worker::run_task
  22: tokio_threadpool::worker::Worker::run
  23: tokio_reactor::with_default
  24: tokio::runtime::threadpool::builder::Builder::build::{{closure}}

**Comment by eugene-babichenko** [comment]
Similar panic reported in #1422

**Comment by rinor** [comment]
@hemants1 this should be fixed now since https://github.com/input-output-hk/jormungandr/pull/1441 was merged. Feel free to reopen if the issue still present after applying the mentioned patch.
