### ISSUE TITLE
Dec 25 00:51:54.086 WARN blockchain is not moving up, the last block was 4963 seconds ago, task: stuck_notifier

### ISSUE THREAD

**Issue by BitcoinMicroPaymentNetwork** [input-output-hk/jormungandr#1443]
**Describe the bug**
Dec 25 00:51:54.086 WARN blockchain is not moving up, the last block was 4963 seconds ago, task: stuck_notifier

**Mandatory Information**
1) jcli 0.8.5-alpha1 (HEAD-5d28516, release, macos [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
2) `jormungandr jormungandr 0.8.5-alpha1 (HEAD-5d28516, release, macos [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**Comment by eugene-babichenko** [comment]
Have you tried the latest `0.8.5`?

**Comment by BitcoinMicroPaymentNetwork** [comment]
Yes it was happening in 0.8.5 on my mac . I also ran the node on Azure and there also it happened . 
No one is reporting this bug because they restart node before this warning happens. If the block height is stuck for more than 15 minutes then only  this error comes . Generally stake pool owner restart Jormungandr before it. 

Also giving more info here . 
I always see the below warning before Stuck Notifier comes . 
"Dec 29 23:03:59.239 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network" . 
It looks this warning is due  to node is not able to to process the latest block . And I thing it happens because  the node has missed a block which is a link between the current height and received latest block . And because of this node not able to process any block and we keep getting this warning . 
After 15 to 20 minute we get main warning as "Blockchain is not moving up , Stuck notifier" . 

This looks like a block propagation problem to the nodes . A network problem  .  As of now every stake pool restarts their node after only waiting for 3 minutes the moment they see that block height is not moving up . So they do not see all this warnings.

**Comment by redbaron-gt** [comment]
Exactly same problem with latest 0.8.5.

**Comment by rinor** [comment]
@BitcoinMicroPaymentNetwork closing this one in favor of https://github.com/input-output-hk/jormungandr/issues/1470 since it has more information and is similar to your other issue https://github.com/input-output-hk/jormungandr/issues/1454. Thank you for the report.
