### ISSUE TITLE
Leader log should have a flag if block was invalidated

### ISSUE THREAD

**Issue by stanfieldr** [input-output-hk/jormungandr#1446]
**Is your feature request related to a problem/context ? Please describe if applicable.**
When you query leader logs from the rest api, it shows blocks which the node made, but did not make it on the main chain.

**Describe the solution you'd like**
That's fine because it's good for figuring out which blocks you missed; however, there should be some kind of flag indicating which ones are not present so that the times of those blocks can be used for debugging purposes.

**Comment by rinor** [comment]
@stanfieldr closing this one in favor of https://github.com/input-output-hk/jormungandr/issues/1472 since it is better tracked and monitored. Check also this comment https://github.com/input-output-hk/jormungandr/issues/1472#issuecomment-571108572
