### ISSUE TITLE
Unable to start gRPC listener on configured port

### ISSUE THREAD

**Issue by gabrielruiu** [input-output-hk/jormungandr#1448]
**Describe the bug**
Jormungandr service crashes when trying to start gRPC listener on the port configured in the node configuration.

**Mandatory Information**
1. `jcli --full-version` output;
`jcli 0.8.5 (HEAD-3db0680, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]`
2. `jormungandr --full-version` output;
`jormungandr 0.8.5 (HEAD-3db0680, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]`

**To Reproduce**
Configure node with a public-facing ip address in the `p2p.public_address`  field of the node configuration then start the jormungandr service.

**Expected behavior**
Node is successfully able to start the gRPC listener on the specified port.

**Additional context**
I have tried to determine if there is any other process running on port `8299` (the one on which I wish to mount the gRPC lsitener), but cant find any. I also tried mounting on port `3000`, which lead to the same error

The following is the log output just before the crash:
```
Dec 25 13:46:09.893 INFO initial bootstrap completed, peer_addr: 52.8.15.52:3000, task: bootstrap
Dec 25 13:46:09.911 INFO start listening and accepting gRPC connections on my-ip:8299, task: network
Dec 25 13:46:09.911 ERRO failed to listen for P2P connections at my-ip:8299, reason: failed to listen for connections on 87.106.195.147:8299, task: network
Dec 25 13:46:09.912 INFO connecting to peer, node_id: 671a9e7a5c739532668511bea823f0f5c5557c99b813456c, peer_addr: 52.9.132.248:3000, task: network
Dec 25 13:46:09.913 INFO connecting to peer, node_id: 52762c49a84699d43c96fdfe6de18079fb2512077d6aa5bc, peer_addr: 13.112.181.42:3000, task: network
Dec 25 13:46:09.914 INFO connecting to peer, node_id: 7e1020c2e2107a849a8353876d047085f475c9bc646e42e9, peer_addr: 13.114.196.228:3000, task: network
Dec 25 13:46:09.914 INFO connecting to peer, node_id: 99cb10f53185fbef110472d45a36082905ee12df8a049b74, peer_addr: 3.124.116.145:3000, task: network
Dec 25 13:46:09.915 INFO connecting to peer, node_id: 18bf81a75e5b15a49b843a66f61602e14d4261fb5595b5f5, peer_addr: 52.8.15.52:3000, task: network
Dec 25 13:46:09.916 INFO connecting to peer, node_id: 23b3ca09c644fe8098f64c24d75d9f79c8e058642e63a28c, peer_addr: 52.28.91.178:3000, task: network
Dec 25 13:46:09.918 INFO connecting to peer, node_id: 22fb117f9f72f38b21bca5c0f069766c0d4327925d967791, peer_addr: 3.125.75.156:3000, task: network
Dec 25 13:46:09.919 DEBG scheduling events, nb_slots: 9823, slot_start: 33377, current_slot: 33376, current_epoch: 11, epoch_tip: 11, task: leadership
Dec 25 13:46:09.921 INFO service finished with error, task: network
Dec 25 13:46:09.922 CRIT Service has terminated with an error
Dec 25 13:46:12.597 DEBG no item scheduled, waiting for next epoch, task: leadership
A service has terminated with an error
```

The log level is set to `debug`, but helpful information is printed as to why the error occurred. This could also help in determining the cause.

**Comment by rinor** [comment]
@gabrielruiu did you sort this out, or still an issue for you?

Based on your logs if looks like:
- `p2p.listen_address` is not set (should be set to an ip configured on your machines network card/interface, if different from `p2p.public_address` - ex: nated machines )
- the ip address configured in `p2p.public_address` is not configured/available in your machine/node.

Feel free to ask for more info, or close this issue if you already figured it out. Thank you.

**Comment by rinor** [comment]
@gabrielruiu closing this one, but feel free to comment if further information is needed. Thank you for the report.
