### ISSUE TITLE
CRIT Task panicked, task: leadership

### ISSUE THREAD

**Issue by zilevai** [input-output-hk/jormungandr#1451]
I am running:

1. jcli 0.5.5 (master-aec29a1c, release, macos [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
2. jormungandr 0.5.5 (master-aec29a1c, release, macos [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

Error message I get:

   0:        0x10750e372 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h415ddd0ba88caaaf
   1:        0x106e6dcc0 - core::fmt::write::h3335552e2df81c1d
   2:        0x10750daab - std::io::Write::write_fmt::he6837371b9a45188
   3:        0x10750d703 - std::panicking::default_hook::{{closure}}::h708e66cfeb0483ba
   4:        0x10750cc51 - std::panicking::rust_panic_with_hook::h9db77b22c2255a16
   5:        0x1075117dd - std::panicking::continue_panic_fmt::h2dfa3a5b90265361
   6:        0x10751c879 - rust_begin_unwind
   7:        0x106e6809c - core::panicking::panic_fmt::hec1ee47b7e17dca5
   8:        0x106e6e349 - core::result::unwrap_failed::hc206b0330c60884a
   9:        0x10751cf0c - std::thread::local::fast::Key<T>::try_initialize::ha19312ed91c78d2b
  10:        0x106dcacb1 - chain_impl_mockchain::stake::distribution::get_distribution::h12e29694a6c8c2aa
  11:        0x106dbe3ea - chain_impl_mockchain::leadership::genesis::LeadershipData::new::h50f8ac67da578c21
  12:        0x106dc90a9 - chain_impl_mockchain::leadership::Leadership::new::h6b2f073cf6561586
  13:        0x106faec71 - jormungandr::blockchain::chain::new_epoch_leadership_from::h0046834ca48edd22
  14:        0x1071fd863 - jormungandr::leadership::process::Module::step::h4fa6f355a44a643e
  15:        0x10723ae2a - <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll::he389f992c5bd09fc
  16:        0x106f85280 - <futures::future::then::Then<A,B,F> as futures::future::Future>::poll::h88ec067a7a2c4594
  17:        0x10755fab6 - futures::task_impl::std::set::h4b0351d1df26e02d
  18:        0x10755bbed - tokio_threadpool::worker::Worker::run_task::h14b0d8ba9f164e74
  19:        0x107559e2f - tokio_threadpool::worker::Worker::run::hfadfbe3618f81765
  20:        0x10753f970 - tokio_reactor::with_default::heb87b681521ad3b7
  21:        0x107539f90 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::hb00790a5ee320569
  22:        0x107558101 - std::sys_common::backtrace::__rust_begin_short_backtrace::h51f6244d1b9cb701
  23:        0x107558c04 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h0045782284eb1afd
  24:        0x10751b2de - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h49b3841a036d0711
  25:        0x10751d84a - std::sys::unix::thread::Thread::new::thread_start::hd9de55a9c1593989
  26:     0x7fff7890e2eb - _pthread_body
  27:     0x7fff78911249 - _pthread_start
Dec 25 20:13:37.672 INFO Shutting down node
Dec 25 20:13:37.684 **CRIT** Task panicked, task: leadership

**Comment by rinor** [comment]
@zilevai please update the node to the latest [version](https://github.com/input-output-hk/jormungandr/releases/) and check if still an issue. Thank you.

**Comment by rinor** [comment]
Closing this one since does not affect the latest version.
