### ISSUE TITLE
referential integrity failure in CandidateForest

### ISSUE THREAD

**Issue by BitcoinMicroPaymentNetwork** [input-output-hk/jormungandr#1460]
**Describe the bug**
thread 'block3' panicked at 'referential integrity failure in CandidateForest', src/libcore/option.rs:1185:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Dec 27 13:02:24.349 CRIT Task panicked, task: block

Dec 27 13:08:22.649 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Dec 27 13:14:57.094 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Dec 27 13:14:59.079 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Dec 27 13:18:59.294 ERRO cannot process network headers, reason: deadline has elapsed, task: block

**Mandatory Information**
Version - 0.8.5 

**To Reproduce**
Killed the node and restarted it and received this error

**Comment by eugene-babichenko** [comment]
Similar issue described in #1422, possibly a duplicate.

**Comment by rinor** [comment]
@BitcoinMicroPaymentNetwork this shouldn’t be an issue anymore in the latest version. Thank you for the report.
