### ISSUE TITLE
Ghost block 

### ISSUE THREAD

**Issue by Proxiweb** [input-output-hk/jormungandr#1464]
**Describe the bug**

- I produced the block 81560d6c34739a0c83381bafc42b5baf5b4e3233e90245be9afeb7033a093371
- This block is not visible on Cardano Shelley Explorer
- But **this block exists on the blockchain** : I asked few members on telegram, not on a wrong fork, nicely synced... they find the block !
- This block hasn't been credited to my pool ADAFR, so performance was lowered
- Rewards for this block hasn't been sent

**Mandatory Information**
1. jcli 0.8.4 (HEAD-2227eb27, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
2. jormungandr 0.8.4 (HEAD-2227eb27, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

**To Reproduce**
You can check block 81560d6c34739a0c83381bafc42b5baf5b4e3233e90245be9afeb7033a093371 existence 

**Expected behavior**
I expect for the bloc I produced to be registered on Cardano Shelley Explorer, performance in Daedalus not beeing lowered and rewards sent

**Comment by psychomb** [comment]
block get output on my side : 
02b60002000000000000000c00008c3f0000a5ba0e5751c026e543b2e8ab2eb06099daa1d1e5df47778f7787faab45cdf12fe3a87274047a17007a90b53be5409f7e5c799e63a8955f01f114d7231f9662815f3a684731018eab4e83784f1a5c580a5de9f5ef4f184986abc3ab61b72ff0e94e1af40689e094fa83a9aa9c900b6cda1f3df98ff431cfb5caeb4ec09fa6ba6a14004b68a5e4e584f6cc23079c1639143dee07156a03656990e665c9c3c572c3da05479976078e5f17d91bdd3c5365636577cdc54ff2b56e4b4df197448323947b0900000000261340d98d4ffce21b5fea8b3397f4a12b362aba6269e0135a59ba5f05df87fbc43d36e5f3b9d13561c733689241b456925a8efd3eb62fe1d66eecea2dbf430d832c18cbe83d7008bbc40cdb7c5bad1d0a2a9ff617b0d91dd345d44fce4c731b942b982900f6d5f34129b38af7ba7f3ee0fb033582b916393c57edebee10220e49d28260469b1dddc34ebe92660fb49155617c404505390cca95503fbdf1135f842ed06ab0305920e867138be705505d985f03e58c4962676c05faff0eba6125799aae9e07515f1b96013563a38e2894cf30d29f3a63dd3d1b81e8efbe48b32b1b02424de8f08065e8eaf54c2b226a0d54966ff1bb9a5d8264ec036232899e74ac66418cc685027803e8de20dad130a07e6fa812f322e156e46c309a0a6a33332708ffe70517db3205ff81f94afa104faa93b62114b6db26ee3bd0c50a3961e0b3a9b6ab3c8219d68b8308da98e5d38235a3819c48083b8ebb2603efbe28e06ba7218806de94e3c18b110dfc2ea534ee273532eba2b0f33026136a8cd2e27a6704c5e883924204edd092a6798adb62b9d24b28695cfc3f43e1928f0d4c1cfdfbee9f9e02478974edca50bccb421b85c7747e77d3fe1cbbb6862d360fd890ed71008f4bab7968e2af723f348c1891c70f5bcb6ea670193106fd43b1136855a237

**Comment by frugalpool** [comment]
I reported this in #1427, same problem and I'm still experiencing it with jormungandr 0.8.5 (HEAD-3db0680, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**Comment by Proxiweb** [comment]
Same thing today for block a8c3111d8a19ed5aed69ea36e80f1405963a49cc4a04e8f8555c1b0d0c87e37f

**Comment by adascanBovich** [comment]
Both blocks encountered double leadership events.
