### ISSUE TITLE
after running no problem for 2 days straight, it dumped out a stack trace

### ISSUE THREAD

**Issue by stanfieldr** [input-output-hk/jormungandr#1467]
**Describe the bug**
stack backtrace:
   0:     0x55c59e8be2b4 - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x55c59e8be2b4 - backtrace::backtrace::trace_unsynchronized::h1a8d6e1f8cb3f5d4
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x55c59e8be2b4 - std::sys_common::backtrace::_print_fmt::h610c4127487e10da
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x55c59e8be2b4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0722dc552e01bd1d
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x55c59e8e1fdc - core::fmt::write::h01edf6dd68a42c9c
                               at src/libcore/fmt/mod.rs:1030
   5:     0x55c59e8b8a27 - std::io::Write::write_fmt::hf15985f193f03c04
                               at src/libstd/io/mod.rs:1412
   6:     0x55c59e8c0805 - std::sys_common::backtrace::_print::hd8d5d08a1795e743
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x55c59e8c0805 - std::sys_common::backtrace::print::hf89a79e3921a2366
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55c59e8c0805 - std::panicking::default_hook::{{closure}}::h3a8f42beb3bb8ae3
                               at src/libstd/panicking.rs:196
   9:     0x55c59e8c04f6 - std::panicking::default_hook::h8f803b0bc31a5c37
                               at src/libstd/panicking.rs:210
  10:     0x55c59e8c0f05 - std::panicking::rust_panic_with_hook::h825f041245da8739
                               at src/libstd/panicking.rs:473
  11:     0x55c59e8c0aa2 - std::panicking::continue_panic_fmt::hbe0378e33481e81b
                               at src/libstd/panicking.rs:380
  12:     0x55c59e8c0996 - rust_begin_unwind
                               at src/libstd/panicking.rs:307
  13:     0x55c59e8ddb4a - core::panicking::panic_fmt::h527855ce0bc891f6
                               at src/libcore/panicking.rs:85
  14:     0x55c59e8ddbb7 - core::option::expect_failed::h616db3795314a1d2
                               at src/libcore/option.rs:1190
  15:     0x55c59e3398c3 - jormungandr::blockchain::candidate::CandidateForestThickets::poll_purge::he4f6a549291f2463
  16:     0x55c59e1cfc57 - futures::future::chain::Chain<A,B,C>::poll::h9b5209a77522b92d
  17:     0x55c59e2d55c6 - <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll::hc3115d87e81e9736
  18:     0x55c59e21f4ac - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h87b71060f81cccac
  19:     0x55c59e89ceb2 - futures::task_impl::std::set::h5e2dc91f62e5cf18
  20:     0x55c59e89cb12 - std::panicking::try::do_call::hd887f77b6241094b
  21:     0x55c59e8c53ea - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  22:     0x55c59e89aa19 - tokio_threadpool::task::Task::run::h0fcec9698b927c77
  23:     0x55c59e897136 - tokio_threadpool::worker::Worker::run_task::ha2cd309bd5962cfc
  24:     0x55c59e8967a5 - tokio_threadpool::worker::Worker::run::h919c78de67a5c047
  25:     0x55c59e872e9c - tokio_reactor::with_default::hab2985ad4b1cae47
  26:     0x55c59e87785f - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::hfddf80a0e4f4724b
  27:     0x55c59e89c42a - std::thread::local::LocalKey<T>::with::h3b622a9f0f767ab9
  28:     0x55c59e89c899 - std::thread::local::LocalKey<T>::with::h70048df880185e0c
  29:     0x55c59e893b98 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4ad5bfdae3a8fe6c
  30:     0x55c59e89ca6c - std::panicking::try::do_call::h7b34e975433e52b2
  31:     0x55c59e8c53ea - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  32:     0x55c59e894e30 - core::ops::function::FnOnce::call_once{{vtable.shim}}::he8411aa3c772e3fc
  33:     0x55c59e8b187f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h483711add4ba2330
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
  34:     0x55c59e8c4750 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7605b45eb29ed0be
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
  35:     0x55c59e8c4750 - std::sys_common::thread::start_thread::h557b0c2dc4449562
                               at src/libstd/sys_common/thread.rs:13
  36:     0x55c59e8c4750 - std::sys::unix::thread::Thread::new::thread_start::h7c2a7f9b68fe4bba
                               at src/libstd/sys/unix/thread.rs:79
  37:     0x7f279bfec6db - start_thread
  38:     0x7f279bafd88f - __clone
  39:                0x0 - <unknown>

**Mandatory Information**
1. jcli 0.8.5 (HEAD-3db06807, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
2. jormungandr 0.8.5 (HEAD-3db06807, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

**Comment by rinor** [comment]
@stanfieldr this may the same/related to https://github.com/input-output-hk/jormungandr/issues/1422 (p.2) and probably will be fixed once https://github.com/input-output-hk/jormungandr/pull/1461 is merged. Meanwhile if you have the full logs file (old file, or new one when/if it happens again), please attach it here if possible. Thank you.
