### ISSUE TITLE
Slot skipped and blocks were not created.

### ISSUE THREAD

**Issue by DAPP360-Mike** [input-output-hk/jormungandr#1469]
**Describe the bug**
This may not be a bug. I don't know yet. My node, D360, was scheduled to create 26 blocks in epoch 13.  It created 22 even though the node was syncing and never went down. So I kept an eye on Epoch 14 to see if it would happen again. It did. At the very beginning of Epoch 14, my leader log (jcli rest v0 leaders logs get --host "http://127.0.0.1:3100/api") showed that I was scheduled for blocks with "scheduled_at_date: 14.30168" and  "scheduled_at_date: 14.22188".  My node did not go down and it was syncing right through that time. I created a block right before and a block after these scheduled_at_dates. However, those two blocks (14.30168, 14.22188 ) were not created by my node or another node. When I checked Shelley Explorer, it seems like the slot 14.30168 was skipped or omitted.
![Bug Report](https://user-images.githubusercontent.com/49951327/71545162-c5759d80-2955-11ea-8e42-40f22ae0b612.jpg)
 

**Mandatory Information**
1. jcli 0.8.5 (HEAD-3db0680, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
2. jormungandr 0.8.5-3db0680

**To Reproduce**
1.  There was no error in my node log file which is set to capture level starting from "Warn" 

**Expected behavior**
I expected to have created the block in that slot as long as my node was up and syncing with the chain.

**Comment by adascanBovich** [comment]
Have the same issues. From my logs it seems that the reason for it is the pool that is creating block right after you (30172). It didn't get your freshly created block and took 30167 as a parent and created his block which was accepted by the network. 

What is more interesting is that in my logs I see messages that block was successfully applied and propagated to the network but after some time I am receiving new block with the same parent and my block just skipped from the network somehow.

**Comment by frugalpool** [comment]
probably same cause as #1427

**Comment by NicolasDP** [comment]
Sorry to hear you missed 2 slots. This issue relates to #1472 . There is a lack of feedback on the leaderlogs when a fork happen or if a block was submitted but not accepted by the blockchain.

while we may not be able to say for sure why the blockchain rejected a block, often it is because it was on a fork and that fork has been rejected. #1472 will be the issue to track down the progress on adding such feedback.

thanks again for your support.
