### ISSUE TITLE
jormungandr node v0.8.5 is syncing data very slowly

### ISSUE THREAD

**Issue by congle-ibl** [input-output-hk/jormungandr#1475]
Hi all,

Here is the status of my jormungandr node:
{
   "version":"jormungandr 0.8.5-3db06807",
   "state":"Running",
   "blockRecvCnt":3518,
   "lastBlockContentSize":249,
   "lastBlockDate":"16.27498",
   "lastBlockFees":400000,
   "lastBlockHash":"b42689b8ac0486e9071dbdd056fccb29cfc35024d9212a83e68a37b07a4b101d",
   "lastBlockHeight":"54797",
   "lastBlockSum":955616039,
   "lastBlockTime":"2019-12-30T10:30:13+00:00",
   "lastBlockTx":1,
   "lastReceivedBlockTime":"2019-12-31T07:43:44+00:00",
   "txRecvCnt":2883,
   "uptime":83964
}

I see that blockRecvCnt is increasing very slowly and never catches up with lastBlockHeight. So, does it sync completely or not and how to make it faster? Thank you so much

**Comment by rdlrt** [comment]
blockRecvCnt is number of blocks you receive since you started your node. It is suppose to increase once there are new block created/announced and received.
It would be easier for you to use the [stakepool workgroup](https://t.me/CardanoStakePoolWorkgroup) on telegram or IOHK [support](https://iohk.zendesk.com/hc/en-us/requests/new) for usage queries.

**Comment by congle-ibl** [comment]
Hi @rdlrt ,

I asked this question on stake pool group on telegram but no one answered me. Thank you so much for your support. And could you please help to answer one more question about this? My question is how to check that my node was synced completely. It's based on lastBlockDate or lastBlockHash compare to latest block on shelley explorer, isn't it? Thank you in advance.

**Comment by NicolasDP** [comment]
Hi,

No it is better to compare you `lastBlockTime` and your `lastReceivedBlockTime`:

* `lastBlockTime`: is the one associated to the block it is the date and time the block should have been created (+ the slot time duration).
* `lastReceivedBlockTime`: is the date and time you received a block from the network for the last time

in your case it seems there have been nearly a day between the 2 values. So it looks like you went out of sync. There are still issues that needs to be addressed on the network and we are looking into improving this.

thanks for your support
