### ISSUE TITLE
Jormungandr - logs - poldercast / policy log task / sub_task

### ISSUE THREAD

**Issue by wxsq2004** [input-output-hk/jormungandr#1499]
**Describe the bug**
When logging 'move node to quarantine' message, 'task' key is used twice. 

**Mandatory Information**
jcli 0.8.5 (HEAD-3db0680, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
jormungandr 0.8.5 (HEAD-3db0680, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**To Reproduce**
1. Start a node with debug log level a plain output.
2. At some point the following is logged: 
Jan 04 01:01:06.999 DEBG move node to quarantine, id: 02a29f423fa669a7ada6effc58c0cb383b3395a38cffe429, task: policy, task: poldercast
3. Key 'task' is used twice
4 Restart the node with json output.
5. 'policy' value is missing

**Expected behavior**
One of the value policy or poldercast should have another key

**Comment by eugene-babichenko** [comment]
Related https://github.com/slog-rs/slog/issues/211
