### ISSUE TITLE
task: client-query thread 'block1' panicked at 'internal error: entered unreachable code

### ISSUE THREAD

**Issue by BitcoinMicroPaymentNetwork** [input-output-hk/jormungandr#1502]
**Describe the bug**

Jan 04 12:51:40.014 WARN request timed out or failed unexpectedly, error: Error(Elapsed), request: GetHeadersRange, task: client-query
thread 'block1' panicked at 'internal error: entered unreachable code', jormungandr/src/blockchain/storage.rs:92:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Jan 04 12:51:40.159 CRIT Task panicked, reason: internal error: entered unreachable code, task: block
Jan 04 12:51:40.159 WARN response canceled by the processing task, request: UploadBlocks, sub_task: server, task: network
Jan 04 12:54:51.602 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Jan 04 12:56:22.905 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Jan 04 12:56:33.145 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Jan 04 12:56:40.054 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Jan 04 13:00:33.913 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Jan 04 13:00:58.056 ERRO cannot process network blocks, reason: deadline has elapsed, task: block
Jan 04 13:01:26.108 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Jan 04 13:04:42.054 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network

**Mandatory Information**
Version 0.8.5

**Comment by rinor** [comment]
Same as https://github.com/input-output-hk/jormungandr/issues/1422 (p.3). Will be fixed once pr https://github.com/input-output-hk/jormungandr/pull/1441 is merged. Thank you for the report.

**Comment by rinor** [comment]
Closing this one in favor of https://github.com/input-output-hk/jormungandr/issues/1422

**Comment by rinor** [comment]
@BitcoinMicroPaymentNetwork just fyi https://github.com/input-output-hk/jormungandr/pull/1441 was just merged so this issue is now fixed in master.
