### ISSUE TITLE
reporting higher block height than pool tool.io

### ISSUE THREAD

**Issue by kenricnelson** [input-output-hk/jormungandr#1504]
**Describe the bug**
Just upgraded to the v0.8.5-3db0680 version.  Running smoothly, but the reported block height by jcli node status is significantly higher than reported by pooltool.io and adapools.org; which seems unusual.  Looking for guidance as to why this might be.

**Mandatory Information**
1. jcli 0.8.5 (HEAD-3db0680, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
2. jormungandr 0.8.5 (HEAD-3db0680, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**To Reproduce**
This is my nightly_config.yaml file

{
  "log": [
    {
      "format": "plain",
      "level": "info",
      "output": "stderr"
    }
  ],
  "p2p": {
    "listen_address": "/ip4/0.0.0.0/tcp/3100",
    "public_address": "/ip4/x.x.x.x/tcp/3100",
    "topics_of_interest": {
      "blocks": "high",
      "messages": "high"
    },
    "trusted_peers": [
      {
        "address": "/ip4/13.230.137.72/tcp/3000",
        "id": "fe3332044877b2034c8632a08f08ee47f3fbea6c64165b3b"
      }

                   …. Etc …

    ]
  },
  "rest": {
    "listen": "127.0.0.1:3101"
  },
  "storage": "/data/storage"
}

This is my jormungandr command:
./jormungandr --config nightly-config.yaml --genesis-block-hash 9409af111b04896c756c1cee3b7f9bae8b9ed1843c9e0a5f07d92ab9b62f6f78 --secret ./node_secret.yaml > /data/logs/jorm_log_jan04_1543.txt

At 17:28 UTC on Jan 4th pooltool.io is reporting a height of 70822 while my node is reporting 88052.

**Expected behavior**
Expected the block height to closely match those reported by public analytical websites such as pooltool.io or adapools.org.  

**Additional context**
Instead my block height is significantly higher, suggesting I'm connected to a different chain.  How did this happen?

**Comment by kenricnelson** [comment]
Jormungandr is reporting messages such as:

Jan 04 18:10:27.252 INFO receiving block stream from network, task: block
Jan 04 18:10:27.255 INFO switching to new candidate branch, task: block
Jan 04 18:10:27.316 INFO received block announcement, hash: f2f8bd1a8fcfa3d9c70003afb99ffc23d357ee0088bbb7d194d0e202bea4ec4c, direction: in, stream: block_events, node_id: fbb5898180341af9cc365191d33eb0bfdca405d419f68911, sub_task: server, task: network
Jan 04 18:10:27.317 INFO received block announcement from network, from_node_id: fbb5898180341af9cc365191d33eb0bfdca405d419f68911, date: 133.1247, parent: c3443eaa58194760b83d1b36d086e43cc5876d0d5d651e5852d98d2b1d79c798, hash: f2f8bd1a8fcfa3d9c70003afb99ffc23d357ee0088bbb7d194d0e202bea4ec4c, task: block

**Comment by kenricnelson** [comment]
Resolved issue by using the itn_rewards_v1-{config,genesis}.yaml files and its genesis-hash.

Recommend that the [Jörmungandr Configurations ](https://hydra.iohk.io/build/1523436/download/1/index.html) webpage be updated to reflect that each of these configurations is for a separate blockchain.  While there may be a particular build that that blockchain is being used for its not necessarily tied to a particular build. In particular, since stake-pool operators have been advised to upgrade to v0.8.5, it's confusing that the itn_rewards_v1 configuration has v0.8.3 next to it.

**Comment by rinor** [comment]
@kenricnelson so just to clarify, you were connected to another network not on `itn` and in the same time you were checking  pooltool.io and adapools.org which are on `itn`, hence the block height differences.

**Comment by rinor** [comment]
@kenricnelson itn_rewards_v1 configuration has v0.8.3 next to it since it was started with that version and all other versions afterwards are compatible with that one.
Regarding update to reflect that each of these configurations is for a separate blockchain, it was supposed to be evident since each cluster has a different Genesis Hash.
Nevertheless will still check if feasible to make things a bit more clear.
Thanking you for reporting it, will close this for now, but feel free to comment if further information is needed.

**Comment by kenricnelson** [comment]
Rinor,

Thanks for the response and clarification.

Kenric
