### ISSUE TITLE
Prevent pools from running multiple active instances

### ISSUE THREAD

**Issue by tstdin** [input-output-hk/jormungandr#1505]
**Is your feature request related to a problem/context ? Please describe if applicable.**
After recent update, [PoolTool website](https://pooltool.io/health) added support for showing forks and also detecting if one stake pool creates multiple blocks at specific slot. And short observation proved some pools are really using this technique of multiple nodes, probably to insure making the block and getting rewards.

- example 1
  ![image](https://user-images.githubusercontent.com/25065143/71779693-a9f33e00-2fb8-11ea-85be-b369c8cb5199.png)
- example 2
  ![image](https://user-images.githubusercontent.com/25065143/71779707-e161ea80-2fb8-11ea-81a3-7e22eda694e3.png)

**Describe the solution you'd like**
Prevent pools from running multiple active instances. Maybe add mechanism that after Jormungandr detects for one slot multiple blocks from same pool id, add it into quarantine and reject all those blocks.

**Additional context**
n/a

**Comment by cardanians** [comment]
+1

[LION4] Lion's Stakehouse 4%   652ac1d9293c2d3f8ffbf40835e26cbf547f057fa8d325562069989c60fa895b

![obrazek](https://user-images.githubusercontent.com/58650764/71780381-51c13980-2fc2-11ea-814a-5f7e8854a155.png)

**Comment by rinor** [comment]
same as / related to https://github.com/input-output-hk/jormungandr/issues/1503
