### ISSUE TITLE
bootstrap - connection timeouts seem too long

### ISSUE THREAD

**Issue by wxsq2004** [input-output-hk/jormungandr#1511]
**Is your feature request related to a problem/context ? Please describe if applicable.**
Connnection timeouts during 'boostrap' state seem too long, for example:

1/ When trying to connect to a bootstrap peer (~ 2 minutes)

2020-01-06 23:19:42| INFO |bootstrap |connecting to bootstrap peer 13.56.0.226:3000
	peer_addr: 13.56.0.226:3000
2020-01-06 23:21:52| WARN |bootstrap |unable to reach peer for initial bootstrap
	peer_addr: 13.56.0.226:3000
	reason: HTTP/2.0 connection error

2/ When trying to pull blocks (~ 4 minutes)

2020-01-07 00:26:01| DEBG |bootstrap |validated block
	peer_addr: 18.182.115.51:3000
	block_date: 3.15292
	hash: 911b7a5def57e25305299f0d99174468baeb75506a8716af1c5a4eb815342be6
2020-01-07 00:30:02| WARN |bootstrap |initial bootstrap failed
	peer_addr: 18.182.115.51:3000
	error: PullStreamFailed { source: Error { code: Unknown, source: Status { code: Unknown, message: "h2 protocol error: broken pipe" } } }

**Describe the solution you'd like**
Shorter timeouts should do.

**Comment by hodlonaut** [comment]
Seems to be the same issue as https://github.com/input-output-hk/jormungandr/issues/991 that I raised couple of months back :(

**Comment by michaeljfazio** [comment]
I’ve looked into fixing this one. It seemed to me that the best approach was to upgrade the hyper crate to the next major version which supports setting connection timeouts. However there are quite a number of breaking changes that this introduces. Best left to someone more confident with the code base than I.

**Comment by mzabaluev** [comment]
Same issue as #991, will be fixed in #1836
