### ISSUE TITLE
MultiAddress invalid public_address 

### ISSUE THREAD

**Issue by stanfieldr** [input-output-hk/jormungandr#1519]
In the [docs](https://input-output-hk.github.io/jormungandr/configuration/network.html#p2p-configuration) it says public_address uses the multiaddress format. On the [multiaddr](https://github.com/multiformats/multiaddr) readme it has a way to specify UDP. The docs should point out that it only works with TCP. Also is there any plans to support UDP, it seems like it would work a lot better for jormungandr's use case

**Comment by rinor** [comment]
@stanfieldr thank you for the report regarding
> The docs should point out that it only works with TCP
it will be updated to make it clearer.

Now regarding UDP support I don't think there are any short-term plans in supporting it. Also the underlaying technology used [grpc](https://grpc.io/) does not support it (iirc) and don't think UDP is suitable at this stage. 

---

That said, unrelated to jormungandr and this issue, there are some attempts like [QUIC](https://en.wikipedia.org/wiki/QUIC). There is also an interesting [article](https://gafferongames.com/post/deterministic_lockstep/) that you can check.

Thank you.

**Comment by NicolasDP** [comment]
Thanks, indeed **The docs should point out that it only works with TCP**. This is a rather simple task to do. If someone wants to pick it up please let us know in the comment of this issue.

**Comment by NicolasDP** [comment]
Fixed in #1598
