### ISSUE TITLE
Error processing incoming header stream -Mac OS Mojave

### ISSUE THREAD

**Issue by lsc3** [input-output-hk/jormungandr#1535]
**Describe the bug**
incoming connection on 192.168.0.149:3000, peer_addr: 5.189.162.14:65326, task: network
Jan 10 17:29:43.594 INFO incoming connection on 192.168.0.149:3000, peer_addr: 80.56.242.38:52728, task: network
Jan 10 17:29:43.595 INFO incoming connection on 192.168.0.149:3000, peer_addr: 73.76.151.210:61404, task: network
Jan 10 17:29:43.596 ERRO Error while accepting connection on 0.0.0.0:3000: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, task: network
Jan 10 17:29:43.597 INFO failed to connect to peer, reason: Operation timed out (os error 60), node_id: da93da2556ceda0bf24ecaec0c611ff8d8349121cadf8f20, peer_addr: 95.217.1.90:3000, task: network
Jan 10 17:29:43.600 INFO failed to connect to peer, reason: Operation timed out (os error 60), node_id: a6fc9f2266ab6bd14388e5c8ba3a840f005ae79a10724951, peer_addr: 23.102.70.21:3000, task: network
Jan 10 17:29:43.601 INFO failed to connect to peer, reason: Operation timed out (os error 60), node_id: 09ddb88980d142475725422c1ff3d1176cd9439c5b98ada3, peer_addr: 138.68.109.144:3000, task: network
Jan 10 17:29:43.603 INFO failed to connect to peer, reason: Operation timed out (os error 60), node_id: 7665a3d736f36ecebaa4545c4ece996e1017bc2e67fea359, peer_addr: 172.105.64.209:37281, task: network
Jan 10 17:29:43.605 INFO failed to connect to peer, reason: Operation timed out (os error 60), node_id: 101631ff14b4ea5809af135c0782bf7e0a01a273db5f418e, peer_addr: 129.146.223.102:31400, task: network
Jan 10 17:29:43.612 INFO failed to connect to peer, reason: Operation timed out (os error 60), node_id: a38d2f24b40eb470943f2c6e2d787485f16848eb5bc61669, peer_addr: 185.253.217.143:4333, task: network
Jan 10 17:29:43.615 INFO failed to connect to peer, reason: Operation timed out (os error 60), node_id: 820e1a54a0667af42948321b08b3be02bc3deb15ca18c90e, peer_addr: 35.235.50.167:3100, task: network
Jan 10 17:29:43.617 INFO failed to connect to peer, reason: Operation timed out (os error 60), node_id: a13b49bf7ec77af4fadbe9e8431f648194e56b53f0104acb, peer_addr: 86.90.6.114:3888, task: network
Jan 10 17:29:43.619 INFO failed to connect to peer, reason: Operation timed out (os error 60), node_id: e719119912b16a2232472b007e8e545088250e129b7c2f9c, peer_addr: 34.90.9.22:3300, task: network
Jan 10 17:29:43.621 INFO failed to connect to peer, reason: Operation timed out (os error 60), node_id: 5c69e1dd992f5e45f4db71124783f081b9130dfa46cc3613, peer_addr: 34.89.205.216:3101, task: network
Jan 10 17:29:43.623 INFO failed to connect to peer, reason: Operation timed out (os error 60), node_id: 7f3b382b32eb8ee7617657d3ba88f494ccc8af24b16bc5a6, peer_addr: 157.230.114.148:3003, task: network
Jan 10 17:29:43.624 INFO failed to connect to peer, reason: Operation timed out (os error 60), node_id: ae2cc128abe89571519b7cacce4db838d56ee573f1235c99, peer_addr: 138.68.109.144:3000, task: network
Jan 10 17:29:43.626 INFO failed to connect to peer, reason: Operation timed out (os error 60), node_id: 748bfe6916482fe29aab730f2c483d4f8cd71f70ca46bc00, peer_addr: 91.178.130.16:3000, task: network
Jan 10 17:29:43.630 INFO failed to connect to peer, reason: Operation timed out (os error 60), node_id: 97e9f976df1f74f895ebd97a01390d4b52f34138e7519ba4, peer_addr: 37.0.94.41:8000, task: network
Jan 10 17:29:43.636 INFO failed to connect to peer, reason: Operation timed out (os error 60), node_id: f436425a9fbb93cfcf4a334f714c3993fe84aea17b041ac1, peer_addr: 62.202.33.120:1337, task: network
Jan 10 17:29:43.665 INFO error processing an incoming header stream, reason: the incoming header stream is empty, task: block
Jan 10 17:29:43.715 INFO error processing an incoming header stream, reason: the incoming header stream is empty, task: block
Jan 10 17:29:43.716 INFO update current branch tip, task: block
Jan 10 17:29:43.719 INFO error processing an incoming header stream, reason: the incoming header stream is empty, task: block
Jan 10 17:29:43.723 INFO error processing an incoming header stream, reason: the incoming header stream is empty, task: block
Jan 10 17:29:43.723 INFO error processing an incoming header stream, reason: the incoming header stream is empty, task: block
Jan 10 17:29:43.724 INFO error processing an incoming header stream, reason: the incoming header stream is empty, task: block
Jan 10 17:29:43.724 INFO error processing an incoming header stream, reason: the incoming header stream is empty, task: block
Jan 10 17:29:43.725 INFO error processing an incoming header stream, reason: the incoming header stream is empty, task: block
Jan 10 17:29:43.738 INFO error processing an incoming header stream, reason: the incoming header stream is empty, task: block
Jan 10 17:29:43.766 WARN response canceled by the processing task, request: UploadBlocks, sub_task: server, task: network
Jan 10 17:29:43.767 WARN response canceled by the processing task, request: UploadBlocks, sub_task: server, task: network
Jan 10 17:29:43.839 WARN response canceled by the processing task, request: UploadBlocks, sub_task: server, task: network
Jan 10 17:29:43.850 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Jan 10 17:29:43.888 INFO connection to peer failed, reason: protocol handshake failed: unknown error, node_id: 93cf877a87bf61fdbf6548583ba608fd89183e83e2c8ea57, peer_addr: 45.153.186.57:3333, task: network
Jan 10 17:29:43.889 INFO service finished with error, task: network
Jan 10 17:29:43.889 CRIT Service has terminated with an error
A service has terminated with an error

**Mandatory Information**
jcli 0.8.5 (HEAD-3db06807, release, macos [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
jormungandr 0.8.5 (HEAD-3db06807, release, macos [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**To Reproduce**
Run the node with stake pool settings. This error occurs frequently with my setup though does not always end in termination of the application.
**Expected behavior**
Expecting jormungandr not to crash.

**Additional context**
Built jormumgandr from source.

**Comment by rinor** [comment]
@lsc3 the real issue here that causes your node to crash is:
```
Jan 10 17:29:43.596 ERRO Error while accepting connection on 0.0.0.0:3000: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, task: network
``` 
that causes
```
Jan 10 17:29:43.889 INFO service finished with error, task: network
Jan 10 17:29:43.889 CRIT Service has terminated with an error
A service has terminated with an error
```
and it is fixed in master and will be available the next release check https://github.com/input-output-hk/jormungandr/issues/1367#issuecomment-574132659.

**Comment by lsc3** [comment]
Thank you. Will close the issue.
