### ISSUE TITLE
Add a limit of entries in listenin port

### ISSUE THREAD

**Issue by Exteroqs** [input-output-hk/jormungandr#1536]
I have noticed that the "max_ connections" configuration: only limits the number of nodes that I can connect from my server, but does not limit the amount of connections that I can maintain from my listening port. 
I noticed that my server freezes (which happens every 30 min approx) when these connections on the listening port exceed 900 connections and I start receiving many syn_recv packages even having my "max_connection" set to 250, I don't know if it is an attack or it is because my PC does not process so many connections or it is a problem of my bandwidth, anyway it would be interesting to add an option that can establish a limit of connections in my listening port.

**Comment by fogstudy** [comment]
sympathy

**Comment by NicolasDP** [comment]
There is an issue (#1581 document well the underlying issue) and we are still looking into it. I will close this issue but it does not mean it is fixed. Just that the other issue provide more insight as to what is the core problem and is easier to follow for the dev team.
