### ISSUE TITLE
CRIT task panicked

### ISSUE THREAD

**Issue by kunoada** [input-output-hk/jormungandr#1542]
**Describe the bug**
So far I have not been able to run my stakepool for more than an hour, due to getting stuck, with the last log message being; CRIT task panicked. This happens for task: network and block.

![stuck_notifier](https://user-images.githubusercontent.com/59795614/72246335-c283d980-35f2-11ea-990f-73d482c83f19.PNG)

**Mandatory Information**
1. `jcli --full-version` output;
jcli 0.8.5 (HEAD-3db0680, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

2. `jormungandr --full-version` output;
jcli 0.8.5 (HEAD-3db0680, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**To Reproduce**
This has happened since the beginning. With everything as default.
I have tried changing the configurations, etc. without any changes in the outcome.

**Expected behavior**
What I have noticed, is that the cpu usage starts being 100% for longer and longer periods.. At some point when the cpu is at 100% for 20-30 sec, it usually panick!

**Comment by tstdin** [comment]
This seems to be related to #1521 and #1459.

**Comment by kunoada** [comment]
> This seems to be related to #1521 and #1459.

Could be same issue! I will close this one then.
