### ISSUE TITLE
Consider Rebranding "jormungandr" to "cardano-node-rust"

### ISSUE THREAD

**Issue by lazaridiscom** [input-output-hk/jormungandr#1562]
(re #1538)

## Current Status

The current product name "**jormungandr**" (flow-breaker) and "**jcli**" (reminds java). 

## Suggested

* Rename to something which "brands" cardano (**cardano-node-rust**, **cardano-node-r**, **cardano** (for cli) etc.

## Resulting Usage Example

```sh
# Binary Install #
snap install cardano-node-rust
cardano --interactive-config
cardano-node-rust --shelly
```

**Comment by NicolasDP** [comment]
I see where you are coming from but Jörmungandr is aimed to support other protocols too.

**Comment by lazaridiscom** [comment]
> I see where you are coming from

Nah, there's many fog.

This issue is essentially C-level stuff (CTO / CEO).

(sidenote: closing issues that fast is anyways a bad process, as a contributors can be discouraged to give further elaborative feedback. It can be even seen as "rude" - not by me though, I'm used to it.).
