### ISSUE TITLE
Resource Temporarily Unavailable

### ISSUE THREAD

**Issue by sdalmeida** [input-output-hk/jormungandr#1575]
**Describe the bug**
After 5 minutes of my starting my node, I see this error message and my node restarts:
```
thread 'tokio-runtime-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', src/libcore/result.rs:1165:5
```

Here's a longer output from my logs

```
Jan 16 01:21:27.482 INFO connecting to peer, node_id: e6e4900b103e319e0e451c78bd97a59e27e59620797c1e62, peer_addr: 167.179.89.25:3000, task: network
Jan 16 01:21:27.682 INFO connection closed, peer_addr: 35.186.188.224:25430, local_addr: 0.0.0.0:3000, task: network
Jan 16 01:21:27.764 INFO connecting to peer, node_id: 4e6cb27d6c33b682c6c1d85ad789321202d2d9b12e9e2c58, peer_addr: 95.216.210.17:3200, task: network
thread 'tokio-runtime-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Jan 16 01:21:27.935 INFO Shutting down node
```

**Mandatory Information**
1. jcli 0.8.6 (HEAD-7686397, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
2. jormungandr 0.8.6 (HEAD-7686397, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**To Reproduce**
1. Start node as a leader
2. Wait for the Bootstrap to finish
3. Give it a few minutes

**Expected behavior**
Node should not crash. In the event the node does crash, this log message should be displayed as CRIT or even ERROR

**Comment by sdalmeida** [comment]
Looks like this is a duplicate of #1510

**Comment by rinor** [comment]
@sdalmeida thanky for the report. Reopened this since it is a bit different from the other one.

**Comment by NicolasDP** [comment]
This is linked to a known issue on the Runtime changes. This will be fixed with a the new service watchdog we are working on (#1488 ).

a short term mitigation would be to have a hard `std::process::exit(0)` in order to stop the node, so the community scripts are not affected by this and can continue to stop their nodes when needed.
