### ISSUE TITLE
Ticker not appear

### ISSUE THREAD

**Issue by jproes** [input-output-hk/jormungandr#1590]
My node was approved two days ago and my ticker doesn't appear in Daedalus and Yoroi. 
I have to do something? Thanks. I haven't found anything in the references

**Comment by mzabaluev** [comment]
This is not related to jormungandr development. Please use the support channel for the testnet. @NicolasDP @vincenthz can you provide a pointer?

**Comment by NicolasDP** [comment]
@jproes , try reporting this issue to https://iohk.zendesk.com/hc/en-us
