### ISSUE TITLE
Remove more peer at a time when evicting when full

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/jormungandr#1592]
We currently one remove one at a time when the peer map is at capacity, we should be able to remove way more than that:

https://github.com/input-output-hk/jormungandr/blob/835e373d7021efb3b0208a4dde7259b1773993af/jormungandr/src/network/p2p/comm/peer_map.rs#L175-L179

**Comment by mzabaluev** [comment]
I think once the locking is done properly in #1591, there won't be a press of async tasks waiting to add a new connection, but blocked on the lock, so the issue will resolve itself. This code is consistent with adding one connection per acquired lock.

**Comment by mzabaluev** [comment]
Not a real problem as described above.

**Comment by NicolasDP** [comment]
I agree. this is no longer valid.
