### ISSUE TITLE
Jormungandr Install issues on NixOS

### ISSUE THREAD

**Issue by Ocycle** [input-output-hk/jormungandr#1600]
Hello Nicolas,

since the removal of shell.nix, I'm getting following two errors if I install w/o nix-shell
I magaged to solve one of them, but want to report it anyway.

(Also, until yesterday 18/01 I was able to install 8.0.6 by opening a nix-shell with the old shell.nix, taken from 8.5.0.)

**Details:**

$ nixos-version 
19.09.1912.5b9eee22acf (Loris)

Jormungandr checked out to 8.0.6 ( but I get same errors if I install from master )
check out method:
- git checkout tags/8.0.6 and git submodule update --init
or
- git checkout -b jorm_8.0.6 8.0.6 --recurse-submodules

**First common error for jormungandr and jcli:
crate:  openssl-sys v0.9.53**

"error: failed to run custom build command for `openssl-sys v0.9.53`
Caused by:
  process didn't exit successfully: `$HOME/jormungandr/target/release/build/openssl-sys-e3e9c15e6d3db1e7/build-script-main` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
cargo:rerun-if-env-changed=OPENSSL_DIR
OPENSSL_DIR unset"

**I solved it by creating an install launcher with vars declaration:**

$ cat install_jormungandr 

cd $HOME/jormungandr

export X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR=/nix/store/ifl3lls0cbsdscbin0v6za9c8yp87v0l-openssl-1.1.1d-bin/bin
export X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR=/nix/store/0425y1vs6f9jndqw0b8whkpliiqn1ccy-openssl-1.1.1d/lib
export X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR=/nix/store/2v45sw2109m2c7xzld4gc8g5bvjzybc4-openssl-1.1.1d-dev/include
export OPENSSL_DIR=/nix/store/ifl3lls0cbsdscbin0v6za9c8yp87v0l-openssl-1.1.1d-bin/bin
export OPENSSL_LIB_DIR=/nix/store/0425y1vs6f9jndqw0b8whkpliiqn1ccy-openssl-1.1.1d/lib
export OPENSSL_INCLUDE_DIR=/nix/store/2v45sw2109m2c7xzld4gc8g5bvjzybc4-openssl-1.1.1d-dev/include

cargo install --path jormungandr ; cargo install --path jcli

**(This vars export doens't works if you put it in .bashrc nor by putting it in nixos config and do a nixos-rebuild).**

This is solved, jormungandr and jcli continue with install process and **jcli build is succeeded.**

**While jormungandr fails on crate: network-grpc v0.1.0****

Error output:
"error: failed to run custom build command for `network-grpc v0.1.0 ($HOME/jormungandr/chain-deps/network-grpc)`

Caused by:
  process didn't exit successfully: `$HOME/jormungandr/target/release/build/network-grpc-f9e548ab5d092451/build-script-build` (exit code: 1)
--- stderr
**No such file or directory (os error 2)"** 

As per my checks I found the following:
**1. directory and build-script-build do actually exists:**

$ jormungandr/target/release/build/network-grpc-f9e548ab5d092451]$ ls -ltr
total 6748
-rw-r--r-- 1 user users     340 Jan 19 11:50 build_script_build-f9e548ab5d092451.d
-rwxr-xr-x 2 user users 3452000 Jan 19 11:50 build_script_build-f9e548ab5d092451
-rwxr-xr-x 2 user users 3452000 Jan 19 11:50 build-script-build

**2. build script fails for an unset var:**

$ jormungandr/target/release/build/network-grpc-f9e548ab5d092451]$ ./build-script-build

**OUT_DIR environment variable is not set**

This is a Rust variable (checked in Rust docs)

Additionally I had a look on some others succeded crates to check the output of build-script-build 

Two examples:
$ /jormungandr/target/release/build/unicase-02684dc753ed8f1e]$ ./build-script-build 
cargo:rustc-cfg=__unicase__iter_cmp
cargo:rustc-cfg=__unicase__default_hasher
cargo:rustc-cfg=__unicase__const_fns
cargo:rustc-cfg=__unicase__core_and_alloc

$ /jormungandr/target/release/build/prost-build-0a90c2fc6cd33e46]$ ./build-script-build 
cargo:rustc-env=PROTOC=/home/user/jormungandr/target/release/build/prost-build-0a90c2fc6cd33e46/third-party/protobuf/protoc-linux-x86_64
cargo:rustc-env=PROTOC_INCLUDE=/home/user/jormungandr/target/release/build/prost-build-0a90c2fc6cd33e46/third-party/protobuf/include
cargo:rerun-if-env-changed=PROTOC
cargo:rerun-if-env-changed=PROTOC_INCLUDE

Is it possible to have a fix for this? 
I could switch to jormungandr-nix, but would like to keep jormungandr.

Many thanks in advance,
Kind regards,
Emanuele

**Comment by Ocycle** [comment]
Hello,
in regarding of what I sated above:

(Also, until yesterday 18/01 I was able to install 8.0.6 by opening a nix-shell with the old shell.nix, taken from 8.5.0.)

Sorry, my fault, I can install 8.0.6 opening a nix-shell with previous 8.0.5 shell.nix and setting those by  openssl path variables.

Regards,
Emanuele

**Comment by manveru** [comment]
You can build on NixOS using https://github.com/input-output-hk/iohk-nix with `nix-build -A jormungandrLib.packages.v0_8_6.jcli` or `nix-build -A jormungandrLib.packages.v0_8_6.jormungandr`

**Comment by Ocycle** [comment]
Hello,
thanks so much, I'm going to install
kind regards.
Emanuele

**Comment by Ocycle** [comment]
Incredible! Installed in two minutes, very interesting repository
I saved it in my projects update script.
Thanks again, I close the issue
best regards,
Emanuele
