### ISSUE TITLE
It still gets stuck

### ISSUE THREAD

**Issue by prographo** [input-output-hk/jormungandr#1615]
**Describe the bug**

The node bootstraps sucessfully.
The node begins to process blocks. 
The node stops processing blocks.
After several minutes the node "jumps forward" to the current block.
Then pauses again for a while.

```
Every 2.0s: ./jcli rest v0 node s...  ip-172-31-14-232: Tue Jan 21 12:04:23 2020

---
blockRecvCnt: 43
lastBlockContentSize: 0
lastBlockDate: "38.30234"
lastBlockFees: 0
lastBlockHash: b4e1373fb27420ea4c58ef0545661b183bb54fde30006c9cfe6007cfd52a9a89
lastBlockHeight: "118082"
lastBlockSum: 0
lastBlockTime: "2020-01-21T12:01:25+00:00"
lastBlockTx: 0
lastReceivedBlockTime: "2020-01-21T12:02:48+00:00"
state: Running
txRecvCnt: 1
uptime: 777
version: jormungandr 0.8.6-7686397
```

**Mandatory Information**
1. `jcli --full-version` output;

```
jcli --full-version
jcli 0.8.6 (HEAD-7686397, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
```

2. `jormungandr --full-version` output;

```
jormungandr --full-version
jormungandr 0.8.6 (HEAD-7686397, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
```

**To Reproduce**

Download it, run it - happens every time.

Machine is 4 core, 16GB, 100Mbps connection.

**Comment by mzabaluev** [comment]
No new information here that is not already in #1459, #1521, #1543 etc.
