### ISSUE TITLE
Configuration issue with Windows version of Jormungandr poolsecret1.yaml

### ISSUE THREAD

**Issue by cmerriamleith** [input-output-hk/jormungandr#1618]
There seems to be a problem with executing the Bootstrap file on Windows Server. The root cause of the problems seems to be related to how the Block-0 bin file is getting created. The problem seems to be caused by the poolsecret1.yaml file. I believe that the poolsecret1.yaml file does not contain the correct values for the ITN_Genesis hash value. 

When the network tries to connect to any of the valid peers it generates the following error message: "Connection to peer failed, reason: genesis block hash 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676 reported by the peer is not the expected 1bd7e5af6f49b8a4f8080cdb98a51d3e180da90a7fabe30fc68d3d3460b78c0f, node_id: fc89bff08ec4e054b4f03106f5312834abdf2fcb444610e9, peer_addr: 18.177.78.96:3000. 

This is happening with all of the peers. I have confirmed that I am using the correct peers by pulling from the adapools.org/peers list. I believe that the cause is the poolsecret1.yaml is getting created with the wrong inputs.

Let me know if you need any other information. I am using Jormungandr 8.6. Also using the correct versions of bootstrap.ps1, jcli, jormungandr, config.yaml, genesis.yaml, Below is a dump of my node messages.

Jan 22 07:05:06.549 INFO connection to peer failed, reason: genesis block hash 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676
reported by the peer is not the expected 1bd7e5af6f49b8a4f8080cdb98a51d3e180da90a7fabe30fc68d3d3460b78c0f, node_id: fcdf302895236d012635052725a0
cdfc2e8ee394a1935b63, peer_addr: 52.9.77.197:3000, task: network
Jan 22 07:05:06.690 INFO connection to peer failed, reason: genesis block hash 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676
reported by the peer is not the expected 1bd7e5af6f49b8a4f8080cdb98a51d3e180da90a7fabe30fc68d3d3460b78c0f, node_id: 8f9ff09765684199b351d520defa
c463b1282a63d3cc99ca, peer_addr: 3.125.31.84:3000, task: network
Jan 22 07:05:06.721 INFO connection to peer failed, reason: genesis block hash 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676
reported by the peer is not the expected 1bd7e5af6f49b8a4f8080cdb98a51d3e180da90a7fabe30fc68d3d3460b78c0f, node_id: fc89bff08ec4e054b4f03106f531
2834abdf2fcb444610e9, peer_addr: 18.177.78.96:3000, task: network
Jan 22 07:05:07.596 INFO failed to connect to peer, reason: No connection could be made because the target machine actively refused it. (os erro
r 10061), node_id: 7ddf203c86a012e8863ef19d96aabba23d2445c492d86267, peer_addr: 13.56.0.226:3000, task: network
Jan 22 07:05:07.784 INFO failed to connect to peer, reason: No connection could be made because the target machine actively refused it. (os erro
r 10061), node_id: 06aa98b0ab6589f464d08911717115ef354161f0dc727858, peer_addr: 18.184.35.137:3000, task: network
Jan 22 07:05:07.784 INFO failed to connect to peer, reason: No connection could be made because the target machine actively refused it. (os erro
r 10061), node_id: 9d15a9e2f1336c7acda8ced34e929f697dc24ea0910c3e67, peer_addr: 3.125.183.71:3000, task: network
Jan 22 07:05:07.877 INFO failed to connect to peer, reason: No connection could be made because the target machine actively refused it. (os erro
r 10061), node_id: 8529e334a39a5b6033b698be2040b1089d8f67e0102e2575, peer_addr: 18.182.115.51:3000, task: network
Jan 22 07:05:12.565 INFO connection to peer failed, reason: protocol handshake failed: unknown error, node_id: df02383863ae5e14fea5d51a092585da3
4e689a73f704613, peer_addr: 54.183.149.167:3000, task: network
Jan 22 07:05:16.471 WARN blockchain is not moving up, the last block was 11993 seconds ago, task: stuck_notifier
Jan 22 07:05:16.471 INFO connecting to peer, node_id: df02383863ae5e14fea5d51a092585da34e689a73f704613, peer_addr: 54.183.149.167:3000, task: ne
twork
Jan 22 07:05:16.471 INFO connecting to peer, node_id: 06aa98b0ab6589f464d08911717115ef354161f0dc727858, peer_addr: 18.184.35.137:3000, task: net
work
Jan 22 07:05:16.471 INFO connecting to peer, node_id: 7ddf203c86a012e8863ef19d96aabba23d2445c492d86267, peer_addr: 13.56.0.226:3000, task: netwo
rk
Jan 22 07:05:16.471 INFO connecting to peer, node_id: 8529e334a39a5b6033b698be2040b1089d8f67e0102e2575, peer_addr: 18.182.115.51:3000, task: net
work
Jan 22 07:05:16.471 INFO connecting to peer, node_id: fcdf302895236d012635052725a0cdfc2e8ee394a1935b63, peer_addr: 52.9.77.197:3000, task: netwo
rk
Jan 22 07:05:16.471 INFO connecting to peer, node_id: 8f9ff09765684199b351d520defac463b1282a63d3cc99ca, peer_addr: 3.125.31.84:3000, task: netwo
rk
Jan 22 07:05:16.471 INFO connecting to peer, node_id: fc89bff08ec4e054b4f03106f5312834abdf2fcb444610e9, peer_addr: 18.177.78.96:3000, task: netw
ork
Jan 22 07:05:16.471 INFO connecting to peer, node_id: 9d15a9e2f1336c7acda8ced34e929f697dc24ea0910c3e67, peer_addr: 3.125.183.71:3000, task: netw
ork
Jan 22 07:05:16.549 INFO connection to peer failed, reason: genesis block hash 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676
reported by the peer is not the expected 1bd7e5af6f49b8a4f8080cdb98a51d3e180da90a7fabe30fc68d3d3460b78c0f, node_id: fcdf302895236d012635052725a0
cdfc2e8ee394a1935b63, peer_addr: 52.9.77.197:3000, task: network
Jan 22 07:05:16.690 INFO connection to peer failed, reason: genesis block hash 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676
reported by the peer is not the expected 1bd7e5af6f49b8a4f8080cdb98a51d3e180da90a7fabe30fc68d3d3460b78c0f, node_id: 8f9ff09765684199b351d520defa
c463b1282a63d3cc99ca, peer_addr: 3.125.31.84:3000, task: network
Jan 22 07:05:16.737 INFO connection to peer failed, reason: genesis block hash 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676
reported by the peer is not the expected 1bd7e5af6f49b8a4f8080cdb98a51d3e180da90a7fabe30fc68d3d3460b78c0f, node_id: fc89bff08ec4e054b4f03106f531
2834abdf2fcb444610e9, peer_addr: 18.177.78.96:3000, task: network
Jan 22 07:05:17.596 INFO failed to connect to peer, reason: No connection could be made because the target machine actively refused it. (os erro
r 10061), node_id: 7ddf203c86a012e8863ef19d96aabba23d2445c492d86267, peer_addr: 13.56.0.226:3000, task: network
Jan 22 07:05:17.784 INFO failed to connect to peer, reason: No connection could be made because the target machine actively refused it. (os erro
r 10061), node_id: 9d15a9e2f1336c7acda8ced34e929f697dc24ea0910c3e67, peer_addr: 3.125.183.71:3000, task: network
Jan 22 07:05:17.784 INFO failed to connect to peer, reason: No connection could be made because the target machine actively refused it. (os erro
r 10061), node_id: 06aa98b0ab6589f464d08911717115ef354161f0dc727858, peer_addr: 18.184.35.137:3000, task: network
Jan 22 07:05:17.862 INFO failed to connect to peer, reason: No connection could be made because the target machine actively refused it. (os erro
r 10061), node_id: 8529e334a39a5b6033b698be2040b1089d8f67e0102e2575, peer_addr: 18.182.115.51:3000, task: network
Jan 22 07:05:21.612 INFO connection to peer failed, reason: protocol handshake failed: unknown error, node_id: df02383863ae5e14fea5d51a092585da3
4e689a73f704613, peer_addr: 54.183.149.167:3000, task: network
Jan 22 07:05:23.080 INFO service finished successfully, task: rest
Jan 22 07:05:23.080 INFO Shutting down node

**Comment by rdlrt** [comment]
It looks like you are confusing creation of block-0 for new network with joining am existing network. Please make sure you're using the right network genesis hash/config combination as per [this](https://hydra.iohk.io/build/1497230/download/1/index.html)  link if you're looking to join existing networks.

Feel free to use telegram staking best practices [workgroup](https://t.me/CardanoStakePoolWorkgroup)  for assistance with queries for getting you started, or use IOHK helpdesk for support instead.

**Comment by cmerriamleith** [comment]
Hi Mikhail,

I appreciate your fast response. But want to clarify that I am not confusing the creation of block-0 with the wrong network. I have confirmed that I am using all the correct versions of the files and the associated correct genesis hash string. I will list them below just so you understand that I have everything configured correctly. What I am saying is that there is a bug within the jormungandr-v0.8.6-x86_64-pc-windows-msvc specifically with the jormungandr application with how it is creating the block-0 file using the poolsecret1.yaml. You need to confirm why it has conflicting genesis hash references. I also noticed that you just uploaded version 8.7 so I will update my configuration with the latest release and then recompile the code and test the node with 8.7. I will let you know if the problem still persists. I will follow up after I update to 8.7.

Thanks,
Chris Merriam-Leith

**Comment by rdlrt** [comment]
Assuming you're creating your own network , the conflicting hash comes from your trusted peers config. Please use the groups suggested above for clarification

**Comment by cmerriamleith** [comment]
I am trying to connect to the itn_rewards_v1 using the config.yaml and genesis.yaml and genesis hash 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676 from https://hydra.iohk.io/build/1523436/download/1/index.html and also confirming the peers from from this site https://adapools.org/peers. 

Here is a copy of my config.yaml

{
  "log": [
    {
      "format": "plain",
      "level": "info",
      "output": "stdout"
    }
  ],
  "storage": "./storage/",
  "p2p": {
  "listen_address": "/ip4/127.0.0.1/tcp/3000",
  "public_address": "/ip4/35.222.myip.myip/tcp/3000",
  "topics_of_interest": {
      "blocks": "high",
      "messages": "high"
    },
    "trusted_peers": [
      {
        "address": "/ip4/13.56.0.226/tcp/3000",
        "id": "7ddf203c86a012e8863ef19d96aabba23d2445c492d86267"
      },
      {
        "address": "/ip4/54.183.149.167/tcp/3000",
        "id": "df02383863ae5e14fea5d51a092585da34e689a73f704613"
      },
      {
        "address": "/ip4/52.9.77.197/tcp/3000",
        "id": "fcdf302895236d012635052725a0cdfc2e8ee394a1935b63"
      },
      {
        "address": "/ip4/18.177.78.96/tcp/3000",
        "id": "fc89bff08ec4e054b4f03106f5312834abdf2fcb444610e9"
      },
      {
        "address": "/ip4/3.115.154.161/tcp/3000",
        "id": "35bead7d45b3b8bda5e74aa12126d871069e7617b7f4fe62"
      },
      {
        "address": "/ip4/18.182.115.51/tcp/3000",
        "id": "8529e334a39a5b6033b698be2040b1089d8f67e0102e2575"
      },
      {
        "address": "/ip4/18.184.35.137/tcp/3000",
        "id": "06aa98b0ab6589f464d08911717115ef354161f0dc727858"
      },
      {
        "address": "/ip4/3.125.31.84/tcp/3000",
        "id": "8f9ff09765684199b351d520defac463b1282a63d3cc99ca"
      },
      {
        "address": "/ip4/3.125.183.71/tcp/3000",
        "id": "9d15a9e2f1336c7acda8ced34e929f697dc24ea0910c3e67"
      }
    ]
  },
  "rest": {
    "listen": "127.0.0.0:3100"
  }
}

**Comment by rdlrt** [comment]
In that case, block-0 does not come into picture. You shouldnt specify a block-0 file on the startup command of jormungandr. The log in the original post of this thread shows you used a genesis reference of 1bd7e5af6f49b8a4f8080cdb98a51d3e180da90a7fabe30fc68d3d3460b78c0f (either as a hash or block-0 file reference), which is why you're seeing the issue.

**Comment by cmerriamleith** [comment]
Thanks for the fast reply. But that is the point that I am trying to communicate. I did not configure the above genesis reference of 1bd7e5af6f49b8a4f8080cdb98a51d3e180da90a7fabe30fc68d3d3460b78c0f I don't know were this genesis reference is orginating from, but the error message says that the peer is looking to receive this above geneis hash and not the ITN genesis of 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676. The only thing I have been able to track it back to is how the bootstrap creates the block-0 file from the poolsecret1.yaml file.

The error message is saying that the ITN Genesis reference is not correct for the peer. But I am submitting correct genesis "7b676" and it says its expecting "78c0f". Note, that I am truncating the codes to make this message easier to read.
 
Error code excerpt from above thread:

Jan 22 07:05:16.690 INFO connection to peer failed, reason: genesis block hash 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676 [Correct Reference]
reported by the peer is not the expected [Incorrect Reference] 1bd7e5af6f49b8a4f8080cdb98a51d3e180da90a7fabe30fc68d3d3460b78c0f, node_id: 8f9ff09765684199b351d520defa
c463b1282a63d3cc99ca, peer_addr: 3.125.31.84:3000, task: network

**Comment by rdlrt** [comment]
I have tagged you on telegram workgroup, if you'd like assistance - please continue there

**Comment by cmerriamleith** [comment]
Ok, I appreciate your time. Note, that I have been out on the telegram workgroup and as far as I have been able to determine there are very few if any successful nodes running on Windows Server. Telegram is not a very good platform for communicating these complex technical discussions. Thanks.
