### ISSUE TITLE
jormungandr no longer shows up in netstat -tupan

### ISSUE THREAD

**Issue by shawnim** [input-output-hk/jormungandr#1636]
**Describe the bug**
jormungandr does not show up in netstat -tupan listings in v0.8.7.
netstat -tupan on v0.8.6:
tcp        0      0 172.30.0.223:20002      174.195.143.35:2451     ESTABLISHED 44819/jormungandr
and on v0.8.7:
tcp      142      0 172.30.0.83:20002       86.184.34.176:60746     ESTABLISHED -

**Mandatory Information**
1. `jcli --full-version` output;
jcli 0.8.7 (HEAD-364cd84e, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
2. `jormungandr --full-version` output;
jormungandr 0.8.7 (HEAD-364cd84e, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**To Reproduce**
1. Run v0.8.6.
2. Run netstat -tupan
3. Upgrade to v0.8.7
4. Run netstat -tupan

**Expected behavior**
v0.8.7 should have similar netstat output as v0.8.6 including program name of jormungandr so it is easy to identify jormungandr established connections.

**Additional context**
Running on Ubuntu 18.04.

**Comment by rinor** [comment]
@shawnim what OS are you running?

**Comment by shawnim** [comment]
Ubuntu 18.04.However this issue seems to have been resolved in v0.8.8 and v0.8.9.

    On Thursday, January 30, 2020, 9:50:00 AM PST, Rinor Hoxha <notifications@github.com> wrote:  
 
 
@shawnim what OS are you running?

**Comment by rinor** [comment]
@shawnim thank you for the feedback.

**Comment by mzabaluev** [comment]
Looks like another manifestation of #1637.
