### ISSUE TITLE
Jormungandr 0.8.7 node does not create blocks on Windows

### ISSUE THREAD

**Issue by piotr-iohk** [input-output-hk/jormungandr#1659]
**Describe the bug**
Jormungandr 0.8.7 node does not create blocks on Windows. It works fine with the very same config.yaml /block0.bin /secret.yaml on Linux and MacOS.
`config.yaml`, `block0.bin` and related `genesis.yaml`, and `secret.yaml` are available here ->
https://github.com/input-output-hk/cardano-wallet/tree/master/lib/jormungandr/test/data/jormungandr

The configs are used in integration tests for cardano-wallet.

**Mandatory Information**
1. `jcli 0.8.7 (HEAD-364cd84e, release, windows [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]`
2. `jormungandr 0.8.7 (HEAD-364cd84e, release, windows [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]`

**To Reproduce**
On Windows:

```
git clone https://github.com/input-output-hk/cardano-wallet.git
cd ./cardano-wallet/lib/jormungandr/test/data/jormungandr/

jormungandr --genesis-block block0.bin --secret secret.yaml --config config.yaml --rest-listen 127.0.0.1:8080 --log-level debug
Jan 28 08:25:35.892 INFO Starting jormungandr 0.8.7 (HEAD-364cd84e, release, windows [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)], task: init
Jan 28 08:25:35.939 DEBG system settings are: limit for open files (RLIMIT_NOFILE): N/A; limit for CPU usage (RLIMIT_CPU): N/A, task: init
Jan 28 08:25:35.939 INFO storing blockchain in memory, task: init
Jan 28 08:25:35.939 DEBG parsing block0 from file path `"block0.bin"', task: init
Jan 28 08:25:35.939 WARN No trusted peers joinable to bootstrap the network, task: bootstrap
Jan 28 08:25:35.939 INFO listening and accepting gRPC connections, local_addr: 127.0.0.1:0, task: network
```
Nothing is logged after that. Also blockchain is not moving up.
```
>jcli rest v0 node stats get  -h http://127.0.0.1:8080/api
---
blockRecvCnt: 0
lastBlockContentSize: 248243
lastBlockDate: "0.0"
lastBlockFees: 0
lastBlockHash: f8c0622ea4b768421fea136a6e5a4e3b4c328fc5f16fad75817e40c8a2a56a56
lastBlockHeight: "0"
lastBlockSum: 0
lastBlockTime: "2019-04-25T14:20:57+00:00"
lastBlockTx: 1021
lastReceivedBlockTime: ~
peerAvailableCnt: "0"
peerQuarantinedCnt: "0"
peerUnreachableCnt: "0"
state: Running
txRecvCnt: 0
uptime: 9
version: jormungandr 0.8.7-364cd84e
```

**Expected behavior**
The node should be creating blocks on Windows as it creates them with the same configuration and setup on Linux and MacOS. 

**Additional context**
Please note that Jormungandr 0.8.6 works fine with the same configs and creates blocks on Windows successfully.

**Comment by mzabaluev** [comment]
The configuration does not have any trusted peers. Is it exactly the same on Linux?

**Comment by piotr-iohk** [comment]
> The configuration file in the repository does not have any trusted peers. Is it exactly the same on Linux?

Yes, it is exactly the same. This is the setup we have been using in our integration tests for cardano-wallet.

**Comment by rinor** [comment]
Probably a manifestation of https://github.com/input-output-hk/jormungandr/issues/1637 now also in windows.

**Comment by rinor** [comment]
@piotr-iohk is it still a problem with the latest release?

**Comment by piotr-iohk** [comment]
@rinor I don't see it any longer on 0.8.9 - thx!

**Comment by rinor** [comment]
@piotr-iohk thanks for the feedback. Will close it, but please reopen/comment if it occurs again. Thank you.
