### ISSUE TITLE
Fragments from api/v0/fragment/logs remains in Pending state

### ISSUE THREAD

**Issue by adascanBovich** [input-output-hk/jormungandr#1673]
**Describe the bug**
When I parse output from api/v0/fragment/logs, some of the fragments have "status":"Pending", while call to explorer/graphql with the same fragment_id returns transaction included in block.

**Mandatory Information**
1. jcli 0.8.7 (HEAD-364cd84, release, macos [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
2. jormungandr 0.8.7 (HEAD-364cd84, release, macos [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**To Reproduce**
1. Start a passive node with enabled explorer
2. Get fragment_id of any record with "status":"Pending" from api/v0/fragment/logs call
3. Make a call to explorer with this fragment_id

**Expected behavior**
api/v0/fragment/logs should return "InABlock" status for transactions that are actually in a block.  

**Additional context**
Example:

`{"fragment_id":"59a42db3e073053b788d925e2b7db6d55029fe8747f7b1a48b1aa24babe074d7","received_from":"Network","received_at":"2020-01-29T17:24:44.900413+00:00","last_updated_at":"2020-01-29T17:24:44.900413+00:00","status":"Pending"}`

Response from graphiql:

<img width="680" alt="Screenshot 2020-01-29 at 21 19 56" src="https://user-images.githubusercontent.com/58727428/73384843-1f62dd80-42dd-11ea-9696-da1173192986.png">

**Comment by dkijania** [comment]
Issue is observed also on newest master in most of tests regarding passive -> leader node. 
When sending tx to passive node, it remains `pending` even though leader node put it into the block.

Passive node fragment logs:

```
[
    {
        "fragment_id": "df41d821f969f51017e8afcc53af2287c4711ab2e8e6f7d425db46a22979105d",
        "received_from": "Rest",
        "received_at": "2020-10-09T11:53:11.107485900+00:00",
        "last_updated_at": "2020-10-09T11:53:11.107486+00:00",
        "status": "Pending"
    }
]
```

Leader node fragment logs:

```
[
    {
        "fragment_id": "df41d821f969f51017e8afcc53af2287c4711ab2e8e6f7d425db46a22979105d",
        "received_from": "Network",
        "received_at": "2020-10-09T11:53:11.108580500+00:00",
        "last_updated_at": "2020-10-09T11:53:12.024467100+00:00",
        "status": {
            "InABlock": {
                "date": "0.26",
                "block": "61f44fd199cc128c4bd0d3e5c9cd6493b17f6c31bae0db43c55a537baf3d08b0"
            }
        }
    }
]
```

To reproduce run test:
`cargo run -- --scenario legacy_current_node_fragment_propagation --root-dir  legacy_current_node_fragment_propagation`

**Comment by mzabaluev** [comment]
@dkijania The problem seen in the scenario test is due to a recently introduced incompatibility between jormungandr 0.9 and master.

**Comment by mzabaluev** [comment]
Please reopen this if the problem is reproducible between nodes running recent jormungandr 0.9.x releases, or a network of nodes running a snapshot off current master, such as the 0.10.0-nightly.* prereleases.
