### ISSUE TITLE
rest api time out

### ISSUE THREAD

**Issue by khkwon01** [input-output-hk/jormungandr#1680]
**Describe the bug**

After starting jormungandr program, it work well for 5 minutes and after that, 
when i execute to jcli command, it happen to time out error over and over.

**Mandatory Information**
1. `jcli --full-version` output;
jcli 0.8.8 (HEAD-4687999, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
2. `jormungandr --full-version` output;
jormungandr 0.8.8 (HEAD-4687999, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**To Reproduce**

**Expected behavior**

There is no time-out for jcli command.

**Additional context**

1. jcli error
 ./jcli rest v0 node stats get -h $(cat 3301);
failed to make a REST request
  |-> connection with node timed out
  |-> http://127.0.0.1:8443/api/v0/node/stats: timed out

2. jormungandr eror
Jan 30 10:34:57 k05 jormungandr[31071]: request stream failed, request: UploadBlocks, sub_task: server, task: network, error: Inbound(Error { code: Internal, source: Status { code: Internal, message: "h2 protocol error: protocol error: unexpected internal error encountered" } })

jormungandr[31071]: inbound subscription stream failed, stream: gossip, node_id: a59a59711c4ed50dddbb84f9889eb9b0bb8b9055c69fbc22, sub_task: server, task: network, direction: in, error: Inbound(Error { code: Canceled, source: Status { code: Cancelled, message: "h2 protocol error: protocol error: stream no longer needed" } })

**Comment by mark-stopka** [comment]
Likely a #1626 duplicate.

**Comment by khkwon01** [comment]
It is different version but i think that it is same like #1626 
This is 0.8.8 version.

**Comment by rinor** [comment]
@khkwon01 thank you for the report. Indeed even though a different version the issue is the same and there is work being done to solve it.
