### ISSUE TITLE
Not computing this schedule because of invalid state against the network blockchain

### ISSUE THREAD

**Issue by BitcoinMicroPaymentNetwork** [input-output-hk/jormungandr#1689]
rohitchandan$ ./jcli rest v0 leaders logs get -h http://127.0.0.1:3100/api
---
- created_at_time: "2020-01-31T03:48:12.042774+00:00"
  enclave_leader_id: 1
  finished_at_time: "2020-01-31T17:40:20.596600+00:00"
  scheduled_at_date: "48.40401"
  scheduled_at_time: "2020-01-31T17:40:19+00:00"
  status:
    Rejected:
      reason: Not computing this schedule because of invalid state against the network blockchain
  wake_at_time: "2020-01-31T17:40:20.596439+00:00"

**Comment by mzabaluev** [comment]
Thanks for the heads-up. Reopened #1379.
