### ISSUE TITLE
Node in sync, block produced successfully but doesn't end on chain due to forks.

### ISSUE THREAD

**Issue by pigofapool** [input-output-hk/jormungandr#1694]
**Describe the bug**

My node was supposed to produce a block according to the leader log:

```
- created_at_time: "2020-02-02T04:10:11.632282020+00:00"
  enclave_leader_id: 1
  finished_at_time: ~
  scheduled_at_date: "50.18353"
  scheduled_at_time: "2020-02-02T05:25:23+00:00"
  status: Pending
  wake_at_time: ~
```

At 2020-02-02T05:25:12.143+00:00, the following message appears in the logs:

```
Feb 02 05:25:12.143 INFO received block announcement from network, from_node_id: 65631d89a5293212ac4e87ad87e315ce8b472109150ae4c1, date: 50.18347, parent: 122c5818ffc90d2a77665637932e170ab2481dcd42865c75681c308480e4acbe, hash: 5df52aeaf25c7a1330ebead64e3a411cfe4c30e09f863fe87afa0ad9a8a725da, task: block
```

Then at 2020-02-02T05:25:12.820+00:00, the same node sends the following announcement:

```
Feb 02 05:25:12.820 INFO received block announcement from network, from_node_id: 65631d89a5293212ac4e87ad87e315ce8b472109150ae4c1, date: 50.18347, parent: 122c5818ffc90d2a77665637932e170ab2481dcd42865c75681c308480e4acbe, hash: dc16ee807935a5de51f8d587993fe16a76f0170aa50571c657ec44fcd0652d18, task: block
```

Note that both blocks have the same parent and only the second one exists on chain.

At 2020-02-02T05:25:23.001+00:00 the leader event starts and my node attempts to produce a block, but produces it using the wrong parent block.

```
Feb 02 05:25:23.001 INFO Leader event started, event_remaining_time: 1s 998ms 230us 36ns, event_end: 2020-02-02T05:25:25+00:00, event_start: 2020-02-02T05:25:23+00:00, event_date: 50.18353, leader_id: 1, task: leadership
Feb 02 05:25:23.008 INFO receiving block from leadership service, date: 50.18353, parent: 5df52aeaf25c7a1330ebead64e3a411cfe4c30e09f863fe87afa0ad9a8a725da, hash: e7964803c794e3abc02f2feba11dfcbf329e85030a7b6813169f096850fc3d7c, task: block
Feb 02 05:25:23.020 INFO block from leader event successfully stored, date: 50.18353, parent: 5df52aeaf25c7a1330ebead64e3a411cfe4c30e09f863fe87afa0ad9a8a725da, hash: e7964803c794e3abc02f2feba11dfcbf329e85030a7b6813169f096850fc3d7c, task: block
Feb 02 05:25:23.021 INFO update current branch tip: 5df52aea-00025f5e-50.18347 -> e7964803-00025f5f-50.18353, date: 50.18353, parent: 5df52aeaf25c7a1330ebead64e3a411cfe4c30e09f863fe87afa0ad9a8a725da, hash: e7964803c794e3abc02f2feba11dfcbf329e85030a7b6813169f096850fc3d7c, task: block
```

Leader log shows this:

```
- created_at_time: "2020-02-02T04:32:31.460482497+00:00"
  enclave_leader_id: 1
  finished_at_time: "2020-02-02T05:25:23.008340363+00:00"
  scheduled_at_date: "50.18353"
  scheduled_at_time: "2020-02-02T05:25:23+00:00"
  status:
    Block:
      block: e7964803c794e3abc02f2feba11dfcbf329e85030a7b6813169f096850fc3d7c
      chain_length: 155487
  wake_at_time: "2020-02-02T05:25:23.001682922+00:00"
```

Then the following two announcements come through, again from the same node. The first is the block my node has generated that occurred on a fork, the second one is the one that was accepted on the chain.

```
Feb 02 05:25:24.170 INFO received block announcement from network, from_node_id: 65631d89a5293212ac4e87ad87e315ce8b472109150ae4c1, date: 50.18353, parent: 5df52aeaf25c7a1330ebead64e3a411cfe4c30e09f863fe87afa0ad9a8a725da, hash: e7964803c794e3abc02f2feba11dfcbf329e85030a7b6813169f096850fc3d7c, task: block
Feb 02 05:25:24.321 INFO received block announcement from network, from_node_id: 65631d89a5293212ac4e87ad87e315ce8b472109150ae4c1, date: 50.18352, parent: dc16ee807935a5de51f8d587993fe16a76f0170aa50571c657ec44fcd0652d18, hash: aeb10245251e423e763ebf3fd9a5eef43ce665d8750e664732ea0d279fdb845a, task: block
```

**Mandatory Information**
1. `jcli --full-version` output:
`jcli 0.8.9 (nix-build-30d20d2, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]`

2. `jormungandr --full-version` output:
`jormungandr 0.8.9 (nix-build-30d20d2, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]`

**To Reproduce**
Run jormungandr and create a block when the network announces two blocks with the same parent.

**Expected behavior**
If the node was scheduled to produce a block, then it should produce a block on the correct parent and that block should be accepted into the chain.

**Additional context**
Running NixOS and have jormungandr running as a systemd service using the IOHK jormungandr-nix and iohk-nix repositories. **Please, please, please** have them in sync with the official release of jormungandr. I keep having to patch and tweak them as the repositories are consistently behind the jormungandr repository...
I thought IOHK was using NixOS? Half the guides are for Nix and NixOS. Why is NixOS a second class distribution now?

**Comment by mzabaluev** [comment]
Tracked under #1513
