### ISSUE TITLE
Far less connections on Jor. 8.9 than previous versions

### ISSUE THREAD

**Issue by A-Caccese** [input-output-hk/jormungandr#1714]
**Describe the bug**
With the lastest installed release of Jor. (0.8.9-30d20d2e) I'm seeing far less connections as before on the same node with the same configuration.  To be concrete, now there are order 10^2 connections, when before there were order 10^3.

**Mandatory Information**
jcli 0.8.9 (8.9_ITN-30d20d2e, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
jormungandr 0.8.9 (8.9_ITN-30d20d2e, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**To Reproduce**
Run Jar. as a leader and let it sync for many hours.

**Expected behavior**
I don't know if this is a real issue or an expected behaviour, however maybe that with few connections, I think, that is less probable to successfully announce new blocks.

**Additional context**
I tried to set a public id in my node configuration and the connections consistently scale up, but after a (casual?) time interval jcli is unresponsive, the CPU saturates and the node gets out of sync.

**Comment by mzabaluev** [comment]
Unless you see it prevents the node from receiving timely updates, there is no problem.
#1696 specifically aims to reduce the number of idle connections throughout the network.

**Comment by A-Caccese** [comment]
So is this behaviour uncorrelated with the vaporized blocks issue? Is sufficient to check that my node tip is similar to that of others independent stake pools to be sure that I'm receiving timely updates? Thanks in advance.

**Comment by mzabaluev** [comment]
> Is sufficient to check that my node tip is similar to that of others independent stake pools to be sure that I'm receiving timely updates?

Yes. There are also INFO messages in the log about branch tip updates.
