### ISSUE TITLE
Simplify REST dispatch

### ISSUE THREAD

**Issue by CodeSandwich** [input-output-hk/jormungandr#172]
The REST API dispatch is complicated. It's built around App-based composition, where each route is a separate App, which may not be necessary. What also may not be necessary is routing based on path patterns with wildcards if REST API is redesigned.

**Comment by carl-shepherd** [comment]
Hello CodeSandwich,

We'd love to hear what you think of our customer service. Please take a moment to tell us. How would you rate the support you received? Please one of these in your reply that will help us to report on our efforts to the team.

Good, I'm satisfied
Bad, I'm unsatisfied

Thanks,
The IOHK Technical Support Desk Team
