### ISSUE TITLE
Trusted nodes rejecting connections when starting the node

### ISSUE THREAD

**Issue by make0x20** [input-output-hk/jormungandr#1751]
Following the guides (here: https://iohk.zendesk.com/hc/en-us/articles/900000038626-Stake-Pool-Operators-How-To and here: https://input-output-hk.github.io/jormungandr/introduction.html) on setting up the node  there seems to be an issue with getting the initial bootstrapping process done.

My node is unable to fetch the genesis block even after making sure that the configuration file and genesis hash are correct. I even tried putting in my external IP parameter and listening port as well as doing port forwarding to see if that works.

`Feb 07 17:05:24.728 WARN failed to download block, error: GetBlocks { source: Error { code: Unknown, source: Status { code: Unknown, message: "connection error: broken pipe" } } }, peer_address: 13.112.181.42:3000, block: 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676, task: init`

Seems like every trusted node from the configuration is rejecting my connection. Replacing those trusted IPs with IPs from adapools.org does not solve anything for me.

I'm using the config and genesis hash from "itn_rewards_v1" https://hydra.iohk.io/job/Cardano/iohk-nix/jormungandr-deployment/latest-finished/download/1/index.html

**Mandatory Information**
JCLI:
`jcli 0.8.9 (HEAD-30d20d2, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]`
Jormungandr:
`jormungandr 0.8.9 (HEAD-30d20d2, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]`

**Comment by vincenthz** [comment]
dup of #1718
