### ISSUE TITLE
Leader Logs Missing Blocks that were previously there - node doesn't create them either

### ISSUE THREAD

**Issue by papacarp** [input-output-hk/jormungandr#1771]
**Describe the bug**
So has anyone noticed leader log upcoming blocks going MIA?  I had some completely missed blocks from this morning - went to check my leader logs and sure enough - my nodes didn't think they had to make those blocks.  Furthermore, there were quite a few missing from the upcoming blocks as well.  My saved logs from the start of the epoch say I have 5 blocks coming up.  leader logs say I have 2 coming up.

![image](https://user-images.githubusercontent.com/11194546/74360557-23313e00-4d7a-11ea-98c3-99d32004af9b.png)

```
- created_at_time: "2020-02-12T17:06:34.874215662+00:00"
  enclave_leader_id: 1
  finished_at_time: ~
  scheduled_at_date: "60.42990"
  scheduled_at_time: "2020-02-12T19:06:37+00:00"
  status: Pending
  wake_at_time: ~
- created_at_time: "2020-02-12T17:06:34.874214622+00:00"
  enclave_leader_id: 1
  finished_at_time: ~
  scheduled_at_date: "60.41593"
  scheduled_at_time: "2020-02-12T18:20:03+00:00"
  status: Pending
  wake_at_time: ~

```

As you can see, block 24 and 25 are missing from leader log output

**Mandatory Information**
1. `jcli --full-version` output;
jcli 0.8.9 (HEAD-30d20d2, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
2. `jormungandr --full-version` output;
jormungandr 0.8.9 (HEAD-30d20d2, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**To Reproduce**
1. Capture leader logs at start of epoch, save
2. Restart node partway though epoch - in this case near end of epoch
3. Some events that were scheduled are now missing from leader logs
4. See error - this is the first time I've seen this issue and I think I would have noticed.

**Expected behavior**
Once a leader event is assigned, it should not change regardless of reboots

**Additional context**
Chrony is fine:
```
chronyc tracking
Reference ID    : A29FC87B (time.cloudflare.com)
Stratum         : 4
Ref time (UTC)  : Wed Feb 12 17:27:26 2020
System time     : 0.000235471 seconds fast of NTP time
Last offset     : +0.000109759 seconds
RMS offset      : 0.000221007 seconds
Frequency       : 3.998 ppm slow
Residual freq   : +0.001 ppm
Skew            : 0.018 ppm
Root delay      : 0.043969739 seconds
Root dispersion : 0.001187710 seconds
Update interval : 1038.4 seconds
```

**Comment by NicolasDP** [comment]
Thanks. I will review this today ASAP.

**Comment by Wirapool** [comment]
I have this issue on my 8.13 node. 

**jcli --full-version output;**

`jcli 0.8.13 (HEAD-241b3a59, release, linux [x86_64]) - [rustc 1.41.0 (5e1a79984 2020-01-27)]`
**jormungandr --full-version output;**

`jormungandr 0.8.13 (HEAD-241b3a59, release, linux [x86_64]) - [rustc 1.41.0 (5e1a79984 2020-01-27)]`
