### ISSUE TITLE
v0.8.10 jormungandr-v0.8.10-x86_64-unknown-linux-musl.tar.gz not working

### ISSUE THREAD

**Issue by subnet-dev** [input-output-hk/jormungandr#1785]
**Describe the bug**
The jormungandr-v0.8.10-x86_64-unknown-linux-musl.tar.gz is not working in busybox

**Mandatory Information**
Unable to get exact version of cat binary it doesn't work

**To Reproduce**
1. Run test docker busybox
`docker run --rm -it busybox sh`

2. Download jormungandr
`JCLI_VERSION="v0.8.10"`
`OS_ARCH="x86_64"`
`mkdir -p /usr/local/bin`
`wget -qO- "https://github.com/input-output-hk/jormungandr/releases/download/${JCLI_VERSION}/jormungandr-${JCLI_VERSION}-${OS_ARCH}-unknown-linux-musl.tar.gz" | tar oxzv 'jcli' -C /usr/local/bin`
`wget -qO- "https://github.com/input-output-hk/jormungandr/releases/download/${JCLI_VERSION}/jormungandr-${JCLI_VERSION}-${OS_ARCH}-unknown-linux-musl.tar.gz" | tar oxzv 'jormungandr' -C /usr/local/bin`

`chmod +x /usr/local/bin/*`

`/usr/local/bin/jcli --version` --> `sh: /usr/local/bin/jcli: not found`

`/usr/local/bin/jormungandr --version` --> `sh: /usr/local/bin/jormungandr: not found`

**Expected behavior**
The binary doesn't seem to be working properly. With the same procedure by modifying the variable JCLI_VERSION, I tried from version v0.8.1 to version v0.8.9 and everything worked perfectly. Would it be possible to tell me my error ? If the problem comes binary, would it be possible to fix it?

Thank you, you are doing a great job!

**Additional context**
-

**Comment by DevAlphaKilo** [comment]
I am also getting a similar error when attempting to use the binaries provided with the armv7 package

/opt/jormungandr $ ./bin/jormungandr --version
-bash: ./bin/jormungandr: cannot execute binary file: Exec format error
/opt/jormungandr $ ./bin/jcli -version
-bash: ./bin/jcli: cannot execute binary file: Exec format error

**Comment by vincenthz** [comment]
the armv7 target (and probably others) are x86-64 binaries instead of arm binaries
```
$ file jormungandr jcli 
jormungandr: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=f67c0cc0625f488ae748044e2b9ca746f51a50b8, with debug_info, not stripped
jcli:        ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=d7379b2f522a44370b48fd4aa0b42d97300eccd2, with debug_info, not stripped
```

**Comment by schmidtp0740** [comment]
I am also getting this error with the following Dockerfile:
```
FROM alpine:3.9.4
LABEL MAINTAINER IOHK
LABEL description="Jormungandr"

ARG VERSION=latest
ARG PREFIX=/app
ARG REST_PORT=8448

ENV ENV_PREFIX=${PREFIX}

# prepare the environment
RUN apk add --no-cache curl jq

# download the release
RUN if [ "${VERSION}" = "latest" ] ; then tag_name="$(curl --silent https://api.github.com/repos/input-output-hk/jormungandr/releases/latest | jq -r .tag_name)" ; else tag_name="v${VERSION}" ; fi && \
    mkdir -p ${ENV_PREFIX}/src && \
    mkdir -p ${ENV_PREFIX}/bin && \
    cd ${ENV_PREFIX}/bin && \
    curl -L "https://github.com/input-output-hk/jormungandr/releases/download/${tag_name}/jormungandr-${tag_name}-x86_64-unknown-linux-musl.tar.gz" | tar xz && \
    cd ${ENV_PREFIX}/src && \
    curl -L "https://github.com/input-output-hk/jormungandr/archive/${tag_name}.tar.gz" | tar xz && \
    cp */scripts/* ${ENV_PREFIX}/bin/ && \
    rm -r ${ENV_PREFIX}/src

ENV PATH=${ENV_PREFIX}/bin:${PATH}
WORKDIR ${ENV_PREFIX}/bin

EXPOSE ${REST_PORT}
```

![image](https://user-images.githubusercontent.com/11967281/74485964-8ce83f80-4e81-11ea-813d-7ce3a87e9219.png)
