### ISSUE TITLE
v0.8.10 jormungandr unable to compile for Alpine Linux

### ISSUE THREAD

**Issue by DavidArayan** [input-output-hk/jormungandr#1787]
**Describe the bug**
Hello,

Having trouble compiling v0.8.10 for Alpine linux using Docker. v0.8.9 and prior had no issues. I've attached a screenshot below on what the error is. The Dockerfile can be found in [https://github.com/CoreGDX/cardano-alpine-base/blob/master/jormungandr-alpine/Dockerfile](https://github.com/CoreGDX/cardano-alpine-base/blob/master/jormungandr-alpine/Dockerfile). 

Any help would be much appreciated! 

Cheers!

**To Reproduce**
1. Change dockerfile and add ```ENV REPO_VERSION="0.8.10"```
2. run ```docker-compose -f live.yml build```

<img width="478" alt="Screen Shot 2020-02-14 at 9 41 23 am" src="https://user-images.githubusercontent.com/7587896/74485870-db441f80-4f0f-11ea-9ab9-e7d1e28b1dfd.png">

**Comment by vincenthz** [comment]
you need to find the actual error. this is the error that tell you that there was a previous error

**Comment by DavidArayan** [comment]
I've attached the full console log. The error is pointing to not being able to compile the ```chain-impl-mockchain``` which I don't know what that is.

The stage when ```chain-impl-mockchain``` starts compiling.

<img width="734" alt="Screen Shot 2020-02-14 at 10 16 10 am" src="https://user-images.githubusercontent.com/7587896/74487284-2e6ba180-4f13-11ea-8282-542eecc55a7a.png">

Full log below including the actual error.

<img width="878" alt="Screen Shot 2020-02-14 at 10 13 00 am" src="https://user-images.githubusercontent.com/7587896/74487164-ea789c80-4f12-11ea-8c9a-7fd03409f78f.png">

**Comment by vincenthz** [comment]
your rust compiler is too old, you need to run the latest stable 1.41 (which you can do with `rustup update` if you use rustup)
