### ISSUE TITLE
jormungandr-v0.8.10-2-x86_64-unknown-linux-gnu.tar.gz -  error while loading shared libraries: libssl.so.1.1

### ISSUE THREAD

**Issue by hemants1** [input-output-hk/jormungandr#1791]
**Describe the bug**

**Mandatory Information**
1. `jcli --full-version` output;

jormungandr-v0.8.10-2-x86_64-unknown-linux-gnu.tar.gz

2. `jormungandr --full-version` output;

jormungandr-v0.8.10-2-x86_64-unknown-linux-gnu.tar.gz
**To Reproduce**

1. wget https://github.com/input-output-hk/jormungandr/releases/download/v0.8.10-2/jormungandr-v0.8.10-2-x86_64-unknown-linux-gnu.tar.gz

2.  tar -xvzf jormungandr-v0.8.10-2-x86_64-unknown-linux-gnu.tar.gz

3. scripts/restartNode.sh
/ada/passive/jcli: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

**Expected behavior**

Expected to start the node without any errors. Appears to be issue with node software. for Linux...!

**Additional context**

**Comment by mzabaluev** [comment]
The OpenSSL shared library is currently a dependency on Linux because the default feature selection of `reqwest` requires it. I have filed #1796 as an item for future implementation.
