### ISSUE TITLE
0.8.10 Bootstrap elapsed time X2

### ISSUE THREAD

**Issue by dmindfuse** [input-output-hk/jormungandr#1795]
Hi
Not sure if anyone else is observing this, but compared 0.8.9 I would say the bootstrap duration has doubled on 0.8.10. I'm on aarch64-unknown-linux-gnu on a Cardano On the Rocks Rock Pi 4 4GB rig on Ubuntu 18.04 Server LTS. 

I get **elapsed times of well over half an hour** and repetitions of:
_WARN initial bootstrap failed, error: PullRequestFailed { source: Error { code: Unknown, source: Status { code: Unknown, message: "connection error: broken pipe" }_

I obtain a current list of available "trusted" pools from adapools.org at every restart. I used to query https://hydra.iohk.io/job/Cardano/iohk-nix/jormungandr-deployment/latest-finished/download/1/ but the peers included in the config.yaml didn't seem to work in the past week anymore so I switched to adapools.org.

Surprisingly I'm very often more successful getting the node up by **NOT** using any trusted_peers at all... very strange.

I have also observed that a max_connections set higher than 128 results in completely unsuccessful bootstrapping within 60 minutes. How to explain that less connections results in better chances of bootstrapping? I'd like to know if I should lower rather than increase connections for optimum performance and faster bootstrapping? 

I'm currently trying to get a successful bootstrap with the attached config.txt.
[config.txt](https://github.com/input-output-hk/jormungandr/files/4208461/config.txt)

Anyone else spot issues with bootstrapping in 0810?

**Comment by boem74** [comment]
https://gist.github.com/michaeljfazio/1fdd90639559f5867401badbaacf831c

Connecting 20 or so succeeded.

**Comment by dmindfuse** [comment]
Closing. Managed to connect in the end.
