### ISSUE TITLE
Bidirectional notification streams

### ISSUE THREAD

**Issue by mzabaluev** [input-output-hk/jormungandr#180]
The current design of gRPC protocol assumes strictly defined server and client roles for the two endpoints in an HTTP/2 connection. For many scenarios this has been sufficient, but to enable p2p propagation without duplicating connections between any two peers, we should be able to reverse the direction of requests and be able to send an announcement message from the endpoint that initially accepted the connection as the server, to the one that connected as the client, over a stream at any point in time.

Check the feasibility of extending the current block subscription mechanism into a fully bidirectional channel that can be used to send node gossip, block announcements, and transaction announcements.

The redesign will bring the gRPC protocol closer to the symmetric network-transport protocol used by the Haskell nodes, harmonizing the software abstractions that should enable use of both protocols.

- [x] Change block and transaction subscription/announcements to work bidirectionally: input-output-hk/rust-cardano#537
- [x] Rework the gossip protocol to use bidirectional streams: input-output-hk/rust-cardano#551
- [x] Support the bidirectional streams and connection state management in jormungandr.

**Comment by NicolasDP** [comment]
@mzabaluev it seems this ticket can be closed
