### ISSUE TITLE
Super slow loading from storage 0.8.10, 0.8.10-2, 0.8.11

### ISSUE THREAD

**Issue by CrazyHolland** [input-output-hk/jormungandr#1810]
**Describe the bug**
On RockPi (aarch) Jormungandr loading from storage super slow
**Mandatory Information**
1. `jcli --full-version` output;
0.8.10, 0.8.10-2, 0.8.11 
2. `jormungandr --full-version` output;
0.8.10, 0.8.10-2, 0.8.11
**To Reproduce**
Install one of the above version on a RockPi4 4GB + ssd

**Expected behavior**
Mega slow loading from storage.

**Additional context**

**Comment by CrazyHolland** [comment]
Not ARM but Aarch

**Comment by laplasz** [comment]
> Mega slow loading from storage.
What does this mean? Long bootstrap phase? what was the experience before this version?

**Comment by CrazyHolland** [comment]
This means, during bootstrapping it needs to load from storage.
On 0.8.9 its done in 20minutes max. No problem in this version on a rockPi during the startup.


On 0.8.10 , 0.8.10-b , 0.8.11 it takes 6 houres minimum to load from same storage during bootstrap.

Back to 0.8.9 and its loading from storage fast again.

Same problem on two different RockPi's.

Thanks for your email and good luck
Hope next version will work ok on rockPi again.

Kind regards,
Alex de Geus




-------- Oorspronkelijk bericht --------
Van: laplasz <notifications@github.com>
Datum: 20-02-20 13:51 (GMT+01:00)
Aan: input-output-hk/jormungandr <jormungandr@noreply.github.com>
Cc: CrazyHolland <alexdegeus@hotmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [input-output-hk/jormungandr] Super slow loading from storage 0.8.10, 0.8.10-2, 0.8.11 (#1810)


Mega slow loading from storage.
What does this mean? Long bootstrap phase? what was the experience before this version?

**Comment by mzabaluev** [comment]
Cc @rinor

**Comment by mzabaluev** [comment]
Some rework has been done to improve performance in this and other instances where storage is processed as a stream: #1802, #1817. Let's see if it improves the loading times.

**Comment by mzabaluev** [comment]
Testing done by @rinor shows that the regression has been fixed. The changes will be in the next release.

**Comment by hodlonaut** [comment]
@mzabaluev I've tried the latest master of jormungandr earlier today, and while the reading from storage issue seems to have been addressed I noticed that my server ran out of memory not long after upgrading both nodes to latest master, as they started using about 25-30% more memory than before... so I reverted back to 0.8.9 for now.

**Comment by mzabaluev** [comment]
> my server ran out of memory not long after upgrading both nodes to latest master, as they started using about 25-30% more memory than before...

@hodlonaut How much memory is that?

**Comment by mzabaluev** [comment]
For reference, the in-memory buffer added to improve loading performance holds 32 blocks maximum (no particular idea yet if it's a good number). Apart from node initialization, it is also used in the explorer and in serving some REST API requests (this is pending rework). If that's too much, we could reduce the buffer size, or implement direct synchronous loading from storage specifically for the bootstrap case which does not really need async.

**Comment by hodlonaut** [comment]
Memory usage of a jormungandr process on my Linux box went up from about 1.3-4 GB to about 1.8-9 GB if I recall correctly.
