### ISSUE TITLE
0.8.11 Compilation Error

### ISSUE THREAD

**Issue by uranuspool** [input-output-hk/jormungandr#1811]
**Describe the bug**

**Mandatory Information**
1. Current version 0.8.9, trying to update to 0.8.11:

`jcli 0.8.9 (heads/v0.8.9-30d20d2e, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
`
2. Current version 0.8.9, trying to update to 0.8.11:

> jormungandr 0.8.9 (heads/v0.8.9-30d20d2e, release, linux [x86_64]) - [rustc 1.41.0 (5e1a79984 2020-01-27)]

**To Reproduce**
1. Clone jormungandr
2. Start compilation:

> cargo install --path jormungandr --force

3. During compilation the following error occurs:

>    Compiling syn v1.0.14
>    Compiling libc v0.2.66
>    Compiling log v0.4.8
>    Compiling proc-macro-nested v0.1.3
>    Compiling futures-sink v0.3.4
>    Compiling futures-core v0.3.4
>    Compiling futures-io v0.3.4
>    Compiling futures-task v0.3.4
>    Compiling pin-utils v0.1.0-alpha.4
>    Compiling arc-swap v0.4.4
>    Compiling untrusted v0.7.0
>    Compiling bytes v0.5.4
>    Compiling pin-project-lite v0.1.4
>    Compiling spin v0.5.2
>    Compiling copyless v0.1.4
>    Compiling fixedbitset v0.1.9
>    Compiling remove_dir_all v0.5.2
>    Compiling multimap v0.4.0
>    Compiling base64 v0.11.0
>    Compiling sha1 v0.6.0
>    Compiling language-tags v0.2.2
>    Compiling slog v2.5.2

> error: `core::slice::<impl [T]>::len` is not yet stable as a const fn
>    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.5.4/src/bytes.rs:130:18
>     |
> 130 |             len: bytes.len(),
>     |                  ^^^^^^^^^^^
> 
>    Compiling tower-service v0.3.0
> error: aborting due to previous error
> 
> error: Could not compile `bytes`.
> warning: build failed, waiting for other jobs to finish...
> error: failed to compile `jormungandr v0.8.11 (/srv/jormungandr/jormungandr)`, intermediate artifacts can be found at `/srv/jormungandr/target`
> 
> Caused by:
>   build failed

Similar behavior occurs when compiling jcli:

> \# cargo install --path jcli --force
>   Installing jcli v0.8.11 (/srv/jormungandr/jcli)
>     Updating crates.io index
>    Compiling structopt v0.2.18
>    Compiling chain-impl-mockchain v0.1.0 (/srv/jormungandr/chain-deps/chain-impl-mockchain)
>    Compiling hyper-tls v0.3.2
>    Compiling reqwest v0.9.24
> error[E0658]: use of unstable library feature 'weak_counts'
>   --> chain-deps/chain-impl-mockchain/src/multiverse.rs:85:48
>    |
> 85 |             GcEntry::Collectable(weak) => weak.strong_count() == 0,
>    |                                                ^^^^^^^^^^^^
>    |
>    = note: for more information, see https://github.com/rust-lang/rust/issues/57977
> 
> error: aborting due to previous error
> 
> For more information about this error, try `rustc --explain E0658`.
> error: Could not compile `chain-impl-mockchain`.
> warning: build failed, waiting for other jobs to finish...
> error: failed to compile `jcli v0.8.11 (/srv/jormungandr/jcli)`, intermediate artifacts can be found at `/srv/jormungandr/target`
> 
> Caused by:
>   build failed

**Expected behavior**
Both jormungandr and jcli should compile without any problems.

**Comment by vincenthz** [comment]
your stable rust compiler is too old, update to 1.41
