### ISSUE TITLE
New type of stucking node

### ISSUE THREAD

**Issue by cardanians** [input-output-hk/jormungandr#1862]
- 0.8.12
- a few hours stucked with this issue (required restart for solving)
- leader node

![obrazek](https://user-images.githubusercontent.com/58650764/75415842-10e40200-592d-11ea-9425-122310fa5246.png)

**Comment by cardanians** [comment]
second node was stucked too, but with diferent issue (required restart too)

![obrazek](https://user-images.githubusercontent.com/58650764/75415975-7801b680-592d-11ea-8fdc-96e8ad22abc5.png)

**Comment by clouduada** [comment]
Me too but restart didn't fix it
-0.8.13

**Comment by dmindfuse** [comment]
Neither 0.8.12 nor 0.8.13 (built from source on aarch64-unknown-linux) are performing as well as 0.8.11 was. I have serious issues with "WARN Blockchain is not moving up" directly after bootstrapping. It takes random amounts of time to receive blocks and then it'll just repeat that error. I suspect it is related to this topic, if it isn't kindly move it to a different topic or delete it.

**Comment by peteroravec** [comment]
Same issues, tried multiple times... also used peers from https://adapools.org/peers
Restarting doesnt fix this
<img width="1442" alt="Screenshot 2020-02-29 09 47 18" src="https://user-images.githubusercontent.com/342313/75604405-a5d72e80-5ad8-11ea-9cd3-dede9fa44c0b.png">

**Comment by clouduada** [comment]
Tried my configuration file see what happens I was stuck to and now is working fine...Make sure you change your IP and the STORAGE parameter. Cheers 


log:
  - format: plain
    level: info
    output: stderr
http_fetch_block0_service:
  - https://bltn.2ndlayer.eu/bootstrap/
p2p:
  listen_address: "/ip4/0.0.0.0/tcp/3000"
  public_address: "/ip4/YOUR_IP/tcp/3000"
  max_connections: 2048
  max_unreachable_nodes_to_connect_per_event: 10
  gossip_interval: 10s
  topics_of_interest:
    blocks: high
    messages: high
  policy:
    quarantine_duration: 3min
  trusted_peers:
    - address: "/ip4/13.56.0.226/tcp/3000"
      id: 7ddf203c86a012e8863ef19d96aabba23d2445c492d86267
    - address: "/ip4/54.183.149.167/tcp/3000"
      id: df02383863ae5e14fea5d51a092585da34e689a73f704613
    - address: "/ip4/52.9.77.197/tcp/3000"
      id: fcdf302895236d012635052725a0cdfc2e8ee394a1935b63
    - address: "/ip4/18.177.78.96/tcp/3000"
      id: fc89bff08ec4e054b4f03106f5312834abdf2fcb444610e9
    - address: "/ip4/3.115.154.161/tcp/3000"
      id: 35bead7d45b3b8bda5e74aa12126d871069e7617b7f4fe62
    - address: "/ip4/18.182.115.51/tcp/3000"
      id: 8529e334a39a5b6033b698be2040b1089d8f67e0102e2575
    - address: "/ip4/18.184.35.137/tcp/3000"
      id: 06aa98b0ab6589f464d08911717115ef354161f0dc727858
    - address: "/ip4/3.125.31.84/tcp/3000"
      id: 8f9ff09765684199b351d520defac463b1282a63d3cc99ca
    - address: "/ip4/3.125.183.71/tcp/3000"
      id: 9d15a9e2f1336c7acda8ced34e929f697dc24ea0910c3e67
    - address: "/ip4/52.9.132.248/tcp/3000"
      id: 671a9e7a5c739532668511bea823f0f5c5557c99b813456c
    - address: "/ip4/52.8.15.52/tcp/3000"
      id: 18bf81a75e5b15a49b843a66f61602e14d4261fb5595b5f5
    - address: "/ip4/13.114.196.228/tcp/3000"
      id: 7e1020c2e2107a849a8353876d047085f475c9bc646e42e9
    - address: "/ip4/13.112.181.42/tcp/3000"
      id: 52762c49a84699d43c96fdfe6de18079fb2512077d6aa5bc
    - address: "/ip4/3.125.75.156/tcp/3000"
      id: 22fb117f9f72f38b21bca5c0f069766c0d4327925d967791
    - address: "/ip4/52.28.91.178/tcp/3000"
      id: 23b3ca09c644fe8098f64c24d75d9f79c8e058642e63a28c
    - address: "/ip4/3.124.116.145/tcp/3000"
      id: 99cb10f53185fbef110472d45a36082905ee12df8a049b74
storage: ./storage/
explorer:
  enabled: false
rest:
  listen: 127.0.0.1:3100

**Comment by clouduada** [comment]
Also make a second node just for test that way you don't have to update until you know that every thing is fine.

**Comment by cardanoinvest** [comment]
Also getting stuck. 0.8.13 . Removing storage helps for a few hours.
