### ISSUE TITLE
rust compile issues - rustc 1.41.1 (f3e1a954d 2020-02-24)

### ISSUE THREAD

**Issue by kiwipool** [input-output-hk/jormungandr#1879]
As discussed via Telegram (Nicolas) , Rust is throwing up compile errors and failing. Errors have occurred compiling jormungandr 0.8.13, jcli 0.8.13 and also jormungandr-0.8.9-stable-alpha6 (Fazio fork).

There appears to be a recent update to rust causing these issues as these compile errors were not happening a couple of days ago. Assumption is "rust update" has broken something . . .

**Versions:**
rustc 1.41.1 (f3e1a954d 2020-02-24)
jormungandr 0.8.13-01acf32
jcli 0.8.13-01acf32

**Steps used to compile jormungandr & jcli:**

  rustup install stable
  rustup default stable
  rustup update  
  git clone --recurse-submodules https://github.com/input-output-hk/jormungandr
  cd jormungandr
  cargo clean
  git checkout tags/v0.8.13							
  git submodule update --init --recursive
  git pull origin master
  cargo install --force --path jormungandr
  cargo install --force --path jcli

See attached output showing failure and error messages

[rust compile issues - 04032020.txt](https://github.com/input-output-hk/jormungandr/files/4286222/rust.compile.issues.-.04032020.txt)

**Comment by kiwipool** [comment]
Just tested on another server that has an older version of rust (which I didn't update before compiling). 

rustc 1.41.0 (5e1a79984 2020-01-27)

Fails with same error as above . . .

**Comment by NicolasDP** [comment]
Thanks. we managed to reproduce the issue. Please try `cargo install --force --path jormungandr --locked`. It seems that the `install` command` does not use the `Cargo.lock`.

**Comment by kiwipool** [comment]
Thanks Nicolas.

Still failing for me - see attached.

[rust compile issues - updated with locked - 04032020.txt](https://github.com/input-output-hk/jormungandr/files/4286597/rust.compile.issues.-.updated.with.locked.-.04032020.txt)

Two rust error codes now - E0432, E0599

**Install steps:**

rustup install stable
rustup default stable
rustup update
git clone --recurse-submodules https://github.com/input-output-hk/jormungandr
cd jormungandr
cargo clean
git checkout tags/v0.8.13
git submodule update --init --recursive
git pull origin master
cargo install --force --path jormungandr --locked

**Comment by dkijania** [comment]
@kiwipool 

What i see is thath original compilation issue: `error[E0277]: the trait bound `cid::Error: std::error::Error` is not satisfied` in multiaddr was fixed by adding `--locked` flag. However, in second compilation attempt i can observe that two commits are missing from deps:

https://github.com/input-output-hk/jormungandr/pull/1853/files
https://github.com/input-output-hk/jormungandr/pull/1797/files

**Comment by kiwipool** [comment]
> 
> 
> @kiwipool
> 
> What i see is that original compilation issue:
> `` error[E0277]: the trait bound `cid::Error: std::error::Error is not satisfied `` in multiaddr was fixed by adding `--locked` flag. However, in second compilation attempt i can observe that two commits are missing from deps:
> 
> #1853
> #1797
> 
> Which leads to conclusion, that you have some mismatch between jormungandr and deps

Hey Dariusz

Are you referring to 'local' deps on my server such as build-essential, libssl-dev, etc? Or rust deps?

I have 3 production and one test server and I have the same compile issue on all of them without having changed anything of note on any of the servers. Everything has compiled AOK previously

**Comment by NicolasDP** [comment]
No he meant deps within the sources. These errors seems related to some we saw in the past when we updated dependencies and they were fixed in the linked pull requests #1853 #1797 . what version is actually being compiled.

**Comment by rinor** [comment]
> 
> **Install steps:**
> 
> rustup install stable
> rustup default stable
> rustup update
> git clone --recurse-submodules https://github.com/input-output-hk/jormungandr
> cd jormungandr
> cargo clean
> git checkout tags/v0.8.13
> git submodule update --init --recursive
> git pull origin master <----------------------------------- this is the problem
> cargo install --force --path jormungandr --locked

@kiwipool you are mixing master code with submodules from v0.8.13. If you want to build v0.8.13 remove `git pull origin master` from your flow since it is wrong.

**Comment by kiwipool** [comment]
> 
> 
> > **Install steps:**
> > rustup install stable
> > rustup default stable
> > rustup update
> > git clone --recurse-submodules https://github.com/input-output-hk/jormungandr
> > cd jormungandr
> > cargo clean
> > git checkout tags/v0.8.13
> > git submodule update --init --recursive
> > git pull origin master <----------------------------------- this is the problem
> > cargo install --force --path jormungandr --locked
> 
> @kiwipool you are mixing master code with submodules from v0.8.13. If you want to build v0.8.13 remove `git pull origin master` from your flow since it is wrong.

Thanks for your suggestion. I'm attempting to build the latest version of master which is why I'm using "git pull origin master". I've had no apparent issues with the above build process until the past few days

**Comment by kiwipool** [comment]
> 
> 
> No he meant deps within the sources. These errors seems related to some we saw in the past when we updated dependencies and they were fixed in the linked pull requests #1853 #1797 . what version is actually being compiled.

This happens when compiling the latest master (git pull origin master) as rinor alluded to above

**Comment by rinor** [comment]
> Thanks for your suggestion. I'm attempting to build the latest version of master which is why I'm using "git pull origin master". I've had no apparent issues with the above build process until the past few days

in that case the flow for master would be:
- rustup install stable
- rustup default stable
- rustup update
- git clone --recurse-submodules https://github.com/input-output-hk/jormungandr
- cd jormungandr
- git submodule update --init --recursive
- cargo install --force --path jormungandr --locked

everytime you switch branch or tag after the initial clone is a good practice to rerun `git submodule update --init --recursive` just to be safe

ex:
```
git pull origin master
git submodule update --init --recursive
cargo install --force --path jormungandr --locked
```

or:
```
git checkout tags/v0.8.13
git submodule update --init --recursive
cargo install --force --path jormungandr --locked
```

**Comment by kiwipool** [comment]
> 
> 
> > Thanks for your suggestion. I'm attempting to build the latest version of master which is why I'm using "git pull origin master". I've had no apparent issues with the above build process until the past few days
> 
> in that case the flow for master would be:
> 
>     * rustup install stable
> 
>     * rustup default stable
> 
>     * rustup update
> 
>     * git clone --recurse-submodules https://github.com/input-output-hk/jormungandr
> 
>     * cd jormungandr
> 
>     * git submodule update --init --recursive
> 
>     * cargo install --force --path jormungandr --locked
> 
> 
> everytime you switch branch or tag after the initial clone is a good practice to rerun `git submodule update --init --recursive` just to be safe
> 
> ex:
> 
> ```
> git pull origin master
> git submodule update --init --recursive
> cargo install --force --path jormungandr --locked
> ```
> 
> or:
> 
> ```
> git checkout tags/v0.8.13
> git submodule update --init --recursive
> cargo install --force --path jormungandr --locked
> ```

Thanks @rinor 

Thanks also @dkijania @NicolasDP
