### ISSUE TITLE
put parent hash for created block in leaders logs

### ISSUE THREAD

**Issue by laplasz** [input-output-hk/jormungandr#1881]
**Is your feature request related to a problem/context ? Please describe if applicable.**
Right now a printout of a block creation looks like this:
```
  {
    "created_at_time": "2020-03-03T20:16:47.470029961+00:00",
    "scheduled_at_time": "2020-03-04T11:17:13+00:00",
    "scheduled_at_date": "81.28908",
    "wake_at_time": "2020-03-04T11:17:13.000963316+00:00",
    "finished_at_time": "2020-03-04T11:17:13.003154792+00:00",
    "status": {
      "Block": {
        "block": "f9fcff7c08b5ee604b3d47ea8898ddf5852493b02ce6173d33d43c7de02b87e6",
        "chain_length": 268757
      }
    },
    "enclave_leader_id": 1
  }
```
when the block has not validated it would be good to see that what was the parent hash it was built on. Right now this information can be found only in the node log with INFO log level.
**Describe the solution you'd like**
So the printout with the new field would look like this:
```
  {
    "created_at_time": "2020-03-03T20:16:47.470029961+00:00",
    "scheduled_at_time": "2020-03-04T11:17:13+00:00",
    "scheduled_at_date": "81.28908",
    "wake_at_time": "2020-03-04T11:17:13.000963316+00:00",
    "finished_at_time": "2020-03-04T11:17:13.003154792+00:00",
    "status": {
      "Block": {
        "block": "f9fcff7c08b5ee604b3d47ea8898ddf5852493b02ce6173d33d43c7de02b87e6",
        "parent": "31f51106381003b3cbf9cebdc1eeb4cf9dfd4d069fb6a837f8bc0eb172ea96dc"
        "chain_length": 268757
      }
    },
    "enclave_leader_id": 1
  }
```
in this way a it would be easier to troubleshoot a block creation. Thanks,

**Comment by NicolasDP** [comment]
That's a good idea.

it's really a matter of adding a new line here: https://github.com/input-output-hk/jormungandr/blob/12f8986cd03da0dd18da5915be9166ba0d4680f4/jormungandr-lib/src/interfaces/leadership_log.rs#L16-L20

and updating the logger there: https://github.com/input-output-hk/jormungandr/blob/12f8986cd03da0dd18da5915be9166ba0d4680f4/jormungandr/src/leadership/process.rs#L505-L508

**Comment by AndrewWestberg** [comment]
This would prevent us from making an extra api call to get the block and parsing out its parent before sending to pooltool. 👍

**Comment by laplasz** [comment]
@AndrewWestberg which API call give you such information?

**Comment by AndrewWestberg** [comment]
@laplasz https://github.com/papacarp/pooltool.io/blob/master/sendmytip.sh#L95,L97

**Comment by laplasz** [comment]
ok, i did not know what v0/block/ API provide
`jcli rest v0 block <blockhash> get -h <url> | cut -c 105-168` gives back the parent hash, even for a not validated block
so this request became a nice to have feature
