### ISSUE TITLE
node can not establish connection with more than 200 peers

### ISSUE THREAD

**Issue by laplasz** [input-output-hk/jormungandr#1889]
**Describe the bug**
node can not make more the ~200 connections

Diagnostic:

    $ curl -s <rest_url>/api/v0/diagnostic
    {"open_files_limit":32768,"cpu_usage_limit":18446744073709551615}
network stat:

    $>curl -s <rest_url>api/v0/network/stats | jq -r ' . | length'
    446
node stats:

    peerAvailableCnt: 9994
    peerQuarantinedCnt: 69
    peerTotalCnt: 10240
    peerUnreachableCnt: 177
    uptime: 14793
node config:

    "gossip_interval": "5s",
    "listen_address": "/ip4/0.0.0.0/tcp/8399",
    "public_address": "/ip4/<public_ip>/tcp/8399",
    "max_connections": 1024,
version: jormungandr 0.8.13-241b3a59

1. number of **unique nodes** my node attempt to **connect**: 2817
`grep "INFO connecting to peer" <node_log> | awk -F',' '{print $3}' | sort | uniq -c | wc -l`
2. number of **connection closed**: 3277
`grep "INFO connection closed" <node_log> | wc -l`
3. number of **accepted connection**: 3509
`grep "INFO accepted connection" <node_log> | wc -l`
4. number of **disconnecting clients**: 286

current connection stats for my node:

     $>netstat -tn | tail -n +3 | awk "{ print \$6 }" | sort | uniq -c | sort -n
      1 SYN_RECV
      1 TIME_WAIT
     10 FIN_WAIT1
    178 ESTABLISHED

**Expected behavior**
The node can establish connection with more than 200 peers to sync with block height better.

**Comment by rinor** [comment]
@laplasz if you are not using `max_client_connections` try to set it to a specific value since by default is set to 8. Check if it helps. Thank you.

**Comment by laplasz** [comment]
once I set

    "max_connections": 768,
    "max_client_connections": 768,

immediately started to grow.. 
    
      6 SYN_RECV
     12 TIME_WAIT
     14 SYN_SENT
     69 CLOSE_WAIT
    625 ESTABLISHED
node stats:

```
peerAvailableCnt: 1680
peerQuarantinedCnt: 1129
peerTotalCnt: 2810
peerUnreachableCnt: 1
state: Running
txRecvCnt: 0
uptime: 1018
```
thanks for the big help - I hope that this will improve the block reaction success rate.
