### ISSUE TITLE
error[E0277]: the trait bound `cid::Error: std::error::Error` is not satisfied

### ISSUE THREAD

**Issue by A-Caccese** [input-output-hk/jormungandr#1891]
**Describe the bug**
Hi, I'm having E0277 when compiling `multiaddr v0.3.1` on Ubuntu 18.04.4 LTS.

**To Reproduce**
`cargo install --path jormungandr --force`

**Comment by rinor** [comment]
@A-Caccese  try `cargo install --path jormungandr --force --locked`

**Comment by A-Caccese** [comment]
> @A-Caccese try `cargo install --path jormungandr --force --locked`

Done, I had the same error.

**Comment by NicolasDP** [comment]
duplicate of #1879
