### ISSUE TITLE
Please investigate a potential vector to a Sybil attack

### ISSUE THREAD

**Issue by stakehodlers** [input-output-hk/jormungandr#1899]
**Describe the bug**
When creating a new pool to lower my pool fees, two pools were created instead of one.  Please see the description in https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/pull/2113 for details.  This may or may not be a problem, and it may be process/code/both, but wanted to get a knowledgable set of eyes on it to be sure.  Hopefully it's nothing...

**Mandatory Information**
Not sure if this matters in this case, but here it is anyway...

1. `jcli --full-version` output;
jcli 0.8.9 (v0.8.9-stable-alpha6-branch-46df05c7, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

2. `jormungandr --full-version` output;
jormungandr 0.8.9 (v0.8.9-stable-alpha6-branch-46df05c7, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**To Reproduce**
Please see detailed steps in:
https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/pull/2113

**Expected behavior**
When creating a new stake pool, one, and only one, should be created and associated with a unique pledge address.

**Additional context**
None.

**Comment by rdlrt** [comment]
Not relevant to jormungandr repo, replied on the mentioned issue link
