### ISSUE TITLE
rename (and add an alias to it for compat) this value parameter to `max_inbound_connections`.

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/jormungandr#1921]
we should rename (and add an alias to it for compat) this value parameter to `max_inbound_connections`.

_Originally posted by @NicolasDP in https://github.com/input-output-hk/jormungandr/pull/1917#issuecomment-599411961_

**Comment by NicolasDP** [comment]
This is creating confusion as to what the parameter does

**Comment by eugene-babichenko** [comment]
@NicolasDP should we close this?
