### ISSUE TITLE
release: create optimised x86-64 binaries release

### ISSUE THREAD

**Issue by vincenthz** [input-output-hk/jormungandr#1924]
It would be a good idea to provide extra x86-64 binaries `-simd` along the normal one which would be compiled with:

```
RUSTFLAGS="-C target_cpu=broadwell" cargo build --release
```

**Comment by danielSanchezQ** [comment]
Just for Windows @vincenthz ?

**Comment by vincenthz** [comment]
no, it would be convenient to have them for every x86-64 releases (linux, windows, macos)

**Comment by danielSanchezQ** [comment]
Perfect just wanted to confirm. Thanks!

**Comment by danielSanchezQ** [comment]
Done in #1955
