### ISSUE TITLE
Since upgrading to 0.8.14-9ca427ef+, node gets stuck. 

### ISSUE THREAD

**Issue by diegueins680** [input-output-hk/jormungandr#1927]
**Describe the bug**
Since I updated to 0.8.14-9ca427ef+, my node's block height seems to get stuck. The CPU usage diminishes. 

**Mandatory Information**
1. `jcli --full-version` output;
jcli 0.8.14 (HEAD-9ca427ef+, release, linux [x86_64]) - [rustc 1.43.0-nightly (54b7d21f5 2020-03-12)]

2. `jormungandr --full-version` output;
jormungandr 0.8.14 (HEAD-9ca427ef+, release, linux [x86_64]) - [rustc 1.43.0-nightly (54b7d21f5 2020-03-12)]

**To Reproduce**
1. Build the latest jormungandr and jcli on NixOs
2. Start the node
3. After a few hours, notice the node's block height lags behind the network. 

**Expected behavior**
The node should be up to date with the rest of the network.

**Comment by eugene-babichenko** [comment]
Which version were you using before? There is similar report reproducible with 0.8.13 and later versions https://github.com/input-output-hk/jormungandr/issues/1887.

**Comment by diegueins680** [comment]
> Which version were you using before? There is similar report reproducible with 0.8.13 and later versions #1887.

I seemed to be fine on 0.8.13. Now I need to restart my node once every few hours, as I notice it falling behind the network.

**Comment by diegueins680** [comment]
Since I upgraded to 0.8.15, my node has been running fine, so I'm closing this issue.
