### ISSUE TITLE
Node created a strange block on slot 97.060 on March 19

### ISSUE THREAD

**Issue by rickymac68** [input-output-hk/jormungandr#1942]
**Describe the bug**
Node DIGI2 created a strange block causing network stall for a few minutes

**Mandatory Information**
1. jcli 0.8.15 19f8eb49
2. jormungandr 0.8.15 19f8eb49

**To Reproduce**
Unknown

**Expected behavior**

**Additional context**
Early in the day on March 19 around 10:00 EST I switch DIGI2 from public IP 68.X.X.X to 173.X.X.X. Then later in the day around 13:00 EST my tech set the system time 1 hour into the future from current time as the nodes displyed time did not 'spring forward'. A few hours later a strange block was created that caused network problems. Logs attached.
[DIGI2loghq.txt](https://github.com/input-output-hk/jormungandr/files/4357626/DIGI2loghq.txt)
[DIGI2loghp.txt](https://github.com/input-output-hk/jormungandr/files/4357627/DIGI2loghp.txt)
![photo_2020-03-19_15-20-59](https://user-images.githubusercontent.com/25856278/77130305-cc302000-6a2d-11ea-8598-d815f6f54d67.jpg)

**Comment by onyxstakepool** [comment]
There were two future blocks minted 97.5961 and 97.6060 in short succession. As a result my whole node cluster running v0.8.14 lost sync at the same time. Similar behavior was also reported by other members of the community.

Mar 19 21:32:01.266 INFO update current branch tip: a4ac510a-0004f2d6-97.4146 -> aae2156d-0004f2d7-97.4152, task: block
Mar 19 21:32:19.972 INFO update current branch tip: aae2156d-0004f2d7-97.4152 -> d162635a-0004f2d8-97.5961, task: block
Mar 19 21:35:35.277 INFO switching branch from d162635a-0004f2d8-97.5961 to 43500962-0004f2d9-97.4259, task: block
Mar 19 21:35:38.052 INFO update current branch tip: 43500962-0004f2d9-97.4259 -> 6f1398e3-0004f2da-97.6060, task: block

**Comment by NicolasDP** [comment]
Two things to look into regarding this:

* leadership scheduler
* new ref processing

There are counter measures to prevent this to happen. If it does not anymore then need to make sure there is a test to prevent this from happening again as this is regression from previous version.

**Comment by NicolasDP** [comment]
We have this line to prevent blocks in the future to make it on the tip: https://github.com/input-output-hk/jormungandr/blob/3b006fcf8483984c53edb34f2352dd827c17b9bb/jormungandr/src/blockchain/chain_selection.rs#L22

**Comment by NicolasDP** [comment]
This has been reported on latest release 0.8.17

**Comment by gufmar** [comment]
2020-04-10 LastBlockDate progress on 6 nodes (one flat-lined)

![2020-04-10_10h48_33](https://user-images.githubusercontent.com/13198220/78977863-272ed180-7b19-11ea-8e32-8dc74748f2a5.png)

**Comment by NicolasDP** [comment]
okay, we have found the problem, the hint was in @rickymac68 's logs:

```Mar 19 17:35:37.011 INFO update current branch tip: 43500962-0004f2d9-97.4259 -> 6f1398e3-0004f2da-97.6060, date: 97.6060, parent: 4350096258c1b9fd74380a757ac019d433459700ec3fd8643a78a8475f2621f8, hash: 6f1398e3cf450db1826008c5fd0363374f7599140414096a56dcfc718ac4979a, task: block
```

The chain selection was not properly applied if the blocks where a _"natural"_ follower of the blockchain tip.: https://github.com/input-output-hk/jormungandr/blob/3b006fcf8483984c53edb34f2352dd827c17b9bb/jormungandr/src/blockchain/process.rs#L300-L314
