### ISSUE TITLE
Where Can I Find The Genesis File?

### ISSUE THREAD

**Issue by gmanroney** [input-output-hk/jormungandr#201]
**Describe the bug**
I can see an example of the node configuration file
I cannot see the genesis file. Where can I find it or create it?

**To Reproduce**
Configuration file in readme but no genesis file.
Can see config YAML file and genesis JSON file in demo folder but not sure how those are used if we want to run up a node. 

**Expected behavior**
Can run node with these two files as arguments

**Additional context**
Nope

**Comment by gufmar** [comment]
See
https://github.com/input-output-hk/jormungandr/blob/master/doc/starting_bft_blockchain.md#example-of-genesis-configuration-file
and
https://github.com/input-output-hk/jormungandr/blob/master/doc/genesis_file.md

**Comment by gmanroney** [comment]
ok will check it out, tnx

**Comment by gmanroney** [comment]
Closed

**Comment by gmanroney** [comment]
Thank you
