### ISSUE TITLE
Getting error "secret config unspecified" when running node

### ISSUE THREAD

**Issue by gmanroney** [input-output-hk/jormungandr#203]
Generate a private key
----------------------
jormungandr generate-priv-key --type=Ed25519 > public.key

Generate a public key
---------------------
cat public.key | jormungandr generate-pub-key > private.key

Creating genesis.config
-----------------------
echo "start_time: 1550822014
slot_duration: 15
epoch_stability_depth: 2600
initial_utxos: []
obft_leaders:
  - ed25519extended_public1k3wjgdcdcn23k6dwr0cyh88ad7a4ayenyxaherfazwy363pyy8wqppn7j3
  - ed25519extended_public13talprd9grgaqzs42mkm0x2xek5wf9mdf0eefdy8a6dk5grka2gstrp3en
" > ../config/genesis.conf

Creating node config
--------------------
echo "storage: "/opt/cardanorust/tmp/storage"
logger:
  verbosity: 1
  format: json
rest:
  listen: "127.0.0.1:8443"
  pkcs12: "example.p12"
  prefix: "api"
peer_2_peer:
  trusted_peers: []
  public_access: "/ip4/127.0.0.1/tcp/8080"
  topics_of_interests:
    transactions: low
    blocks: normal
" > ../config/node.config

Running the node
-----------------
./jormungandr  start --genesis-config ../config/genesis.config --config ../config/node.config

Outcome
-------
secret config unspecified

Help Needed
-----------
Not sure how to reference public and private keys or what the error means. Tried to use -v (verbose) but did not get any extra data to help.

**Comment by robkorn** [comment]
You need to generate _Ed25519Extended_ keys rather than _Ed25519_.

```
jormungandr generate-priv-key --type=Ed25519Extended > private.key 

cat private.key | jormungandr generate-pub-key > public.key
```

**Comment by NicolasDP** [comment]
This has been fixed
