### ISSUE TITLE
Message("missing field `address_discrimination`)

### ISSUE THREAD

**Issue by gmanroney** [input-output-hk/jormungandr#204]
$ export RUST_BACKTRACE=1
 $ ./jormungandr start --genesis-config ../config/genesis3.yaml --config ../config/node.config  --secret ../config/private.key 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Message("missing field `address_discrimination`", Some(Pos { marker: Marker { index: 10, line: 1, col: 10 }, path: "." }))', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/macros.rs:16
   9: <core::result::Result<T, E>>::unwrap
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/result.rs:798
  10: jormungandr::start
             at src/main.rs:138
  11: jormungandr::main
             at src/main.rs:309
  12: std::rt::lang_start::{{closure}}
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  13: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  14: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:92
  15: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  16: std::rt::lang_start
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  17: main
  18: __libc_start_main
  19: _start

**Comment by gmanroney** [comment]
I am not familiar with address discrimination so could do with some help please

**Comment by NicolasDP** [comment]
Thanks for reporting this to us. We have changed a lot the way we start the node in the last past days. Can you try again with this?

**Comment by gufmar** [comment]
@NicolasDP 
Can you please provide an updated configuration file template? after the mentioned changes, the existing configuration file ends in a
```
Error in the overall configuration of the node
Cannot read the node configuration file
```

**Comment by NicolasDP** [comment]
Arf, the source of the error didn't display. Once #235 is merged it will display the error message. My guess is that the file either not readable (wrong file path ?) or it is not a valid block 0.

There is documentation regarding the genesis file [here](https://github.com/input-output-hk/jormungandr/blob/master/doc/genesis_file.md) and how to create the `block0` [there](https://github.com/input-output-hk/jormungandr/blob/master/doc/starting_bft_blockchain.md#creating-the-block-0).

The command line parameter `--genesis-block <FILE | BLOCK HASH>` takes as a parameter either:

* file path of the block0 (the genesis file converted into a block);
* the hash of the block 0 (only works if you have already started the node with a block0 file);

**Comment by gufmar** [comment]
Sorry my mistake
with #235 the error message was more clear

```
Error in the overall configuration of the node
Error while parsing the node configuration file: while parsing a quoted scalar, found unknown escape character at line 1 column 10
```
And also sorry for having hijacked this issue. (@gmanroney still an issue or can it be closed?)

**Comment by vincenthz** [comment]
it's not very clear yet, but I would imagine it's due to the recent change of `consensus` that now takes a string `bft | genesis`

**Comment by NicolasDP** [comment]
This is fixed now
