### ISSUE TITLE
Reward dumps don't include pools and accounts anymore

### ISSUE THREAD

**Issue by manveru** [input-output-hk/jormungandr#2045]
**Describe the bug**

The CSV reward dumps are still written, but don't include any lines of type `pool` or `address` anymore.

**Mandatory Information**
1. `jcli 0.8.17 (nix-build-09b99a8, debug, linux [x86_64]) - [rustc 1.41.0 (5e1a79984 2020-01-27)]`
2. `jormungandr 0.8.17 (nix-build-09b99a8, debug, linux [x86_64]) - [rustc 1.41.0 (5e1a79984 2020-01-27)]`

**To Reproduce**
1. Set `JORMUNGANDR_REWARD_DUMP_DIRECTORY`
2. See that CSVs are missing info

**Expected behavior**
Get the rewards info for pools and addresses.

**Additional context**
This seems to be happening since at least 0.8.14.

So far we kept running a node on 0.8.13 to still get this information, but wanted to upgrade it and even in 0.8.17 this information is missing.

**Comment by NicolasDP** [comment]
use `--rewards-report-all` this was documented in the release note actually: https://github.com/input-output-hk/jormungandr/releases/tag/v0.8.14

**Comment by manveru** [comment]
Can confirm this works now, thanks :)

**Comment by NicolasDP** [comment]
thanks @manveru
