### ISSUE TITLE
REST API Swagger documentation points to the wrong URL for specification file

### ISSUE THREAD

**Issue by ashisherc** [input-output-hk/jormungandr#2073]
**Describe the bug**
The documentation for Jormungandr rest API available here, https://input-output-hk.github.io/jormungandr/quickstart/03_rest_api.html, this page has link to the swagger rest API documentation which points to wrong URL due to restricting of this commit
https://github.com/input-output-hk/jormungandr/commit/dec557ab4c87800d6f2fe8af5afcc1235909c326

**Mandatory Information**
// Not a bug report related to Jormungandr

**To Reproduce**
1. Go to https://input-output-hk.github.io/jormungandr/quickstart/03_rest_api.html
2. Click on To see the whole Node API documentation, **click here**
3. See error,
Errors
Fetch errorNot Found https://raw.githubusercontent.com/input-output-hk/jormungandr/master/doc/openapi.yaml

**Expected behavior**
Should display REST API documentation swagger specs

**Additional context**
Changing URL to https://editor.swagger.io/?url=https://raw.githubusercontent.com/input-output-hk/jormungandr/master/doc/api/v0.yaml

Fixes the issue, which is the new destination for spec file

**Comment by rinor** [comment]
@ashisherc thank you for the report. It will be fixed in https://github.com/input-output-hk/jormungandr/pull/2071
