### ISSUE TITLE
Revert `type_length_limit` change when rustc 1.43 is out

### ISSUE THREAD

**Issue by eugene-babichenko** [input-output-hk/jormungandr#2094]
rustc 1.43-beta.5 includes improvements to type operations which makes [this change](https://github.com/input-output-hk/jormungandr/pull/2083/commits/c30347279c807e6d0fb9ed279fd40bf483f920eb#diff-bab1167aa3424ac8c5610b44ab8a1bb3R3) to `type_length_limit` unnecessary. Once we build on 1.43 we can change `type_length_limit`back to 10000000.

_Original comment: https://github.com/input-output-hk/jormungandr/pull/2083#discussion_r412144776_

**Comment by tstdin** [comment]
Rust 1.43 is out: https://blog.rust-lang.org/2020/04/23/Rust-1.43.0.html
