### ISSUE TITLE
Build broken on FreeBSD

### ISSUE THREAD

**Issue by fruicz** [input-output-hk/jormungandr#2126]
```
error[E0425]: cannot find value `CLOCK_BOOTTIME` in crate `libc`
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/sysinfo-0.14.1/src/linux/system.rs:121:43
    |
121 |     if unsafe { libc::clock_gettime(libc::CLOCK_BOOTTIME, &mut up) } == 0 {
    |                                           ^^^^^^^^^^^^^^ help: a constant with a similar name exists: `CLOCK_REALTIME`
```
It looks like you added a dependency that doesn't support it. If FreeBSD is being dropped forever then perhaps make a note about this in the readme. This is a shame though because it was working well for me before.

**Comment by eugene-babichenko** [comment]
Are you able to build this pull request on your version of FreeBSD? https://github.com/input-output-hk/jormungandr/pull/2164
