### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at 'missing scheme'

### ISSUE THREAD

**Issue by cardanoinvest** [input-output-hk/jormungandr#2169]
**Describe the bug**
After updating to 0.8.19 on CentOS and starting Jormungandr I am getting this error.

thread 'tokio-runtime-worker' panicked at 'missing scheme', /home/***/.cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.2.2/src/filters/cors.rs:614:24
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_failed
             at src/libcore/option.rs:1203
  14: <&str as warp::filters::cors::internal::IntoOrigin>::into_origin
  15: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  16: warp::filters::cors::Builder::allow_origins
  17: jormungandr::rest::start_rest_server::{{closure}}
  18: <std::future::GenFuture<T> as core::future::future::Future>::poll
  19: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  20: std::panicking::try::do_call
  21: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  22: tokio::runtime::task::harness::Harness<T,S>::poll
  23: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
  24: std::thread::local::LocalKey<T>::with
  25: tokio::runtime::thread_pool::worker::Context::run_task
  26: tokio::runtime::thread_pool::worker::Context::run
  27: tokio::macros::scoped_tls::ScopedKey<T>::set
  28: tokio::runtime::thread_pool::worker::run
  29: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  30: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  31: std::panicking::try::do_call
  32: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  33: tokio::runtime::task::harness::Harness<T,S>::poll
  34: tokio::runtime::blocking::pool::Inner::run
  35: tokio::runtime::context::enter
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Mandatory Information**
1. jcli 0.8.19 (HEAD-776347c+, release, linux [x86_64]) - [rustc 1.43.0 (4fb7144ed 2020-04-20)]
2. jormungandr 0.8.19 (HEAD-776347c+, release, linux [x86_64]) - [rustc 1.43.0 (4fb7144ed 2020-04-20)]

**To Reproduce**
1. Install 0.8.19
2. Run jormungandr --genesis-block-hash 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676 --config node-config.yaml --secret node_secret.yaml
3. Error - thread 'tokio-runtime-worker' panicked at 'missing scheme', /home/***/.cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.2.2/src/filters/cors.rs:614:24

**Comment by eugene-babichenko** [comment]
@cardanoinvest can you please provide your `node-config.yaml`?

**Comment by cardanoinvest** [comment]
> 
> 
> @cardanoinvest can you please provide your `node-config.yaml`?

 cat node-config.yaml
---
log:
- output:
  format: plain
  level: warn

http_fetch_block0_service:
- "https://github.com/input-output-hk/jormungandr-block0/raw/master/data/"
p2p:
  gossip_interval: 3s
  trusted_peers:
   - address: "/ip4/13.56.0.226/tcp/3000"
     id: 7ddf203c86a012e8863ef19d96aabba23d2445c492d86267
   - address: "/ip4/52.28.91.178/tcp/3000"
     id: 23b3ca09c644fe8098f64c24d75d9f79c8e058642e63a28c
   - address: "/ip4/3.125.75.156/tcp/3000"
     id: 22fb117f9f72f38b21bca5c0f069766c0d4327925d967791
   - address: "/ip4/13.112.181.42/tcp/3000"
     id: 52762c49a84699d43c96fdfe6de18079fb2512077d6aa5bc
   - address: "/ip4/13.114.196.228/tcp/3000"
     id: 7e1020c2e2107a849a8353876d047085f475c9bc646e42e9
   - address: "/ip4/52.8.15.52/tcp/3000"
     id: 18bf81a75e5b15a49b843a66f61602e14d4261fb5595b5f5
   - address: "/ip4/52.9.132.248/tcp/3000"
     id: 671a9e7a5c739532668511bea823f0f5c5557c99b813456c
   - address: "/ip4/3.125.183.71/tcp/3000"
     id: 9d15a9e2f1336c7acda8ced34e929f697dc24ea0910c3e67
   - address: "/ip4/3.125.31.84/tcp/3000"
     id: 8f9ff09765684199b351d520defac463b1282a63d3cc99ca
   - address: "/ip4/18.184.35.137/tcp/3000"
     id: 06aa98b0ab6589f464d08911717115ef354161f0dc727858
   - address: "/ip4/18.182.115.51/tcp/3000"
     id: 8529e334a39a5b6033b698be2040b1089d8f67e0102e2575
   - address: "/ip4/3.115.154.161/tcp/3000"
     id: 35bead7d45b3b8bda5e74aa12126d871069e7617b7f4fe62
   - address: "/ip4/18.177.78.96/tcp/3000"
     id: fc89bff08ec4e054b4f03106f5312834abdf2fcb444610e9
   - address: "/ip4/52.9.77.197/tcp/3000"
     id: fcdf302895236d012635052725a0cdfc2e8ee394a1935b63
   - address: "/ip4/54.183.149.167/tcp/3000"
     id: df02383863ae5e14fea5d51a092585da34e689a73f704613
   - address: "/ip4/3.124.116.145/tcp/3000"
     id: 99cb10f53185fbef110472d45a36082905ee12df8a049b74
  topics_of_interest:
    blocks: "high"
    messages: "high"
rest:
  listen: "127.0.0.1:8443"
  cors:
    allowed_origins: ["127.0.0.1:8443"]
    max_age_secs: 120
storage: "/home/***/jorm_tmp"

**Comment by eugene-babichenko** [comment]
@cardanoinvest thank you, I was able to reproduce that. Please add the scheme before origin IP address:

	allowed_origins: ["http://127.0.0.1:8443"]

**Comment by cardanoinvest** [comment]
> allowed_origins: ["http://127.0.0.1:8443"]

Thanks! That solved the error.
