### ISSUE TITLE
[VIT] implement index in vote proposal

### ISSUE THREAD

**Issue by rinor** [input-output-hk/jormungandr#2217]
Implement Proposal index (ex: like we have it in UTxO) within voteplan since is needed for vote casting.

Right now we have to rely on the order outputed from the rest api which may not be in correct order.

**Comment by NicolasDP** [comment]
this is something the REST should provide, the `index` for every proposals

**Comment by rinor** [comment]
closing, since will be done as part of https://github.com/input-output-hk/jormungandr/issues/2218
