### ISSUE TITLE
UnexpectedEof, error: StringError("failed to fill whole buffer")

### ISSUE THREAD

**Issue by gufmar** [input-output-hk/jormungandr#227]
`jormungandr start --genesis-block genesis.yaml --config mynode.config --secret private.key
`
since today panicks wihth
 ```
[cardano-deps/chain-impl-mockchain/src/block/headerraw.rs:38] header_size = 8992
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: UnexpectedEof, error: StringError("failed to fill whole buffer") }', src/libcore/result.rs:997:5
```

I have created `genesis.yaml` with jcli
`mynode.config` and `private.key` remained the same as yesterday when the node started fine.

**Comment by NicolasDP** [comment]
Yes recent changes, have a look at the [documentation](https://github.com/input-output-hk/jormungandr/blob/master/doc/genesis_file.md). --genesis-block is expected a serialized block now. There will be a lot of churn in this area in the next couple of days (just warnings)

**Comment by gufmar** [comment]
Thanks 
so I will wait because even the example block from the documentation as well as a new created from jcli at the moment end in the same panick error. No problem. Continue with the good work. last 3 days looked very promising!

**Comment by NicolasDP** [comment]
ha yes, this is certainly a storage error? The hash of the block 0 has changed, so you will need to reset your storage too (or do without storage atm, remove the line storage in the `config.yaml`)

**Comment by gufmar** [comment]
problem solved with the secret magic
`jcli genesis init | jcli genesis encode --output block_0.bin`
