### ISSUE TITLE
Error while installing jcli - error[E0063]

### ISSUE THREAD

**Issue by mestakepool** [input-output-hk/jormungandr#2274]
**Describe the bug**

**Mandatory Information**
1. `jcli --full-version` output;
jcli v0.8.19

2. `jormungandr --full-version` output;
jormungandr 0.8.19 (v20-776347cf, release, linux [x86_64]) - [rustc 1.43.0 (4fb7144ed 2020-04-20)]

**To Reproduce**
1. git clone https://github.com/input-output-hk/jormungandr.git
2. cd jormungandr
3. git tag 
4. git checkout v0.8.19
5.  git checkout -b <new branch>
6. git submodule update --init --recursive
7. cargo install --path jormungandr --force - Successfully completed

8. cargo install --path jcli --force - Failed with below error 

------------------------------------------------------------------------------------
warning: unused import: `chain_impl_mockchain::certificate::Proposals`
 --> jormungandr-lib/src/interfaces/vote/mod.rs:3:5
  |
3 | use chain_impl_mockchain::certificate::Proposals;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error[E0063]: missing fields `max_length`, `min_length` in initializer of `openapiv3::StringType`
   --> jcli/src/jcli_app/utils/open_api_verifier.rs:395:59
    |
395 |     let valid_schema_kind = SchemaKind::Type(Type::String(StringType {
    |                                                           ^^^^^^^^^^ missing `max_length`, `min_length`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0063`.
error: could not compile `jcli`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `jcli v0.8.19 (/home/dxbnode/jormungandr/jcli)`, intermediate artifacts can be found at `/home/dxbnode/jormungandr/target`

------------------------------------------------------------------------------------

**Comment by mestakepool** [comment]
closing as I resolved the issue by directly copying latest file.

**Comment by pipozzz** [comment]
I have the same issue, what is the workaround?

**Comment by mestakepool** [comment]
Copy the latest version and use below command instead of install commands

tar -xzvf nameofthefileyoujustdownloaded

Make sure you download latest version

**Comment by twistedpair-io** [comment]
> closing as I resolved the issue by directly copying latest file.

I'm attempting to build a VM with Ubuntu 18.04 LTS. I have same issue. 

Which file should I DL?
Cut and Paste from v0.8.19 page:

Thanks!
jormungandr-v0.8.19-x86_64-unknown-linux-gnu-broadwell.tar.gz
11.6 MB
jormungandr-v0.8.19-x86_64-unknown-linux-musl-broadwell.tar.gz
13.7 MB
jormungandr-v0.8.19-x86_64-apple-darwin-broadwell.tar.gz
11.2 MB
jormungandr-v0.8.19-x86_64-apple-darwin-generic.tar.gz
11.1 MB
jormungandr-v0.8.19-x86_64-unknown-linux-musl-generic.tar.gz
13.7 MB
jormungandr-v0.8.19-aarch64-unknown-linux-gnu-generic.tar.gz
12.8 MB
jormungandr-v0.8.19-aarch64-linux-android-generic.tar.gz
12.9 MB
jormungandr-v0.8.19-arm-unknown-linux-gnueabi-generic.tar.gz
14.2 MB
jormungandr-v0.8.19-x86_64-unknown-linux-gnu-generic.tar.gz
11.6 MB
jormungandr-v0.8.19-armv7-unknown-linux-gnueabihf-generic.tar.gz
14 MB
jormungandr-v0.8.19-x86_64-pc-windows-gnu-generic.zip
11.9 MB
jormungandr-v0.8.19-x86_64-pc-windows-msvc-broadwell.zip
10.6 MB
jormungandr-v0.8.19-x86_64-pc-windows-msvc-generic.zip
10.4 MB
jormungandr-v0.8.19-x86_64-pc-windows-gnu-broadwell.zip
12 MB
Source code
(zip)
Source code
(tar.gz)
 v0.8.18
 690eb54
R

**Comment by eugene-babichenko** [comment]
It looks like GitHub does not include submodules to the automatically generated source archives and thus you have missing `chain-deps`. You should better use git (`git submodule update --init && git checkout v0.8.19` after you clone the repo) if you want to build from the source. I will create an issue about the source archives.

**Comment by twistedpair-io** [comment]
> It looks like GitHub does not include submodules to the automatically generated source archives and thus you have missing `chain-deps`. You should better use git (`git submodule update --init && git checkout v0.8.19` after you clone the repo) if you want to build from the source. I will create an issue about the source archives.

Thanks so MUCH! Eugene!

I was half asleep, trying to make this load fly, when I wrote my post! So glad you could make sense of what was going on, as there was many fruitless google searches to figure out the issue. This thread threw the best hint, as I figured out the two files that it needed to compile from.

I know that I can't be the only one bitten by this bug, and I'm sure your help with this post will serve many Cardano pioneers well.
