### ISSUE TITLE
Legacy node cannot sync with node from master

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#2301]
**Describe the bug**
In given scenario:
![image](https://user-images.githubusercontent.com/20424186/83388097-2a925b00-a3ee-11ea-8505-ce8d1bfdaa49.png)

Where:
- Leader1 - is a node from 0.8.19
- other nodes are from 0.9.0-nightly

Nodes from master cannot sync with node from legacy version:

part of the log:

```
[INFO ][Leader3@127.0.0.1:8018]: Jun 01 05:35:41.025 INFO connection to peer failed, error: Subscription(Error { code: InvalidArgument, source: Status { code: InvalidArgument, message: "invalid request data (missing metadata node-id-bin)" } }), address: /ip4/127.0.0.1/tcp/12019, peer_addr: 127.0.0.1:12019, task: network
[INFO ][Leader1@127.0.0.1:8019]: Jun 01 05:35:41.026 INFO connection closed, peer_addr: 127.0.0.1:47128, local_addr: 127.0.0.1:12019, task: network
[INFO ][Leader2@127.0.0.1:8021]: Jun 01 05:35:41.026 INFO connection to peer failed, error: Subscription(Error { code: InvalidArgument, source: Status { code: InvalidArgument, message: "invalid request data (missing metadata node-id-bin)" } }), address: /ip4/127.0.0.1/tcp/12019, peer_addr: 127.0.0.1:12019, task: network
[INFO ][Leader1@127.0.0.1:8019]: Jun 01 05:35:41.028 INFO connection closed, peer_addr: 127.0.0.1:47126, local_addr: 127.0.0.1:12019, task: network
[INFO ][Leader2@127.0.0.1:8021]: Jun 01 05:35:41.565 INFO connecting to peer, address: /ip4/127.0.0.1/tcp/12019, peer_addr: 127.0.0.1:12019, task: network
[INFO ][Leader1@127.0.0.1:8019]: Jun 01 05:35:41.565 INFO accepted connection, peer_addr: 127.0.0.1:47130, local_addr: 127.0.0.1:12019, task: network
[INFO ][Leader2@127.0.0.1:8021]: Jun 01 05:35:41.566 INFO connection to peer failed, error: Subscription(Error { code: InvalidArgument, source: Status { code: InvalidArgument, message: "invalid request data (missing metadata node-id-bin)" } }), address: /ip4/127.0.0.1/tcp/12019, peer_addr: 127.0.0.1:12019, task: network
[INFO ][Leader1@127.0.0.1:8019]: Jun 01 05:35:41.566 INFO connection closed, peer_addr: 127.0.0.1:47130, local_addr: 127.0.0.1:12019, task: network
```

**Mandatory Information**
1. `jcli --full-version`
`0.9.0-nightly (master-dc50b235, release, linux [x86_64]) - [rustc 1.43.1 (8d69840ab 2020-05-04)]`

2. `jormungandr --full-version` 
`0.9.0-nightly (master-dc50b235, release, linux [x86_64]) - [rustc 1.43.1 (8d69840ab 2020-05-04)]`

**To Reproduce**
1. Go to testing/jormungandr-scenario-testing
2. run command
'cargo run -- --scenario legacy_disruption_last_release --document --root-dir legacy --progress-bar-mode standard > log.log'
3. See error in 'log.log' file 

**Expected behavior**
test should pass

**Additional context**
configs and genesis file should be available after running test in legacy 'testing/jormungandr-scenario-testing/folder'

**Comment by mzabaluev** [comment]
Legacy expects there to be a `node-id-bin` metadata header. Perhaps it makes sense to add one just for backward compatibility.

**Comment by mzabaluev** [comment]
Steps to fix:
- [ ] Support in chain-libs: https://github.com/input-output-hk/chain-libs/pull/394
- [ ] Enable in jormungandr

**Comment by dkijania** [comment]
Unfortunately there is another issue in place on the old one:

```
[Leader3@127.0.0.1:8005]: Jun 06 05:30:28.015 INFO connection to peer failed, error: Subscription(Error { code: InvalidArgument, source: Status { code: InvalidArgument, message: "invalid request data (invalid node ID in node-id-bin: invalid request data (the size limit has been reached))" } }), address: /ip4/127.0.0.1/tcp/12002, peer_addr: 127.0.0.1:12002, task: network
[INFO ]
```
