### ISSUE TITLE
Source archives do not include chain-deps

### ISSUE THREAD

**Issue by eugene-babichenko** [input-output-hk/jormungandr#2374]
GitHub does not include submodules to source archives, so we should find a way to build a proper archive with `chain-deps` included.

**Comment by mzabaluev** [comment]
I wonder if there is a way to remove the auto-built source links from releases.

**Comment by mzabaluev** [comment]
Nothing here: https://developer.github.com/v3/repos/releases/#create-a-release

**Comment by mzabaluev** [comment]
Would a proper solution involve hosting chain-libs in a cargo package registry, perhaps?

**Comment by eugene-babichenko** [comment]
> 
> 
> I wonder if there is a way to remove the auto-built source links from releases.

just overwrite them perhaps?

**Comment by mark-stopka** [comment]
> Would a proper solution involve hosting chain-libs in a cargo package registry, perhaps?

It's a shame that GitHub Packages don't support Cargo packages yet, but I guess up-streaming it would not hurt...

> just overwrite them perhaps?

That is not a good idea,  it will make packaging for distributions a nightmare...

**Comment by mzabaluev** [comment]
With #2659, we will convert chain-deps to proper cargo dependencies, so a source build will pull them in as per normal.

**Comment by eugene-babichenko** [comment]
@mzabaluev are these locked to specific commits in `Cargo.lock`, or do we need to do some kind of locking for them in `Cargo.toml`? These deps might be an issue when trying to build older commits in the `jormungandr` repo, for example.

**Comment by mzabaluev** [comment]
@eugene-babichenko git dependencies are locked to a specific commit in `Cargo.lock`. If you are targeting the last state in master, it should be enough to run `cargo update` and commit the changed `Cargo.lock`. If you need to target a specific commit, this needs to be addressed in `Cargo.toml` under either a ref name (branch or tag), or the commit hash.

**Comment by mzabaluev** [comment]
Obviated by #2659.
