### ISSUE TITLE
0.9.0 tokio-runtime-worker' panicked at 'missing scheme'

### ISSUE THREAD

**Issue by genepool-one** [input-output-hk/jormungandr#2425]
**Describe the bug**
I have built 0.9.0 and that went fine but when I run it I get the message:

thread 'tokio-runtime-worker' panicked at 'missing scheme', /home/jr/.cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.2.3/src/filters/cors.rs:614:24

**Mandatory Information**
1. `jcli --full-version` output;

jcli 0.9.0 (9.0-5729735b, release, linux [x86_64]) - [rustc 1.44.1 (c7087fe00 2020-06-17)]

2. `jormungandr --full-version` output;

jormungandr 0.9.0 (9.0-5729735b, release, linux [x86_64]) - [rustc 1.44.1 (c7087fe00 2020-06-17)]

**To Reproduce**
On my system:

build 0.9.0
run it

**Additional context**

I had an error with 0.8.19? maybe the same, but as ITN was finishing I decided to let it run to end with 0.8.18.  Now of course we have the chance to vote so I need to get to 0.9.0 if possible.

Running on Arch linux (Manjaro)...

**Comment by adasnakepoolcom** [comment]
Hello,
I get same error on NixOs after built succeeded
thanks
cheers.

**Comment by NicolasDP** [comment]
Hmm looks like a bug in the REST settings. @eugene-babichenko or @danielSanchezQ I think I remember we saw this at some point, do you have more insight you could provide to mitigate while we work on a better error handling?

**Comment by danielSanchezQ** [comment]
I believe is because the cors address lacks the `http/s` at the beginning. @eugene-babichenko do you confirm?

**Comment by genepool-one** [comment]
Thanks @NicolasDP for suggesting invalid config.

I changed my config and the node now starts.

For you reference here is the config that was working on 0.8.18 and broke with 0.9.0.  Yes it is made up from all the rumours and suggestions in the operators channel over many versions of jormungandr so don't laugh too much at it ;)

`rest:
  listen: "127.0.0.1:3001"
  cors:
    allowed_origins: ["127.0.0.1:3001"]
    max_age_secs: 120
    
http_fetch_block0_service:
- "https://github.com/input-output-hk/jormungandr-block0/raw/master/data/"
- "https://adanorthpool.com/bootstrap/"
skip_bootstrap: true
bootstrap_from_trusted_peers: false
storage: /home/jregan/storage

p2p:
  listen_address: "/ip4/192.168.1.91/tcp/3000"
  public_address: "/ip4/81.161.155.210/tcp/3000"
  public_id: 950965ee66b52bd8c81fc227ad5af00661ff47e4d47ff4f9
  max_connections: 650
  #Changed Mar 4 below from 480 to 32
  max_connections_threshold: 32
  #Changed Mar 4 from 7s to 5s
  gossip_interval: 5s
  #Changed Mar 4 from 4 to 0
  max_unreachable_nodes_to_connect_per_event: 0
  trusted_peers:
    ### EU
  - address: "/ip4/52.28.91.178/tcp/3000"
#       id: 23b3ca09c644fe8098f64c24d75d9f79c8e058642e63a28c
  - address: "/ip4/18.184.35.137/tcp/3000"
#       id: 06aa98b0ab6589f464d08911717115ef354161f0dc727858
  - address: "/ip4/3.125.31.84/tcp/3000"
#       id: 8f9ff09765684199b351d520defac463b1282a63d3cc99ca
  - address: "/ip4/3.125.75.156/tcp/3000"
#       id: 22fb117f9f72f38b21bca5c0f069766c0d4327925d967791
  - address: "/ip4/3.125.183.71/tcp/3000"
#       id: 9d15a9e2f1336c7acda8ced34e929f697dc24ea0910c3e67
  - address: "/ip4/3.124.116.145/tcp/3000"
#       id: 99cb10f53185fbef110472d45a36082905ee12df8a049b74


  topics_of_interest:
    messages: high
    blocks: high
  policy:
    quarantine_duration: 15m

mempool:
    pool_max_entries: 30000
    #fragment_ttl: 15m
    #log_ttl: 24h
    log_max_entries: 100000
    #garbage_collection_interval: 30m

log:
  - output: stderr
    level: warn
    format: plain



explorer:
  enabled: true

#leadership:
    #log_ttl: 24h
    #garbage_collection_interval: 30m`

**Comment by adasnakepoolcom** [comment]
Hello Nicolas,
just installed 0.9.1 and still get tokio-runtime missing scheme error,
node config is ok (I think) no public_id and no trusted peers.
On node start:
1. get the error message
2. loading the storage
3. node shutdown itself

kind regards
Emanuele

**Comment by adasnakepoolcom** [comment]
same issue faced using various rc's of 0.9.0 installed through cargo or via nix-build from iohk-nix repo

**Comment by adasnakepoolcom** [comment]
I removed cors section from node-config and starts ok

**Comment by eugene-babichenko** [comment]
CORS origin setting must contain a scheme, usually http or https. This is a valid example: `["http://127.0.0.1:8080"]`.

**Comment by eugene-babichenko** [comment]
duplicated #2618
