### ISSUE TITLE
Project's status

### ISSUE THREAD

**Issue by sinasalek** [input-output-hk/jormungandr#2523]
What is the status of the project and is there a roadmap? also is this going to be drop in replacement for cardano-node project? does it support staking?
Thank you

**Comment by mark-stopka** [comment]
> also is this going to be drop in replacement for cardano-node project?

No, this is incompatible node implementation, it does however support staking if you run your own chain...

**Comment by sinasalek** [comment]
My own chain? so is this for testing purpose and can't be used on mainnet?

**Comment by LokiOdinsonCoin** [comment]
The protocol is completely different from Cardano.

**Comment by marko-k0** [comment]
So, what is the long term idea and purpose of this project then?

**Comment by mark-stopka** [comment]
> So, what is the long term idea and purpose of this project then?

Jormungandr is used in BFT federated mode as a side-chain for Project Catalyst voting.
