### ISSUE TITLE
Cancellable bootstrap

### ISSUE THREAD

**Issue by mzabaluev** [input-output-hk/jormungandr#2654]
With #2650 we intercept graceful shutdown signals before bootstrap starts, but the handlers defer shutdown until the node is fully bootstrapped.

It would be useful to pass a [cancellation handle](https://docs.rs/tokio-util/0.4.0/tokio_util/sync/struct.CancellationToken.html) and intersperse the bootstrap pull with checks for cancellation that may be triggered by the termination signal watcher.

To be deferred until #2620 is done.

**Comment by eugene-babichenko** [comment]
This was already done. https://github.com/input-output-hk/jormungandr/blob/master/jormungandr/src/main.rs#L406

Looks like two `ctrl_c` handlers are in conflict.

**Comment by mzabaluev** [comment]
> This was already done. https://github.com/input-output-hk/jormungandr/blob/master/jormungandr/src/main.rs#L406
> 
> Looks like two `ctrl_c` handlers are in conflict.

That only handles `SIGINT` and yes, the second handler panics when `SIGINT` is sent. I think we need to work this into the signal watchers that are initialized [at startup](https://github.com/input-output-hk/jormungandr/blob/dc981a9941d44503cbadcbbbc4e26a5c604bc22f/jormungandr/src/main.rs#L547-L547).
