### ISSUE TITLE
Repository split

### ISSUE THREAD

**Issue by danielSanchezQ** [input-output-hk/jormungandr#2726]
We want to split jormungandr repository into different ones. Separating different testing and libraries responsabilities.
The idea is to move `testing` into it independant repository. Keeping `jormungandr-integration-tests` into the original `jormungandr` repository for CI porpouses.

Even more, later, `jormungandr-testing-utils` could be also splitted into:
- jormugandr_node_api
- load tools
- wallet 

We need a roadmap in order to fullfill this task correctly.

**Comment by dkijania** [comment]
1st step:

-move `iapyx`  to separate crate
-move `jormungandr-scenario-tests` to separate crate 
-move `jormungandr-testing-utils`  to separate crate

2nd step

split  `jormungandr-testing-utils` into workspace with projects:
- jormungandr-connector (all rest/grpc/explorer interfaces)
- jormungandr-mocks (jormugnandr-grpc-mock/jormungandr-adversary-node/wallet) / alternatively extract all mocks as a projects under mocks folder
- jormungandr-performance (all cli and api for load: explorer/rest/fragments)

3rd step

rename iapyx to voting-app-mock

4th step

extract wallet stuff from jormungandr-mocks as a iapyx (or wallet-mock)

**Comment by eugene-babichenko** [comment]
BTW, what to do you think of the following approach:

- Create `lib.rs` in  `jormungandr` and `jcli` that will contain the `main` function accepting environment and argv as arguments
- Reuse this function in `main.rs`
- Use exported `main` from `lib.rs` combined with `fork` system call in integration tests to avoid building binary and tests separately?

**Comment by danielSanchezQ** [comment]
I like that approach @eugene-babichenko.

**Comment by mzabaluev** [comment]
> Use exported main from `lib.rs` combined with `fork` system call

Do we have a Windows equivalent for that?

**Comment by mzabaluev** [comment]
The part of `jormungandr-testing-utils` that is used by integration tests can stay on in the `jormungandr` workspace, maybe renamed as `jormungandr-testing-libs`. Crates moved to other repositories can depend on it and `jormungandr-lib` with git dependency style:

```
jormungandr-lib = { git = "https://github.com/input-output-hk/jormungandr.git" }
```

The rest of the moved crates can be in the same `jormungandr-testing` workspace repository, or be split as needed.

**Comment by mzabaluev** [comment]
Superseded by other changes.
