### ISSUE TITLE
jcli transaction stalls

### ISSUE THREAD

**Issue by robkorn** [input-output-hk/jormungandr#274]
**Describe the bug**
When trying to do anything with the latest `jcli transaction` other than `jcli transaction new` it causes the program to stall. There is no output, it just freezes as if stuck in some sort of internal loop. If arguments are not provided, it will spit out an error, but if proper arguments are provided then it stalls.

**To Reproduce**
1. `jcli transaction info` or `jcli transaction add-input 301... 0 10`
2. Program stalls.

**Expected behavior**
Return results based on command.

**Additional context**
This was tested on Ubuntu 18.04 x86-64.

**Comment by NicolasDP** [comment]
Hi, thanks for your interest. Can you try again but either by providing the staging transaction in the standard input or by providing the `--staging /path/to/staging/transaction`. Thanks.

**Comment by robkorn** [comment]
Ah, right of course. I imagined that when a new transaction was created it would be saved in a temp folder somewhere until it was finished, I didn't realize that it was suppose to be added as input. Thanks.
