### ISSUE TITLE
Cannot read the transaction: Invalid formatted transaction

### ISSUE THREAD

**Issue by robkorn** [input-output-hk/jormungandr#276]
**Describe the bug**
From my understanding I am creating a transaction properly however no matter whether I try using `add-input` to use a UTXO dirctly, or if I try using `add-account`, `add-witness` keeps throwing out an error.

In this case it is:
```
Cannot add witness to the transaction
  |-> cannot read the transaction: Invalid formatted transaction
```

**To Reproduce**
```
./jcli transaction new --staging test.tx
./jcli transaction add-output $outaddress 10 --staging test.tx
./jcli transaction add-input $utxoid 1 100 --staging test.tx

./jcli transaction lock $address --staging test.tx

./jcli transaction make-witness $utxoid --type utxo test.wit 0 ~/keys/private.key
witness=$(cat test.wit)
./jcli transaction add-witness $witness --staging test.tx


```

**Expected behavior**
Witness to be added to transaction.

**Comment by NicolasDP** [comment]
You need to lock the transaction before adding witnesses : https://github.com/input-output-hk/jormungandr/blob/master/doc/cli_transaction.md#transaction

**Comment by NicolasDP** [comment]
I believe this is fixed now
