### ISSUE TITLE
Explorer spawned with passive node cannot find transaction 

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#2790]
**Describe the bug**
having network topology like below:

![image](https://user-images.githubusercontent.com/20424186/101155146-ff9bf480-3626-11eb-83d8-63e53562f945.png)

Where leader3 is a passive node with explorer

I'm sending transaction to node 1, with expectation that explorer setup on passive node would show it when sending query:
```
query:
{
     transaction(id: "bfa87e6841b2fabda40502efebeb129f1b2f09a2ca231193bb129ceb81699595") {
        id
    }
}", against: http://127.0.0.1:8002/explorer/graphql
```

Unfortunately i'm receiving an error:
```
Response: Response { data: None, errors: Some([Error { message: "transaction not found: bfa87e6841b2fabda40502efebeb129f1b2f09a2ca231193bb129ceb81699595", locations: Some([Location { line: 2, column: 5 }]), path: Some([Key("transaction")]), extensions: None }]) }
```
**Mandatory Information**
1. `jcli --full-version` output: `newest master`
2. `jormungandr --full-version` output: `newest master`

**To Reproduce**
`cargo run -- --scenario passive_node_explorer`

**Expected behavior**
transaction should be available in explorer

**Comment by eugene-babichenko** [comment]
The REST API of the passive node responds with `InABlock` status for the same fragment, so the current assumption is that the explorer lags behind the main data store.
