### ISSUE TITLE
Unexpected shut down of retired stake pool

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#2800]
**Describe the bug**
For topology like below:
![image](https://user-images.githubusercontent.com/20424186/101154703-5ce37600-3626-11eb-8412-fec5060a8360.png)

when send `retire stake pool` certificate for leader3, node unexpectedly is shutdown.
Logs: 
[retire_stake_pool_explorer.zip](https://github.com/input-output-hk/jormungandr/files/5642195/retire_stake_pool_explorer.zip)

**Mandatory Information**
1. `jcli --full-version` output;
2. `jormungandr --full-version` output;

**To Reproduce**
`cargo run -- --scenario retire_stake_pool_explorer --root-dir retire_stake --document`

**Comment by mzabaluev** [comment]
The root cause is a panic also observed in #2147.

This issue, then, is about improving the diagnostics so that the cause of shutting down is reflected in the logs.

**Comment by eugene-babichenko** [comment]
With https://github.com/input-output-hk/jormungandr/pull/2812 it outputs a proper error.
