### ISSUE TITLE
Transaction with more than 97 outputs if forever pending 

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#2806]
**Describe the bug**

In test `jormungandr::genesis::fragments::one_hundreds_addresses` i try to send transaction with single input and 98 or more outputs. As a result transaction is pending forever, but never rejected. If i decrease outputs count to 97, transaction is put in block

**Mandatory Information**
1. `jcli --full-version` newest master;
2. `jormungandr --full-version` newest master;

**To Reproduce**
1. checkout branch: `more_than_97_addresses`
2. run test from jormungandr-integration-test:
`cargo test jormungandr::genesis::fragments::one_hundreds_addresses`

**Expected behavior**
test should pass

**Comment by eugene-babichenko** [comment]
This should be either fixed by #2941 or by increasing the block contents size limit.

**Comment by dkijania** [comment]
It is fixed by increasing block contents size limit.

**Comment by dkijania** [comment]
this is follow up issue: #2947
