### ISSUE TITLE
Test Maintenance

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#2809]
| Test              | Reason          | Issue          |            Fix |       Status |        Assignee|
| ------------- |---------------:|:-------------:| ----------:|  ----------:| --------------:|
| networking::stats::passive_node_last_block_info|  |  |    |  In Analysis | Darek | 
| jormungandr::grpc::client_tests::pull_blocks_hashes_wrong_order| | | |  In Analysis | Darek | 
|newest_node_enters_legacy_network| lack of backward compatibility| | move to unstable | TODO| Darek |
| vote_e2e_flow| cannot access resources for db migration | | #2789 |In Test| Darek | 
| passive_node_explorer | ancestor of block cannot be found in the explorer |#2790  | #2807|Fixed| Eugene | 
| relay_soak | lack of sync between nodes | #2719/#2582 | |TODO| Mikhail/Eugene| 
| jormungandr::grpc::client_tests::pull_headers_correct_hash| | ||  In Analysis | Darek|
| jormungandr::fragments::send_all_fragments | | | | In Test| |

**Comment by eugene-babichenko** [comment]
Updated:

* jormungandr::vit::test_vote_flow_praos
* passive_node_explorer
* retire_stake_pool_explorer

**Comment by eugene-babichenko** [comment]
Updated: uncovored the mystery of recovering from `SIGKILL`.
