### ISSUE TITLE
Develop Encode/Decode Qr code method in Rust

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#2811]
It would be helpful regarding vote end to end flow testing if we have a very simple method that is able to decode/encode method like below:

https://github.com/input-output-hk/vit-kedqr/blob/master/internal/ked/ked.go

**Comment by mzabaluev** [comment]
`cryptoxide` would be ideal for this if not for https://github.com/typed-io/cryptoxide/issues/13.

**Comment by enzoc4** [comment]
forgot to link here from #2856. In any case, we should probably close this, right?

**Comment by mzabaluev** [comment]
All seems done, please reopen if something is missing.
