### ISSUE TITLE
On a node started with multiple stake pools they produce blocks with different sets of transactions

### ISSUE THREAD

**Issue by eugene-babichenko** [input-output-hk/jormungandr#2834]
**Describe the bug**
When the node is started with multiple leaders, both of them are creating new blocks. Due to the current implementation of the fragments pool, where the selected blocks are immediately removed from the fragment pool, the two stake pools always end up with two entirely different sets of transactions in their blocks.

This caused random failures in `test_vote_flow_praos` due to the fact that some blocks were not included into the main chain and thus the transaction history in the main chain was different from what the test expected. In the case of this test the failure manifested itself as:

- An "invalid signature" message due to mismatch of the spending counter used for generating the witness (it was smaller in the ledger than in the test client due to a transaction not being in the main branch). Example: https://github.com/input-output-hk/jormungandr/runs/1562468481
- A failure to get the expected voting result due to vote casts missing from the main branch. Example: https://github.com/input-output-hk/jormungandr/runs/1556761271?

Note that this is the state at the time writing this issue and the test may change.

**Mandatory Information**
1. `jcli --full-version` output: `jcli 0.10.0-alpha.2 (master-fc517e40, debug, linux [x86_64]) - [rustc 1.48.0 (7eac88abb 2020-11-16)]`
2. `jormungandr --full-version` output: `jormungandr 0.10.0-alpha.2 (master-fc517e40, debug, linux [x86_64]) - [rustc 1.48.0 (7eac88abb 2020-11-16)]`

**To Reproduce**
1. `cargo build --locked -p jormungandr -p jcli`
2. `cargo test test_vote_flow_praos`

**Expected behavior**
We should either provide a way for multiple pools to work on the same set of transactions or forbid such configuration.

**Comment by mzabaluev** [comment]
As much as running multiple pools on a single node makes sense, the behavior should be sensible.
Should we clone the transactions to every leader's block and clear the pool after all leader's blocks are formed? Is there any important logic that necessitates pulling fragments from the pool immediately?

**Comment by eugene-babichenko** [comment]
I decided to work on that and an important part is transaction rejection. In general, a transaction is pulled from the pool, _validated against the current ledger state_ and only after that is selected as a candidate. This also includes modifying the transaction log. This is important, because different leaders may produce different validation results even with the same set of transactions, although I do not see this as a highly probable scenario. This poses a question about how we should update the fragment log when we have multiple leaders. Having multiple leaders updating the same log may be fine though, if we put correct statuses after a block was committed.
