### ISSUE TITLE
[Tests] Scenario tests should use the same runtime object for each async call

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#2948]
Jormungandr scenario tests project is using runtime in an incorrect way. Right now it creating runtime only for client bootstrap. Every each grpc method execution will produce and error. 

Putting runtime object to context and share it for each node should solve that issue. Hopefully we are not using any grpc call in scenario, but in nearest future it can change.

**Comment by Zeegomo** [comment]
closed by https://github.com/input-output-hk/jormungandr/pull/2970
