### ISSUE TITLE
[JCLI_REST] Panic instead of well-formed error message

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#298]
**Describe the bug**
There are few places where jcli throws internal exception on bad input while it should produce error message like in the other parts. 

**To Reproduce**
1. Start jormungandr with any settings
2.  run command with bad data like below:
  `jcli rest v0 block e1049ea45726f0b1fc473af54f706546b3331765abf89ae9e6a8333e49621641aa get --host http://127.0.0.1:8443/api `
3. See panic is produced:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: ClientError(400), url: `Some("http://127.0.0.1:8443/api/v0/block/e1049ea45726f0b1fc473af54f706546b3331765abf89ae9e6a8333e49621641aa") }', src\libcore\result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.`

**Expected behavior**
Similar output should be presented:
Cannot get block
  |-> unknown id

**Additional context**

There are others commands in jcli rest subcommand that have the same behavior:

1) ` jcli rest v0 block e1049ea45726f0b1fc473af54f706546b3331765abf89ae9e6a8333e49621a641a next-id get -c "1001" --host "http://127.0.0.1:8443/api"`

2) ` jcli rest v0 tip get -h tcp://127.0.0.1:1/apixxxxxxxx`
3) `jcli rest v0 tip get -h http://127.0.0.100:1/api`

**Comment by CodeSandwich** [comment]
This is a tip of a JCLI-wide problem of inconsistent error handling. The final goal is to make it fully panic-free  with components returning errors and a single point of handling them.

**Comment by CodeSandwich** [comment]
@vincenthz Milestone week 1 is for removal of transaction panics
