### ISSUE TITLE
Release workflow produces unusable binaries for macOS

### ISSUE THREAD

**Issue by eugene-babichenko** [input-output-hk/jormungandr#2984]
All macOS builds are failing in GitHub Actions with the same error:

```
---- jormungandr::legacy::test_legacy_node_all_fragments stdout ----
thread 'jormungandr::legacy::test_legacy_node_all_fragments' panicked at 'called `Option::unwrap()` on a `None` value', /Users/runner/work/jormungandr/jormungandr/testing/jormungandr-testing-utils/src/testing/node/legacy/mod.rs:57:56
```

**Comment by dkijania** [comment]
Oh yes, i didn't have a chance to resolve it. but it looks like downloading last release from github is a problem

**Comment by eugene-babichenko** [comment]
Looks like it is not even about downloading the release, but finding the executable after unpacking the archive.

**Comment by mzabaluev** [comment]
@dkijania

> last release

As in, 0.10.0-alpha.2?

> finding the executable after unpacking the archive.

The macOS archives have exactly the same executables as the ones for linux:

```
$ tar -tzvf jormungandr-0.10.0-alpha.2-x86_64-apple-darwin-generic.tar.gz 
-rwxr-xr-x runner/staff 17741080 2020-11-09 11:25 jormungandr
-rwxr-xr-x runner/staff 10603632 2020-11-09 11:32 jcli
```

Will try to run the binaries on an x86 Mac to see if there is any obvious problem with them.

Weirdly, the tar.gz archives for macOS are about 3 times smaller than the linux tarballs, even though the binaries are about the same size.

**Comment by mzabaluev** [comment]
Wat

```
jormungandr-0.10.0-nightly.20210204-x86_64-apple-darwin-generic mzabaluev$ ./jormungandr --help
-bash: ./jormungandr: cannot execute binary file: Exec format error
```

**Comment by mzabaluev** [comment]
For the record, this is reproducible on MacOS 1.11, kernel Darwin 20.2.0.

**Comment by eugene-babichenko** [comment]
Could it be that the binary is not signed or the signature is incorrect? IIRC they changed they signing policies for Big Sur.

**Comment by mzabaluev** [comment]
The fix is replacing whatever weird tar installation the macOS runner has with gnu tar: https://github.com/actions/virtual-environments/issues/1534

Should be deployed to the runners soon.
