### ISSUE TITLE
Investigate issues with shared fragment logs in presence of multiple fragment pools

### ISSUE THREAD

**Issue by mzabaluev** [input-output-hk/jormungandr#3011]
* There may be problems with having shared logs for different pools that could have different state. What would happen for example if `pool.select` is first called on pool1 and succeed while a second call on the second pools fails due to (for instance) changes in the ledger? What status should `get_fragment_logs` return? That being said, in a first look such scenarios do not seem highly probable.

* I think it is a problem if `logs_max_entries` < `pool_max_entries`, because for example some of the logs would be thrown away when inserting a chunk of transactions of size `pool_max_entries`, and an attempt to modify the logs (e.g. a call to select) would flag those fragments as originating from the network while that may not be the case

_Originally posted by @Zeegomo in https://github.com/input-output-hk/jormungandr/pull/2923#issuecomment-775204380_

**Comment by mzabaluev** [comment]
> What status should `get_fragment_logs` return?

In the REST API for fragment log entries, there should be a disambiguation as to which leader has selected the fragment. Would it be a problem to have otherwise duplicate entries?

**Comment by Zeegomo** [comment]
in https://github.com/input-output-hk/jormungandr/pull/2923#issuecomment-776544365 I shared another idea that could helps us solve the same problem without using multiple pools or shared logs

**Comment by eugene-babichenko** [comment]
>     * I think it is a problem if `logs_max_entries` < `pool_max_entries`, because for example some of the logs would be thrown away when inserting a chunk of transactions of size `pool_max_entries`

Yes, ideally `logs_max_entries` should be `pool_max_entries * n_pools` if we stick to "multiple pools  single log".

**Comment by eugene-babichenko** [comment]
> What would happen for example if `pool.select` is first called on pool1 and succeed while a second call on the second pools fails due to (for instance) changes in the ledger?

I think it shouldn't matter, it will be overwritten by `InABlock` status when committing a block.

What is more interesting, is that the block ID in `InABlock` might be inconsistent with with the actual system state. For example, block B was submitted later than block A (and the log entry state was overwritten), but later block A was selected, whereas the log entry still refers to block B.

**Comment by eugene-babichenko** [comment]
> What would happen for example if `pool.select` is first called on pool1 and succeed while a second call on the second pools fails due to (for instance) changes in the ledger?

UPD: We can just make `InABlock -> Rejected` state transition invalid and that would be the solution.

**Comment by Zeegomo** [comment]
> UPD: We can just make InABlock -> Rejected state transition invalid and that would be the solution.

Yes, this should fix it
> What is more interesting, is that the block ID in InABlock might be inconsistent with with the actual system state. For example, block B was submitted later than block A (and the log entry state was overwritten), but later block A was selected, whereas the log entry still refers to block B.

I think this can happen regardless of the two blocks being produced by the same node. If another node on the network produces a block for this slot and includes some of the fragments then the logs would point to that block hash (because coming from the network it will be processed later). The fact is that a transaction could be in more than one block and we do not know in advance which one will be selected on the main chain.

**Comment by mzabaluev** [comment]
> Yes, ideally `logs_max_entries` should be `pool_max_entries * n_pools` if we stick to "multiple pools single log".

I think we should bump the effective value to `pool_max_entries * n_pools` if the configured value is less than that.

**Comment by Zeegomo** [comment]
Resolved as we now only have one pool https://github.com/input-output-hk/jormungandr/pull/3556
