### ISSUE TITLE
gRPC methods not behaving as expected

### ISSUE THREAD

**Issue by Zeegomo** [input-output-hk/jormungandr#3017]
**Describe the bug**
tests `pull_blocks_to_tip_incorrect_hash` and `pull_headers_empty_start_hash` fails because `grpc::pull_blocks_to_tip` with an incorrect starting hash and `pull_headers` with an empty start hash only returns info about the tip instead of the whole chain

**To Reproduce**
0. checkout updated grpc tests from https://github.com/input-output-hk/jormungandr/pull/3016
1. cargo test jormungandr::grpc::client_tests::pull_blocks_to_tip_incorrect_hash
2. cargo test jormungandr::grpc::client_tests::pull_headers_empty_start_hash

**Example output**:
```
pull_headers_empty_start_hash

server_hashes: [Hash(Blake2b256(0x4874dc89975b517b967464181c9f3727be670b4b5e7391fac4520f6c4eb6b621)), Hash(Blake2b256(0xa85e19aa46750551e4832ddafa07fb8c4f2e75e2771f7efe5841ef282c160a43)), Hash(Blake2b256(0xff52b2be240d7c4c15b375e8ab0b8588eafc4bd079eb29a15c8daf7822b4e6af)), Hash(Blake2b256(0x4ef126aa3090354aa30e2785d9bc65bdd46d7ec2d12f397d6e81e2f0cbb7c57e)), Hash(Blake2b256(0x3c515fd7a7e51828f40b34498a9b7328f121804b7e35b3b4e322a9c99722711a)), Hash(Blake2b256(0x2e8b51c28e7300b7f6f637a9f70f2154da4059b6dd41eaf07874e9dfbc5dfaa9)), Hash(Blake2b256(0x1016a3627fa36144fdfa87afd93285f5d21491c197cee5ee0edad3d29099e608)), Hash(Blake2b256(0x003da55cc15a092397ba38a45a18097fe60c034f101bd8ca06cda9727eba24cb)), Hash(Blake2b256(0xbd9b92634744737df3066471ef9a03351bd43007c4c8183b39f2d979659c3763)), Hash(Blake2b256(0x67a1946ee1be0156bbe33c547490b354fe3fcfede28aeb0c3689c4c3c267471c)), Hash(Blake2b256(0x5b2868df30e83dbd8e5148eb180a633eb181ad7c5728958833992c3dd10136c7)), Hash(Blake2b256(0x5140eba7ec286250babf86bd8e55b1c66d015cf540f6481d45c2d84ae1b7e234)), Hash(Blake2b256(0xfc7a14c76829bc03bf2c123095e43d322d95bede413819834e5d675fbb0da465)), Hash(Blake2b256(0x9618698338c58fec62255d21d60ff2bcdc4a869ec4c03157dd0a083958eaeb7c))]

client_hashes: [Hash(Blake2b256(0x9618698338c58fec62255d21d60ff2bcdc4a869ec4c03157dd0a083958eaeb7c))]
```

**Comment by Zeegomo** [comment]
I have investigated this issue a bit, and found that different gRPC "range" methods have different behavior regarding how they treat values in `from` field.

In particular, when the blocks in `from` field are not present locally (or the list is empty):
* `PullHeaders(from, to)` : return only the header specified by `to` (it it's valid)
* `PullBlocksToTip(from)`: return only the tip
* `PullBlocks(from, to)`: returns an error

In tests we check for different behavior as well but they are a bit scattered, i.e. we check that:
* `pull_headers_empty_start_hash` the whole chain (starting from the genesis to `to`) is returned when `from` is empty
* `pull_blocks_to_tip_incorrect_hash`  the whole chain is returned when no hash in `from` points to a block known to the server
* `pull_blocks_incorrect_hashes` an error is returned if no hash in `from` points to a block known to the server

I think those should have a consistent behavior (at least pull blocks and pull headers), maybe differentiating unknown blocks and empty values.

**Comment by mzabaluev** [comment]
@Zeegomo Thank you for the observations.

> In particular, when the blocks in from field are not present locally (or the list is empty)

I think all of these should result in an error. If the client accepts the possibility of pulling from genesis, they should include the genesis hash in `from`.

> `pull_headers_empty_start_hash` the whole chain (starting from the genesis to to) is returned when from is empty

This should be removed or converted to a test that exercises pull from genesis with the explicitly given genesis block hash in `from`.

> `pull_blocks_to_tip_incorrect_hash` the whole chain is returned when no hash in from points to a block known to the server.

This should be changed to testing for the error. Another test can be added giving the genesis and a hash not present in the block, to check that it pulls from genesis.

> `pull_blocks_incorrect_hashes` an error is returned if no hash in from points to a block known to the server

This is correct.

**Comment by mzabaluev** [comment]
Make sure to un-ignore the tests disabled in #3016 when done.

**Comment by mzabaluev** [comment]
All done.
