### ISSUE TITLE
No Bug, No Issue - just a question on jormungandr

### ISSUE THREAD

**Issue by kiwipool** [input-output-hk/jormungandr#3036]
Hey

Shelley Mainnet Stakepool Operator + jormungandr ITN Pool operator here.

Our jormungandr pools + nodes are all still running although I guess there is not much happening on the ITN any more? The last time I checked, the newer jormungandr releases didn't work with the old configs that I used to know.

I'm keen to refresh my jormungandr skills and get them up to date. Is there a new Testnet that I can point my servers at to keep the dream alive? Or info on how to update our exisiting ITN pool configs to be compatible with the latest jormungandr releases in order to connect to peers in the ITN if it is still being run?

Great to see so much work continuing on jormungandr!

Thanks

Cheers - Matt :)

**Comment by mzabaluev** [comment]
The ITN has been discontinued as per the community vote in the summer 2020.

The new development is mostly to support Catalyst and possible other deployments that make use of voting on the blockchain, as well as some newer experiments.
The upcoming 0.10 release is not to be compatible with the ITN nodes.
