### ISSUE TITLE
Improve the dynamic composition of tracing subscribers

### ISSUE THREAD

**Issue by mzabaluev** [input-output-hk/jormungandr#3040]
#2929 composes the `tracing` backends configured from logs as a chain of boxed `dyn Subscriber` objects and also had to implement `Subscriber` for `Box<dyn Subscriber + ...>`. There may be better performing and/or more idiomatic alternatives to compose a list of subscribers: with a star-like dispatch instead of a linear chain, using a different trait for dynamic dispatch, etc.

There are associated long-lived objects that need to be kept around to back some of the backends, like worker guards for `io::Writer` appenders and a future to back the GELF layer, so some struct in the `logging` module could be made to encapsulate that state.

**Comment by danielSanchezQ** [comment]
Ideally, this should be done with [layers](https://docs.rs/tracing-subscriber/0.2.15/tracing_subscriber/layer/trait.Layer.html). But it is trickier than it seems. The `with` extension returns a `Dispatch` object that changes its type signature depending on what it is holding, and it is not abstracted over any trait afaik. Since our approach is that we have dynamically size of subscribers it cannot be composed that way. One way of bypassing this would be to wrap the layers into an `Option<Layer>` for each subscriber we may have and then compose the results for the max size of them manually.

**Comment by mzabaluev** [comment]
> One way of bypassing this would be to wrap the layers into an Option<Layer> for each subscriber we may have and then compose the results for the max size of them manually.

One feature we currently have is we can have multiple log subscribers of the same type, so if we want to support that, we can't just compose all possible layers statically with `Option` and return the result in an anonymous impl type. At the front of the pipeline, there has to be a dynamically populated subscriber dispatching the messages to a list of boxed backends.

The frontend could also configure pre-filtering by noting the highest severity level configured across all backends and putting that as the global subscriber's filter.

**Comment by danielSanchezQ** [comment]
> One feature we currently have is we can have multiple log subscribers of the same type, so if we want to support that, we can't just compose all possible layers statically with `Option` and return the result in an anonymous impl type. At the front of the pipeline, there has to be a dynamically populated subscriber dispatching the messages to a list of boxed backends.

No way of doing that with the current layer API afaik. That is why I had to solve it with the dynamic boxing stuff. We could implement our own subscriber that dispatches things as we need to the list of boxed backends. But I don't see the behavior differs from what we have now.

> The frontend could also configure pre-filtering by noting the highest severity level configured across all backends and putting that as the global subscriber's filter.
That would be nice, but I think events will be raised anyway in runtime. So right now they would be discarded anyway too if I understood correctly.

**Comment by mzabaluev** [comment]
> We could implement our own subscriber that dispatches things as we need to the list of boxed backends. But I don't see the behavior differs from what we have now.

Yes, the behavior would not change, and even the potential performance gains are probably miniscule for typical setups of one or two backends.

Not necessary to do a star-dispatcher, but let's keep this around for code cleanup and better encapsulation.

**Comment by mzabaluev** [comment]
Closing this along with #3066. The remaining issues take unreasonable amount to work around with the current architecture of `tracing`. We'll simplify the logging to a single subscriber backend instead.
