### ISSUE TITLE
bootstrap.ps1 should be updated to latest config.yaml

### ISSUE THREAD

**Issue by qubicsys** [input-output-hk/jormungandr#3109]
**Describe the bug**
While running "bootstrap.ps1", I received this error:
 
Error in the overall configuration of the node
 |-> Error while parsing the node configuration file: log: invalid type: map, expected a sequence at line 3 column 8
 |-> log: invalid type: map, expected a sequence at line 3 column 8

Line 3 Column 8 refers to a location in config.yaml:

storage: "C:/Users/Rod/documents/gitprojects/jormungandr-node/storage/"
log:
  level: debug
  format: plain
  output: stderr
rest:
  listen: "127.0.0.1:48443"
p2p:
  trusted_peers: []
  public_address: "/ip4/127.0.0.1/tcp/8299"
  topics_of_interest:
    messages: low
    blocks: normal

**Mandatory Information**
1. `jcli --full-version` output;
2. `jormungandr --full-version` output;

PS C:\Users\Rod\documents\gitprojects\jormungandr-node> .\bootstrap.ps1
WorkDir: C:\Users\Rod\documents\gitprojects\jormungandr-node
PS Version:  + 5.1.19041.610

There is  JCLI v0.9.3.20200924 in use.
Should I upgrade to v0.9.3 ?
( Y / n ):
Default, update
Downloading https://github.com/input-output-hk/jormungandr/releases/download/v0.9.3/jormungandr-0.9.3-x86_64-pc-windows-msvc-broadwell.zip ...
Downloading https://github.com/input-output-hk/jormungandr/releases/download/v0.9.3/jormungandr-0.9.3-x86_64-pc-windows-msvc-generic.zip ...
Using jcli 0.9.3.20200924
Found an existing CONFIG folder (config) Remove it? (Default is Yes)
 ( Y / n ) : n
No, keep existing configuration
Found an existing DATA folder (storage) Remove it? (Default is Yes)
 ( Y / n ) : n
No, keep existing database
Found an existing SECRET folder (secret) Remove it? (Default is Yes)
 ( y / n ) : n
No, keep existing secrets
FAUCET_SK (ed25519e_sk1cruh65s35e8sga37qplvxkta7hj39ql9mt5sl6kqg7pawhfh29gz8nal6q9zued03q0s6f649mguayz87szqx7g0daexm5z9hxl54sq2qezh5)
FAUCET_PK (ed25519_pk1s5m2ymd893jpxnj0v73m2556zfefan0t59gl7mdmkng53sykdm9q5p4nsc)
FAUCET_ADDR (ca1skzndgnd5ukxgy6wfan68d2jngf898kdaws4rlmdhw6dzjxqjehv5zgx9a8)
Faucet keys: done
Fixed keys: done
LEADER_SK
LEADER_PK (ed25519_pk1rc6ekl5wle5mwwrcrfmx3pdzdxx3h6285xqs5xqmnvmf6z7mpu5s5hgud0)
leader keys: done
POOL_VRF_SK
POOL_KES_SK
POOL_VRF_PK (vrf_pk17gtdlthtdc8wu5rd452amvlwl5r059y5w5lspnwyvct4mrtydf2sn6737d)
POOL_KES_PK (kes25519-12-pk1c055k9ysla6u7sg300er3wzq64r5z9yljku5gudmx30zwnxk4wwqh00t9s)
stake-pool vrf and kes keys: done
stake-pool-registration certificate: done
stake-pool-delegation certificate 1: done
stake-pool-delegation certificate 2: done
poolsecret file: done
genesis block binary encoded: done
Do you want to start it now?  ( y / N ) : y
Made it here...error to follow...
Error in the overall configuration of the node
 |-> Error while parsing the node configuration file: log: invalid type: map, expected a sequence at line 3 column 8
 |-> log: invalid type: map, expected a sequence at line 3 column 8

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by eugene-babichenko** [comment]
This is now replaced with a single Python script for all platforms. Please check it out. https://github.com/input-output-hk/jormungandr/blob/master/scripts/bootstrap.py

**Comment by qubicsys** [comment]
Thanks!
