### ISSUE TITLE
cargo install failed on jormungandr

### ISSUE THREAD

**Issue by paedeveloper** [input-output-hk/jormungandr#3115]
hello guys, I'm trying to set up jormungandr and after installing the dependencies, this is an error that i am with.

``pae@fossabossax64:~/jormungandr$ cargo install --locked --path jormungandr
error: failed to read `/home/pae/jormungandr/testing/jortestkit/Cargo.toml`

Caused by:
  No such file or directory (os error 2)``

can anyone help 

Thank you

**Comment by dkijania** [comment]
jortestkit is no longer a part of jormungandr.. are you sure you are on newest master ?

**Comment by paedeveloper** [comment]
yes i am on the newest master with tag/v0.9.3

**Comment by mzabaluev** [comment]
You need to initialize submodules:

```sh
git submodule update --init
```

**Comment by paedeveloper** [comment]
thank you, it would be helpful to add this to the install instructions on README.md :)

**Comment by mzabaluev** [comment]
> thank you, it would be helpful to add this to the install instructions on README.md :)

Can do, but the submodule dependencies have been switched to be managed by cargo in master, so this will not be needed past the 0.9 branch.
