### ISSUE TITLE
Network outage and quarantine config

### ISSUE THREAD

**Issue by Zeegomo** [input-output-hk/jormungandr#3229]
Suppose there are 2 nodes, `A`, `B` . For some reason, the link that connects `A` to the other nodes goes offline, so that `A` is isolated.
What happens is that `A` quarantines `B` , because from her perspective it is not responding, and `B` will do the same with `A`.

Now, since they will not contact each other due to quarantine, there's no way they will get to talk again on their own, and the only fix is to restart either `A` or `B`.

Some ways we deal with this is the `preferred_layer`, that prevents peers from being quarantined, or the quarantine whitelist itself.

Before the recent poldercast update, the node tried to connect to quarantined nodes as well (I'm not sure if that was a bug or not, the jormungandr doc says it should not, but there are some outdated info there), so it was more resilient to such outages even without custom layers or quarantine whitelist.

That changed with the new quarantine: a single failure will put the `A` in quarantine and prevent the `B` from connecting to it and viceversa, and if that happens both ways the nodes are isolated.

What we could do:
* Nothing, nodes should use `preferred_list` or `quarantine_whitelist` if they want such functionality
* Forgive a report for nodes we connected to in the past (this is actually the default behavior for poldercast, which I override)
* Introduce reasons for a report (that is just connection failure now, but may change in the future), and still send gossips (but not fragments or nodes) to nodes that are quarantined because of a connection failure. Upon reception of a gossip from such nodes, remove them from quarantine.

**Comment by eugene-babichenko** [comment]
>  What happens is that A quarantines B , because from her perspective it is not responding, and B will do the same with A.

Shouldn't the quarantine be lifted after a timeout?

**Comment by eugene-babichenko** [comment]
I think this might be resolved with a sort of circuit breaker pattern:

1. After a few failures to communicate with a node we put it into quarantine.
2. After the quarantine is lifted we return to step 1.

This should add some "grace period" during which nodes should be able to restore the connection.

**Comment by Zeegomo** [comment]
> Shouldn't the quarantine be lifted after a timeout?

Yes, but the way it works is that the node will not be re-added to the view until we receive a new gossip about it, so that we won't re-add nodes that went offline "forever".

**Comment by eugene-babichenko** [comment]
Then what I decscribed should work. At least because it implies attempts to reconnect. :)

**Comment by Zeegomo** [comment]
I'm not sure I understand properly what you are saying, that way nodes will always try to talk to each other right? Eviction from the nodes pools will also happen at the same rate of "good" nodes, so there's the risk that a node will retain only dead ones in his topology.

Apart from that, there is a problem in the transition 2 -> 1, that is, we can't manually force a node back in the view because of how poldercast works. We could send a gossip to that node when exiting the quarantine though, so that if it is online, it will respond and will be re-added

**Comment by mzabaluev** [comment]
> Upon reception of a gossip from such nodes, remove them from quarantine.

Please clarify this. If our node is not connected to a quarantined node, we cannot receive gossip _from_ them, but we can receive gossip _of_ them from third parties?

**Comment by Zeegomo** [comment]
>  If our node is not connected to a quarantined node, we cannot receive gossip from them, but we can receive gossip of them from third parties?

if node `A` quarantines node `B` it will not contact him for propagation/gossip, but it will not actively drop incoming communications from `B`. For example, `B` could be have been restarted and/or have a clear record of `A`.

**Comment by mzabaluev** [comment]
> Forgive a report for nodes we connected to in the past (this is actually the default behavior for poldercast, which I override)

What is the reason for overriding it?

**Comment by mzabaluev** [comment]
> We could send a gossip to that node when exiting the quarantine

I think it's a good idea, but we should add logic to increase the quarantine period if this propagation attempt fails.

**Comment by Zeegomo** [comment]
Closed by https://github.com/input-output-hk/jormungandr/pull/3245.
