### ISSUE TITLE
REST: Add an endpoint to gather the account state

### ISSUE THREAD

**Issue by vincenthz** [input-output-hk/jormungandr#328]
**Is your feature request related to a problem/context ? Please describe if applicable.**

it's useful to get the state of a specific account from the node, specifically the spending counter.

**Describe the solution you'd like**

the REST endpoint takes an account id, then try to find it in the current ledger, then return some of the content (at the moment everything) of the mockchain::account::State structure in JSON

**Comment by CodeSandwich** [comment]
`mockchain::account::State` contains 2 fields: value and spending counter. Value is obviously a valuable piece of information, but are users interested in getting the counter?
