### ISSUE TITLE
Jormungandr node accepts incorrect transaction with amount smaller than initial utxo

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#332]
**Describe the bug**
Previously Jormungandr node was correctly verifying transactions correctness. Now it fails to do that 
when transaction input amount is smaller than initial utxo value.

**To Reproduce**
1. Create to utxo accounts
1. Start jormungandr with some initial utxo = 100 for first utxo account
2. Create transaction with input = 99 and output = 99 from first to second utxo account
3. Post transaction 
4. Transaction is accepted

**Expected behavior**
Transaction should be rejected

**Comment by NicolasDP** [comment]
Is it a UTxO or an Account ? if it is an UTxO, this is indeed a bug. If this is an account : then this is not a bug, it is a feature of the account.

**Comment by dkijania** [comment]
this is for UTXO, i think this is a regression. Please refer to the test case ``test jcli_transaction::input_output_tests::test_input_with_smaller_value_than_initial_utxo_is_rejected_by_node``` for more details

**Comment by NicolasDP** [comment]
The only way to guarantee a UTxO has been stored properly in the blockchain is *if* the UTxO is in the blocks of the blockchain. One way we allow you to test this is with the REST API command _GET UTxO_
