### ISSUE TITLE
Jormungandr node accepts incorrect transaction with wrong input transaction id

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#333]
**Describe the bug**
Previously Jormungandr node was correctly verifying transactions correctness. Now it fails to do that 
when transaction input id is incorrect.

**To Reproduce**
1. Create to utxo accounts
1. Start jormungandr with some initial utxo = 100 for first utxo account
2. Create transaction with incorect input transaction id
3. Post transaction 
4. Transaction is accepted

**Expected behavior**
Transaction should be rejected

**Comment by NicolasDP** [comment]
is it a UTxO or an account ?

**Comment by dkijania** [comment]
Utxo. Please refer to test case ```jcli_transaction::input_output_tests::test_transaction_with_non_existing_id_should_be_rejected_by_node``` for more details

**Comment by vincenthz** [comment]
all transactions are "accepted" since 86d532c145838629bd9afd80887cff2e4f838caa , but it doesn't means that it will be accepted on the blockchain ledger. we need to improve our transaction logs to be able to know what is the status of a transaction (including rejection reason)

**Comment by NicolasDP** [comment]
This will be improved with #350

**Comment by NicolasDP** [comment]
Same as in #332 the only valid way to check the transaction has been accepted is to check the UTxO state of the ledger or to check the block contents themselves. The REST API command *POST Transaction* accept the transaction but cannot know if the transaction is valid.
