### ISSUE TITLE
Different Blockdate format in /vote/active/plans endpoint depending on voting privacy 

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#3481]
**Describe the bug**
/vote/active/plans returns different BlockDate field format depending on voting privacy:

- Public
```
  "payload": "public",
  "vote_start": {
       "epoch": 4,
       "slot_id": 0
  },
 "vote_end": {
       "epoch": 58,
       "slot_id": 0
 },
 "committee_end": {
       "epoch": 92,
       "slot_id": 0
 },
```

- Private 
```
"payload": "private",
"vote_start": "0.0",
"vote_end": "24.0",
"committee_end": "81.0",
      
```

Which cause that VotePlanStatus struct cannot parse private vote plan status.

**Mandatory Information**
1. `jcli --full-version` newest master;
2. `jormungandr --full-version` newest master;

**To Reproduce**

**Expected behavior**
Both endpoints return parseable formats by jormungandr-lib crate

**Additional context**
[private.txt](https://github.com/input-output-hk/jormungandr/files/6921441/private.txt)
[public.txt](https://github.com/input-output-hk/jormungandr/files/6921443/public.txt)

**Comment by danielSanchezQ** [comment]
Fixed in https://github.com/input-output-hk/jormungandr/pull/3458
