### ISSUE TITLE
CARDANO TESTNET

### ISSUE THREAD

**Issue by bert2002** [input-output-hk/jormungandr#365]
Hi,
is it possible to connect the `jormungandr` node with the Cadano testnet? Wondering if we can generate or use the genesis block with the testnet with it.

Many thanks,
bert

**Comment by gufmar** [comment]
I recommend watching this: https://youtu.be/K6_EcEMbFoY

**Comment by bert2002** [comment]
Thanks @gufmar  very interesting and thought it would be much further already. :)
