### ISSUE TITLE
Network IP Address - Public vs Binding

### ISSUE THREAD

**Issue by phillewis** [input-output-hk/jormungandr#368]
**Is your feature request related to a problem/context ? Please describe if applicable.**
When starting jormungandr passing a configuration, the IP address used as a value for "public_address" is used as a binding address.  This causes a problem if the actual public IP that needs to be used for communicating across networks is different to the IP address available on the server.  If a private IP is used to allow proper binding, the server will not be accessible over public networks.

**Describe the solution you'd like**
A new setting for binding to an interface on the server is required.  This may not need to be a required setting, as the absence of the setting should cause binding to the default interface.  This will allow servers with dynamic addresses to be used so they don't need to be known beforehand.

**Additional context**
This is based on the documentation currently available.  If there already is a setting to support the separation of binding and public access, then please advise what it is.

This should also be applied to the REST service.  However as this doesn't broadcast its address to other servers, only support for dynamic addresses (i.e. default interface) is required.

**Comment by onicrom** [comment]
I like the idea to setting a particular interface but as a workaround you could set the listen addresses to 0.0.0.0 which would listen on all interfaces/addresses.

**Comment by mzabaluev** [comment]
We need a publicly reachable IP address to advertise in gossip and the like. I agree that there needs to be a separate setting for the binding address, which defaults to public address but may be set to 0.0.0.0 or a local interface address.

**Comment by phillewis** [comment]
Thanks @onicrom and @mzabaluev.

Rather than using the public address config item as the default for the local binding address, could the OS default be used?  Could you also confirm this will be applied to both the node service and the REST service?

**Comment by gufmar** [comment]
Maybe we should first list the probably typical setup's. 

1. The simplest case is a single node with public IP. 
2. There may also be nodes with private IP addresses in the LAN that are made public on a router with NAT. 
3. If multiple nodes form a cluster of one master and multiple proxy nodes, some of them may have private and/or public IP addresses.
4. There will be virtual and physical servers with multiple IP addresses or interfaces or even VPN links.
...

Based on this we can see how differentiated settings have to be, by now overcomplicating things.

My opinion regarding dynamic IPs:
If someone really wants to run a node with a dynamic IP address, he should probably also take care of determining it, entering it in the configuration file and restarting the services affected by it. (manually or 
 automatically)  This can be a third-party tool for click&play users and probably makes sense for all repeating/edge/home nodes, and not so much for pool nodes.

**Comment by phillewis** [comment]
Hi @gufmar, if the protocol requires that the node have the ability to advertise its public address then this will obviously need to be supported.

Having another setting for the local binding address should therefore allow for almost all other scenarios where it needs to be something different.

While unlikely (due to how most public IP addresses are used today) if the public IP was local to the server, then putting this as the value for both settings is not complicated.  By allowing the binding address to default to the OS default (rather than defaulting to the value set for the public address) it will support most use cases.  

If the public address is the default then this is catered for.  If the default is a private IP that is NATted to then this is catered for.

Just for clarity, when talking about dynamic addresses, I am referring to private addresses on the server that a static public address can NAT to.  If you are referring to dynamic addresses as dynamic public addresses, then I agree that this does add complication, unless this setting becomes a public hostname that can have its dynamic IP managed through a DNS service (but that takes this down a different path).

**Comment by onicrom** [comment]
It's less than ideal to require a sysctl change, but binding to a non-local ip is supported in Linux:
http://linux-ip.net/html/adv-nonlocal-bind.html

**Comment by mzabaluev** [comment]
I support most of points made by @gufmar in that we should mostly target scenarios where the node is deployed with a known public address and maybe a different, but still externally configured, private IP address. This should also work well in cloud deployments where a config.yaml could be created dynamically based on the parameters passed into a container or VM instance and the IP address binding does not change for the lifetime of an instance.

Some users with a dynamically assigned IP address behind a NAT could get by with configuring a static external IP address/port mapping and setting their local binding IP address to `::` or `0.0.0.0`. I don't think binding to all interfaces is a good default, though.

**Comment by mzabaluev** [comment]
> It's less than ideal to require a sysctl change, but binding to a non-local ip is supported in Linux:
> http://linux-ip.net/html/adv-nonlocal-bind.html

I prefer not to invest too much effort into platform-specific features at this point, as simpler alternatives are available that should cover a large part of intended usage.
