### ISSUE TITLE
Should attempt to reconnect to peers after some connection breakage conditions

### ISSUE THREAD

**Issue by mzabaluev** [input-output-hk/jormungandr#379]
When a client-side connection to a peer breaks (in current implementation, when any of the subscription streams get disconnected), that peer is removed from the connection map and may never be connected to again unless the p2p topology returns it.

With connections to trusted peers, the behavior should be different: when a connection fails or a previously established connection breaks, the node should consider reconnecting to avoid becoming isolated after a possibly intermittent drop in internet connectivity.

**Comment by mzabaluev** [comment]
Reconnection may not be necessary if some peer connections remain: it shouldn't be fatal to have all the initial trusted peers fall off the net as long as some peers discovered through gossip are reachable.

**Comment by dkijania** [comment]
Already Implemented by another PR

**Comment by mzabaluev** [comment]
This is obsolete: the trusted peers module in `poldercast` serves to treat trusted peers specially.
