### ISSUE TITLE
UTXO is not updated after successful transaction

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#387]
**Describe the bug**
if correct transaction is send to node. utxo is not updated with old utxo value while it should now be transaction

**To Reproduce**
1. Go to PR https://github.com/input-output-hk/jormungandr/pull/384
2. Run test **jcli::transaction::e2e::test_correct_utxo_transaction_replaces_old_utxo_by_node** by command:
`cargo test jcli::transaction::e2e::test_correct_utxo_transaction_replaces_old_utxo_by_node --features integration-test`

**Expected behavior**
test is passed

**Additional context**

**Comment by NicolasDP** [comment]
Thanks, Having failing tests in a PR is the way to go
