### ISSUE TITLE
Account is not created after successful utxo->account transaction

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#388]
**Describe the bug**
after correct transaction (utxo->account) is send to node and node has **allow_account_creation** option set to **true**. then if we want to fetch account data using jcli command:
```jcl rest v0 account get ta1sv0rtc9rwrty05lt4mxur7egzvyac7qz2l5j65v8z37s5pqfntk969w7z99 -h http://127.0.0.1:8073/api```

we are recieving error:

```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Status(400), "http://127.0.0.1:8073/api/v0/account/ta1sv0rtc9rwrty05lt4mxur7egzvyac7qz2l5j65v8z37s5pqfntk969w7z99")', src\libcore\result.rs:997:5```

**To Reproduce**
1. Go to PR https://github.com/input-output-hk/jormungandr/pull/384
2. Run test **jcli::transaction::e2e::test_account_is_created_if_transaction_out_is_account** by command:
`cargo test jcli::transaction::e2e::test_account_is_created_if_transaction_out_is_account --features integration-test`

**Expected behavior**
test is passed

**Additional context**

**Comment by vincenthz** [comment]
allow_account_creation is gone, and the jcli call should now be working
