### ISSUE TITLE
Allow logging to multiple outputs

### ISSUE THREAD

**Issue by CodeSandwich** [input-output-hk/jormungandr#392]
# Current design
## User input
- CMD provides verbosity in form of `-vvv` (default 0 a.k.a. `info`) and optional log format
- Config provides optional verbosity and optional log format
## Logger setup
- If config provides verbosity, it overwrites CMD verbosity
- If CMD does not provide log format, it's set to `plain`
- Logger uses CMD verbosity and log format
## Consequences
- Only 1 logging output
- Config log format is always ignored

# Design proposition
## User input
- CMD provides verbosity in form of `-vvv` (default 0 a.k.a. info) and optional log format
- Config provides **list** of structures with mandatory verbosity and log format, may be empty
## Logger setup
- Convert config list to list of loggers
- If CMD provides log format, create logger and append to list
- If list is still empty, append logger with CMD verbosity and `plain` format
- Create logger which dispatches logs to each logger using slog::Duplicate
## Consequences
- User can log to multiple outputs, some may have different logging levels from others
- Config log format is always respected
- Sane default - same as in current solution

**Comment by carl-shepherd** [comment]
Hello CodeSandwich,

We'd love to hear what you think of our customer service. Please take a moment to tell us. How would you rate the support you received? Please one of these in your reply that will help us to report on our efforts to the team.

Good, I'm satisfied
Bad, I'm unsatisfied

Thanks,
The IOHK Technical Support Desk Team

**Comment by mzabaluev** [comment]
We can change the config to enable this and roll this out together with #575.

The `log` section in `config.yaml` can contain a list of outputs with per-output settings:

```yaml
log:
  - stdout:
      format: plain
  - gelf:
      backend: graylog-host:9000
      log_id: node-1
```

**Comment by mzabaluev** [comment]
#621 adds a twist to requirements: multiple output backends may be configured in `config.yaml` and then one or some of them selected with the command line option.

cc @disassembler
