### ISSUE TITLE
Add different output formats for JCLI

### ISSUE THREAD

**Issue by CodeSandwich** [input-output-hk/jormungandr#395]
Currently JCLI outputs structured data as YAML.

The users might want to get it as JSON as well or even something else.

JCLI should provide special option for such commands, which will enable different formats.

**Comment by NicolasDP** [comment]
What about using the same as in `jcli transaction info` ? Let the user decide what is being printed by providing the format in the CLI?

**Comment by CodeSandwich** [comment]
I think you're referring to a `format` parameter. Example:
```
"Transaction `{id}' ({status})\n  Input:   {input}\n  Output:  {output}\n  Fees:    {fee}\n  Balance: {balance}\n"
```
This could be tricky when processing non-flat structures like JSON, which may have nested lists and structures.

I think that this could be an addition to JSON/YAML/etc. as yet another output format not replacement for them.

**Comment by carl-shepherd** [comment]
Hello CodeSandwich,

We'd love to hear what you think of our customer service. Please take a moment to tell us. How would you rate the support you received? Please one of these in your reply that will help us to report on our efforts to the team.

Good, I'm satisfied
Bad, I'm unsatisfied

Thanks,
The IOHK Technical Support Desk Team
