### ISSUE TITLE
jcli rest --host parameter being at the end of the command quite inconvenient

### ISSUE THREAD

**Issue by piotr-iohk** [input-output-hk/jormungandr#397]
**Is your feature request related to a problem/context ? Please describe if applicable.**
Currently pretty much every `rest` command on `jcli` requires host parameter which needs to be placed at the end of the command like: `jcli rest v0 tip get --host http://localhost:8607/api`. It is quite inconvenient as, pretty much always, one needs to put it by hand which makes working with `jcli rest...` rather painful.

**Describe the solution you'd like**
Possible solutions:
 - introduce something like `jcli rest save-host <host>` that would save host (perhaps in a file). Moving forward each `jcli rest...` command would simply read the host from this source which would make usage of `jcli rest...` more user friendly. I.e. `jcli rest v0 tip get` would be then enough.

 - move host from the end and put it as a positional parameter like `jcli rest http://localhost:8607 v0 tip get`. In this case user may use jcli with bash history more conveniently, i.e. simply get previous command from bash history and change it modifying only last arguments of the command 

**Additional context**
Add any other context about the feature request here.

**Comment by sjmackenzie** [comment]
much like adding remotes in git it would seem.

**Comment by sjmackenzie** [comment]
I'd prefer not even seeing `v0` and even `rest` its too implementation specific.

`jcli get account <account-id> [--host host]`
`jcli get block <block-id> [--host host]`
`jcli get next-blocks <block-id> <count>`
`jcli send transaction [file] [--host host]`
`jcli get node-stats [--host host]`
`jcli get tip [--host host]`
`jcli get utxo [--host host]`

something to this effect.


`

**Comment by mzabaluev** [comment]
IIRC the whole `rest` command was made to be able to exercise the REST API in an explicit way.
Still, it could be made more ergonomic: the API version does not need to be a stumbling block in every command, but be given with an option like `--version`. The latest version would be the default, and we currently only have version 0.

**Comment by NicolasDP** [comment]
the `v0` block is for another issue. If you want this discussed/considered please create another issue.

Regarding the problem of this issue: the `--host=` option should be set _globally_ in `clap` application. I am sure we can allow it to be set in dependently from the position (https://docs.rs/clap/2.33.0/clap/struct.Arg.html#method.global)

**Comment by dkijania** [comment]
It is solved by using env variable instead of host parameter.

```
export JORMUNGANDR_RESTAPI_URL=https://dryrun-servicing-station.vit.iohk.io/api
```
