### ISSUE TITLE
Documentation: Add documentation for all Node's working modes

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#419]
**Describe the bug**
Under chapter 1 we have documentation only for `Starting a passive node`. We need documentation also for the other working modes - "Leadership Node", "Leadership with Stake Pool Node", etc

**To Reproduce**
Documentation Link: https://input-output-hk.github.io/jormungandr/

**Expected behavior**
Each Node's working mode should have a different section under the documentation. Ideally, we should provide also a link to a script (that configures and starts the node) with the specific details. 

**Additional context**

**Comment by dkijania** [comment]
Fixed by #593
