### ISSUE TITLE
[v0.1.0] Stake Pool script generates wrong configuration on v0.1.0 

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#427]
**Describe the bug**
Script location: https://github.com/input-output-hk/jormungandr/blob/v0.1.0/scripts/stakepool-single-node-test
I receive a timeout error while starting the node with the default values generated by the script. Even I update the node config to use the localhost, I continue to receive some other errors. 
```
D:\iohk\otherProjects\jormungandr\scripts>jormungandr --genesis-block block-0.bin --config config.yaml --secret poolsecret1.yaml
Jun 07 09:27:07.596 INFO storing blockchain in '"/d/iohk/otherProjects/jormungandr/scripts/jormungandr-storage-test/blocks.sqlite"', task: init
Jun 07 09:27:07.611 INFO connecting to bootstrap peer 104.24.28.11:8299, task: bootstrap
Jun 07 09:27:28.637 ERROthread 'network ' panicked at 'not yet implementedfailed to connect to bootstrap peer: ConnectError(Http(Connect(Os { code: 10060, kind: TimedOut, mes
sage: "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has fa
iled to respond." })))', src\network\grpc\server.rs, :25:Error while loading the node's secrets.13

Invalid Node secret file: note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
genesis.sig_key: Invalid prefix: expected kes25519-12-sk but was kes25519-12-pk at line 2 column 12
```

**To Reproduce**
1. run the script 
2. start the node with the suggested command

**Expected behavior**
After generating the files with the script, the node should successfully start, generate blocks and accept transactions.

**Additional context**
Based on this thread the script version from master has more updates - https://input-output-rnd.slack.com/archives/GJY4XC3DM/p1559889042005700

**Comment by NicolasDP** [comment]
Yes, this issue has been addressed, initial script was providing a network configuration too which is not in the scope of the script (since it is starting a brand new blockchain).

The changes has been made in [0e6ff00a594bc1b199c3728c16283dc1369c604c](https://github.com/input-output-hk/jormungandr/commit/0e6ff00a594bc1b199c3728c16283dc1369c604c).

The work around until the next release is to apply the following changes in the node configuration file:

```diff
-  trusted_peers:
-    - id: 1
-      address: "/ip4/104.24.28.11/tcp/8299"
-  public_address: "/ip4/1.2.3.4/tcp/8299"
+  trusted_peers: []
+  public_address: "/ip4/127.0.0.1/tcp/8299"
```
