### ISSUE TITLE
gelf logging support for slog

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/jormungandr#447]
**Is your feature request related to a problem/context ? Please describe if applicable.**
We'd like to have gelf logging support via slog so we can send logs to a 3rd party service that supports gelf. The main reason for this is slog-syslog does not support windows so the only way to setup logging on windows to send to a 3rd party server would be to instruct end users to install nixlog, configure it to read a log file and forward it to a syslog server. Having gelf support to be able to send directly to graylog would be much simpler for the user to enable.
**Describe the solution you'd like**
Add gelf slog support (either with a custom implmenetation or 3rd party library)

**Comment by mzabaluev** [comment]
There is an [unpublished crate](https://github.com/lancastr/slog-gelf) that claims to integrate gelf support into slog.
