### ISSUE TITLE
Can't read secret key for creating witness with jcli

### ISSUE THREAD

**Issue by enzoc4** [input-output-hk/jormungandr#448]
**Describe the bug**

I'm getting the following error when trying to create a witness for a transaction with `jcli transaction make-witness`

```
could not decode secret file 'key.prv'
  |-> Failed to parse bech32, invalid data format
  |-> invalid character (code=
)
```
Error when using `jcli transaction make-witness` 

**To Reproduce**

```sh
jcli key generate --type=Ed25519Extended > key.prv
jcli transaction new > tx
jcli transaction id --staging tx
jcli genesis init > genesis.yaml
cat genesis.yaml | jcli genesis encode > block-0.bin
jcli transaction make-witness --genesis-block-hash $(cat block-0.bin | jcli genesis hash) --type utxo $(jcli transaction id --staging tx) witness key.prv > witness
```

**Expected behavior**
The witness generated in the _witness_ file without errors

**Additional context**

It works by with this change [here](https://github.com/input-output-hk/jormungandr/blob/07aa46afa3b74aa8e24612de86a1d8fb5753fa07/jcli/src/jcli_app/transaction/mk_witness.rs#L70) , so I think is a problem somewhere with the newline.

```Rust
SecretKey::try_from_bech32_str(&bech32_str).map_err(|source| Error::SecretFileMalformed {
```
```Rust
SecretKey::try_from_bech32_str(&bech32_str[0..&bech32_str.len() - 1]).map_err(|source| Error::SecretFileMalformed {
```

**Comment by NicolasDP** [comment]
Thanks, it looks like it is missing the [`trim_end()`](https://doc.rust-lang.org/stable/std/primitive.str.html#method.trim_end) in this code: https://github.com/input-output-hk/jormungandr/blob/07aa46afa3b74aa8e24612de86a1d8fb5753fa07/jcli/src/jcli_app/transaction/common.rs#L55-L59:

```rust
pub fn read_line<P: AsRef<Path>>(path: &Option<P>) -> Result<String, std::io::Error> {
    let mut line = String::new();
    io::open_file_read(path)?.read_line(&mut line)?;
    Ok(line)
}
```

**Comment by dkijania** [comment]
Just for the record, there is a workaround to just simply remove NEW_LINE from file. This is what we do in automation tests. We are not using pipe, but read output from command `jcli key generate --type=Ed25519Extended` as a single line (without NEW_LINE). Probably this is the reason why it was not discovered eariler.
