### ISSUE TITLE
stakepool-single-node-test throws errors with the new versions.

### ISSUE THREAD

**Issue by elviejo79** [input-output-hk/jormungandr#452]
When executing the lastest release of stakepool-single-node-test.sh
and the version 0.1.0 of jcli it throws the following error:

```
./stakepool-single-node-test.sh 
generated block is not a valid genesis block
  |-> Error or Invalid account
  |-> Account does not exist
```

**To Reproduce**
Downolad version 0.1.0 of jormungandr and jcli from releases.
and the script with release 0d6e01d37bbd39d49a36aa8b6caa98d7c177ac39
try to execute and you will get the error

**Expected behavior**
The script should execute cleanly

**Additional context**
I've also found that with the script in release  e4055a60a05db558f40e7330e86acde1ebabfe1f
it works perfectly

**Comment by ilap** [comment]
You should update the script then, by adding the "allow_account_creation: true" for the genesis block generation, see and example below:
``` bash
cat << EOF > genesis.yaml
blockchain_configuration:
  block0_date: $(date +%s)
  allow_account_creation: true
  discrimination: test
  slots_per_epoch: 5000
```

**Comment by vincenthz** [comment]
Dup of #388 #422

@elviejo79 current quickfix stop using 0.1.0 and use master. there will be a new release very soon
