### ISSUE TITLE
Missing section in documentation  - Jormungandr P2P

### ISSUE THREAD

**Issue by gmanroney** [input-output-hk/jormungandr#457]
**Describe the bug**
https://input-output-hk.github.io/jormungandr/quickstart/02_passive_node.html
The trusted peers are the nodes in the public network that your Node will trust in order to initialise the Peer To Peer network. More details in TODO: add chapter about Jormungandr P2P.
Needs section about P2P or have this removed until it is ready (if that is feasible)

**To Reproduce**
Go to
https://input-output-hk.github.io/jormungandr/quickstart/02_passive_node.html

**Expected behavior**
Section on Jormungandr P2P

**Additional context**

**Comment by enzoc4** [comment]
What could go in there? Do we have some idea?

**Comment by dkijania** [comment]
Fixed by #593
