### ISSUE TITLE
Cannot start stake pool with utxo faucet

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#465]
**Describe the bug**
After change https://github.com/input-output-hk/jormungandr/pull/440 there is a problem in starting stake pool with utxo faucet 

**To Reproduce**
1. run test case: jormungandr::genesis::start_node::test_genesis_stake_pool_with_utxo_faucet_starts_successfully
(in jormungandr-integration-tests)
2. test produces error during `jcli genesis encode command`:
```
Running command: "C:\\Work\\iohk\\jormungandr\\target\\debug\\jcli.exe" "genesis" "encode" "--input" "C:\\Users\\Nobody\\AppData\\Local\\Temp\\0812cdc1d8dc48a795e5d2160f8775c1\\genesis.yaml" "--output" "C:\\Users\\Nobody\\AppData\\Local\\Temp\\d0aefb91cb6c48a294d91833613bc563\\block-0.bin"
Error: generated block is not a valid genesis block
  |-> Error or Invalid account
  |-> Account does not exist
```

**Expected behavior**
stake pool starts successfully

**Additional context**
Possibly related to #403

**Comment by NicolasDP** [comment]
@dkijania , so #483 was not fixing this PR after all? :trollface:
