### ISSUE TITLE
jcli: Add a way to get fragment_id from a posted fragment

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#467]
**Is your feature request related to a problem/context ? Please describe if applicable.**
If we build a transaction with some id. and successfully send it to node (via jcli message post command). There is no way to correlate it to fragment id that is available with command (jcli message logs).

Example:

tx_id of posted transaction: `991a2739bdfb2a823041e9ae35f1bb18029bcc94bb36abcedbb9ea0b65586d57`

Fragment:
```- fragment_id: 2ad9768a1814383266ae8f97dfb80bfc7fc7101fd85daf3b23c2fdbd1138d66a
  last_updated_at: "2019-06-12T09:24:14.011399600Z"
  received_at: "2019-06-12T09:24:13.741416700Z"
  received_from: Rest
  status:
    InABlock: "61463.14"
```

**Describe the solution you'd like**
Either fragment has a field: source_tx_id or jcli will return fragment_id after we use `message post` command

**Comment by NicolasDP** [comment]
This has been addressed now. The fragment ID is displayed and there is no longer distinction between fragment ID and transaction ID
