### ISSUE TITLE
Documentation: Small improvements

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#470]
**Describe the bug**
1. Add example of submitting a Transaction for delegating stake (**both for Account and UTXO delegation**) - https://input-output-hk.github.io/jormungandr/stake_pool/delegating_stake.html

2. Add example for input when creating a Transaction and the source is an Account Address
- https://input-output-hk.github.io/jormungandr/jcli/transaction.html

3. Staking and Delegation - https://input-output-hk.github.io/jormungandr/stake_pool/delegating_stake.html
- it is not clear that: (i) rewards are not implemented yet, (ii) you cannot delegate part of a thing (account or utxo). in a case of an account you need to split the account into 2 accounts, in a case of utxo, you’d need to split your utxo into 2 utxos with 2 different grouping key.

4. Look and feel
  - Use same fonts/sizes/formats/capitalization in similar places
	- EX: https://input-output-hk.github.io/jormungandr/stake_pool/registering_stake.html
The paragraph titles have different sizes, one starts with a small letter, the other with capital one

5. Add links to the existing scripts - https://github.com/input-output-hk/jormungandr/tree/master/scripts (for Transaction, starting node)

**To Reproduce**
1. https://input-output-hk.github.io/jormungandr/stake_pool/delegating_stake.html.
- the section is ending in "The output can now be added in the transaction and submitted to a node." but it is not clear what values should you use for input,output, withnes when creating the delegation transaction

In order to Delegate the Stake from a Transaction to a Stake Pool, both for Account and UTXO addresses, you need to follow the below steps:
1. create a stake key pair - like here: https://input-output-hk.github.io/jormungandr/stake_pool/registering_stake.html
2. create and sign a Delegation Certificate like here: https://input-output-hk.github.io/jormungandr/stake_pool/delegating_stake.html
  - you need to use the public key generated at step 1 + desired stake pool ID (the one generated by the bootstrap script if you started the node using it)
3. create a delegation transaction using the below parameters
  - input
     - use the Personal Account (that you want to delegate)
     - as a value add the Transaction Fee (the remaining value of the Account will be Delegated) - somebody needs to pay the TxFee
     - EX
        - for Account: jCLI transaction add-account %sourceAccountAddress% 10 --staging transaction.tx
        - for UTXO: not tested yet
  - output
      - don't add any output
  - delegation certificate
      - add the signend delegation certificate before adding the witness and before finalizing the transaction
         - EX: jcli transaction add-certificate %acc_stake_delegation.signcert --staging transaction.tx
  - witness
      - as usual, use the private key of the account sourcing the transaction (the one that wants to delegate to the stake pool in this case)
  - finalize transaction as usual and send it to the node

NOTE: you cannot delegate part of an Account/UTXO. 

**Expected behavior**
The fonts/sizes/formats/capitalization should be consistent on all documentation pages.
There should not be any ambiguous configurations.

**Additional context**
2. When creating an offline transaction we have 2 cases based on the source address type (Account or UTXO); 
  - If the source address type is UTXO --> jcli transaction add-input  55762218e5737603e6d27d36c8aacf8fcd16406e820361a8ac65c7dc663f6d1c 0 100 --staging tx
  - if the source address type is Account --> jcli transaction add-account $FAUCET_ADDRESS $AMOUNT --staging $STAGING_FILE

**Comment by vincenthz** [comment]
@dorin100 many of the improvements above could be done instead of writing this issue :)
