### ISSUE TITLE
invalid --type=SumEd25519_12 for powershell execution

### ISSUE THREAD

**Issue by gufmar** [input-output-hk/jormungandr#478]
**Describe the bug**
seen in v0.1.0 and 0.2.0
`jcli.exe key generate --type=sumed25519_12` when executed in powershell cli shows

_error: Invalid value for '--type <key_type>': valid values: Ed25519 ,Ed25519Bip32 ,Ed25519Extended ,FakeMMM ,Curve25519_2HashDH_

Note: sumed25519_12 is not listed

**To Reproduce**
In a powershell CLI it's possible to generate all types of keys except SumEd25519_12
It shows an error without listing this type as a valid one.
```
EXEC:         jcli.exe key generate --type=Curve25519_2HashDH
POOL_VRF_SK:  OK
EXEC:         jcli.exe key generate --type=SumEd25519_12
error: Invalid value for '--type <key_type>': valid values: Ed25519 ,Ed25519Bip32 ,Ed25519Extended ,FakeMMM ,Curve25519_2HashDH
```

From a **classic windows command** line, it works as expected.
When I try an effective invalid type (Sumed12345_67) it shows the same sort of error as above but lists up the sumed type as a valid one

_error: Invalid value for '--type <key_type>': valid values: Ed25519, Ed25519Bip32, Ed25519Extended, **SumEd25519_12**, Curve25519_2HashDH_

**Expected behavior**
--type=SumEd25519_12 in powershell CLI should work the same way as all other key types

@NicolasDP I saw you wrote a ps1 script to prepare the windows builds as zip archives. this issue here blocks me at porting the test config script to windows environment.

**Comment by NicolasDP** [comment]
so if I understand the problem properly. it works well on windows `command` terminal. But not in the windows `PowerShell` terminal?

Sorry to ask, but are you sure you have updated your `jcli` ? It seems you are utilising 2 different version of `jcli`

**Comment by vincenthz** [comment]
clearly you're using an old version of jcli somewhere. `FakeMMM` shouldn't be in the list of key anymore. maybe an old version get picked up in the powershell version.

**Comment by rinor** [comment]
Not sure if it helps, but just tried both v0.2.0 windows releases (gnu & msvc) on PowerShell terminal and it works as expected.

**Comment by gufmar** [comment]
my mistake. Back in February I once tried to compile 0.0.1 on this computer and (don't remind why) executed a cargo install ...
I did all the powershell scripting with creation of all the files in a separate folder with copies of both exe's. 
TIL: command shell uses executable in local folder. Powershell's preference is whatever he may can find in a PATH variable folder.
