### ISSUE TITLE
documentation: improve the documentation for 'jcli rest v0 account get'

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#484]
**Describe the bug**
It is not clear what the 'delegation' values mean in the response from 'jcli rest v0 account get %faucetPublicKey% --host http://127.0.0.1:8607/api'

**To Reproduce**
1. start node using the bootstrap script 
2. execute jcli rest v0 account get %faucetPublicKey% --host http://127.0.0.1:8607/api

**Expected behavior**
The returned values should be self-explanatory or/and we should also include description inside the documentation. At this moment none of the 2 is true regarding the meaning of 'delegation'.

The example provided into the documentation does not contain the "delegation" response field at all. It should contain it + meaningful explanation. 

**Additional context**

```
jcli rest v0 account get %sourcePublicKey% --output-format json --host http://127.0.0.1:8607/api
{
  "counter": 1,
  "delegation": [
    73,
    184,
    89,
    25,
    20,
    83,
    99,
    28,
    72,
    169,
    158,
    207,
    181,
    204,
    2,
    137,
    242,
    207,
    205,
    54,
    165,
    202,
    205,
    57,
    23,
    79,
    201,
    225,
    133,
    35,
    3,
    170
  ],
  "value": 999999965
}
```

**Comment by mzabaluev** [comment]
Why do we feel the need to document something that was meant to be a way to test the REST API, rather than documenting the REST API itself (preferably with some formal-ish tool like swagger)?

If people need a more convenient CLI command to do something, there should be one outside `rest`. If the REST API itself is deficient, it should be improved.

**Comment by mzabaluev** [comment]
The `delegation` field looks like its value needs a more efficient text representation for JSON, rather than a dump of a byte array, but it's rather an issue with the API itself.

**Comment by dorin100** [comment]
Hi. The "delegation" response parameter is not documented at all at this moment even it is an important part of the main scenario (staking and delegation). There are 2 issues here:
1. the field is not documented at all
2. the field is not working at all - separate issue opened - #506

**Comment by dorin100** [comment]
The Delegation value is now more meaningful.
