### ISSUE TITLE
output and format of logger defined in config yaml is ignored

### ISSUE THREAD

**Issue by jbgi** [input-output-hk/jormungandr#494]
**Describe the bug**
Only command line arguments are taken into account for the logger output and format. Values defined in config file are ignored.

**To Reproduce**
Set logger output to `json` in config file.
Start jormungandr.
See log in plain text format.
start jormungandr with ` --log-format json`
See log in json text format.

**Expected behavior**

Output and format of logger defined in config file is used if not overridden by command line.

**Additional context**
Function to fix:
https://github.com/input-output-hk/jormungandr/blob/master/jormungandr/src/settings/start/mod.rs#L46

**Comment by jbgi** [comment]
looks like this was already mentioned in https://github.com/input-output-hk/jormungandr/issues/392

**Comment by NicolasDP** [comment]
not really, #392 is the idea of being able to set multiple logging output with multiple logging format and logging levels. You have found an issue with the current setting.

**Comment by jbgi** [comment]
Yeah, what I meant is that #392 mentioned this issue in the "Consequences" section:
> Config log format is always ignored
