### ISSUE TITLE
jcli add-certificate does not take fees into account

### ISSUE THREAD

**Issue by enzoc4** [input-output-hk/jormungandr#499]
**Issue**

`jcli add-certificate` can not be applied before `jcli finalize`, and it's the latter the one that computes the fees, but the fees also depend on the certificate.

**To Reproduce**

Try to add a certificate before `finalize`
See message: adding certificate to balancing transaction is not valid.

If you use `finalize`, then you can add the certificate but the balance doesn't change.

---
Probably the certificate should be added in the same stage that inputs and outputs (the finalize command does actually take the `--fee-certificate`), otherwise, it should update the fees later.

I think the check is [here](https://github.com/input-output-hk/jormungandr/blob/b8fd159afd531eba7ce101c2bfd5d9227999afb5/jcli/src/jcli_app/transaction/staging.rs#L146)

```rust
    pub fn set_extra(&mut self, extra: chain::certificate::Certificate) -> Result<(), Error> {
        match self.kind {
            StagingKind::Finalizing => Ok(self.extra = Some(Certificate(extra))),
            kind => Err(Error::TxKindToAddExtraInvalid { kind }),
        }
    }
```

**Comment by rinor** [comment]
Shoul be fixed by commit 1676dc41e7f9476af48a2d6061b2800ba3cf34f4
Now the _certificate_ can be added it the **same** stage (_balancing_) as input/output.

**Comment by rinor** [comment]
There is more work to do related to this issue, or it can be closed?

Based on latest changes the _certificate_ has to be added in the **balancing** stage, before finalazing the transaction.
https://github.com/input-output-hk/jormungandr/blob/5edc1d3e3e73f9fa4328cfff681cff6e0b768815/jcli/src/jcli_app/transaction/staging.rs#L146-L151

Just asking so we can [document](https://input-output-hk.github.io/jormungandr/stake_pool/delegating_stake.html#submitting-to-a-node) this change.

**Comment by enzoc4** [comment]
Well, I'm not quite sure that was enough... At least, from what I see, the finalize is ignoring the --fee-certificate anyways?
For example

```sh
jcli transaction new > tx
jcli transaction add-account ta1shxlja20rlyjm9cf7sj78zkysy3t0ynazv0h5pcdaselyrpg9tauwpsx4kk 1000 --staging tx
jcli transaction add-output ta1shxlja20rlyjm9cf7sj78zkysy3t0ynazv0h5pcdaselyrpg9tauwpsx4kk 100 --staging tx
jcli transaction add-certificate cert1qgqqqqqqqqqqqqqqqqqqq0p5avfqqlljr5wfhhp4q733auh2pd6xg9eqpgqc9g6ag243yx0lnled4urc7r4sljsv0ftpfscfzn8ap0lhvf4feesj62qvqk27ehzm7t6r7ejszqzqsgs2dmxnfry0x6jea639nfgjlhzfx4mw0xcnvlzpmj2qfpwpvlzdcu6p0pu783jeuxsy2h302asr0m5pzh58rc8rjsux43egft6avrgzfuwgg --staging tx
jcli transaction finalize ta1shxlja20rlyjm9cf7sj78zkysy3t0ynazv0h5pcdaselyrpg9tauwpsx4kk --fee-certificate 100 --staging tx
jcli transaction info --staging tx --fee-certificate 10
```
Shows me a perfectly balanced transaction without fees?
```
Transaction `ffe7d55f2a68166761bd4ac703b810ac8883c09d56417cea1a252417ebee10ae' (finalizing)
  Input:   1000
  Output:  1000
  Fees:    0
  Balance: 0
 - cdf9754f1fc92d9709f425e38ac48122b7927d131f7a070dec33f20c282afbc7 1000
 + ta1shxlja20rlyjm9cf7sj78zkysy3t0ynazv0h5pcdaselyrpg9tauwpsx4kk 100
 + ta1shxlja20rlyjm9cf7sj78zkysy3t0ynazv0h5pcdaselyrpg9tauwpsx4kk 900
```

Unless I'm not understanding something, shouldn't the output be 990?

**Comment by NicolasDP** [comment]
I just had a little look at this issue, there is a problem in the `finalize` function, at this line:

https://github.com/input-output-hk/jormungandr/blob/master/jcli/src/jcli_app/transaction/staging.rs#L172

This is because the `builder` function returns the transaction builder Typed to `NoExtra`:

https://github.com/input-output-hk/jormungandr/blob/master/jcli/src/jcli_app/transaction/staging.rs#L255-L259

While actually, in the `finalize` function we should have something similar to the `finalizer` function:

```rust
if let Some(certificate) = &self.extra {
    let transaction = self.transaction_with_extra(certificate);
    // balance and update inputs/outputs
} else {
    let transaction = self.transaction();
    // balance and update inputs/outputs
};
```

Ideally we should have a function, just like `Staging::id(&self) -> Hash` to gives us the estimated fee for us and to use that result in the `info` CLI output.

**Comment by enzoc4** [comment]
I think the biggest difference is that the [TransactionFinalizer](https://github.com/input-output-hk/rust-cardano/blob/13af7aa08cdac8efc9dc8b0f7ff9162d28b2d479/chain-impl-mockchain/src/txbuilder.rs#L187) is an `enum`, but the TransactionBuilder is a generic `struct`, so I think it may be necessary to implement some kind of wrapper sum type over the TransactionBuilder for the `builder()`function? And maybe over `tx::Transaction<Address, Extra>` (As the one for AuthenticatedTransaction [here](https://github.com/input-output-hk/rust-cardano/blob/13af7aa08cdac8efc9dc8b0f7ff9162d28b2d479/chain-impl-mockchain/src/txbuilder.rs#L198)?
