### ISSUE TITLE
Documentation: How to use the faucet-send-certificate.sh ?

### ISSUE THREAD

**Issue by elviejo79** [input-output-hk/jormungandr#505]
**Describe the bug**
When trying to execute the `faucet-send-certificate.sh` script it says that is lacking a <CERTIFICATE PATH> parameter.
However I don't know how or when I should have created said certificate.
It seems like I'm missing an intermediate step.

**To Reproduce**
```bash
$   ./faucet-send-certificate.sh 
usage: ./faucet-send-certificate.sh <CERTIFICATE PATH>
```

**Expected behavior**
I was expecting to be almos as transparent as the `faucet-send-money.sh` script

**Additional context**
This is how the output from the bootstrap script, in case the information there is relevant.

[initial_configuration.txt](https://github.com/input-output-hk/jormungandr/files/3295065/initial_configuration.txt)

**Comment by vincenthz** [comment]
this means:

`faucet-send-certificate.sh path/of/my/certificate`

what you send as certificate is really up to you, and the documentation on how to create those certificate is somewhere else.

**Comment by sanjaychandak** [comment]
I got the same problem, as there is no documentation to run the script without any problem, we need to guess what parameters we need to pass to the script, little or example can help to use this script better

Here what i tried where I am running my testnet on my machine
$ ls -lrt

-rw-r--r--. 1 root root 66 Jun 23 08:26 stake_pool_vrf.prv
-rw-r--r--. 1 root root 66 Jun 23 08:26 stake_pool_vrf.pub
-rw-r--r--. 1 root root 1974 Jun 23 08:27 stake_pool_kes.prv
-rw-r--r--. 1 root root 74 Jun 23 08:27 stake_pool_kes.pub
-rw-r--r--. 1 root root 122 Jun 23 08:31 stake_key.prv
-rw-r--r--. 1 root root 251 Jun 23 08:31 stake_pool.cert
-rw-r--r--. 1 root root 65 Jun 23 08:32 stake_pool.id
-rwxr-xr-x. 1 root root 2948 Jun 23 08:33 faucet-send-certificate.shtempl
-rw-r--r--. 1 root root 6000 Jun 23 08:35 my_node.log

[root@cardano]# ./faucet-send-certificate.shtempl

./faucet-send-certificate.shtempl: line 19: [: ####COLORS####: integer expression expected

usage: ./faucet-send-certificate.shtempl <CERTIFICATE-PATH> [ACCOUNT-SOURCE-SK]

<CERT-PATH> Path to a readable certificate file

[SOURCE] Source Secret key (if not present, use the faucet)



Which CERT-PATH and SOURCE do i need to use from the above file listing?

I also tried this but I got another issue about COLORS and CLI

 ./faucet-send-certificate.shtempl stake_pool.cert
./faucet-send-certificate.shtempl: line 19: [: ####COLORS####: integer expression expected
./faucet-send-certificate.shtempl: line 67: ####CLI####: command not found
