### ISSUE TITLE
jcli: After a Delegation Transaction was accepted by the node, the response of "jcli rest v0 account get %publicKeyPersonalAccount%" command does not update the value of the "delegation" parameter

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#506]
**Describe the bug**
Create a Transaction in order to Delegate the Stake from an Account Address to a Staking Pool. After the Transaction was accepted by the node run the "jcli rest v0 account get %publicKeyPersonalAccount%" command. The value of the "delegation" parameter is not changed.

**To Reproduce**
**Scenario**: 
1. execute bootstrap script (using -p and -g parameters)
2. start node
3. create the delegation keys + certificate + sign certificate (using the pool ID created by bootstrap script)
4. create a new (personal) Account + 1 transaction in order to send funds from Faucet to the new/personal account 
5. run the "jcli rest v0 account get %publicKeyPersonalAccount%" command and check the value of the "delegation" parameter
6. create a new (Delegation) Transaction in order to Delegate the Stake from the personal account to the staking pool created thru the bootstrap script
7. run the "jcli rest v0 account get %publicKeyPersonalAccount%" command and check the value of the "delegation" parameter --> it has the same value as the one from step 5

**Expected behavior**
The value of the "delegation" parameter should change to something meaningful (in order to make the difference between delegation ON and OFF).

**Additional context**

**Comment by vincenthz** [comment]
it's working as expected
