### ISSUE TITLE
jcli: add option to "jcli transaction info" command to request a specific transaction that was accepted by the node

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#508]
**Describe the bug**
If you have some transactions that were accepted by the node, there is no (at least documented) way to get the details of a specific transaction.

**To Reproduce**
1. create some transactions and wait for them to be accepted by the node

**Expected behavior**
You should be able to use "jcli transaction info" or a similar command to get the details of a specific transaction.

**Additional context**

**Comment by NicolasDP** [comment]
are the fragment logs not enough for this?

**Comment by dorin100** [comment]
If there is any mean to get the specific transaction details from the fragment logs, yes these should be enough (but we will need a procedure/documentation/example on how to get that).

**Comment by rinor** [comment]
I think now we can do it correctly. PR https://github.com/input-output-hk/jormungandr/pull/647 was finally merged.

**Comment by dkijania** [comment]
i think #647 is sufficient fix for this issue. Instead of getting id from transaction info you get it as a result of send operation
