### ISSUE TITLE
Logging to stdout

### ISSUE THREAD

**Issue by CodeSandwich** [input-output-hk/jormungandr#510]
Logger should be able to log to stdout. This may be useful for users and will be very useful for testing, as test runner has excellent interception and printing mechanism for this stream.

**Comment by mzabaluev** [comment]
Implemented in #587.

**Comment by mzabaluev** [comment]
Note also this helper in `slog-term`: [TestStdoutWriter](https://docs.rs/slog-term/2.4.0/slog_term/struct.TestStdoutWriter.html)

**Comment by NicolasDP** [comment]
implemented in #587
