### ISSUE TITLE
Documentation: address remarks of IOHK's Director of Engineering

### ISSUE THREAD

**Issue by ceilican** [input-output-hk/jormungandr#517]
The remarks are here: https://docs.google.com/document/d/1qxtcWOr8c-1zkQYSbIm-er8JbKPHbRv33bw8bgMODgE/ .

Please leave comments in the google doc if you decide not to address some of the remarks for some reason.

**Comment by sjmackenzie** [comment]
what's wrong with an open issue tracker so everyone can see?

**Comment by ceilican** [comment]
It is just a long list of mostly minor cosmetic suggestions. The document was produced before the reviewer was made aware that issues of the documentation were being posted in this issue tracker. It would be tedious and time-consuming to transfer everything here.

**Comment by sjmackenzie** [comment]
this is the equivalent of throwing a bag over the wall and saying "deal with it". It's far more polite to get the reviewer to transcribe the list into the correct process of submitting problems to this project. The issue tracker is designed to manage state associated with a project not a random word document.

**Comment by vincenthz** [comment]
private issues mostly been addressed I believe
