### ISSUE TITLE
Solidify ledger terminology in the network API

### ISSUE THREAD

**Issue by mzabaluev** [input-output-hk/jormungandr#523]
The method names and types in the network API use terms "content" and "message" to refer to ledger contents that constitute blocks. This was admittedly a stopgap coinage and we should change it to the terminology consistent with other documentation (provided such consistency is established elsewhere).

**Comment by mzabaluev** [comment]
@vincenthz proposed `Entry` to refer to an abstract ledger item in the storage API; I think it's a sufficently unambiguous term in the context of the other network protocol entities.

`ContentService` in network-core could be named `LedgerService` or (less preferred by me, but more mnemonic) `EntryService`.

**Comment by mzabaluev** [comment]
input-output-hk/chain-libs#48 uses Fragments now.

**Comment by NicolasDP** [comment]
@mzabaluev It seems to me we have finalize the renaming to `Fragment` now. Can we close this issue?
