### ISSUE TITLE
Logging to syslog via UDP

### ISSUE THREAD

**Issue by mzabaluev** [input-output-hk/jormungandr#525]
Would it be possible to have an option who let jormungandr log to udp localhost instead of unix sockets? For example with https://docs.rs/syslog/4.0.1/syslog/
There is an existing free open-source syslog server also available for windows hosts. It can be configured to accept/filter/reformat and also redirect messages in many different ways. (For example redirect to a global testnet syslog server)
He can also parse new messages out from a logfile written by Jormungandr but the direct, fast and cool way would be to send the messages directly to the syslog service. 
Will help then also in a multiple proxy node setup.

_Originally posted by @gufmar in https://github.com/input-output-hk/jormungandr/issues/511#issuecomment-502949717_

**Comment by carl-IOHK** [comment]
Linked to https://iohk.myjetbrains.com/youtrack/issue/IOHKS-157
