### ISSUE TITLE
Documentation: Improve the documentation related to Staking&Delegation 

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#530]
**Describe the bug**
There are 2 distinct cases: Account Delegation and UTXO Delegation
There should be made this distinction also inside the documentation: https://input-output-hk.github.io/jormungandr/stake_pool/delegating_stake.html

**To Reproduce**
https://input-output-hk.github.io/jormungandr/stake_pool/delegating_stake.html

Tested: in case of Account type addresses, the delegation certificate needs to be created and signed using the PERSONAL_ACCOUNT's keys so you should not create anymore the Delegation Keys Pair as per https://input-output-hk.github.io/jormungandr/stake_pool/registering_stake.html

**Expected behavior**
The end user should have all step-by-step details in order to be able to delegate the stake both for Account and UTXO addresses.

**Additional context**
*Scenario*:
1. start node using the bootstrap script
2. create a PERSONAL_ACCOUNT (`privateKey1`, `publicKey1`, `address1`)
3. send some funds from Faucet to PERSONAL_ACCOUNT
4. delegate the stake from the PERSONAL_ACCOUNT to the Stake Pool created thru the bootstrap script

**Comment by sanjaychandak** [comment]
I am also following this page (https://testnet.iohkdev.io/cardano/shelley/get-started/setting-up-stake-distribution/) to setup Stack&Delegation but when I tried to use the script I cant proceed further as there is no clear documentation on steps to proceed further. Only I could as of now is stake pool certificate creation and I can not send to the blockchain to register the stake pool with the other participants of the blockchain.

**Comment by dorin100** [comment]
Staking and Delegation documentation was improved - https://input-output-hk.github.io/jormungandr/stake_pool/delegating_stake.html

An example script was created too (generated thru bootstrap) - create-account-and-delegate.sh

Notes: 
1. the delegation certificate should be added inside the delegation transaction before finalizing the transaction
2. the delegation transaction should not have any output
3. when using Genesis-Praos mode, make sure that the transaction for sending money from Faucet to Account was included into a block before creating the Delegation one.
