### ISSUE TITLE
bootstrap error in genesis_praos, genesis file corrupted

### ISSUE THREAD

**Issue by AcostaJoshua** [input-output-hk/jormungandr#562]
Running "bootstrap.sh" and/or "bootstrap.sh -g", the following error is encountered:

> genesis file corrupted
  |-> blockchain_configuration.block0_consensus: Matching variant not found at line 14 column 21

__________________________________________

Configuration settings assumed to be valid, as "bootstrap.sh -b" for bfk consensus does not return this error.

Running on MacOS Mojave 10.14.5

Is this a new issue as of PR #560 	
> consensus version renamed `genesis_praos` instead of `genesis`

Or is this a user error?

<img width="680" alt="genesis block error" src="https://user-images.githubusercontent.com/51791990/59977298-955fd300-959d-11e9-975c-9b85fe62182a.png">

**Comment by vincenthz** [comment]
Thanks for reporting the issue. It looks like you're using the bootstrap from master on the 0.2.2 release, either get the bootstrap from 0.2.2 at https://github.com/input-output-hk/jormungandr/tree/v0.2.2/scripts or upgrade to 0.2.3 which is just out to fix this discrepancy
