### ISSUE TITLE
broken link, registering stake key guide

### ISSUE THREAD

**Issue by AcostaJoshua** [input-output-hk/jormungandr#565]
On page https://input-output-hk.github.io/jormungandr/advanced/03_starting_genesis_praos_blockchain.html
under "The stake key declaration" link for [registering stake key guide](https://input-output-hk.github.io/jormungandr/stake_pool/registering_stake.html) is broken.

**Comment by AcostaJoshua** [comment]
![image](https://user-images.githubusercontent.com/51791990/59985891-033de600-9602-11e9-9ec5-23c0d834b6a9.png)

**Comment by dorin100** [comment]
fixed by https://github.com/input-output-hk/jormungandr/pull/629

**Comment by dorin100** [comment]
@vincenthz - you can close this (I cannot do it).
