### ISSUE TITLE
new-key-registration missing under "jcli certificate new"

### ISSUE THREAD

**Issue by AcostaJoshua** [input-output-hk/jormungandr#566]
From [registering_stake.md](https://github.com/input-output-hk/jormungandr/blob/stake_pool_setup/doc/stake_pool/registering_stake.md)
The sub-command **stake-key-registration** should exist under _jcli certificate new_, however it is missing.
![image](https://user-images.githubusercontent.com/51791990/59986338-72b4d500-9604-11e9-9192-706eb89074bf.png)
![image](https://user-images.githubusercontent.com/51791990/59986428-d6d79900-9604-11e9-8b0e-e57a6e561060.png)

**Comment by rdlrt** [comment]
I think you're in the wrong branch, please check the doco from master branch instead. Key registration is not valid [anymore](https://github.com/input-output-hk/jormungandr/pull/461)
