### ISSUE TITLE
How to use the faucet-send-certificate.sh ?

### ISSUE THREAD

**Issue by sanjaychandak** [input-output-hk/jormungandr#571]
**Describe the bug**
I got the problem while using this script, as there is no documentation to run the script without any problem, we need to guess what parameters we need to pass to the script, little or example can help to use this script better

**To Reproduce**
Here what i tried where I am running my testnet on my machine
$ ls -lrt

-rw-r--r--. 1 root root 66 Jun 23 08:26 stake_pool_vrf.prv
-rw-r--r--. 1 root root 66 Jun 23 08:26 stake_pool_vrf.pub
-rw-r--r--. 1 root root 1974 Jun 23 08:27 stake_pool_kes.prv
-rw-r--r--. 1 root root 74 Jun 23 08:27 stake_pool_kes.pub
-rw-r--r--. 1 root root 122 Jun 23 08:31 stake_key.prv
-rw-r--r--. 1 root root 251 Jun 23 08:31 stake_pool.cert
-rw-r--r--. 1 root root 65 Jun 23 08:32 stake_pool.id
-rwxr-xr-x. 1 root root 2948 Jun 23 08:33 faucet-send-certificate.shtempl
-rw-r--r--. 1 root root 6000 Jun 23 08:35 my_node.log

[root@cardano]# ./faucet-send-certificate.shtempl

./faucet-send-certificate.shtempl: line 19: [: ####COLORS####: integer expression expected

usage: ./faucet-send-certificate.shtempl [ACCOUNT-SOURCE-SK]

Path to a readable certificate file

[SOURCE] Source Secret key (if not present, use the faucet)

Which CERT-PATH and SOURCE do i need to use from the above file listing?

**Expected behavior**
I was expecting to be almost as transparent as the faucet-send-money.sh script

**Additional context**
I also tried this but I got another issue about COLORS and CLI

./faucet-send-certificate.shtempl stake_pool.cert
./faucet-send-certificate.shtempl: line 19: [: ####COLORS####: integer expression expected
./faucet-send-certificate.shtempl: line 67: ####CLI####: command not found

**Comment by vincenthz** [comment]
you likely skip many of the instructions. you should not be running the .shtempl file, but the .sh file that you get *AFTER* running the `bootstrap` script.

**Comment by vincenthz** [comment]
This repository is mainly for developer bug report, if you need support you should be opening issue there: https://github.com/input-output-hk/shelley-testnet/
