### ISSUE TITLE
Improve naming in config YAML

### ISSUE THREAD

**Issue by mzabaluev** [input-output-hk/jormungandr#575]
Names used in configuration YAML can be made more concise and memorable. Tracking this to roll out next time we are about to break it for our users. We could opt for a soft change as well, with the old names supported for backward compatibility.

- [x] Rename `logger` to `log`. The users are interested in logs, not in an internal subsystem named 'logger". Also to correspond with command line options `--log-format` and `--log-output`.
- [x] Rename `topics_of_interests` to just `topics` (one word, easier to remember) or `topics_of_interest` (more likely remembered this way by English language users).

**Comment by gufmar** [comment]
+1 for more concise and memorable names, and better now than later.
As already seen with renaming "genesis" to "genesis_praos" this creates some unexpected :-(? moments for the users. But on the other side, it makes them think about and have a better understanding.

**Comment by NicolasDP** [comment]
renaming topics_of_interest into topics is not a good choice. the understanding that this is registering the level of interest into a given topic is lost.

**Comment by mzabaluev** [comment]
Now it's not even `topics_of_interest`, but `topics_of_interests`. The more words, the harder to remember which spelling needs to be used.

**Comment by mzabaluev** [comment]
All renamings discussed have been done.
