### ISSUE TITLE
No blocks are created if there is no stake in the system and node is restarted. 

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#576]
**Describe the bug**
If I empty my faucet to a newly created address without delegation, stop and restart my node, then no additional blocks are created.

**To Reproduce**
1. execute bootstrap script with: bootstrap -g
2. create a new account address (no delegation)
3. send all funds from Faucet to the newly created address (used faucet-send-money script)
4. wait for the transaction to be included in a node and for some more blocks to be created
5. stop node 
6. start node with the exact parameters from step 1
--> no blocks are created anymore

**Expected behavior**
There should be an indication if the node cannot work normally.

**Additional context**
If there are any funds in the Faucet (that is delegating its stake), the nodes are created normally after node restart.

**Comment by psychomb** [comment]
I could reproduce the situation without stopping and restarting the node - No step 5 and step 6 required - I have precised this on the initial issue here : https://github.com/input-output-hk/shelley-testnet/issues/17
The node simply stops producing blocks without any other intervention.
This non-requirement for restart might be double checked by someone else

**Comment by dorin100** [comment]
Thank you @psychomb for the details. In my case, the node continued to produce blocks even after all funds from Faucet were sent to the non-delegated account. 

Based on @vincenthz 's comment (https://github.com/input-output-hk/shelley-testnet/issues/17#issuecomment-505017314), we might be at the boundary of a new epoch. Anyway, this case needs more investigation from dev team and most probably a fix.

**Comment by vincenthz** [comment]
for now, we're not going to solve this problem, and have other general plan for this edge case.
the bootstrap script now create a shadow faucet that contains coins so that it can cope with the faucet being actually empty
