### ISSUE TITLE
cargo install compile fail

### ISSUE THREAD

**Issue by cliffc2** [input-output-hk/jormungandr#581]
after cfg-if v0.1.9
compiling error: linker 'cc' not found
no such file or dir (os err 2)
![Screenshot (4)](https://user-images.githubusercontent.com/52220259/60154224-360df700-9819-11e9-8be9-a422fb94c7a2.png)

**Comment by mzabaluev** [comment]
The C compiler needs to be installed. I've proposed to add this requirement in the steps of installation from source in #582.
