### ISSUE TITLE
bootstrap script error

### ISSUE THREAD

**Issue by kengo198979** [input-output-hk/jormungandr#602]
Hello.
I attempted to install testnet, but  the following error occurred.

`# ./bootstrap.sh 
########################################################

* Consensus: genesis_praos
* REST Port: 8443
* Slot duration: 10

########################################################

* CLI version: jcli 0.2.3
* NODE version: jormungandr 0.2.3

########################################################

genesis file corrupted
  |-> initial[0].fund[0]: invalid type: map, expected a string at line 19 column 16
error: building the genesis block`

My PC system is debian 9.5, linux kernel is 4.9.0-8-amd64.
Please tell me this solution.

**Comment by vincenthz** [comment]
you're not using the right version of the script: you need to use the version associated with the version you're using (0.2.3), at https://github.com/input-output-hk/jormungandr/tree/v0.2.3/scripts
