### ISSUE TITLE
gelf logging broken

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/jormungandr#621]
**Describe the bug**
Because of the new structure of gelf logging can no longer be enabled at runtime with a single flag. With 0.2.3 we used the `--log-output` parameter to set it to gelf and defaulted in the config to stderr. The main reason for this is GDPR requiring the user to specifically choose to send IOHK their logs. I think this primarily is a result of log-output being switched to a attribute set in the case of gelf logging where it's a string otherwise, and the server and unique ID used to be at the top level, so it was just a string that needed changed at runtime to enable logs to be sent.

Easiest way to reproduce is `nix-shell --argstr logger_output gelf` in jormungandr-nix.

This diff of the configuration generation fixes the problem, but it makes it always on in the snappy package which could be complicated with GDPR so I haven't pushed a new working snappy package yet. The problem in snappy is the config file is pre-generated and there's no nix-build the user does to rebuild the config file, so we need a way at runtime to enable gelf logging without having to alter the configuration file.

```
--- i/nix/make-config.nix
+++ w/nix/make-config.nix
@@ -14,12 +14,17 @@
 }:
 with lib; builtins.toJSON {
   storage = storage;
-  logger = {
+  logger = let
+    output = if logger_output == "gelf" then {
+      gelf = {
+        backend = logger_backend;
+        log_id = logs_id;
+      };
+    } else logger_output;
+  in {
     verbosity = logger_verbosity;
     format = logger_format;
-    output = logger_output;
-    backend = logger_backend;
-    logs_id = logs_id;
+    output = output;

```

**Expected behavior**
Log using the gelf config when `--log-output` is set to gelf.

**Comment by mzabaluev** [comment]
I believe it's currently possible, as a workaround, to have a GELF output configuration in `config.yml`, but override it with logging to stdout/stderr with the command line option.

Proper command line support should take multiple outputs (#392) into consideration.

**Comment by NicolasDP** [comment]
I believe that we should not expose complex command line options. Multiple outputs is rather a complex settings and it is easier for users to utilise the configuration file to set them than utilising the command line options.

**Comment by disassembler** [comment]
Resolving by generating duplicate config with gelf enabled at build time of jormungandr-nix.
