### ISSUE TITLE
Log Level consistency between CLI and config file

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/jormungandr#622]
The log level management is not very clear and or consistent between what is available in the command line options and what can be defined in the config file.

We need to have a more consistent log level settings across the board:

- [ ] remove `--verbose` option and utilise `--log-level` instead in the command line options. We can use the `slog`'s [`Level`](https://docs.rs/slog/2.4.1/slog/enum.Level.html) directly as it implements `FromStr` and `Display`. The default value would be `None`.
- [ ] update the configuration file's `log_level` setting to take the same strings as in the command line option (for consistency), the default value would be `Level::Info`
- [ ] if the command line option is set, it overrides whatever is in the configuration file.
- [ ] update the bootstrap scripts and the documentation to reflect the changes

**Comment by mzabaluev** [comment]
While you are at it, notice that currently the release builds do not compile `debug!` and above, and the debug builds would not compile `trace!` if anyone ever decide to use it. This can be changed with [slog compile-time features](https://docs.rs/slog/2.4.1/slog/#notable-details).

**Comment by mzabaluev** [comment]
As this is going to be a breaking change, we can do some of the renaming discussed in #575.
