### ISSUE TITLE
add-output example missing value

### ISSUE THREAD

**Issue by sedwardstx** [input-output-hk/jormungandr#628]
**Describe the bug**
https://input-output-hk.github.io/jormungandr/jcli/transaction.html

The example for step to **Add output** is incorrect.

For the output, we need the address we want to transfer to, **and the amount**.
**Example:**
jcli transaction add-output  ca1qvnr5pvt9e5p009strshxndrsx5etcentslp2rwj6csm8sfk24a2wlqtdj650 --staging tx

The above example is missing a **value** and throws an error.

jcli transaction add-output xyzsomeaddressxyz --staging tx
error: The following required arguments were not provided:
    **<value>**

**Comment by dorin100** [comment]
fixed by https://github.com/input-output-hk/jormungandr/pull/629

**Comment by dorin100** [comment]
@vincenthz - you can close this (I cannot do it).
