### ISSUE TITLE
Cargo install --path jormungandr fails

### ISSUE THREAD

**Issue by khwerhahn** [input-output-hk/jormungandr#638]
**Describe the bug**
cargo install --path jormungandr fails to run on MacOS 10.14.5 (18F203) and throws the following error:

```
error: failed to compile `jormungandr v0.3.0 (/Users/xxx/Documents/development/jormungandr/jormungandr)`, intermediate artifacts can be found at `/Users/xxx/Documents/development/jormungandr/target`

Caused by:
  failed to load source for a dependency on `actix-net`

Caused by:
  Unable to update registry `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to authenticate when downloading repository
attempted ssh-agent authentication, but none of the usernames `git` succeeded

Caused by:
  no authentication available
```

**Comment by onicrom** [comment]
similar here
error: could not find `jormungandr` in registry `https://github.com/rust-lang/crates.io-index`

**Comment by rinor** [comment]
Do you have smth like:
```
[url "git@github.com:"]
  insteadOf = https://github.com/
```
inside `~/.gitconfig`?

**Comment by onicrom** [comment]
> 
> 
> Do you have smth like:
> 
> ```
> [url "git@github.com:"]
>   insteadOf = https://github.com/
> ```
> 
> inside `~/.gitconfig`?

I have something custom in there yes.  I have multiple github accounts and differentiate which key to use based on the host i assign:

Host userabc-githhub
  Hostname github.com
  User git
  IdentityFile /path/to/userabc-github

Host userxyz-githhub
  Hostname github.com
  User git
  IdentityFile /path/to/userxyz-github

**Comment by rinor** [comment]
@onicrom : the error you describe looks related to the command usage ex: 
- `cargo install jormungandr` (missing --path), results in such error.
- `cargo install path jormungandr` (missing -- before path), results in similar error. 

Can you still confirm that `cargo install --path jormungandr` errors?

**Comment by onicrom** [comment]
> 
> 
> @onicrom : the error you describe looks related to the command usage ex:
> 
>     * `cargo install jormungandr` (missing --path), results in such error.
> 
>     * `cargo install path jormungandr` (missing -- before path), results in similar error.
> 
> 
> Can you still confirm that `cargo install --path jormungandr` errors?

Thank you.

*face palm*
$ cargo install --force jormungandr
vs
$ cargo install --force --path jormungandr

**Comment by khwerhahn** [comment]
> Do you have smth like:
> 
> ```
> [url "git@github.com:"]
>   insteadOf = https://github.com/
> ```
> 
> inside `~/.gitconfig`?

@rinor  Yes I do. 

and `cargo install --path jormungandr`still errors. Also neither of @onicrom suggested `cargo install...`versions worked.

**Comment by rinor** [comment]
@khwerhahn : can you please comment those lines or remove it with `git config --global --remove-section url."git@github.com"` and try again.

**Comment by rinor** [comment]
@khwerhahn 
also if you **don't want to delete** that config from .gitconfig can you try with:
- `env CARGO_NET_GIT_FETCH_WITH_CLI=true cargo install --path jormungandr`

**Comment by khwerhahn** [comment]
@rinor `env CARGO_NET_GIT_FETCH_WITH_CLI=true cargo install --path jormungandr`did the trick. Thank you! You might want to add this to the documentation?

There were some warnings though:
```
warning: unreachable expression
  --> jormungandr/src/fragment/process.rs:93:23
   |
93 |                     B(future::ok(unimplemented!()))
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(unreachable_code)] on by default

warning: unused variable: `tip`
   --> jormungandr/src/blockchain/chain.rs:331:10
    |
331 |     let (tip, tip_info) = blockchain.get_block_tip()?;
    |          ^^^ help: consider prefixing with an underscore: `_tip`
    |
    = note: #[warn(unused_variables)] on by default

warning: unused variable: `subscriber`
   --> jormungandr/src/network/service.rs:225:9
    |
225 |         subscriber: Self::NodeId,
    |         ^^^^^^^^^^ help: consider prefixing with an underscore: `_subscriber`

    Finished release [optimized] target(s) in 4m 51s
  Installing /Users/xxx/.cargo/bin/jormungandr
   Installed package `jormungandr v0.3.0 (/Users/xxx/Documents/development/jormungandr/jormungandr)` (executable `jormungandr`)
```

**Comment by rinor** [comment]
@khwerhahn glad it worked.
Those warnings are harmless and will be handled over time.

> You might want to add this to the documentation?

Sure, but please keep in mind that it is not related to `jormungandr` itself, but to `cargo` (**libgit2** library to be more exact, IIRC) and manifests itself under some specific circumstances. 

Please check https://github.com/rust-lang/cargo/issues/2078 if you want more information.

**Comment by Rankgor** [comment]
![image](https://user-images.githubusercontent.com/35565656/61588356-8b051900-abdd-11e9-8c53-bc8f080ae808.jpg)

Hello 
I have tried all of the above,,, sorry I am still a novice, I keep getting
Failed to select a version for the requirement slog = “^2.5.1”

**Comment by psychomb** [comment]
A post on behalf of @rinor : 
Once you git cloned, you can run the following to circumvent the slog issue : 

     cargo fetch
     cargo build --release --frozen

Then, copy the freshly created binaries from target/release into your ''~/.cargo/bin/'' folder. 
You can check that it worked by typing 

     jcli -V
     jormungandr -V

**Comment by Rankgor** [comment]
Thank you I will give it a go.  👍🏻

**Comment by Rankgor** [comment]
Thank you for your help,
everything work until i tried to connect.
any help wold be great, seem to going around in circles. 




four@four-System-Product-Name:~/jormungandr-node/jormungandr$ chmod +x scripts/bootstrap
four@four-System-Product-Name:~/jormungandr-node/jormungandr$ cd ..
four@four-System-Product-Name:~/jormungandr-node$ mkdir selfnode
four@four-System-Product-Name:~/jormungandr-node$ cd selfnode/
four@four-System-Product-Name:~/jormungandr-node/selfnode$ ../jormungandr/scripts/bootstrap | tee node_config.txt
########################################################

* Consensus      : genesis_praos
* REST Port      : 8443
* Slot duration  : 10
* Slots per epoch: 5000

########################################################

* CLI  version: jcli 0.3.1
* NODE version: jormungandr 0.3.1

########################################################

faucet account: ca1shfcuwpnd506vdwczjkwpyyzrxp20j7f6y7w0dcmfl4wdtwetezlqectewh
  * public: ed25519_pk16w8rsvmdr7nrtkq54nsfpqses2nuhjw38nnmwx60atn2mk27ghcq76sfsj
  * secret: ed25519e_sk1fzn02ap9xtew5dluju7c0mlls8qvla7z5z3ved29rflm30nqdpg2uw0tzgk2cn3afvdwc3adjvpl05s36cwt42vzjtl5px5gm7v0klc8fv78h
  * amount: 1000000000000

pool id: 648050e50acee4f12cafe1400832ecdcb781ac4a201723953971739605b0bc6e
block-0 hash: 06023cda3015b1b8ee8ba7cff2799eb0c939f05437c0a4fe5b7d156e60c3c2b3

To start the node:
  jormungandr --genesis-block ./block-0.bin --config ./config.yaml --secret ./pool-secret1.yaml
To connect using CLI REST:
  jcli rest v0 <CMD> --host "http://127.0.0.1:8443/api"
For example:
  jcli rest v0 node stats get -h "http://127.0.0.1:8443/api"
four@four-System-Product-Name:~/jormungandr-node/selfnode$ jormungandr --genesis-block ./block-0.bin --config ./config.yaml --secret ./pool-secret1.yaml &> my_node.log &
[1] 25427
four@four-System-Product-Name:~/jormungandr-node/selfnode$ jcli rest v0 account get ca1shfcuwpnd506vdwczjkwpyyzrxp20j7f6y7w0dcmfl4wdtwetezlqectewh -h "http://127.0.0.1:8443/api"
could not connect with node
  |-> http://127.0.0.1:8443/api/v0/account/d38e38336d1fa635d814ace090821982a7cbc9d13ce7b71b4feae6add95e45f0: error trying to connect: Connection refused (os error 111)
  |-> Connection refused (os error 111)
[1]+  Exit 2                  jormungandr --genesis-block ./block-0.bin --config ./config.yaml --secret ./pool-secret1.yaml &> my_node.log
four@four-System-Product-Name:~/jormungandr-node/selfnode$

**Comment by rinor** [comment]
Can someone close this issue. It is becoming a dumping place ...
If deemed necessary we can create another issue related to `CARGO_NET_GIT_FETCH_WITH_CLI=true` regarding docs/readme
