### ISSUE TITLE
Node crash with Crit error when sending multiple transactions from the same Account, with the same Counter, in 2 consecutive slots

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#641]
**Describe the bug**
The Node is crashing at the beginning of the second slot when continuously sending transactions from Account 1 to Account 2 (using the same value for ACCOUNT1_COUNTER). If you use different/incremental ACCOUNT1_COUNTER values, the node will not crash. 

**To Reproduce**
1. use this branch/repo - `https://github.com/dorin100/jormungandr`
- `multiple-transactions-per-slot-2-accounts-same-counter.sh` generated through bootstrap script
2. go to the scripts folder
3. execute the bootstrap script -> `bash bootstrap -b`
4. execute multiple-transactions-per-slot-2-accounts-same-counter script -->` bash multiple-transactions-per-slot-2-accounts-same-counter.sh 20`

**Expected behavior**

**Expected result**: Only the first transaction should be accepted and included into a new block (the one with the correct Counter - the other will have Counter < actualCounter). The node should not crash and not Critical error should be shown.

**Additional context**
The steps executed by `multiple-transactions-per-slot-2-accounts-same-counter.sh` script are:
1. create 2 accounts and send 10000000 Lovelaces from Faucet to each account
2. create a loop of transactions, sending funds from Account 1 to Account 2 that would span on 2 consecutive slots
- the SOURCE_ADDR_COUNTER (used for witness) is ALWAYS the same = 0

Logs:
- [nodeLogs.txt](https://github.com/input-output-hk/jormungandr/files/3397968/nodeLogs.txt)
- [scriptLogs.txt](https://github.com/input-output-hk/jormungandr/files/3397969/scriptLogs.txt)

**Comment by rinor** [comment]
@dorin100 
1. can you provide `multiple-transactions-per-slot-2-accounts-same-counter` .sh or .shtempl, just to be on the same page with testing. I couldn`t find it in your repo.
2. Based on your logs the binaries are from release 0.2.4 ca7be06

**Comment by dorin100** [comment]
this is no longer reproducible on v0.3.0. Thanks again @rinor
