### ISSUE TITLE
v0.3.1 Cannot Compile

### ISSUE THREAD

**Issue by DavidArayan** [input-output-hk/jormungandr#648]
**Describe the bug**
Hello. Just trying to compile v0.3.1 of the code in alpine but failing to compile. Should note that v0.3.0 compiled properly.

Error is as follows.

```
failed to compile jormungandr v0.3.1
Caused by:
failed to select a version for the requirement slog = "^2.5.1"
candidate versions found which didn't match: 2.5.0, 2.4.1, 2.4.0, ...
```

Could this have caused due to the dependency cleanups that happened?

**To Reproduce**
```docker-compose -f live.yml build``` in [DavidArayan/cardano-node](https://github.com/DavidArayan/cardano-node/tree/master/jormungandr-alpine)

**Expected behavior**
Expected compile to finish

**Additional context**
Compiling in Alpine Linux.

**Comment by rinor** [comment]
Is being handled: https://github.com/input-output-hk/jormungandr/pull/637#issuecomment-513499078

Meanwhile, if you don't want to wait for the fix and prevent similar future cases causing build issues, you can change the way the build is done, from : 
```
  cargo build --release && \ 
  cargo install --path jormungandr && \
  cargo install --path jcli && \
```
to
```
  cargo fetch && \
  cargo build --release --frozen && \
```
and instead of `cargo install ...` just copy the bins created from **target/release** folder.

**Comment by CodeSandwich** [comment]
Right, patch fixing yanking: https://github.com/slog-rs/slog/pull/220 When it's published on crates.io, it will start compiling again.

**Comment by Rankgor** [comment]
Hello
I have had the same problem with v0.3.1
replaced  (cargo install --path jormungandr) with (cargo fetch) and cargo build --release --frozen)
Now (Connection refused (os error 111)



four@four-System-Product-Name:/jormungandr-node/jormungandr$ chmod +x scripts/bootstrap
four@four-System-Product-Name:/jormungandr-node/jormungandr$ cd ..
four@four-System-Product-Name:/jormungandr-node$ mkdir selfnode
four@four-System-Product-Name:/jormungandr-node$ cd selfnode/
four@four-System-Product-Name:~/jormungandr-node/selfnode$ ../jormungandr/scripts/bootstrap | tee node_config.txt
########################################################

    Consensus : genesis_praos
    REST Port : 8443
    Slot duration : 10
    Slots per epoch: 5000

########################################################

    CLI version: jcli 0.3.1
    NODE version: jormungandr 0.3.1

########################################################

faucet account: ca1shfcuwpnd506vdwczjkwpyyzrxp20j7f6y7w0dcmfl4wdtwetezlqectewh

    public: ed25519_pk16w8rsvmdr7nrtkq54nsfpqses2nuhjw38nnmwx60atn2mk27ghcq76sfsj
    secret: ed25519e_sk1fzn02ap9xtew5dluju7c0mlls8qvla7z5z3ved29rflm30nqdpg2uw0tzgk2cn3afvdwc3adjvpl05s36cwt42vzjtl5px5gm7v0klc8fv78h
    amount: 1000000000000

pool id: 648050e50acee4f12cafe1400832ecdcb781ac4a201723953971739605b0bc6e
block-0 hash: 06023cda3015b1b8ee8ba7cff2799eb0c939f05437c0a4fe5b7d156e60c3c2b3

To start the node:
jormungandr --genesis-block ./block-0.bin --config ./config.yaml --secret ./pool-secret1.yaml
To connect using CLI REST:
jcli rest v0 --host "http://127.0.0.1:8443/api"
For example:
jcli rest v0 node stats get -h "http://127.0.0.1:8443/api"
four@four-System-Product-Name:/jormungandr-node/selfnode$ jormungandr --genesis-block ./block-0.bin --config ./config.yaml --secret ./pool-secret1.yaml &> my_node.log &
[1] 25427
four@four-System-Product-Name:/jormungandr-node/selfnode$ jcli rest v0 account get ca1shfcuwpnd506vdwczjkwpyyzrxp20j7f6y7w0dcmfl4wdtwetezlqectewh -h "http://127.0.0.1:8443/api"
could not connect with node
|-> http://127.0.0.1:8443/api/v0/account/d38e38336d1fa635d814ace090821982a7cbc9d13ce7b71b4feae6add95e45f0: error trying to connect: Connection refused (os error 111)
|-> Connection refused (os error 111)
[1]+ Exit 2 jormungandr --genesis-block ./block-0.bin --config ./config.yaml --secret ./pool-secret1.yaml &> my_node.log

**Comment by CodeSandwich** [comment]
@Rankgor This looks like a totally different problem. Could you create a separate issue and include content of `my_node.log` and `config.yaml`?

**Comment by CodeSandwich** [comment]
Slog 2.5.2 was released, the issue should be gone

**Comment by DavidArayan** [comment]
Hello, Just like to confirm that the issue is fixed. I just managed to complete the v0.3.1 build in DockerHub, cheers!
