### ISSUE TITLE
Connection refused (os error 111)

### ISSUE THREAD

**Issue by Rankgor** [input-output-hk/jormungandr#649]
**Describe the bug**
Hello i am completely over my head and should go back to school, have to start somewhere.
when connecting via (jcli rest v0 account)
Connection refused (os error 111)

Error is as follows.

could not connect with node
|-> http://127.0.0.1:8443/api/v0/account/d38e38336d1fa635d814ace090821982a7cbc9d13ce7b71b4feae6add95e45f0: error trying to connect: Connection refused (os error 111)
|-> Connection refused (os error 111)
[1]+ Exit 2 jormungandr --genesis-block ./block-0.bin --config ./config.yaml --secret ./pool-secret1.yaml &> my_node.log

**To Reproduce**
????

**Expected behavior**
Node will connect and start.

**Additional context**
Compiling in Ubuntu 18.04.2 Linux. latest release 
I am very green!!!! with Linux. 
I don't know how to include content of my_node.log and config.yaml?    SORRY i was getting to know 16.04 with running master-nodes now 18.04 is a bit different.

**Comment by CodeSandwich** [comment]
You can paste it as code block: https://help.github.com/en/articles/creating-and-highlighting-code-blocks

**Comment by Rankgor** [comment]
```
could not connect with node
|-> http://127.0.0.1:8443/api/v0/account/d38e38336d1fa635d814ace090821982a7cbc9d13ce7b71b4feae6add95e45f0: error trying to connect: Connection refused (os error 111)
|-> Connection refused (os error 111)
[1]+ Exit 2 jormungandr --genesis-block ./block-0.bin --config ./config.yaml --secret ./pool-secret1.yaml &> my_node.log
```

**Comment by CodeSandwich** [comment]
Great, now open `my_node.log` in a text editor and post its content here

**Comment by Rankgor** [comment]
i am wasting your time i have no idea how to.........

**Comment by Rankgor** [comment]
tried to install atom and sublime with no luck
i am so sorry.
i should wait till it is fully up and running.

**Comment by CodeSandwich** [comment]
You can run `cat my_node.log` to print its content to a console, then you can copy and paste it

**Comment by Rankgor** [comment]
```
cat my_node.log
cat: my_node.log: No such file or directory

```

**Comment by CodeSandwich** [comment]
You must be in place where running Jormungandr

**Comment by Rankgor** [comment]
```

########################################################

* Consensus      : genesis_praos
* REST Port      : 8443
* Slot duration  : 10
* Slots per epoch: 5000

########################################################

* CLI  version: jcli 0.3.1
* NODE version: jormungandr 0.3.1

########################################################

faucet account: ca1s54jtf3qx9z9lq5g36pcfcsw3dtpxhy3ka97uz08jv9twxyt3sxc789furm
  * public: ed25519_pk19vj6vgp3g30c9zywswzwyr5t2cf4eydhf0hqneunp2m33zuvpk8sjy0yu3
  * secret: ed25519e_sk1apqhnsv9c40g0xduf0c97uy8nfeje90d5jpjzg2yxmag72gweagw4dztk7jt2x9u0xc9w50x5fvfnjy4del8wu085avnxzxgc5wl8aqfpx67f
  * amount: 1000000000000

pool id: 292d028379a0e699873eb800856b5dca37d6beba831dbdd983ccd30985c56de6
block-0 hash: c425ba824073a983edd9979098c37fa5aa7cb639d91308ca095ad4921e191d42

To start the node:
  jormungandr --genesis-block ./block-0.bin --config ./config.yaml --secret ./pool-secret1.yaml
To connect using CLI REST:
  jcli rest v0 <CMD> --host "http://127.0.0.1:8443/api"
For example:
  jcli rest v0 node stats get -h "http://127.0.0.1:8443/api"
four@four-System-Product-Name:~/jormungandr-node/selfnode$ cat my_node.log
Error in the overall configuration of the node
Cannot read the node configuration file: Permission denied (os error 13)
four@four-System-Product-Name:~/jormungandr-node/selfnode$ 

```

**Comment by Rankgor** [comment]
don't have a running jormungandr i guess

**Comment by CodeSandwich** [comment]
Great, so we've got the root cause: `config.yaml` has invalid privileges and Jormungandr can't read it. There are a lot of materials on the Internet on how to fix that.

**Comment by Rankgor** [comment]
thank you i will do some homework.

**Comment by vincenthz** [comment]
@Rankgor for support question please open at https://github.com/input-output-hk/shelley-testnet/issues . this issue tracker is mostly for developer kind of issues.
