### ISSUE TITLE
Jcli: address info - wrong subcommand description

### ISSUE THREAD

**Issue by rinor** [input-output-hk/jormungandr#670]
**To Reproduce**
1. `jcli address --help`
2. Output:
```
...
    info       start jormungandr service and start participating to the network
...
```
**Expected behavior**
Smth like:
```
...
    info       display the content and info of a bench32 formatted address
...
```

**Comment by NicolasDP** [comment]
Thanks for spotting this.

This is a good first issue for that can easily be fixed by changing the documentation here: https://github.com/input-output-hk/jormungandr/blob/3e9b84f0af7cb9c86286846dd9901bad78725291/jcli/src/jcli_app/address.rs#L12-L13

**Comment by NicolasDP** [comment]
If someone wants to pick this issue before one of the dev does, please say so in a comment on this issue

**Comment by rinor** [comment]
lol, I can do that, just thought it didn't merit a separate commit.

**Comment by vincenthz** [comment]
@rinor just to maybe clarify what @NicolasDP meant, is that sometimes it's faster to just fix the problem in the code quickly and submit the PR (specially as github make this fairly easy) than to create an issue about fixing the issue.
