### ISSUE TITLE
JCLI's transaction `info` and `id` not really doing what they say

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/jormungandr#674]
since change in #633 `jcli transaction id` does not return the transaction `ID` in the sense to retrieve it in the UTxO or to use it in the input of a transaction.

In order to make things right we ought to update this:

- [x] rename current `jcli transaction id` into `jcli transaction data-for-witness`
- [ ] write function `jcli transaction id` to actually create the fragment id;
- [ ] update `jcli transaction info` to return the fragment id.

**Comment by rinor** [comment]
Based on the latest changes https://github.com/input-output-hk/chain-libs/pull/64 and https://github.com/input-output-hk/jormungandr/pull/726, thank you @vincenthz,
with `self` being an instance of:
https://github.com/input-output-hk/jormungandr/blob/ec5eba4611754f0eec40441cbbd8f71115f891db/jcli/src/jcli_app/transaction/staging.rs#L34-L40

would the following be the correct way to create/get the fragment id?
```rust
pub fn id(&self) -> FragmentId {
    let finalizer = chain::txbuilder::TransactionFinalizer::new(self.transaction());
    finalizer.to_fragment().unwrap().hash() //.to_raw().id()
}
```
If yes, is `panic` (through unwrap) the desired action in case `to_fragment()` errors?

**Comment by rinor** [comment]
Answering to myself:
> would the following be the correct way to create/get the fragment id?

No, it is wrong. `to_fragment()` will try to finalize the transaction, which is only possible if all witnesses have been filled. If not it will fail with an `Err` value: MissingWitnessAt { index: 0 }

**Comment by rinor** [comment]
I think this would be the right moment to implement also this (due to recent breaking-changes).

Question: 
Is it necessary for the (new fragment related) `transaction id` to be available at all transaction states (StagingKind) or it suffices just on `sealed`

**Comment by rinor** [comment]
Done in https://github.com/input-output-hk/jormungandr/pull/1073

**Comment by NicolasDP** [comment]
Thanks again @rinor
