### ISSUE TITLE
Explorer mode

### ISSUE THREAD

**Issue by enzoc4** [input-output-hk/jormungandr#694]
# Add an explorer node for jormungandr

## Objective

Allow Jormungandr to work in an explorer node, configurable by command line settings. This requires the creation of a separate module that only is used when the feature is on, as implementing this would require to store things that are not necessary (and are not stored right now) and would waste space for other use cases, like stake pools.

The new component should receive messages from the Block task to acknowledge any new blocks, read all the transactions and update the state accordingly. It should also communicate with the Blockchains component, with read-only access.
The state could be kept in memory using the Multiverse to later add the necessary branching logic. The important data to keep is the transactions, to be able to query for specific ones by its id, and the block information given it's block number.

A graphql interface would be provided to access the information.

# Planned query support:

Edit: See schema below

### Possible:
Delegated pool from Address

### Missing details (to consider):
- Pagination
- Filters for the lists

## Tasks

| PR | Description |
| ------------- | ------------- |
| #702  | Write a new Explorer task, conditionally enabled, that receives messages from the Block task when new blocks are added, and keeps an in-memory data structure with the required state. |
| #727  | And endpoint with graphql schema |
| #771 | Use imhamt and multiverse in explorer for keeping multiple branches |

## Current status (including #771, not on master. Right now the explorer is not doing anything in master)

The explorer can be enabled by passing `--enable-explorer` to jormungandr when starting. Or by setting:
```yaml
explorer:
    enabled: true
```
in the node configuration.

Process all the blocks produced by the leadership task. Also restore the longest branch from storage.
The explorer listens for querys on `/explorer/graphql` 
The graphiql (interactive playground) is served at `/explorer/graphiql`

### Query support:

At this point is possible to query:
- Blocks by id and chain length
Example 
```graphql
{
  blockByChainLength(length: "79") {
    date {
      slot
      epoch {
        id
      }
    }
  }
}
```
- Epochs by number

```graphql
{
  epoch(id: "0") {
    lastBlock {
      id
      chainLength
    }
  }
}
```
- Get latest block.

Example: 

```graphql
{
  status {
    latestBlock {
      id
      chainLength
    }
  }
}
```

- Transactions by id and by address

For example: 
```graphql
{
  transaction(id: "3b30d56c916e2974b3d8ba0d088dce54ea1c1bf5d907f8df2f4ee0a6b9484b0e") {
    inputs {
      amount
      address {
        id
      }
    }
    outputs {
      amount
      address {
        id
      }
    }
  }
}
```

By address: 

```graphql
{
  address(bech32: "ca1skmmqxvaesaew6aygcpkshrs0et80rh6hutkzlt6k6dpgewyarwv7zl5efq") {
    transactions {
      id
    }
  }
}
```

### Current schema (not every path is implemented yet): 
![graph](https://user-images.githubusercontent.com/48031343/65353893-9b794600-dbc4-11e9-9736-fd3d26a7e6e8.png)

## Possible future considerations

- Be able to query data by addresses/keys (such as transaction history)

**Comment by rhyslbw** [comment]
Running from `master`,  commit `17f43288b8ebf8eb80da7a8f9169701eafcb9c70`
```
➜  self_node jcli rest v0 message logs -h "http://127.0.0.1:8443/api"
---
- fragment_id: f68abddbbddb1c7bed8f28f2d1b66e672638dcf2526ab8ccd157ddc819b7398b
  last_updated_at: "2019-09-10T05:34:32.914146+00:00"
  received_at: "2019-09-10T05:34:01.426236+00:00"
  received_from: Rest
  status:
    InABlock:
      date: "0.457"
```

```
{
  transaction(id: "f68abddbbddb1c7bed8f28f2d1b66e672638dcf2526ab8ccd157ddc819b7398b") {
    id
    block {
      date {
        epoch {
          id
        }
        slot
      }
    }
  }
}
```

``` json
{
  "data": null,
  "errors": [
    {
      "message": "Couldn't find transaction in explorer",
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ],
      "path": [
        "transaction",
        "block"
      ],
      "extensions": {
        "internal_error": "Transaction is not in explorer"
      }
    }
  ]
}
```

**Comment by enzoc4** [comment]
Thanks for the report @rhyslbw  . The error is probably not very informative, but what I think is happening here is that at this moment in master, the explorer is actually not processing blocks. (since #764). So it makes sense that it didn't process the transaction. The idea is for it to be re-enabled with  #771. The reason for this are changes to one of the data structures that the explorer was using, but won't use anymore.
