### ISSUE TITLE
CORS not enabled

### ISSUE THREAD

**Issue by sjmackenzie** [input-output-hk/jormungandr#708]
**Bug Description**
When querying /api/v0/info for the block0 hash the server throws a CORS not enabled.

**Steps to Reproduce**
1. write a small JS script that constructs an HTTP request for data to /api/v0/info
2. ensure you've enabled CORS in the above HTTP request
3. execute it in the browser targetting the jormungandr REST (from a different origin)

**Expected behavior**
Jormungandr REST server returns the data

**Actual behaviour**
Jormungandr REST server throws a CORS not enabled error

**Comment by mzabaluev** [comment]
It would be nice if you can attach the script and describe steps to enable CORS.
