### ISSUE TITLE
Network: Tree Topology, AddrInUse error in long run

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#752]
**Describe the bug**
For given topology:

![image](https://user-images.githubusercontent.com/20424186/64250037-65299e80-cf15-11e9-80e4-68917e02d699.png)

In above scenario there is a constant transaction sent to leader 1 synchronously (it wait for confirmation and the send another)

During long run (> 9 hours [run started at 12:30 ended at 21:00] ) multiple errors can be found in logs for Leader3,Leader2 and Leader 1:
```
[INFO ][Leader3@127.0.0.1:8003]: Sep 04 21:06:53.011 WARN error connecting to peer: ConnectError(Http(Connect(Os { code: 10048, kind: AddrInUse, message: "Only one usage of each socket address (protocol/network address/port) is normally permitted." }))), peer_addr: 127.0.0.1:12002, task: network
```

Then after a while we can observe more severe issue:

```
[INFO ][Leader1@127.0.0.1:8001]: Fragment '36092200008d61c5a91df855b7d57ba147f257187c830405b75786eb5ecfda35' sent
[INFO ][Leader3@127.0.0.1:8003]: Sep 04 21:07:11.477 WARN error connecting to peer: ConnectError(Http(Connect(Os { code: 10055, kind: Other, message: "An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full." }))), peer_addr: 127.0.0.1:12002, task: network
[INFO ][Leader1@127.0.0.1:8001]: GET 'fragment/logs'
[ERROR][thread 'Leader1@127.0.0.1:8001]: mainFailed to send request http://127.0.0.1:8001/api/v0/fragment/logs: error trying to connect: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full. (os error 10055)' panicked at '
▘called `Result::unwrap()` on an `Err` value: Error(Reqwest(Error(Hyper(Error(Connect, Os { code: 10055, kind: Other, message: "An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full." })), "http://127.0.0.1:8002/api/v0/shutdown")), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })  Leader4',  ... [127.0.0.1:8002]

```

[logs](https://github.com/input-output-hk/jormungandr/files/3577811/addinuse.txt)

**Mandatory Information**
1. `jcli --full-version` output;
`jormungandr 0.3.3 (master-f39cb72, release, windows [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]`
2. `jormungandr --full-version` output:
`jormungandr 0.3.3 (master-f39cb72, release, windows [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]`
3. jormungandr-scenario-test seed:
`59b234c3c44616ab53f542d6d1fbd5893f3f684e25b7b30bfaf63b3336ef8665`

**To Reproduce**
1.  checkout branch https://github.com/input-output-hk/jormungandr/pull/744
2. run command: jormungandr-scenario-tests --root-dir T3005 --document
3. Observe logs
4. Run jcli commands (get account/message logs) to check status of transaction

**Expected behavior**
No error in logs. All Nodes are in sync

**Comment by mzabaluev** [comment]
From the logs, it looks like an OS handle leak somewhere: both gRPC and REST sockets fail.
If you can reproduce it on Linux, I'd suggest `strace` to track down where the leak occurs; on Windows, tools should be available as well.

**Comment by dkijania** [comment]
Issue no longer occurs
