### ISSUE TITLE
'block subscription stream failure' when starting a Passive node connected to a Leader node

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#754]
**Describe the bug**
Subscription failure after Passive node is started (connected to Leader node)

**Mandatory Information**
```
jormungandr --full-version
jormungandr 0.3.3 (master-0acbb222, release, windows [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]
```
```
jcli --full-version
jcli 0.3.3 (master-0acbb222, release, windows [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]
```

**To Reproduce**
1. unzip the attached files
2. start the Leader node using: `jormungandr --genesis-block block0.bin --config node_config_leader.yaml --secret node_secret_leader.yaml`
3. wait for a couple of blocks to be created - everything is fine
4. start the Passive node using: `jormungandr ---config node_config_passive.yaml --genesis-block-hash 6ebcedcaf48791a48ba1dcd59a2b33dbea3e22667f018a7ce9d66a89cfecec97`
- genesis hash was obtained with: `cat block-0 | jcli genesis hash` (as specified into the documentation [here](https://input-output-hk.github.io/jormungandr/quickstart/02_passive_node.html))

**Expected behavior**
Passive node is successfully connected to Leader node, no errors are shown and subscription is working successfully.

**Additional context**
Scenario: 1 Passive node that connects to 1 Active node.

[multiple_nodes.zip](https://github.com/input-output-hk/jormungandr/files/3578318/multiple_nodes.zip)
[passive_node_logs.txt](https://github.com/input-output-hk/jormungandr/files/3578333/passive_node_logs.txt)
[leader_node_logs.txt](https://github.com/input-output-hk/jormungandr/files/3578334/leader_node_logs.txt)

![image](https://user-images.githubusercontent.com/29144964/64326614-f743ac80-cfd2-11e9-829b-af023ec6a929.png)

**Comment by dkijania** [comment]
Bug is also reproducible in Leader-Leader mode

**Comment by mzabaluev** [comment]
It looks like the leader node does not encode its node ID into metadata headers of subscription responses.

Further oddity in the leader log:

```
Sep 05 11:36:20.173 INFO our node id: 140607974911606275411456246539209467038, task: network
```

This is different from the ID given in configuration: `43594425551286079828071352457839944954`

**Comment by mzabaluev** [comment]
> This is different from the ID given in configuration: `43594425551286079828071352457839944954`

The configuration parameter should be `public_id`, not `id`. This does not explain why even the generated ID is not encoded in the metadata, though.

**Comment by mzabaluev** [comment]
Analysis of Wireshark trace shows that a split response issue https://github.com/tower-rs/tower-grpc/issues/202 results in the missing metadata diagnostic.

Additionally, there is a recently introduced failure with an "unimplemented" service response for fragment subscriptions.
