### ISSUE TITLE
Error displayed (on Leader) after stopping Passive node connected to Leader

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#760]
**Describe the bug**
There is an ERROR level log displayed after stopping the Passive node connected to a Leader node.

**Mandatory Information**
```jcli --full-version
jcli 0.3.3 (master-f39cb72f, release, windows [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]
```
```jormungandr --full-version
jormungandr 0.3.3 (master-dd038efa, release, windows [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]
```

**To Reproduce**
1. unzip the attached files
2. start the Leader node using: `jormungandr --genesis-block block0.bin --config node_config_leader.yaml --secret node_secret_leader.yaml`
3. wait for a couple of blocks to be created - everything is fine
4. start the Passive node using: `jormungandr ---config node_config_passive.yaml --genesis-block-hash 6ebcedcaf48791a48ba1dcd59a2b33dbea3e22667f018a7ce9d66a89cfecec97`
5. stop the Passive node and check the logs on Leader node --> error level log can be seen
```
server error: Protocol(Error(Io, Os { code: 10054, kind: ConnectionReset, message: "An existing connection was forcibly closed by the remote host." })), task: network
```

**Expected behavior**
No error level logs should be displayed. 

**Additional context**
Scenario: 1 Passive node that connects to 1 Active node.

[multiple_nodes.zip](https://github.com/input-output-hk/jormungandr/files/3583258/multiple_nodes.zip)

[leader_logs.txt](https://github.com/input-output-hk/jormungandr/files/3583253/leader_logs.txt)
[passive_logs.txt](https://github.com/input-output-hk/jormungandr/files/3583254/passive_logs.txt)

![image](https://user-images.githubusercontent.com/29144964/64416991-e6616c80-d0a0-11e9-91cd-8be2a58cee0b.png)

**Comment by mzabaluev** [comment]
A number of network errors have been since release 0.3.3. #777 reduced the severity of connection errors to warning and changed the wording of the message to reflect that the error is non-fatal, pertains to the connection, and is likely caused by the peer.

**Comment by NicolasDP** [comment]
I think the issue has now been addressed.
