### ISSUE TITLE
Server Error when directing rest calls to public_address instead of rest address

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#775]
**Describe the bug**
A server error log message can be seen when directing rest calls to public_address instead of rest address.

**Mandatory Information**
```
jcli --full-version
jcli 0.3.3 (master-17f43288, release, windows [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]
```
```
jormungandr --full-version
jormungandr 0.3.3 (master-046b35b9, release, windows [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]
```

**To Reproduce**
1. unzip the attached files
2. start the Leader1 node using: jormungandr --genesis-block block0.bin --config node_config_leader.yaml --secret node_secret_leader.yaml
3. start the Leader2 node using: jormungandr --genesis-block block0.bin --config node_config_leader.yaml --secret node_secret_leader.yaml
- both nodes are using the same block0 and genesis files;
4. execute ` Jcli rest v0 tip get --host "http://127.0.0.1:8299/api"` and check Leader1's logs --> `Sep 11 13:23:53.620 ERRO server error: Protocol(Error(Http2, Error { kind: Proto(PROTOCOL_ERROR) })), task: network`

**Expected behavior**
No error logs should be displayed.

**Additional context**
[leader_leader.zip](https://github.com/input-output-hk/jormungandr/files/3600263/leader_leader.zip)

[leader2_logs.txt](https://github.com/input-output-hk/jormungandr/files/3600227/leader2_logs.txt)
[leader1_logs.txt](https://github.com/input-output-hk/jormungandr/files/3600228/leader1_logs.txt)

![Screenshot_1](https://user-images.githubusercontent.com/29144964/64689503-25bffc80-d497-11e9-9846-efd46f4a02be.jpg)

**Comment by mzabaluev** [comment]
The p2p public address does not serve as a REST endpoint, so this is wrong:

> **Expected behavior**
> No error logs should be displayed.

**Comment by dorin100** [comment]
The end users (community members) can still do this and having an Error level log message (especially saying `protocol error`) could raise doubts about the functionality.

**Comment by mzabaluev** [comment]
We should lower the severity of the log message, as it would not be unexpected to receive mistaken or malicious requests on the gRPC ports. Maybe we should also add a hint to the log message. Other than that, I don't think it is worthwhile to try to detect specifically the mistaken use of the port for various REST requests.

**Comment by dorin100** [comment]
Yeap. That was the idea of this issue :).
