### ISSUE TITLE
Prune unresponsive peers from the topology

### ISSUE THREAD

**Issue by mzabaluev** [input-output-hk/jormungandr#792]
When a peer connections fails because the peer node has been shut down or dropped off the network, they persist in the topology until the node is restarted.

The peer should be expunged from local gossip so that it stops being advertised and the nodes stop attempting to contact it.

**Comment by mzabaluev** [comment]
Let's proudly close this as fixed in #862 and create another item for the blacklist feature, if needed.

**Comment by mzabaluev** [comment]
@NicolasDP should the new strikes API in poldercast be used to enhance this?

**Comment by NicolasDP** [comment]
This is done actually, as soon as you report a failing nodes/unresponsive node to the toppology it is quarantined. Then it will escalate to prune it later.
