### ISSUE TITLE
Unreachable nodes should not be mentioned in gossiping protocol

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/jormungandr#796]
**Describe the bug**
A user running a jormungandr node behind a firewall that can't be reached will tell the trusted peers it's public address. Those trusted peers will then start gossiping about that users address even though those peers can't reach that address. Before gossiping about a new address, a node should validate it can connect back to that node.

**Mandatory Information**
jcli 0.3.9999 (, release, linux [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]

jormungandr 0.3.9999 (, release, linux [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]

**To Reproduce**
```
nix-shell --argstr trusted_peers "/ip4/18.140.134.230/tcp/3000"
jormungandr --genesis-block-hash f40001894fec0a93a754ff7cdc125ed64fc88260f575f9971b98ee85a35750b6 --config config.yaml
```

```
Sep 20 10:58:33.564 INFO start listening and accepting gRPC connections on 127.0.0.1:8299, task: network
Sep 20 10:58:33.564 INFO connecting to initial gossip peer, peer_addr: 18.140.134.230:3000, task: network
Sep 20 10:58:33.566 INFO Starting 1 workers, scope: global
Sep 20 10:58:33.566 INFO Starting server on 127.0.0.1:8443, scope: global
Sep 20 10:58:54.801 WARN error connecting to peer: ConnectError(Http(Connect(Os { code: 113, kind: Other, message: "No route to host" }))), peer_addr: 86.105.120.221:3456, task: network
Sep 20 10:59:16.033 WARN error connecting to peer: ConnectError(Http(Connect(Os { code: 113, kind: Other, message: "No route to host" }))), peer_addr: 86.105.120.221:3456, task: network
Sep 20 10:59:16.033 WARN error connecting to peer: ConnectError(Http(Connect(Os { code: 113, kind: Other, message: "No route to host" }))), peer_addr: 86.105.120.221:3456, task: network
```

**Expected behavior**
Node will only receive gossips about other nodes that have a reachable connection.

**Additional context**

**Comment by NicolasDP** [comment]
So we are working into not adding the `public_address` for this kind of nodes, the node would then not announce itself to others. But would still receive _gossips_ and exchange _gossips_ with others in order to allow peer discovery to do its thing.
