### ISSUE TITLE
Filter addresses that are not reachable

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/jormungandr#799]
something to add ASAP. It's important to filter addresses that are not reachable `10.0.0.0/8` or `0.0.0.0`.

**Comment by gufmar** [comment]
May consider https://www.arin.net/reference/research/statistics/address_filters/

**Comment by mzabaluev** [comment]
Do I understand correctly that we need to filter private addresses out of gossip?

This will remove possibility of testing in private networks, so perhaps this should be optional (defaulting to filtering).

**Comment by mzabaluev** [comment]
There is also a problem of trusting private addresses advertised by nodes, to prevent induced DDoS attacks. This is partially solved by dropping nodes that can't be contacted out of the p2p topology.
