### ISSUE TITLE
Node logs are flooded with `ConnectError` messages

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#808]
**Describe the bug**
After starting a node connected to the testnet, the node logs (with default logging level) is flooded with `ConnectError` messages.

**Mandatory Information**
```
jcli 0.3.9999 (heads/v0.3.9999-d6e8fabf, release, windows [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]
jormungandr 0.3.9999 (heads/v0.3.9999-d6e8fabf, release, windows [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]
```

**To Reproduce**
1. start a passive node connected to the devops testnet
2. let the node run for 2-3 mins
3. check the node logs --> there are many `ConnectError` messages per second 

**Expected behavior**
Even the log level is only `Warn`, having so many `ConnectError` messages can raise functionality concerns. My questions at this point is: does my node work? is it connected to anybody? 

**Additional context**
[node_logs.txt](https://github.com/input-output-hk/jormungandr/files/3642357/node_logs.txt)

[node_config.zip](https://github.com/input-output-hk/jormungandr/files/3642368/node_config.zip)

**Comment by mzabaluev** [comment]
Resolving #792 should reduce connect errors.

**Comment by NicolasDP** [comment]
and some comforting quietness from #807

**Comment by NicolasDP** [comment]
already exist with #792 and #807 is mitigating the issue
