### ISSUE TITLE
Coredump shortly after node startup on 0.5.0

### ISSUE THREAD

**Issue by johnalotoski** [input-output-hk/jormungandr#812]
Coredumps are observed shortly after starting a node.  Journalctl snippet and coredump backtrace attached.

jcli 0.5.0 (, release, linux [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]
jormungandr 0.5.0 (, release, linux [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]

Coredump/Journalctl logs:
[coredump-c-c-1.zip](https://github.com/input-output-hk/jormungandr/files/3644432/coredump-c-c-1.zip)

**Comment by dkijania** [comment]
Duplicates #814
