### ISSUE TITLE
Coredump shortly after node startup on 0.5.0 -- "corrupted double-linked list"

### ISSUE THREAD

**Issue by johnalotoski** [input-output-hk/jormungandr#814]
Coredumps are observed shortly after starting a node. Journalctl snippet and coredump backtrace attached.  The journalctl log indicates "corrupted double-linked list" immediately prior to the coredump.

jcli 0.5.0 (, release, linux [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]
jormungandr 0.5.0 (, release, linux [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]

Coredump/Journalctl logs:
[coredump-c-c-2.zip](https://github.com/input-output-hk/jormungandr/files/3644478/coredump-c-c-2.zip)

**Comment by mzabaluev** [comment]
This looks bad and may hint at a problem with unsafe code: `corrupted double-linked list`

The `CannotIterate` errors suggest there is a branch that refers to a block missing from storage.

**Comment by mzabaluev** [comment]
Please, if possible, remove the storage folders (back up for possible forensic) and retry from clean storage.

**Comment by johnalotoski** [comment]
Sure.  Retrying.  Thanks.

**Comment by dkijania** [comment]
Duplicate: https://github.com/input-output-hk/jormungandr/issues/820

**Comment by mzabaluev** [comment]
A possible cause shows up in Valgrind (#833). Write after free is probably why we don't see it on glibc, which has a different malloc implementation.

**Comment by mzabaluev** [comment]
A likely cause was fixed in #841. Please reopen if the problem persists with jormungandr 0.5.2 or later.
