### ISSUE TITLE
Coredump/SegFault shortly after node startup on 0.5.0

### ISSUE THREAD

**Issue by johnalotoski** [input-output-hk/jormungandr#815]
Coredumps/Segmentation-Fault is observed shortly after starting a node. Journalctl snippet and coredump backtrace attached.

jcli 0.5.0 (, release, linux [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]
jormungandr 0.5.0 (, release, linux [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]

Coredump/Journalctl logs:
[coredump-c-b-2.zip](https://github.com/input-output-hk/jormungandr/files/3644532/coredump-c-b-2.zip)

**Comment by mzabaluev** [comment]
Likely a duplicate of #815. There is no message about heap corruption here, but one thread is in a `Drop` implementation.

**Comment by dkijania** [comment]
duplicate of #814
