### ISSUE TITLE
[Relay Topology] Block solicitation: PropagateError 

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#823]
**Describe the bug**
For given topology:
![image](https://user-images.githubusercontent.com/20424186/65506682-6cb4e580-decc-11e9-89c8-4e629285f114.png)

And Scenario in which every node (except relay nodes) are receiving transaction.

Problem is visible in logs. Each 10 seconds there is an log warn:

```
[INFO ][Leader2@127.0.0.1:8007]: Sep 24 12:40:45.029 WARN block solicitation from 4490497795010484487 failed: PropagateError { kind: SubscriptionClosed, item: [Hash(Blake2b256(0x2a1eb10501759965a972dd74243c92e66b2c208566a03b1f8bf112fc6f66b6d3))] }, task: network
[INFO ][Leader2@127.0.0.1:8007]: Sep 24 12:40:45.107 WARN block solicitation from 3266296967263845275 failed: PropagateError { kind: SubscriptionClosed, item: [Hash(Blake2b256(0x2a1eb10501759965a972dd74243c92e66b2c208566a03b1f8bf112fc6f66b6d3))] }, task: network
```
Or

```
[INFO ][Leader5@127.0.0.1:8004]: Sep 24 10:17:34.283 WARN GetBlocks request (solicitation) failed: Error { code: Unknown, source: Status { code: Unknown, message: "operation was canceled: connection was not ready" } }, node_id: 14279183162823531222, peer_addr: 127.0.0.1:12006, task: network
```
There is a pr with automation test which reproduces this issue

**Mandatory Information**
1. `jcli --full-version` output;
`jcli 0.5.0 (HEAD-98922c77, release, windows [x86_64]) - [rustc 1.37.0 (eae3437df 2019-08-13)]`
2. `jormungandr --full-version` output;
`jormungandr 0.5.0 (HEAD-98922c77, release, windows [x86_64]) - [rustc 1.37.0 (eae3437df 2019-08-13)]`

**To Reproduce**
1. Checkout PR: https://github.com/input-output-hk/jormungandr/pull/822
1. Go to jormungandr-scenario-tests
2. `cargo run`

**Expected behavior**
No errors in logs 

**Additional context**
full log: [logs.txt](https://github.com/input-output-hk/jormungandr/files/3646820/logs.txt)

**Comment by mzabaluev** [comment]
The log messages can occur in normal operation and therefore have been bumped down to debug level.
