### ISSUE TITLE
IPv6 local nodes does not connect to IPv4 trusted peers

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#826]
**Describe the bug**
ConnectError/ConnectionRefused by IPv4 trusted peers when the local node is configured with IPv6 address.

**Mandatory Information**
```
jormungandr 0.5.0 (HEAD-98922c77, release, windows [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]
jcli 0.5.0 (HEAD-98922c77, release, windows [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]
```

**To Reproduce**
1. Start the local node using an IPv6 address
2. Check the local node logs

**Expected behavior**
- The local node successfully connects to IPv4 nodes/trusted-peers

**Additional context**
- it seems that the local IPv6 node has incoming connections from other IPv6 nodes but it has only `ConnectionError` from IPv4 nodes/trusted-peers
```
Sep 25 09:30:10.239 INFO incoming P2P connection on [Ipv6Address]:3000, peer_addr: [2400:8902::f03c:91ff:fe8c:14f9]:44898, task: network
Sep 25 09:30:11.270 WARN error connecting to peer: ConnectError(Http(Connect(Os { code: 10061, kind: ConnectionRefused, message: "No connection could be made because the target machine actively refused it." }))), peer_addr: 5.12.114.32:3000, task: network
Sep 25 09:30:12.231 WARN error connecting to peer: ConnectError(Http(Connect(Os { code: 10061, kind: ConnectionRefused, message: "No connection could be made because the target machine actively refused it." }))), peer_addr: 18.140.134.230:3000, task: network  
Sep 25 09:30:14.678 WARN error connecting to peer: ConnectError(Http(Connect(Os { code: 10061, kind: ConnectionRefused, message: "No connection could be made because the target machine actively refused it." }))), peer_addr: 5.12.114.32:3000, task: network                                                                                                                                                                                   
Sep 25 09:30:15.763 WARN error connecting to peer: ConnectError(Http(Connect(Os { code: 10061, kind: ConnectionRefused, message: "No connection could be made because the target machine actively refused it." }))), peer_addr: 18.140.134.230:3000, task: network
```

- node config:
```
p2p:
  public_address: /ip6/Ipv6Address/tcp/3000
  listen_address: /ip6/Ipv6Address/tcp/3000
  trusted_peers: [valid IPv4 trusted peers]
```

- node logs:
[node_logs.txt](https://github.com/input-output-hk/jormungandr/files/3650874/node_logs.txt)

- testnet logs
[testnet_logss_graylog-search-result-relative-300.zip](https://github.com/input-output-hk/jormungandr/files/3650877/testnet_logss_graylog-search-result-relative-300.zip)

**Comment by mzabaluev** [comment]
@dorin100 Can you please find some method of capturing log files that does not result in multiple log lines jumbled together horizontally with wide spaces between? It's very confusing, I needed to realize that the editor buffer had long lines and scroll waaay right to see what really went on.

The node actually connects to the initial gossip peers, as can be seen in the attached `node_logs.txt`.
The error messages may result from gossip about nodes that are not reachable being still present in the gossip received from other peers (#792).

If there is still a connection problem with initial peers that are verified to be up and running at the moment, and it can be demonstrated by a line-by-line text log file that does not require 2D reading skills, please reopen this issue.

**Comment by gufmar** [comment]
Doesn't this mean we would need one or multiple public_address values?

```p2p:
  trusted_peers:
    - "/ip4/52.208.94.64/tcp/80"
  public_address: 
    - "/ip4/1.2.3.4/tcp/8299"
    - "/ip6/2a02:2f01:0:e200::1001/tcp/8299"
```

if my node runs on both IPv4 and v6 addresses I need to announce both of them and use the appropriate one to communicate with ipv4 and ipv6 only nodes.

**Comment by mzabaluev** [comment]
Support for dual addresses is a feature that's not yet implemented. We could support multiple IP addresses per node, or treat different IP addresses as virtual nodes, this is not decided yet.

**Comment by dorin100** [comment]
Hi @mzabaluev . I updated the formatting of the node logs file. Can you please reopen the issue as I don't have the right to do it? 

Some more details:
1. if I start the node with IPv6 address, I will receive incoming connections only from IPv6 nodes; all the IPv4 ones are ConnectionClosed
2. if I stop the node, change the node address to IPv4 and start it again, we can see incoming connections from all previous non-reachable IPv4 nodes;

**Comment by mzabaluev** [comment]
The behavior is as expected, considering that the current node only listens on either IPv4 or IPv6 address, and this is the only address advertised to the network.
