### ISSUE TITLE
To many ConnectError messages in the logs for the same unreachable node

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#828]
**Describe the bug**
If there is an unreachable node/trusted-peer, at least 2 ConnectionError log warnings are sent every 10 seconds. This is creating a lot of noise (containing the `error` keyword) in the node logs.

**Mandatory Information**
```
jormungandr 0.5.0 (HEAD-98922c77, release, windows [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]
jcli 0.5.0 (HEAD-98922c77, release, windows [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]
```

**To Reproduce**
1. Start a local node with the trusted-peers provided by devops
2. Let the node run for ~5 mins and check the logs
3. check for `18.140.134.230` inside the attached node logs.

**Expected behavior**
There should not be so many `ConnectionError` warnings for each unreachable node for an infinite time. Maybe we can have 1 message per minute? Stopping to display the warnings after 5 min? <- this could be wrong (it is only an idea)

**Additional context**
- nod logs:
[New Text Document.txt](https://github.com/input-output-hk/jormungandr/files/3651172/New.Text.Document.txt)

**Comment by mzabaluev** [comment]
Thanks, it's a known problem, the work item for this is #792.
