### ISSUE TITLE
Transaction for sending the stake-pool certificate is rejected with `Pool Registration certificate invalid`

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#836]
**Describe the bug**
Transaction for sending the stake-pool certificate is rejected with `Pool Registration certificate invalid`

**Mandatory Information**
```
jormungandr 0.5.0 (HEAD-98922c77, release, windows [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]
jcli 0.5.0 (HEAD-98922c77, release, windows [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]
```

**To Reproduce**
1. extract the attached node configs in a new folder
2. start the nodes (1 to 3) using below commands:
- node1: `jormungandr --genesis-block ./block-0.bin --config ./config.yaml --secret ./pool-secret1.yaml`
- nodes 2 and 3: `jormungandr ---config config.yaml --genesis-block-hash ef573c182c05e017b93c297a3650f8ff7bc216dc3a48c255b144a6cf3ef1130c`
3. Create a new Account to be used as stake pool owner
```
ACCOUNT_SK=$(jcli key generate --type=ed25519extended)
ACCOUNT_PK=$(echo ${ACCOUNT_SK} | jcli key to-public)
ACCOUNT_ADDR=$(jcli address account ${ACCOUNT_PK} --testing)
```
4. Create VRF keys
```
POOL_VRF_SK=$(jcli key generate --type=Curve25519_2HashDH)
POOL_VRF_PK=$(echo ${POOL_VRF_SK} | jcli key to-public)
echo POOL_VRF_SK: ${POOL_VRF_SK}
echo POOL_VRF_PK: ${P
```
5. Create KES keys
```
POOL_KES_SK=$(jcli key generate --type=SumEd25519_12)
POOL_KES_PK=$(echo ${POOL_KES_SK} | jcli key to-public)
echo POOL_KES_SK: ${POOL_KES_SK}
echo POOL_KES_PK: ${POOL_KES_PK}
```
6. Create the Stake Pool certificate using above VRF and KEY public keys
```
jcli certificate new stake-pool-registration --kes-key ${POOL_KES_PK} --vrf-key ${POOL_VRF_PK} --serial 1010101010 --start-validity 0 --management-threshold 1 > stake_pool.cert
```
7. Sign the Stake Pool certificate with the Stake Pool Owner private key
```
STAKE_KEY=${ACCOUNT_SK}
echo ${STAKE_KEY} > stake_key.sk
cat stake_pool.cert | jcli certificate sign stake_key.sk > stake_pool.signcert
cat stake_pool.signcert
```
8. Send the signed Stake Pool certificate to the blockchain
```
bash faucet-send-certificate.sh stake_pool.signcert
```
9. wait for at least 1 new block to be created 

10. get the node stats for all 3 nodes
```
$ bash logs.sh
Node 1 logs:
---
- fragment_id: a56dad2be789ef9808f263115afbc292e5b5dbeac96f2633a75f85b0e2435135
  last_updated_at: "2019-09-25T16:00:43.011049800+00:00"
  received_at: "2019-09-25T15:59:59.945215800+00:00"
  received_from: Network
  status:
    Rejected:
      reason: Pool Registration certificate invalid
----------------------------------------------------------
Node 2 logs:
---
- fragment_id: a56dad2be789ef9808f263115afbc292e5b5dbeac96f2633a75f85b0e2435135
  last_updated_at: "2019-09-25T15:59:59.945215800+00:00"
  received_at: "2019-09-25T15:59:59.945215800+00:00"
  received_from: Network
  status: Pending
----------------------------------------------------------
Node 3 logs:
---
- fragment_id: a56dad2be789ef9808f263115afbc292e5b5dbeac96f2633a75f85b0e2435135
  last_updated_at: "2019-09-25T15:59:59.944215800+00:00"
  received_at: "2019-09-25T15:59:59.944215800+00:00"
  received_from: Rest
  status: Pending
----------------------------------------------------------
```

Issues:
1. the transaction is rejected on node 1 when new block as created - `reason: Pool Registration certificate invalid`
2. the transactions remains in `Pending` on nodes 2 and 3.

**Expected behavior**
1. The transaction is successful when a new block is created. The certificate is successfully sent to blockchain.
2. The transaction is displayed with the same status on all 3 nodes.

**Additional context**
- node configs:
[local_cluster.zip](https://github.com/input-output-hk/jormungandr/files/3653639/local_cluster.zip)

- node logs:
[node1_logs.txt](https://github.com/input-output-hk/jormungandr/files/3653603/node1_logs.txt)
[node2_logs.txt](https://github.com/input-output-hk/jormungandr/files/3653604/node2_logs.txt)
[node3_logs.txt](https://github.com/input-output-hk/jormungandr/files/3653605/node3_logs.txt)

**Comment by NicolasDP** [comment]
it's because there is no OWNER key

**Comment by NicolasDP** [comment]
add an `--owner` and it will work.

this issue can be fixed with a better error friendly message from the `jcli`:

if `--threshold N` then we need `N` owners

**Comment by dorin100** [comment]
ok. I will add `--owner` to the documentation issue. thank you!

**Comment by NicolasDP** [comment]
I am keeping this issue to track down an improvement that could be done in the `jcli`

**Comment by NicolasDP** [comment]
In `jcli` code, it is possible to check that the list of `owner` is at list the number of `threshold`

https://github.com/input-output-hk/jormungandr/blob/c5a92b7a6d0a6c23d208b60553c2ba110368cd70/jcli/src/jcli_app/certificate/new_stake_pool_registration.rs#L51-L67

i.e. `self.owners.len() >= self. management_threshold` and if not, returns an appropriate error in https://github.com/input-output-hk/jormungandr/blob/c5a92b7a6d0a6c23d208b60553c2ba110368cd70/jcli/src/jcli_app/certificate/mod.rs#L13-L22

This would improve the user experience a lot.

**Comment by NicolasDP** [comment]
closing in favour or #837
