### ISSUE TITLE
My local node/stake pool did not create any block

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#840]
**Describe the bug**
My local node/stake pool did not create any block (at least 26 epochs from starting the node/stake pool).

**Mandatory Information**
```
jcli 0.5.0 (HEAD-c5a92b7a, release, windows [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]
jormungandr 0.5.0 (HEAD-c5a92b7a, release, windows [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]
```

**To Reproduce**
1. extract the attached archive to a new folder
2.  start the node using: `jormungandr ---config node_config.yaml --secret node_secret.yaml --genesis-block-hash 875f778274389cc09474b7ec75a60503aca681dfb15abad1d58ae476977c009f`
- I already configured a stake pool - `a573440b8c97190b5a6281d49ebb352132a8b5292b581d6474a4f7496a05c94c`; 
![image](https://user-images.githubusercontent.com/29144964/65691601-cc9cbf00-e079-11e9-997c-c79c518449ce.png)
- the stake pools keys and certificate are also included into the archive
3. let the node run as long as you want - I let it run for > 26 epochs and no block was created by this node (looking into the node logs for anything similar with the below line)
```
Sep 26 16:13:30.023 INFO block from leader event successfully stored, date: 0.34, parent: 99a7ec21e7ac83254953781434126e977b3b00682a4bd0f75801b29a335122ef, hash: bb5681b854a286faca97f7e23c5403cbc0067a20077c62e289e517fa161daccd, task: block
```

**Expected behavior**
As a stake pool operator, I am expecting to see some blocks created by my node/stake pool.

**Additional context**
- node logs:
[node_logs.txt](https://github.com/input-output-hk/jormungandr/files/3657903/node_logs.txt)

-  node files:
[connect-to-cluster.zip](https://github.com/input-output-hk/jormungandr/files/3657929/connect-to-cluster.zip)

**Comment by disassembler** [comment]
I think this can be closed now. My node has created numerous blocks as has a number of community nodes.

**Comment by disassembler** [comment]
@NicolasDP @dorin100
