### ISSUE TITLE
Information and statistics per network peer

### ISSUE THREAD

**Issue by mzabaluev** [input-output-hk/jormungandr#846]
Information and some communication statistics should provided for all currently connected peers to be available for retrieval (e.g. through a REST status endpoint) and internal housekeeping such as rotating out peer connections accordingly to policies that can be tuned later.

Tentatively, the information to provide should be:
- The peer address;
- Timestamps of the last received item of certain protocol communications (block via subscription, fragment via subscription, possibly incoming requests/solicitations).

**Comment by mzabaluev** [comment]
The suitable place for this in the current code is `PeerComms` records in the `PeerMap`.

**Comment by jbax** [comment]
Can you guys add network stats such as what linux's `ping` and `traceroute` provide, for each peer?

**Comment by NicolasDP** [comment]
with #921 merged we only need to look at the REST handler now and to have a way to query/redistribute the stats.

- [ ] add `/network/stats` handler
- [ ] query the network modules for the network stats (there is an intercom message for this now);
- [ ] display it in JSON
- [ ] update the OpenAPI file

then next step will be to add something to display the info in a nice and fancy way with 3D webgl (or Oculus Rift?) for user (and dev) to be able to visualise that (preference is to add that in https://github.com/input-output-hk/fenrir)
