### ISSUE TITLE
initial bootstrap completedthread 'network, ' panicked at 'not yet implementedpeer_addr'

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#849]
**Describe the bug**
Panic after starting the local node.

**Mandatory Information**
```
jcli 0.5.2 (HEAD-e7a3efe7, release, windows [x86_64]) - [rustc 1.37.0 (eae3437df 2019-08-13)]
jormungandr 0.5.2 (HEAD-e7a3efe7, release, windows [x86_64]) - [rustc 1.37.0 (eae3437df 2019-08-13)]
```

**To Reproduce**
1. Start the local node using: `jormungandr --config node_config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770`

**Expected behavior**
The node should successfully start with no panic/error.

**Additional context**
- OS: win 10, **ports not open on firewall (3000)**
**- If I add `listen_address` in the node config, the node starts normally with no panic;**

- node config
```
---
rest:
  listen: "127.0.0.1:9000"
p2p:
  public_address: /ip4/5.12.xx.xx/tcp/3000
  trusted_peers: [/ip4/3.123.177.192/tcp/3000,
                  /ip4/3.123.155.47/tcp/3000,
                  /ip4/52.57.157.167/tcp/3000,
                  /ip4/3.112.185.217/tcp/3000,
                  /ip4/18.140.134.230/tcp/3000,
                  /ip4/18.139.40.4/tcp/3000,
                  /ip4/3.115.57.216/tcp/3000]
  topics_of_interest:
    messages: high
    blocks: high
```

- node logs:
[node_logs.txt](https://github.com/input-output-hk/jormungandr/files/3662688/node_logs.txt)
![image](https://user-images.githubusercontent.com/29144964/65769019-3b8e1c80-e13b-11e9-8311-9b50dcf08cdf.png)
[node_logs_second_try.txt](https://github.com/input-output-hk/jormungandr/files/3662709/node_logs_second_try.txt)

**Comment by dorin100** [comment]
If I add listen_address in the node config, the node starts normally with no panic;

**Comment by NicolasDP** [comment]
This is your error:

<img width="1014" alt="Screenshot 2019-09-27 at 14 09 11" src="https://user-images.githubusercontent.com/5445840/65771578-6cb51f80-e130-11e9-8c98-2e3f8ca821de.png">

it cannot listen to the `listen_address` you have set. So you have found an error, but you might have  mismatched your testing inputs

**Comment by mzabaluev** [comment]
The failure to listen on the address will result in node exiting with an error code when #911 is merged and released.

**Comment by mzabaluev** [comment]
The configuration is at fault here: If `listen_address` is not given, the node will try to bind to the socket address as specified in `public_address`. If the public IP address is not bindable locally at the host (due to NAT), this will not work. The solution is to specify the local address/port to listen, which needs to be mapped to the public address by the network administrator.
