### ISSUE TITLE
REST API: get stake distribution for any arbitrary previous epoch (or, the immediate previous one only) 

### ISSUE THREAD

**Issue by KtorZ** [input-output-hk/jormungandr#852]
**Describe the bug**

At the moment, it isn't possible to get the stake distribution for any arbitrary epoch via the REST API,  but we only get it for the current (i.e. node's tip) epoch:

https://input-output-hk.github.io/jormungandr/jcli/rest.html#get-stake-distribution

Yet, this makes it fairly hard for client to reliably keep track of the distribution over several epochs for it requires them to be online all the time.

**Mandatory Information**
1. `jcli --full-version` output;
```
jcli 0.5.0 (HEAD-98922c7, release, linux [x86_64]) - [rustc 1.37.0 (eae3437df 2019-08-13)]
```

2. `jormungandr --full-version` output;
```
jormungandr 0.5.0 (HEAD-98922c7, release, linux [x86_64]) - [rustc 1.37.0 (eae3437df 2019-08-13)]
```

**To Reproduce**
> Steps to reproduce the behavior:

N/A

**Expected behavior**
> A clear and concise description of what you expected to happen.

The `/v0/stake` endpoint takes an additional `epoch-number` parameter allowing for fetching the stake distribution of any arbitrary epoch in the past.

At the very least, it'll be nice to have access to the previous epoch distribution if considering any arbitrary epoch in the past is too much.

**Additional context**

Thank you :heart:

**Comment by Straightpool** [comment]
Let me add a user story for this:

> As cardano_wallet I want to query jormungandr for stake_distribution for the number of epochs I use to calcluatate both `desirability` and `apparent_performance` to be able to show consistent ranking data for all users boosting decentralization as this benefits small pools with unregular blocks the most

Currently I understand this is 14 epochs.

**Comment by Straightpool** [comment]
Woohoo, thanks for bumping this up into scope to do! 0.8.14 will be awesome!
