### ISSUE TITLE
accept host for jcli rest via env var

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/jormungandr#854]
**Is your feature request related to a problem/context ? Please describe if applicable.**

**Describe the solution you'd like**
I'd like to set an env var in my nix-shell so all jcli rest requests go through the address of my node and I don't have to specify `-h` to every request.

**Additional context**
Add any other context about the feature request here.

**Comment by rinor** [comment]
I can take this one!
What would be the preferred env var name?
