### ISSUE TITLE
Change the start up order for node processes

### ISSUE THREAD

**Issue by psychomb** [input-output-hk/jormungandr#857]
**problem**
While bootstraping on the unified testnet, REST queries end up with a 'not-so-user-friendly error message', although all is fine in the background.

**solution**
Is there a way to start the REST server before or during bootstraping - so that if the node is not up and running yet, any query to REST will end up saying " Bootstraping on going - Please be patient while chain is being downloaded"

**context**
jormungandr 0.5.2 (HEAD-e7a3efe7, release, linux [x86_64]) - [rustc 1.37.0 (eae3437df 2019-08-13)]

**Comment by NicolasDP** [comment]
- [ ] booting the REST module and only the node/stats end point available (because of course, we don't have the other module started);
- [ ] add in the node/stats more info: the current booting stage (fetching block0 | loading storage | loading from network | ...).

**Comment by NicolasDP** [comment]
will be in the next release. fixed by #986

**Comment by NicolasDP** [comment]
will be in 0.7.0
