### ISSUE TITLE
Blockchain Settings: maximum number of fragment per block

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/jormungandr#86]
We have currently control over the block size limits except the limit by design (see [block format](https://github.com/input-output-hk/chain-libs/blob/master/chain-impl-mockchain/doc/format.md#block-header): size of content _unsigned integer of 32bits_ (2,147,483,647)). We need the protocol to enforce a reasonable number.

Previously we had in the settings an option to do something similar: number of transaction per block. We need now to have max size of a block settings.

- [x] add in the settings a maximum block size;
- [x] add a way to enforce the size; 
- [x] update the fragment selection algorithm to take this into account for bit-packing;
- [x] update the block0 configuration to provide this value (with minimum and maximum check);

---

### Old description before re-design of the blockchain ledger.

we are missing a mean to extract the blockchain's setting, here we are missing the maximum number of transaction per block.

In the current implementation of the `Update` trait, the ChainState is not giving the correct value. It is giving the total number of transaction ever seen in the blockchain.

see what is being introduced in [PR85](https://github.com/input-output-hk/jormungandr/pull/85/files#diff-18dec51afac534e0691e0e22e4455c8a)

**Comment by CodeSandwich** [comment]
Is getting it via REST endpoint enough?

**Comment by NicolasDP** [comment]
Not the same thing. Here it is related to the blockchain settings not being correct. I'll provide an update to this issue as we have changed some internal design since and it is no longer clear what this is about.
