### ISSUE TITLE
ERRO cannot propagate block to network: send failed because channel is full

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#861]
**Describe the bug**
Error while running the node as `leader candidate` (using `--secret` parameter - stake pool keys attached).

**Mandatory Information**
```
jcli 0.5.2 (HEAD-e7a3efe7, release, windows [x86_64]) - [rustc 1.37.0 (eae3437df 2019-08-13)]
jormungandr 0.5.2 (HEAD-e7a3efe7, release, windows [x86_64]) - [rustc 1.37.0 (eae3437df 2019-08-13)]
```

**To Reproduce**
1. Start the local node using: `jormungandr --config node_config.yaml --secret node_secret.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770`
2. Let the node run for a couple of hours 
3. Check the logs for errors - I suppose that the error is displayed when my node/stake pool was elected to create a block;

**Expected behavior**
No errors displayed; From time to time, my local node successfully creates blocks and send them to the blockchain. 

**Additional context**
- OS: win 10; port 3000 is both open in firewall and forward on router (conectivity ok);
- stake pool ID: `b7b132fdff13b998da3313c93ce36a75e2ca2f52288e95d944c9a6d6ba9042f3`
- node config + secret:
[configSecret.zip](https://github.com/input-output-hk/jormungandr/files/3669098/configSecret.zip)
- node logs:
[node_logs.txt](https://github.com/input-output-hk/jormungandr/files/3669092/node_logs.txt)
![image](https://user-images.githubusercontent.com/29144964/65853302-b9cc0800-e361-11e9-99d0-823ccb3ddbe9.png)

- the node seems correctly synced
```
C:\Users\Dorin>jcli rest v0 node stats get --host "http://127.0.0.1:9000/api"
---
blockRecvCnt: 3219
lastBlockDate: "219.40106"
lastBlockFees: 0
lastBlockHash: 904f0767793f4b8357f4e797b08ebd54c3de75fa45edeccb2d38812d3ebb65be
lastBlockHeight: "27775"
lastBlockSum: 0
lastBlockTime: "2019-09-30T06:10:28+00:00"
lastBlockTx: 0
txRecvCnt: 0
uptime: 4934
```

**Comment by gufmar** [comment]
this happened also to my 0.5.2 node when not attending or being a stake pool
restarting the node solved the issue, the fragments were submitted and became included/confirmed to a block. Then I saw the moved funds from source to dest address.

**Comment by gufmar** [comment]
upgraded to 0.5.4
created and submitted a transaction
Didn't see any such red 'ERRO cannot progagate ...' messages but the TX wasn't propagated and included to the chain.
after restarting the node the TX was included and became visible on the chain.

**Comment by dkijania** [comment]
can be related to #752

**Comment by bjarnekvae** [comment]
Just happened to me while logging with strace, see appendix
[errCannotProp.zip](https://github.com/input-output-hk/jormungandr/files/3717038/errCannotProp.zip)

Also got some pullHeader errors in there, probably a different issue

**Comment by NicolasDP** [comment]
It is our believe that the issue was a side effect of #860 and other like the file descriptor issue.

**Comment by bjarnekvae** [comment]
This error just occurred for me at v0.6.5. Node log and strace log here:
https://www.sendspace.com/file/n8wmj2

My node also stopped receiving blocks, don't know if it is a consequence of this error or not. should I make a separate issue for this?

**Comment by bjarnekvae** [comment]
@NicolasDP Just happened again, my memory use is about 78% of 20GB of ram. Also the node stopped receiving blocks when the errors happened

**Comment by mzabaluev** [comment]
Cleaning up old bugs; please reopen if the problem reoccurs in 0.9.3 or later versions.
