### ISSUE TITLE
add warning if blockchain is not moving up

### ISSUE THREAD

**Issue by vincenthz** [input-output-hk/jormungandr#863]
add a period check process that check that the slot id of the last block is close to the latest slot id expected related to a given time clock.

In pseudo code:
```
loop {
  delay(waited-time)
  if tip.slot + waited-time-in-slot < tip.time.expected_slot(current-time) {
      warning-log
      set-status-of-node = disconnected 
  }
}
```

**Comment by carl-IOHK** [comment]
Linked to https://iohk.myjetbrains.com/youtrack/issue/IOHKS-157

**Comment by NicolasDP** [comment]
@carl-IOHK , we cannot access the issue you are linking us to. This is pretty useless and not adding anything to the issue.

**Comment by eugene-babichenko** [comment]
What should we determine the number of slots to wait between blocks?

**Comment by NicolasDP** [comment]
it's based on different parameter of the blockchain, the number of slots per epoch, the active slots coefficient and the number of seconds per slot. And it's not a hard limit. More a _signal_ that can be escalated. From a simple notification, comfort logging PoV, to an error that needs the user's attention.

Would be nice to connect this value to the node's stats too in the REST side of thing.

**Comment by eugene-babichenko** [comment]
> it's based on different parameter of the blockchain, the number of slots per epoch, the active slots coefficient and the number of seconds per slot.

So this would something like `slots_per_epoch * active_slots_coeff * slot_duration`?

> Would be nice to connect this value to the node's stats too in the REST side of thing.

This can be just something like `last_block_time` which is pretty easy to achieve without creating an additional service.
