### ISSUE TITLE
Move the AssertUnwindSafe at the task level when possible

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/jormungandr#879]
Not sure what is required besides, in the worst case, shifting the `AssertUnwindSafe` wrapper to every use site for the few tasks we have, to leave audit markers for re-evaluation later if this causes problems.
But let's move it forward.

_Originally posted by @mzabaluev in https://github.com/input-output-hk/jormungandr/pull/873#discussion_r330228027_

**Comment by CodeSandwich** [comment]
This was discussed in https://github.com/input-output-hk/jormungandr/pull/1141#pullrequestreview-318199670:
> Whenever there's a panic, we catch it and finish execution, but because it's the only future on executor, it stops right away guaranteeing to never touch !UnwindSafe data anymore.

@mzabaluev is it OK to close this issue or is this really a threat that needs addressing?

**Comment by mzabaluev** [comment]
> because it's the only future on executor

What about tasks spawned in various places?
