### ISSUE TITLE
GET /api/v0/block/<hash> gives empty response when hash is invalid

### ISSUE THREAD

**Issue by piotr-iohk** [input-output-hk/jormungandr#922]
**Describe the bug**
When querying Jormungandr for block hash that is invalid the response from the server is empty. As a consequence tools like `cardano-wallet CLI` (and even `jcli`) report wrongly that Jormungandr is offine in such a case.

e.g. 
**valid block hash**
```
$ curl -v http://127.0.0.1:8080/api/v0/block/44966aab1f4727d6c009b8960f840342ce225ae19cc73fd83e163b137b7368f1
>
< HTTP/1.1 200 OK
```
**invalid block hash**
```
$ curl -v http://127.0.0.1:8080/api/v0/block/1111111111111111111111111111111111111111111111111111111111111111
> 
* Empty reply from server
```
As a consequence `jcli` reports:
```
$ jcli rest v0 block 1111111111111111111111111111111111111111111111111111111111111111 get
failed to make a REST request
  |-> could not connect with node
  |-> http://127.0.0.1:8080/api/v0/block/1111111111111111111111111111111111111111111111111111111111111111: connection closed before message completed
```
Cardano-wallet reports: https://github.com/input-output-hk/cardano-wallet/issues/767

**Mandatory Information**
1. `jcli --full-version` output;
     `jcli 0.5.6 (HEAD-7ab929e+, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]`
2. `jormungandr --full-version` output;
     `jormungandr 0.5.6 (HEAD-7ab929e+, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]`

**To Reproduce**
1. Start Jormungandr
2. Query for invalid block hash 
```
curl -v http://127.0.0.1:8080/api/v0/block/1111111111111111111111111111111111111111111111111111111111111111
```

**Expected behavior**
A server could possibly respond with `404` in such a case rather than empty response.

**Additional context**
https://github.com/input-output-hk/cardano-wallet/issues/767

**Comment by rinor** [comment]
Fixed after release by https://github.com/input-output-hk/jormungandr/pull/912. The observed behaviour is from https://github.com/input-output-hk/jormungandr/issues/859
