### ISSUE TITLE
Suspected file descriptor leak (ERRO Error while accepting connection on 0.0.0.0:3000: Os)

### ISSUE THREAD

**Issue by bjarnekvae** [input-output-hk/jormungandr#923]
**Describe the bug**
First error in logs are "ERRO Error while accepting connection on 0.0.0.0:3000: Os { code: 24, kind: Other, message: "Too many open files" }, task: network", after a while its starts spamming "ERRO cannot send PullHeaders request to network: send failed because receiver is gone, task: block" and node stops receving blocks

**Mandatory Information**
1. jcli 0.5.6 (HEAD-7ab929e+, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
2. jormungandr 0.5.6 (HEAD-7ab929e+, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

**To Reproduce**
Dont know how to reproduce, happens after the node has run a few hours

**Expected behavior**
No error

**Additional context**
See appendix for output logs and strace logs. I have four examples as I happens every time I try to run my node.

[errPullHeader.zip](https://github.com/input-output-hk/jormungandr/files/3717092/errPullHeader.zip)

**Comment by mzabaluev** [comment]
Thank you for the captures, will investigate.

**Comment by mzabaluev** [comment]
Massively duplicate connections are still present; working on a better fix.

**Comment by bjarnekvae** [comment]
I'm running 0.6.0 with strace, will serve you fresh logs when(/if?) it crashes :)

**Comment by bjarnekvae** [comment]
Error just happened on my other server, running a other setup with a old-style mechanical HDD, dont know if it is relevant. Running v0.6.1 

Here are the logs:
[err_24.zip](https://github.com/input-output-hk/jormungandr/files/3732813/err_24.zip)

**Comment by bjarnekvae** [comment]
Just happened on my other server, so its not hardware related as this one uses a SSD. Still on v0.6.1

Logs:
[err_24_2.zip](https://github.com/input-output-hk/jormungandr/files/3734347/err_24_2.zip)

**Comment by vincenthz** [comment]
@bjarnekvae it's not storage related, it is a network subsystem issue as indicated in the log : `task: network" `

**Comment by mzabaluev** [comment]
One probable cause has been fixed in #981 (and fixes of the fix that have followed).
Please retry with version 0.6.5 or later.

**Comment by bjarnekvae** [comment]
running 0.6.5 with strace now

**Comment by bjarnekvae** [comment]
This error just came back in v0.8.0-rc2

[node_log.log](https://github.com/input-output-hk/jormungandr/files/3907054/node_log.log)

**Comment by bjarnekvae** [comment]
Strace log:
[tooManyFiles.zip](https://github.com/input-output-hk/jormungandr/files/3907070/tooManyFiles.zip)

**Comment by bjarnekvae** [comment]
@mzabaluev This is still relevant for v0.8.0-rc5

**Comment by babelitconsulting** [comment]
ERRO Error while accepting connection on 0.0.0.0:3001: Os { code: 24, kind: Other, message: "Too many open files" }, task: network

version: jormungandr 0.8.5-3db06807
