### ISSUE TITLE
Accept sensitive parameters for jormungandr via environment variables.

### ISSUE THREAD

**Issue by ilap** [input-output-hk/jormungandr#935]
**Is your feature request related to a problem/context ? Please describe if applicable.**
N/A

**Describe the solution you'd like**
Accept sensitive parameters such as `private_id` , `sig_key`, `vrf_key` and bft's `signing_key` through environment variables. This would prevent key leakages in certain configurations.

However, more sophisticated methods should be implemented in the future for protecting keys.

**Additional context**
N/A

**Comment by NicolasDP** [comment]
So actually one of the method you can use is via the control API to send in your `sig_key` `vrf_key` or `signing_key`. Have a look at [openapi documentation](https://editor.swagger.io/?url=https://raw.githubusercontent.com/input-output-hk/jormungandr/master/doc/openapi.yaml) for more details.

the `private_id` is not necessary for you to generate unless you wish to be a trusted peer on the network, but indeed adding a new method would be nice too, please comment on #942
