### ISSUE TITLE
0.56+lock load-average skyrockets; centos 7

### ISSUE THREAD

**Issue by rgoerwit** [input-output-hk/jormungandr#936]
**Describe the bug**
0.56+lock load-average skyrockets; centos 7

**Mandatory Information**
1. `jcli --full-version` output;  jcli 0.5.6+lock (master-3c613ee, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
2. `jormungandr --full-version` output; jormungandr 0.5.6+lock (master-3c613ee, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

**To Reproduce**

In debug logs below, load average jumps to 10.0 shortly after timestamp Oct 14 01:03:30
---------------------------------
YAML file:
---------------------------------
  listen_address: "/ip4/0.0.0.0/tcp/3100"
  public_address: "/ip4/X.X.X.X/tcp/3100"
  topics_of_interest:
    blocks: "high"
    messages: "high"
  trusted_peers:
    - "/ip4/3.123.177.192/tcp/3000"
    - "/ip4/3.123.155.47/tcp/3000"
    - "/ip4/52.57.157.167/tcp/3000"
    - "/ip4/3.112.185.217/tcp/3000"
    - "/ip4/18.140.134.230/tcp/3000"
    - "/ip4/18.139.40.4/tcp/3000"
    - "/ip4/3.115.57.216/tcp/3000"
    - "/ip4/35.199.15.206/tcp/9000"
    - "/ip4/54.255.233.57/tcp/3100"
    - "/ip4/13.229.67.97/tcp/3100"
    - "/ip4/163.172.195.51/tcp/4444" #kyleo
    - "/ip4/144.76.40.23/tcp/3333" #kyleo
    - "/ip4/73.52.25.31/tcp/3100" #disasm
    - "/ip4/95.179.241.144/tcp/3100" #Glenn
    - "/ip4/140.82.40.6/tcp/3100" #Glenn
    - "/ip4/209.209.238.36/tcp/14509" #Lazr
rest:
  listen: "127.0.0.1:3101"
storage: "/usr/local/cardano/blockchain"
explorer:
  enabled: true
------------------------------
/var/log/messages section
------------------------------
Oct 14 01:03:30 instance-1 jormungandr[18303]: sending gossip to node 13974267336447834572, task: network
Oct 14 01:03:56 instance-1 jormungandr[18303]: connecting to node, node_id: 13974267336447834572, peer_addr: 209.209.238.36:14509, task: network
Oct 14 01:04:14 instance-1 jormungandr[18303]: selecting gossips for 12186300889126854364, task: network
Oct 14 01:04:32 instance-1 jormungandr[18303]: sending gossip to node 12186300889126854364, task: network
Oct 14 01:04:47 instance-1 jormungandr[18303]: selecting gossips for 15870000297337153516, task: network
Oct 14 01:05:11 instance-1 jormungandr[18303]: sending gossip to node 15870000297337153516, task: network
Oct 14 01:06:06 instance-1 jormungandr[18303]: selecting gossips for 18068927349944395760, task: network
Oct 14 01:06:45 instance-1 jormungandr[18303]: sending gossip to node 18068927349944395760, task: network
Oct 14 01:07:12 instance-1 jormungandr[18303]: connecting to node, node_id: 18068927349944395760, peer_addr: 54.255.233.57:3100, task: network
Oct 14 01:07:44 instance-1 jormungandr[18303]: error connecting to peer, peer_addr: 13.229.67.97:3100, task: network, reason: Connection timed out (os error 110)
Oct 14 01:08:20 instance-1 jormungandr[18303]: dropping I/O source: 23, scope: global
Oct 14 01:09:09 instance-1 jormungandr[18303]: client P2P connection closed, node_id: 845440531341738765, peer_addr: 13.229.67.97:3100, task: network
Oct 14 01:09:35 instance-1 jormungandr[18303]: evicted node, node_id: 845440531341738765, peer_addr: 13.229.67.97:3100, task: network
Oct 14 01:10:11 instance-1 jormungandr[18303]: error connecting to peer, peer_addr: 54.255.233.57:3100, task: network, reason: Connection timed out (os error 110)
Oct 14 01:10:49 instance-1 jormungandr[18303]: dropping I/O source: 32, scope: global
Oct 14 01:11:03 instance-1 jormungandr[18303]: client P2P connection closed, node_id: 18068927349944395760, peer_addr: 54.255.233.57:3100, task: network
Oct 14 01:11:20 instance-1 jormungandr[18303]: evicted node, node_id: 18068927349944395760, peer_addr: 54.255.233.57:3100, task: network
Oct 14 01:11:32 instance-1 jormungandr[18303]: error connecting to peer, peer_addr: 13.229.67.97:3100, task: network, reason: Connection timed out (os error 110)
Oct 14 01:11:40 instance-1 jormungandr[18303]: dropping I/O source: 25, scope: global
Oct 14 01:11:47 instance-1 jormungandr[18303]: client P2P connection closed, node_id: 845440531341738765, peer_addr: 13.229.67.97:3100, task: network
Oct 14 01:11:54 instance-1 jormungandr[18303]: evicted node, node_id: 845440531341738765, peer_addr: 13.229.67.97:3100, task: network
Oct 14 01:12:03 instance-1 jormungandr[18303]: error connecting to peer, peer_addr: 54.255.233.57:3100, task: network, reason: Connection timed out (os error 110)
Oct 14 01:12:13 instance-1 jormungandr[18303]: dropping I/O source: 34, scope: global
Oct 14 01:12:21 instance-1 jormungandr[18303]: client P2P connection closed, node_id: 18068927349944395760, peer_addr: 54.255.233.57:3100, task: network
Oct 14 01:12:43 instance-1 jormungandr[18303]: evicted node, node_id: 18068927349944395760, peer_addr: 54.255.233.57:3100, task: network
Oct 14 01:13:04 instance-1 jormungandr[18303]: scheduling Read for: 0, scope: global
Oct 14 01:13:20 instance-1 jormungandr[18303]: selecting gossips for 7759025128004985606, task: network
Oct 14 01:13:37 instance-1 jormungandr[18303]: sending gossip to node 7759025128004985606, task: network
Oct 14 01:13:54 instance-1 jormungandr[18303]: selecting gossips for 845440531341738765, task: network
Oct 14 01:14:42 instance-1 jormungandr[18303]: sending gossip to node 845440531341738765, task: network

**Expected behavior**
Normally load averages are under 1

**Additional context**
I'm not entirely sure why CPU utilization goes dramatically up when it does, and I'm not entirely sure the debugs logs are enough for you to determine this.  Nevertheless, I offer them in case it is helpful.

**Comment by mzabaluev** [comment]
We have fixed a few polling bugs, please reopen if this still occurs with 0.6.5 or a later version.
