### ISSUE TITLE
error starting version v0.6.0-rc1 + 1

### ISSUE THREAD

**Issue by RonnyTome** [input-output-hk/jormungandr#944]
ronny@Toshiba:~/Downloads/jormungandr-v0.6.0-rc1+1-x86_64-unknown-linux-musl$ ./jormungandr --config ./node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770
Error in the overall configuration of the node
 |-> Error while parsing the node configuration file: p2p.trusted_peers[0]: invalid type: string "/ip4/3.123.177.192/tcp/3000", expected struct TrustedPeer at line 12 column 7
 |-> p2p.trusted_peers[0]: invalid type: string "/ip4/3.123.177.192/tcp/3000", expected struct TrustedPeer at line 12 column 7
ronny@Toshiba:~/Downloads/jormungandr-v0.6.0-rc1+1-x86_64-unknown-linux-musl$ 

i'm using default node-config.yaml

log:
  format: "plain"
  level: "info"
  output: "stderr"
p2p:
  listen_address: "/ip4/0.0.0.0/tcp/3100"
  public_address:
  topics_of_interest:
    blocks: "high"
    messages: "high"
  trusted_peers:
    - "/ip4/3.123.177.192/tcp/3000"
    - "/ip4/3.123.155.47/tcp/3000"
    - "/ip4/52.57.157.167/tcp/3000"
    - "/ip4/3.112.185.217/tcp/3000"
    - "/ip4/18.140.134.230/tcp/3000"
    - "/ip4/18.139.40.4/tcp/3000"
    - "/ip4/3.115.57.216/tcp/3000"
rest:
  listen: "127.0.0.1:3101"
storage: "/tmp/jormungandr"

**Comment by NicolasDP** [comment]
this is the feature. as stated in the release note, there is a breaking change.
