### ISSUE TITLE
Document changes in p2p.trusted_peers configuration

### ISSUE THREAD

**Issue by hemants1** [input-output-hk/jormungandr#945]
Installed latest binaries...and tried to start the node...Getting following error..!

 ./jormungandr --config ./node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770  --log-output=stdout >> node2.log &
[1] 117507
xxxxxxx@MyTestNode2:/mnt/temp$ Error in the overall configuration of the node
 |-> Error while parsing the node configuration file: p2p.trusted_peers[0]: invalid type: string "/ip4/3.123.177.192/tcp/3000", expected struct TrustedPeer at line 9 column 7
 |-> p2p.trusted_peers[0]: invalid type: string "/ip4/3.123.177.192/tcp/3000", expected struct TrustedPeer at line 9 column 7

The same command to start the node was working fine for previous version..! What has changed now? any configuration changes need to be applied to  node-config.yaml before starting the node???

**Comment by rinor** [comment]
That release has breaking changes. Check release notes and also https://github.com/input-output-hk/jormungandr/issues/944 and https://github.com/input-output-hk/jormungandr/issues/932

**Comment by Philluminati** [comment]
i have the same issue

Linux 4.19.78-1-MANJARO #1 SMP PREEMPT Mon Oct 7 20:24:34 UTC 2019 x86_64 GNU/Linux

$ ./jormungandr --version
jormungandr 0.6.0

$ ./jormungandr --config ./node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770
Error in the overall configuration of the node
 |-> Error while parsing the node configuration file: p2p.trusted_peers[0]: invalid type: string "/ip4/3.123.177.192/tcp/3000", expected struct TrustedPeer at line 12 column 7
 |-> p2p.trusted_peers[0]: invalid type: string "/ip4/3.123.177.192/tcp/3000", expected struct TrustedPeer at line 12 column 7

config:
log:
  format: "plain"
  level: "info"
  output: "stderr"
p2p:
  listen_address: "/ip4/0.0.0.0/tcp/3100"
  public_address:
  topics_of_interest:
    blocks: "high"
    messages: "high"
  trusted_peers:
    - "/ip4/3.123.177.192/tcp/3000"
    - "/ip4/3.123.155.47/tcp/3000"
    - "/ip4/52.57.157.167/tcp/3000"
    - "/ip4/3.112.185.217/tcp/3000"
    - "/ip4/18.140.134.230/tcp/3000"
    - "/ip4/18.139.40.4/tcp/3000"
    - "/ip4/3.115.57.216/tcp/3000"
rest:
  listen: "127.0.0.1:3101"
storage: "/tmp/jormungandr"

**Comment by CraniumDad** [comment]
I'm having same error and issue with release 0.6.0 commit 44ff7c1...

**Comment by mzabaluev** [comment]
The configuration format has changed due to introduction of peer IDs. We should update the documentation.

**Comment by NicolasDP** [comment]
we don't have access to zendesk doc. Please create an issue over there: https://iohk.zendesk.com/hc/en-us/requests/new

**Comment by W3S88** [comment]
So is there a solution for this? or updated documentation? and where?

**Comment by aidik** [comment]
The new format is described here https://github.com/input-output-hk/jormungandr/blob/master/doc/configuration/introduction.md It is not a huge change, what is a bit disappointing is that we don't know any of the trusted_peers ids.

**Comment by hemants1** [comment]
Tried with those trusted peers in the link, but it does not work....it appears to be dead trusted peers..! Does anybody know the working trusted peers with their PIDs?
