### ISSUE TITLE
v0.6.0 - How to get public ID of trusted peers?

### ISSUE THREAD

**Issue by hemants1** [input-output-hk/jormungandr#947]
Installed v0.6.0 and followed breaking changes..!

1. Able to generate private id of my node and added to node-config.yaml 

  USING :   ./jcli key generate --type ed25519

In node-config.yaml added following line:

  p2p:
  private_id: xxxxxxxxxxxxxxxxxxxxxxxxxxx

2. When started the node, getting following error:

@MyTestNode2:/mnt/temp$ Error in the overall configuration of the node
 |-> Error while parsing the node configuration file: p2p.trusted_peers[0]: invalid type: string "/ip4/3.123.177.192/tcp/3000", expected struct TrustedPeer at line 10 column 7
 |-> p2p.trusted_peers[0]: invalid type: string "/ip4/3.123.177.192/tcp/3000", expected struct TrustedPeer at line 10 column 7
^C
[1]+  Exit 2  

Wondering how to get the public key of the exiting trusted peers (in node-config.yaml) ?? Is there a new / default config file published somewhere for v0.6.0????

**Comment by NicolasDP** [comment]
It will be available from IOHK's website: https://testnet.iohkdev.io/cardano/shelley/get-started/configuring-your-network/

**Comment by hugodeanda** [comment]
This was shared in the telegram group of the Cardano Shelley Testnet:

trusted_peers:
  - address: "/ip4/3.115.194.22/tcp/3000"
    id: ed25519_pk1npsal4j9p9nlfs0fsmfjyga9uqk5gcslyuvxy6pexxr0j34j83rsf98wl2
  - address: "/ip4/13.113.10.64/tcp/3000"
    id: ed25519_pk16pw2st5wgx4558c6temj8tzv0pqc37qqjpy53fstdyzwxaypveys3qcpfl
  - address: "/ip4/52.57.214.174/tcp/3000"
    id: ed25519_pk1v4cj0edgmp8f2m5gex85jglrs2ruvu4z7xgy8fvhr0ma2lmyhtyszxtejz
  - address: "/ip4/3.120.96.93/tcp/3000"
    id: ed25519_pk10gmg0zkxpuzkghxc39n3a646pdru6xc24rch987cgw7zq5pmytmszjdmvh
  - address: "/ip4/52.28.134.8/tcp/3000"
    id: ed25519_pk1unu66eej6h6uxv4j4e9crfarnm6jknmtx9eknvq5vzsqpq6a9vxqr78xrw
  - address: "/ip4/13.52.208.132/tcp/3000"
    id: ed25519_pk15ppd5xlg6tylamskqkxh4rzum26w9acph8gzg86w4dd9a88qpjms26g5q9
  - address: "/ip4/54.153.19.202/tcp/3000"
    id: ed25519_pk1j9nj2u0amlg28k27pw24hre0vtyp3ge0xhq6h9mxwqeur48u463s0crpfk
