### ISSUE TITLE
Does not compile on Ubuntu 18.04.3 LTS (rustc 1.36)

### ISSUE THREAD

**Issue by markvq** [input-output-hk/jormungandr#948]
Release 0.6.0 does not compile on Ubuntu 18.04.3 LTS with rustc 1.36.0

**Steps to reproduce**
$ rm -r -f jormungandr
$ git clone --recurse-submodules https://github.com/input-output-hk/jormungandr
$ cd jormungandr
$ git checkout tags/v0.6.0
$ cargo install --force --path jormungandr

Compiling jormungandr-lib v0.6.0 (/home/csp/jormungandr-networking/jormungandr/jormungandr-lib)
   Compiling network-grpc v0.1.0-dev (/home/csp/jormungandr-networking/jormungandr/chain-deps/network-grpc)
   Compiling actix-net v0.2.6
warning: unused import: `crate::network::p2p::comm::PeerStats`
  --> jormungandr/src/rest/v0/handlers.rs:17:5
   |
17 | use crate::network::p2p::comm::PeerStats;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default

warning: unused import: `crate::network::p2p::topology::NodeId`
  --> jormungandr/src/rest/v0/handlers.rs:18:5
   |
18 | use crate::network::p2p::topology::NodeId;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: enum variants on type aliases are experimental
  --> jormungandr/src/network/grpc/server.rs:62:33
   |
62 |                             Err(Error::Protocol(e)) => {
   |                                 ^^^^^^^^^^^^^^^^^^

warning: use of deprecated item 'blockchain::storage::Storage::get_inner': use the stream iterator instead
   --> jormungandr/src/client.rs:106:27
    |
106 |     let storage = storage.get_inner().wait().unwrap();
    |                           ^^^^^^^^^
    |
    = note: #[warn(deprecated)] on by default

warning: use of deprecated item 'blockchain::storage::Storage::get_inner': use the stream iterator instead
   --> jormungandr/src/client.rs:133:27
    |
133 |     let storage = storage.get_inner().wait().unwrap();
    |                           ^^^^^^^^^

warning: use of deprecated item 'blockchain::storage::Storage::get_inner': use the stream iterator instead
   --> jormungandr/src/client.rs:195:27
    |
195 |     let storage = storage.get_inner().wait().unwrap();
    |                           ^^^^^^^^^

error: aborting due to previous error

error: failed to compile `jormungandr v0.6.0 (/home/csp/jormungandr-networking/jormungandr/jormungandr)`, intermediate artifacts can be found at `/home/csp/jormungandr-networking/jormungandr/target`

Caused by:
  Could not compile `jormungandr`.

Best regards,
Mark

**Comment by gmanroney** [comment]
Can you try?
Run rustup install stable
Run rustup default stable

**Comment by mzabaluev** [comment]
The issue is really, should we support such antiquated :smirk: compiler versions as rustc 1.36.
Need to check what does it take to port the code back.

**Comment by rinor** [comment]
> The issue is really, should we support such antiquated smirk compiler versions as rustc 1.36.
In my opinion, no. At this stage the last 2 stable releases should be more than enough.

**Comment by NicolasDP** [comment]
compile with latest stable. Follow @gmanroney's instruction.
