### ISSUE TITLE
Huge memory consumption on Jormungandr 0.6.0

### ISSUE THREAD

**Issue by rickymac68** [input-output-hk/jormungandr#956]
The memory climbed to consuming 50 GB of RAM
<img width="737" alt="Screen Shot 2019-10-15 at 6 52 46 AM" src="https://user-images.githubusercontent.com/25856278/66826263-17dc1c00-ef1a-11e9-9eb4-40de44724af7.png">
<img width="731" alt="Screen Shot 2019-10-15 at 6 33 38 AM" src="https://user-images.githubusercontent.com/25856278/66826313-36421780-ef1a-11e9-830c-2cb60c5cf426.png">
<img width="861" alt="Screen Shot 2019-10-15 at 6 36 51 AM" src="https://user-images.githubusercontent.com/25856278/66826326-3b9f6200-ef1a-11e9-9177-95e0738a7ad6.png">

**Comment by CraniumDad** [comment]
my release 0.6.1 node (not a pool) on Ubuntu 16 using GNU binary also suffered from growing memory utilization (~10GB RAM) after 10-12 hours

**Comment by jbax** [comment]
Still an issue on version 0.6.3

**Comment by mzabaluev** [comment]
There is now version 0.6.5 with one identifed cause of runaway resource hogging fixed. Please retry with the new version.

**Comment by mzabaluev** [comment]
One possible source for runaway RAM consumption is unbounded message queues that are currently used to respond to client requests. Fixing this requires a rewrite of the "client" serving task.

**Comment by NicolasDP** [comment]
Memory consumption issue has been addressed since `0.7.0-rc3`
