### ISSUE TITLE
jcli should use ta hrp for test addresses as it's stated in the design implementations decisions

### ISSUE THREAD

**Issue by carl-IOHK** [input-output-hk/jormungandr#957]
**Describe the bug**
https://github.com/input-output-hk/shelley-testnet/issues/54

**Mandatory Information**
1. `jcli --full-version` output;
2. `jormungandr --full-version` output;

**To Reproduce**

**Expected behavior**
but jcli should use ta hrp for test addresses as it's stated in the [design implementations decisions](https://github.com/input-output-hk/implementation-decisions/blob/master/text/0001-address.md#guide-level-explanation).

**Additional context**
Reported by @ilap

**Comment by ilap** [comment]
As an other comment. Jormungandr should not allow any custom hrps (like "addr" in the testnet's genesis block) in the generated blocks as nothing stops a malicious user from creating an address /w offensive or illegal hrp.

**Comment by vincenthz** [comment]
@carl-IOHK you're pointing to the old document, new relevant document is at https://github.com/input-output-hk/chain-libs/blob/master/chain-impl-mockchain/doc/address.md

@ilap there's no human representation in the genesis block

**Comment by ilap** [comment]
Thx, I missed this somehow:
<quote>
`The blockchain network doesn't use any human encoding in its data, and thus the BECH32 prefix is left to clients / networks. It's also perfectly possible technically for different clients to use different prefix for the same networks although it would be confusing to the user of this network.`
</quote>

**Comment by carl-IOHK** [comment]
Thanks @vincenthz
