### ISSUE TITLE
Leader node on Mac has issues after first exchange of new block information

### ISSUE THREAD

**Issue by hodlonaut** [input-output-hk/jormungandr#961]
Simple setup, one leader node on Linux with ~40% of the stake pool total, one leader on Macbook with 40% of the stake pool total. Both are running latest master code, Macbook leader configured with Linux leader as the only trusted node entry with id/address syntax.

After startup, Mac node bootstraps fine and gets its set of leader events generated.
While it's not producing any blocks it receives block updates from Linux node without issues and keeps on updating local storage with that information.

After Mac node actions its first leadership event, it notifies the Linux node of the new block and that step seems to work fine as is. After this point in time, there is no more successful block notification/propagation between two nodes without any sign of errors in either node's logs.

Sample log output:

Oct 16 00:11:02.929 INFO leader event starting, date: 136.323, leader: 1, task: leadership
Oct 16 00:11:02.932 INFO block from leader event successfully stored, date: 136.323, parent: 895c1d8d10ee21bfa2c3c11e896fffd3d8dd6868e8af47e5b834c968b20b654e, hash: caff89a64e7ee06bdabea80f8231b655fd2d68d596bb2d87fef1b7011eff3368, task: block
Oct 16 00:11:02.933 INFO update current branch tip, date: 136.323, parent: 895c1d8d10ee21bfa2c3c11e896fffd3d8dd6868e8af47e5b834c968b20b654e, hash: caff89a64e7ee06bdabea80f8231b655fd2d68d596bb2d87fef1b7011eff3368, task: block
Oct 16 00:11:02.933 INFO to propagate: Block(Header { common: Common { any_block_version: Supported(KesVrfproof), block_date: BlockDate { epoch: 136, slot_id: 323 }, block_content_size: 0, block_content_hash: Hash(Blake2b256(0x0e5751c026e543b2e8ab2eb06099daa1d1e5df47778f7787faab45cdf12fe3a8)), block_parent_hash: Hash(Blake2b256(0x895c1d8d10ee21bfa2c3c11e896fffd3d8dd6868e8af47e5b834c968b20b654e)), chain_length: ChainLength(3848) }, proof: GenesisPraos(GenesisPraosProof { node_id: $ hash_ty(0xc9cfa1627e848aaca226d4ff2af2f05e9d9da275a475f8990c5ebff366dceccc), vrf_proof: <omitted for brevity> }), task: network
**Oct 16 00:11:02.934 INFO will propagate to: [NodeId("7ae7730a9f19b8398e415c199d22035e48c4e220f75ea0a12870ad2ab309b7a0")], task: network
Oct 16 00:11:09.032 INFO sending gossip to node 7ae7730a9f19b8398e415c199d22035e48c4e220f75ea0a12870ad2ab309b7a0, task: network
Oct 16 00:11:09.032 INFO result of propagate gossip was: Ok(()), task: network**

on the Linux node side there's nothing being logged about block information being received (e.g. no sign of block applied, etc), just boring repetitive old P2P messages like:

INFO incoming P2P connection on 45.32.188.204:3200, peer_addr: 14.201.165.168:54935, task: network
INFO incoming P2P connection closed, peer_addr: 14.201.165.168:54934, task: network

Worth noting that this Mac node is running fine in passive mode i.e. getting consistent updates from the leader.

**Comment by rinor** [comment]
It is not related to Mac. It happens on all OSes.

**Comment by hodlonaut** [comment]
> It is not related only to Mac. It happens on all OSes.

The same source code with basically identical config is working fine in a node built on Windows 10 laptop in Windows powershell. It's exchanging new block information just fine with the Linux node that's also used in the earlier mentioned setup. That is why I mentioned Mac explicitly in the title of the issue.

Also, just to clarify what i mean by running 'latest code' - all nodes are running 0.6.1 git master.

**Comment by hodlonaut** [comment]
Also worth noting that when I had a bit of extra logging added earlier, after Mac node had this in its logs:

**Oct 14 23:22:42.993 INFO will propagate to: [NodeId("7ae7730a9f19b8398e415c199d22035e48c4e220f75ea0a12870ad2ab309b7a0")], task: network
Oct 14 23:22:42.993 INFO res is Ok(()), task: network**

the Linux leader had:

**Oct 14 12:22:43.032 INFO Announced block has a locally stored parent, fetch it, task: block**

followed by a period of silence, i.e. fetching by Linux leader the details from Mac silently failed.

**Comment by hodlonaut** [comment]
Working smoother in 0.6.5 build, closing the ticket for the time being.
