### ISSUE TITLE
Transactions are not propagated to the Stake Pool nodes

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#966]
**Describe the bug**
I receive a transaction hash after requesting funds from the web faucet but: (i) I don't receive te funds because (ii) the transaction remains on `Pending` on the faucet node.

**Mandatory Information**
`v0.6.1' on nodes (faucet/trusted peers) - Michael Fellinger to confirm this

**To Reproduce**
1. Go to https://testnet.iohkdev.io/cardano/
2. Request funds for an address - it is displayed as `Success`
3. Check that the funds were received by the address

**Expected behavior**
Money to be sent to the address

**Additional context**
- my Tx Hash: `129B16A00F17C4E845C4C958DB53A751FD445332BBEE08D226D490F5DB1F6505`
- Michael Fellinger will add the details about the faucet/trusted peers + logs

**Comment by manveru** [comment]
That's the status right now: https://gist.github.com/manveru/742a787faa3ff17e196a28d3e0768924
The fragment already disappeared from the faucet instance, and didn't get propagated to any stake node that could put it into a block.

**Comment by gmanroney** [comment]
@manveru @dorin100 is this resolved now?

**Comment by dorin100** [comment]
Nope. The same here.

**Comment by dorin100** [comment]
this was fixed
