### ISSUE TITLE
Method to load a Ref from the storage is not yet there

### ISSUE THREAD

**Issue by VDamas** [input-output-hk/jormungandr#969]
thread 'block2' panicked at 'not yet implemented: method to load a Ref from the storage is not yet there', jormungandr/src/blockchain/chain.rs:259:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
not yet implemented: method to load a Ref from the storage is not yet there
thread 'leadership2' panicked at 'Expect the event to not close', src/libcore/option.rs:1166:5
thread 'leadership2' panicked at 'cannot access stderr during shutdown', src/libcore/option.rs:1166:5

**Mandatory Information**

jcli 0.6.1 (master-4e8cd69, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
jormungandr 0.6.1 (master-4e8cd69, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

**Comment by dorin100** [comment]
duplicate on https://github.com/input-output-hk/jormungandr/issues/788
