### ISSUE TITLE
Error while parsing the node configuration file

### ISSUE THREAD

**Issue by smurf123444** [input-output-hk/jormungandr#971]
Hi so i am working on linux and trying to get my node running with the config found here https://iohk.zendesk.com/hc/en-us/articles/360036898153-How-to-install-Jormungandr-Networking-Linux-macOS- 

and i am left with these errors

`RUST_BACKTRACE=full ./jormungandr --config node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770
Error in the overall configuration of the node
 |-> Error while parsing the node configuration file: while parsing a block mapping, did not find expected key at line 9 column 2
 |-> while parsing a block mapping, did not find expected key at line 9 column 2
`

my config is exactly as it is on zendesk. Thanks.

**Comment by smurf123444** [comment]
i know it must be an extra tab or special character, but seriously? any one have a working node-config that i dont have to dry hump to work.

**Comment by rdlrt** [comment]
Thanks for highlighting the syntax (documentation) issue.
You can use [this](https://github.com/Kodex-Data-Systems/jormungandr/wiki/Sample-Config-For-Jormungandr-v0.6.0) as an example to work with.
Also, I presume since the developers may not necessarily access to make changes to docos on zendesk, would be best if you could create a ticket at https://iohk.zendesk.com itself.

**Comment by smurf123444** [comment]
hmm same error just at line 31, alwell

**Comment by smurf123444** [comment]
best answer for this is the comment left by user on zendesk https://iohk.zendesk.com/hc/en-us/articles/360036898153/comments/360003196413 has exactly the format needed and extra install guide

**Comment by carl-IOHK** [comment]
We identified the issue with the node-config.yaml file that we published today. This should work. I'm also working on a better process to make this file available in future. 

---
log:
 format: plain
 level: info
 output: stderr
p2p:
 trusted_peers:
   - address: "/ip4/3.115.194.22/tcp/3000"
     id: ed25519_pk1npsal4j9p9nlfs0fsmfjyga9uqk5gcslyuvxy6pexxr0j34j83rsf98wl2
   - address: "/ip4/13.113.10.64/tcp/3000"
     id: ed25519_pk16pw2st5wgx4558c6temj8tzv0pqc37qqjpy53fstdyzwxaypveys3qcpfl
   - address: "/ip4/52.57.214.174/tcp/3000"
     id: ed25519_pk1v4cj0edgmp8f2m5gex85jglrs2ruvu4z7xgy8fvhr0ma2lmyhtyszxtejz
   - address: "/ip4/3.120.96.93/tcp/3000"
     id: ed25519_pk10gmg0zkxpuzkghxc39n3a646pdru6xc24rch987cgw7zq5pmytmszjdmvh
   - address: "/ip4/52.28.134.8/tcp/3000"
     id: ed25519_pk1unu66eej6h6uxv4j4e9crfarnm6jknmtx9eknvq5vzsqpq6a9vxqr78xrw
   - address: "/ip4/13.52.208.132/tcp/3000"
     id: ed25519_pk15ppd5xlg6tylamskqkxh4rzum26w9acph8gzg86w4dd9a88qpjms26g5q9
   - address: "/ip4/54.153.19.202/tcp/3000"
     id: ed25519_pk1j9nj2u0amlg28k27pw24hre0vtyp3ge0xhq6h9mxwqeur48u463s0crpfk
rest:
 listen: 127.0.0.1:3101
storage: "./storage

**Comment by carl-IOHK** [comment]
The web site has been updated 
How to install Jormungandr Networking
https://iohk.zendesk.com/hc/en-us/articles/360036898353
https://iohk.zendesk.com/hc/en-us/articles/360036898153
have been updated

**Comment by carl-IOHK** [comment]
https://github.com/input-output-hk/shelley-testnet/issues/120
