### ISSUE TITLE
Leader event generation issue around the time of the epoch boundary

### ISSUE THREAD

**Issue by hodlonaut** [input-output-hk/jormungandr#972]
Observed after converting a few debug log messages to info level on a leader node.

Log output demonstrating the issue:

Oct 12 00:23:22.844 INFO end of epoch, task: leadership
Oct 12 00:23:22.848 INFO Current slot: Slot(32039), epoch: 89, task: leadership
Oct 12 00:23:22.848 INFO Within era: EpochPosition { epoch: Epoch(88), slot: EpochSlotOffset(359) }, epoch: 89, task: leadership
Oct 12 00:23:22.848 INFO handling new epoch event, nb_slots: 1, slot start: 359, epoch: 89, task: leadership
Oct 12 00:23:22.849 INFO scheduling new end of epoch, scheduled at: 2019-10-11T15:23:23+00:00, task: leadership
Oct 12 00:23:22.849 INFO Inside query_schedules - logging is working - slot start value is 359, nb slots is 1, epoch: 89, task: leadership
Oct 12 00:23:22.849 INFO Number of leaders is 1, epoch: 89, task: leadership
Oct 12 00:23:22.849 INFO For slot_idx 359 the date_at_slot via leadership is 89.359, epoch: 89, task: leadership
Oct 12 00:23:22.849 INFO Finished the loop of leaders, epoch: 89, task: leadership

Towards the end of the last slot of epoch 88 the above was logged, as you can see the new epoch event handling started while we were still towards the end of slot 359 - because of that the query_schedules was invoked with slot_start value of 359, nb slot = 1 (instead of what I think should have been 0 and 360 for the leadership event generation for new epoch)

As a result, my leader node has no leadership events generated for epoch 89 and sat silent for 2 hours.

If I were to manually stop it and start it shortly after the above log messages were produced, then I'd observe the query_schedules now being invoked with slot_start = 1 (or something small, early in the epoch), nb slots = (360 - 1) and get my share of leadership events generated for current epoch.

My local workaround for this issue was adding the following snippet of code to handle_new_epoch_event, but i'm sure expert devs will find a better way to address it:

    while within_era.epoch.0 != epoch {
        thread::sleep(Duration::from_millis(10));
        info!(logger, "Having a 10 ms sleep because {} is not equal to {}", within_era.epoch.0, epoch);
        current_slot = time_frame.slot_at(&std::time::SystemTime::now()).unwrap();
        info!(logger, "Current slot: {:?}", current_slot);
        within_era = era.from_slot_to_era(current_slot).unwrap();
        info!(logger, "Within era: {:?}", within_era);
    }

And here's an extra logging snippet demonstrating this bug in action overnight:

Oct 17 00:23:22.756 INFO end of epoch, task: leadership
Oct 17 00:23:22.756 INFO preparing new epoch schedule, epoch: 149, task: block
Oct 17 00:23:22.781 INFO handle new epoch, epoch is 149 while within_era.epoch.0 is 148, epoch: 149, task: leadership
Oct 17 00:23:22.782 INFO handling new epoch event, nb_slots: 1, slot start: 359, epoch: 149, task: leadership
Oct 17 00:23:22.782 INFO scheduling new end of epoch, scheduled at: 2019-10-16T15:23:23+00:00, task: leadership
Oct 17 02:23:22.751 INFO end of epoch, task: leadership
Oct 17 02:23:22.751 INFO preparing new epoch schedule, epoch: 150, task: block
Oct 17 02:23:22.765 INFO handle new epoch, epoch is 150 while within_era.epoch.0 is 149, epoch: 150, task: leadership
Oct 17 02:23:22.765 INFO handling new epoch event, nb_slots: 1, slot start: 359, epoch: 150, task: leadership
Oct 17 02:23:22.766 INFO scheduling new end of epoch, scheduled at: 2019-10-16T17:23:23+00:00, task: leadership
Oct 17 04:23:22.743 INFO end of epoch, task: leadership
Oct 17 04:23:22.743 INFO preparing new epoch schedule, epoch: 151, task: block
Oct 17 04:23:22.745 INFO handle new epoch, epoch is 151 while within_era.epoch.0 is 150, epoch: 151, task: leadership
Oct 17 04:23:22.746 INFO handling new epoch event, nb_slots: 1, slot start: 359, epoch: 151, task: leadership
Oct 17 04:23:22.746 INFO scheduling new end of epoch, scheduled at: 2019-10-16T19:23:23+00:00, task: leadership
Oct 17 06:23:22.740 INFO end of epoch, task: leadership
Oct 17 06:23:22.740 INFO preparing new epoch schedule, epoch: 152, task: block
Oct 17 06:23:22.744 INFO handle new epoch, epoch is 152 while within_era.epoch.0 is 151, epoch: 152, task: leadership
Oct 17 06:23:22.744 INFO handling new epoch event, nb_slots: 1, slot start: 359, epoch: 152, task: leadership
Oct 17 06:23:22.744 INFO scheduling new end of epoch, scheduled at: 2019-10-16T21:23:23+00:00, task: leadership

as you can see, no leader events were generated on this leader node for the last 3 epochs due to it - notice how the end of epoch event is triggered ~200-300ms before the actual end of the previous epoch.

**Comment by NicolasDP** [comment]
This is fixed since #1106
