### ISSUE TITLE
Not receiving block v0.6.1

### ISSUE THREAD

**Issue by dimasprase** [input-output-hk/jormungandr#973]
I have set up to jormungandr v0.6.1, but it's been 2 hours I'm not receiving any block, how long i should wait ?

![Screenshot from 2019-10-17 13-23-04](https://user-images.githubusercontent.com/12593755/66984507-08f59500-f0e5-11e9-99b6-1ac002328647.png)
![Screenshot from 2019-10-17 13-49-14](https://user-images.githubusercontent.com/12593755/66984539-17dc4780-f0e5-11e9-9667-e03700e20298.png)

**Comment by kristek-jozef** [comment]
I have exactly the same behavior using jormungandr v0.6.1. on Windows 10. I ran the node during the night and no block after 8 hours. Now I restarted it and still nothing.
![image](https://user-images.githubusercontent.com/43762819/66993408-d3907d80-f0cb-11e9-8048-ebfebcfcb0a9.png)

**Comment by kristek-jozef** [comment]
Today I realized that my firewall was reset to previous state and I had closed ports. After allowing all connections for jormungandr.exe it starts to receive blocks.

**Comment by mzabaluev** [comment]
Good to know it works for someone :smile:
If you are behind NAT (have no public address mapped to a local port), consider also setting `p2p.max_connections` to a reasonably low value so that the NAT gateway does not penalize the node for having too many bindings.
